// vuejs-bootstrap/src/components/Dashboard/RealEstateAgent/LatestTransactions.vue
<template>
  <div class="card bg-white border-0 rounded-3">
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-20"
      >
        <h5 class="mb-0">Latest Transactions</h5>
        <div class="dropdown select-dropdown">
          <button
            class="dropdown-toggle border text-body rounded-2 bg-gray-100"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ selectedPeriod }}
          </button>
          <ul
            class="dropdown-menu dropdown-menu-end bg-white border-0 box-shadow py-3"
          >
            <li v-for="period in timePeriods" :key="period">
              <button
                class="dropdown-item text-secondary py-2 px-3"
                @click="selectedPeriod = period"
              >
                {{ period }}
              </button>
            </li>
          </ul>
        </div>
      </div>
      <div
        class="default-table-area style-two campaigns-table px-20 py-12 latest-transactions-table"
      >
        <div class="table-responsive">
          <table class="table align-middle border-0">
            <thead>
              <tr class="border-bottom">
                <th scope="col" class="bg-transparent">
                  <span class="fs-10 text-body fw-semibold letter-spacing-1"
                    >CLIENT</span
                  >
                </th>
                <th scope="col" class="bg-transparent">
                  <span class="fs-10 text-body fw-semibold letter-spacing-1"
                    >EMAIL</span
                  >
                </th>
                <th scope="col" class="bg-transparent">
                  <span class="fs-10 text-body fw-semibold letter-spacing-1"
                    >AMOUNT</span
                  >
                </th>
                <th scope="col" class="bg-transparent">
                  <span class="fs-10 text-body fw-semibold letter-spacing-1"
                    >PAYMENT METHOD</span
                  >
                </th>
                <th scope="col" class="bg-transparent">
                  <span class="fs-10 text-body fw-semibold letter-spacing-1"
                    >STATUS</span
                  >
                </th>
              </tr>
            </thead>
            <tbody>
              <tr
                v-for="transaction in paginatedTransactions"
                :key="transaction.id"
              >
                <td>
                  <div class="d-flex align-items-center">
                    <div class="flex-shrink-0">
                      <img
                        :src="transaction.avatar"
                        class="rounded-circle"
                        style="width: 32px; height: 32px"
                        alt="user"
                      />
                    </div>
                    <div class="flex-grow-1 ms-2">
                      <h4 class="fs-14 fw-semibold mb-0">
                        {{ transaction.name }}
                      </h4>
                    </div>
                  </div>
                </td>
                <td class="fs-12 fw-semibold text-body">
                  {{ transaction.email }}
                </td>
                <td class="fs-12 fw-semibold text-secondary">
                  {{ formatCurrency(transaction.amount) }}
                </td>
                <td>
                  <div class="d-flex align-items-center gap-1">
                    <img
                      :src="transaction.paymentMethod.icon"
                      :alt="transaction.paymentMethod.name"
                    />
                    <span class="ms-2 text-secondary fs-12 fw-semibold">
                      {{ transaction.paymentMethod.name }}
                    </span>
                  </div>
                </td>
                <td>
                  <span
                    class="d-inline-block rounded-pill fs-12 fw-medium"
                    :class="statusClasses(transaction.status)"
                    style="padding: 1px 10px"
                  >
                    {{ transaction.status }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div
          class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap mt-12"
        >
          <span class="fs-12 fw-medium">
            Showing {{ showingFrom }}-{{ showingTo }} of
            {{ transactions.length }} Results
          </span>

          <nav aria-label="Page navigation example">
            <ul class="pagination mb-0 justify-content-center">
              <li class="page-item">
                <button
                  class="page-link icon hover-bg"
                  aria-label="Previous"
                  @click="prevPage"
                  :disabled="currentPage === 1"
                >
                  <i class="material-symbols-outlined"> keyboard_arrow_left </i>
                </button>
              </li>
              <li class="page-item" v-for="page in totalPages" :key="page">
                <button
                  class="page-link"
                  :class="{ active: currentPage === page }"
                  @click="currentPage = page"
                >
                  {{ page }}
                </button>
              </li>
              <li class="page-item">
                <button
                  class="page-link icon hover-bg"
                  aria-label="Next"
                  @click="nextPage"
                  :disabled="currentPage === totalPages"
                >
                  <i class="material-symbols-outlined">
                    keyboard_arrow_right
                  </i>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

interface PaymentMethod {
  name: string;
  icon: string;
}

interface Transaction {
  id: number;
  name: string;
  email: string;
  avatar: string;
  amount: number;
  paymentMethod: PaymentMethod;
  status: "Completed" | "Pending" | "Failed";
  date: string;
}

export default defineComponent({
  name: "LatestTransactions",
  setup() {
    const timePeriods = ["Daily", "Weekly", "Monthly", "Yearly"];
    const selectedPeriod = ref("Monthly");

    const transactions = ref<Transaction[]>([
      {
        id: 1,
        name: "Johhna Loren",
        email: "loren123@gmail.com",
        avatar: require("@/assets/images/user-166.png"),
        amount: 6240,
        paymentMethod: {
          name: "Paypal",
          icon: require("@/assets/images/paypal.png"),
        },
        status: "Completed",
        date: "2023-05-15",
      },
      {
        id: 2,
        name: "Skyler Queen",
        email: "skyqueen@gmail.com",
        avatar: require("@/assets/images/user-170.png"),
        amount: 5135,
        paymentMethod: {
          name: "Wise",
          icon: require("@/assets/images/wise.png"),
        },
        status: "Pending",
        date: "2023-05-14",
      },
      {
        id: 3,
        name: "Jonathon Watson",
        email: "jona2134@gmail.com",
        avatar: require("@/assets/images/user-172.png"),
        amount: 4321,
        paymentMethod: {
          name: "Bank",
          icon: require("@/assets/images/bank.png"),
        },
        status: "Failed",
        date: "2023-05-13",
      },
      {
        id: 4,
        name: "Walter White",
        email: "puzzleworld@gmail.com",
        avatar: require("@/assets/images/user-171.png"),
        amount: 3124,
        paymentMethod: {
          name: "Paypal",
          icon: require("@/assets/images/paypal.png"),
        },
        status: "Completed",
        date: "2023-05-12",
      },
      {
        id: 5,
        name: "David Carlen",
        email: "liveslong@gmail.com",
        avatar: require("@/assets/images/user-166.png"),
        amount: 2137,
        paymentMethod: {
          name: "Skrill",
          icon: require("@/assets/images/skrill.png"),
        },
        status: "Pending",
        date: "2023-05-11",
      },
      {
        id: 6,
        name: "Walter White",
        email: "puzzleworld@gmail.com",
        avatar: require("@/assets/images/user-171.png"),
        amount: 3124,
        paymentMethod: {
          name: "Paypal",
          icon: require("@/assets/images/paypal.png"),
        },
        status: "Completed",
        date: "2023-05-12",
      },
      {
        id: 7,
        name: "Skyler Queen",
        email: "skyqueen@gmail.com",
        avatar: require("@/assets/images/user-170.png"),
        amount: 5135,
        paymentMethod: {
          name: "Wise",
          icon: require("@/assets/images/wise.png"),
        },
        status: "Pending",
        date: "2023-05-14",
      },
    ]);

    // Pagination
    const itemsPerPage = 5;
    const currentPage = ref(1);

    const totalPages = computed(() =>
      Math.ceil(transactions.value.length / itemsPerPage)
    );
    const paginatedTransactions = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage;
      const end = start + itemsPerPage;
      return transactions.value.slice(start, end);
    });

    const showingFrom = computed(
      () => (currentPage.value - 1) * itemsPerPage + 1
    );
    const showingTo = computed(() => {
      const end = currentPage.value * itemsPerPage;
      return end > transactions.value.length ? transactions.value.length : end;
    });

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    // Helper functions
    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
        minimumFractionDigits: 0,
      }).format(amount);
    };

    const statusClasses = (status: string) => {
      const classes: Record<string, string> = {
        Completed:
          "bg-success-60 bg-opacity-10 border-success-60 border text-success-60",
        Pending:
          "bg-card-bg-c bg-opacity-10 border-card-bg-c border text-card-bg-c",
        Failed:
          "bg-danger-80 bg-opacity-10 border-danger-80 border text-danger-80",
      };
      return classes[status] || "";
    };

    return {
      timePeriods,
      selectedPeriod,
      transactions,
      paginatedTransactions,
      currentPage,
      totalPages,
      showingFrom,
      showingTo,
      nextPage,
      prevPage,
      formatCurrency,
      statusClasses,
    };
  },
});
</script>

// react-nextjs-material-ui/src/components/Dashboard/RealEstateAgent/LatestTransactions/index.tsx
"use client";

import { useState } from "react";
import {
  Box,
  Typography,
  Card,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Paper,
  Button,
  TableHead,
} from "@mui/material";
import Image from "next/image";

interface Transaction {
  id: number;
  clientName: string;
  email: string;
  amount: string;
  paymentMethod: {
    name: string;
    icon: string;
  };
  status: "completed" | "pending" | "failed";
  avatar: string;
}

const LatestTransactions = () => {
  // Transaction data state
  const [transactions, setTransactions] = useState<Transaction[]>([
    {
      id: 1,
      clientName: "Johhna Loren",
      email: "loren123@gmail.com",
      amount: "$6240",
      paymentMethod: {
        name: "Paypal",
        icon: "/images/payment-method/paypal.svg",
      },
      status: "completed",
      avatar: "/images/users/user58.jpg",
    },
    {
      id: 2,
      clientName: "Skyler Queen",
      email: "skyqueen@gmail.com",
      amount: "$5135",
      paymentMethod: {
        name: "Wise",
        icon: "/images/payment-method/wise.svg",
      },
      status: "completed",
      avatar: "/images/users/user59.jpg",
    },
    {
      id: 3,
      clientName: "Jonathon Watson",
      email: "jona2134@gmail.com",
      amount: "$4321",
      paymentMethod: {
        name: "Bank",
        icon: "/images/payment-method/bank.svg",
      },
      status: "failed",
      avatar: "/images/users/user60.jpg",
    },
    {
      id: 4,
      clientName: "Emily Davis",
      email: "emilyd@gmail.com",
      amount: "$3250",
      paymentMethod: {
        name: "Stripe",
        icon: "/images/payment-method/stripe.png",
      },
      status: "pending",
      avatar: "/images/users/user61.jpg",
    },
    {
      id: 5,
      clientName: "Michael Brown",
      email: "michaelb@gmail.com",
      amount: "$2890",
      paymentMethod: {
        name: "Paypal",
        icon: "/images/payment-method/paypal.svg",
      },
      status: "completed",
      avatar: "/images/users/user62.jpg",
    },
    {
      id: 6,
      clientName: "Emily Davis",
      email: "emilyd@gmail.com",
      amount: "$3250",
      paymentMethod: {
        name: "Stripe",
        icon: "/images/payment-method/stripe.png",
      },
      status: "pending",
      avatar: "/images/users/user61.jpg",
    },
    {
      id: 7,
      clientName: "Michael Brown",
      email: "michaelb@gmail.com",
      amount: "$2890",
      paymentMethod: {
        name: "Paypal",
        icon: "/images/payment-method/paypal.svg",
      },
      status: "completed",
      avatar: "/images/users/user62.jpg",
    },
    {
      id: 8,
      clientName: "Skyler Queen",
      email: "skyqueen@gmail.com",
      amount: "$5135",
      paymentMethod: {
        name: "Wise",
        icon: "/images/payment-method/wise.svg",
      },
      status: "completed",
      avatar: "/images/users/user59.jpg",
    },
    {
      id: 9,
      clientName: "Johhna Loren",
      email: "loren123@gmail.com",
      amount: "$6240",
      paymentMethod: {
        name: "Paypal",
        icon: "/images/payment-method/paypal.svg",
      },
      status: "completed",
      avatar: "/images/users/user58.jpg",
    },
    {
      id: 10,
      clientName: "Jonathon Watson",
      email: "jona2134@gmail.com",
      amount: "$4321",
      paymentMethod: {
        name: "Bank",
        icon: "/images/payment-method/bank.svg",
      },
      status: "failed",
      avatar: "/images/users/user60.jpg",
    },
  ]);

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  // Pagination calculations
  const totalItems = transactions.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = transactions.slice(indexOfFirstItem, indexOfLastItem);

  // Generate page numbers
  const pageNumbers = [];
  for (let i = 1; i <= totalPages; i++) {
    pageNumbers.push(i);
  }

  // Handle page change
  const handlePageChange = (page: number) => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
    }
  };

  // Get status styles
  const getStatusStyles = (status: Transaction["status"]) => {
    switch (status) {
      case "completed":
        return {
          bgcolor: "success.100",
          color: "success.main",
          borderColor: "success.300",
        };
      case "pending":
        return {
          bgcolor: "warning.100",
          color: "warning.main",
          borderColor: "warning.300",
        };
      case "failed":
        return {
          bgcolor: "error.100",
          color: "error.main",
          borderColor: "error.300",
        };
      default:
        return {
          bgcolor: "grey.100",
          color: "grey.800",
          borderColor: "grey.300",
        };
    }
  };

  return (
    <Card
      sx={{
        boxShadow: "none",
        borderRadius: "7px",
        mb: "25px",
        padding: { xs: "18px", sm: "20px", lg: "25px" },
      }}
      className="rmui-card"
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          flexWrap: "wrap",
          gap: "15px",
          mb: "10px",
        }}
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
          }}
          className="text-black"
        >
          Latest Transactions
        </Typography>
      </Box>

      <TableContainer
        component={Paper}
        sx={{
          boxShadow: "none",
          borderRadius: "0",
        }}
        className="rmui-table"
      >
        <Table sx={{ minWidth: 700 }}>
          <TableHead>
            <TableRow
              className="border-bottom"
              sx={{
                "& th": {
                  fontSize: "10px",
                  fontWeight: 700,
                  color: "text.primary",
                  padding: "15px 8px",
                },
              }}
            >
              <th className="text-start">CLIENT</th>
              <th className="text-start">EMAIL</th>
              <th className="text-start">AMOUNT</th>
              <th className="text-start">PAYMENT METHOD</th>
              <th className="text-end">STATUS</th>
            </TableRow>
          </TableHead>

          <TableBody>
            {currentItems.map((transaction) => (
              <TableRow
                key={transaction.id}
                sx={{
                  "& td": {
                    padding: "13px 8px",
                    fontSize: "12px",
                    fontWeight: 600,
                  },
                }}
              >
                <TableCell className="border-bottom">
                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      gap: "10px",
                    }}
                  >
                    <Image
                      src={transaction.avatar}
                      alt={transaction.clientName}
                      width={32}
                      height={32}
                      style={{
                        borderRadius: "50%",
                      }}
                    />
                    <Typography
                      variant="h6"
                      sx={{
                        fontSize: { xs: "13px", md: "14px" },
                        fontWeight: 600,
                      }}
                    >
                      {transaction.clientName}
                    </Typography>
                  </Box>
                </TableCell>

                <TableCell className="border-bottom">
                  {transaction.email}
                </TableCell>

                <TableCell
                  className="border-bottom text-black"
                  sx={{ fontWeight: 700 }}
                >
                  {transaction.amount}
                </TableCell>

                <TableCell className="border-bottom">
                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      gap: "10px",
                    }}
                  >
                    <Image
                      src={transaction.paymentMethod.icon}
                      alt={transaction.paymentMethod.name}
                      width={24}
                      height={24}
                    />
                    <Typography
                      variant="h6"
                      sx={{
                        fontSize: { xs: "13px", md: "13px" },
                        fontWeight: 600,
                      }}
                    >
                      {transaction.paymentMethod.name}
                    </Typography>
                  </Box>
                </TableCell>

                <TableCell className="border-bottom text-end">
                  <Box
                    sx={{
                      border: "1px solid",
                      borderRadius: "30px",
                      lineHeight: 1,
                      fontSize: "12px",
                      display: "inline-block",
                      fontWeight: 500,
                      p: "3.5px 9px",
                      textTransform: "capitalize",
                      ...getStatusStyles(transaction.status),
                    }}
                  >
                    {transaction.status}
                  </Box>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>

        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: "15px",
            mt: "15px",
          }}
        >
          <Typography fontSize={"12px"} fontWeight={500} mb={"0"}>
            Showing {indexOfFirstItem + 1}-
            {Math.min(indexOfLastItem, totalItems)} of {totalItems} results
          </Typography>

          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              gap: "5px",
            }}
          >
            <Button
              className="border text-body"
              sx={{
                minWidth: "auto",
                padding: "0",
                width: { xs: "28px", md: "34px" },
                height: { xs: "28px", md: "34px" },
              }}
              onClick={() => handlePageChange(currentPage - 1)}
              disabled={currentPage === 1}
            >
              <i className="material-symbols-outlined">keyboard_arrow_left</i>
            </Button>

            {pageNumbers.map((number) => (
              <Button
                key={number}
                onClick={() => handlePageChange(number)}
                className="border"
                sx={{
                  minWidth: "auto",
                  padding: "0",
                  width: { xs: "28px", md: "34px" },
                  height: { xs: "28px", md: "34px" },
                  backgroundColor:
                    number === currentPage ? "primary.main" : "transparent",
                  color: number === currentPage ? "white !important" : "text.primary",
                }}
              >
                {number}
              </Button>
            ))}

            <Button
              onClick={() => handlePageChange(currentPage + 1)}
              disabled={currentPage === pageNumbers.length}
              className="border text-body"
              sx={{
                minWidth: "auto",
                padding: "0",
                width: { xs: "28px", md: "34px" },
                height: { xs: "28px", md: "34px" },
              }}
            >
              <i className="material-symbols-outlined">keyboard_arrow_right</i>
            </Button>
          </Box>
        </Box>
      </TableContainer>
    </Card>
  );
};

export default LatestTransactions;
