// react-nextjs-material-ui/src/app/dashboard/saas/page.tsx
import * as React from "react";
import { Grid } from "@mui/material";
import TodaysPayment from "@/components/Dashboard/SaaS/TodaysPayment";
import ActiveUser from "@/components/Dashboard/SaaS/ActiveUser";
import Revenue from "@/components/Dashboard/SaaS/Revenue";
import Conversion from "@/components/Dashboard/SaaS/Conversion";
import ActiveUsers from "@/components/Dashboard/SaaS/ActiveUsers";
import TopRefers from "@/components/Dashboard/SaaS/TopRefers";
import GrossRevenue from "@/components/Dashboard/SaaS/GrossRevenue";
import SalesByCountry from "@/components/Dashboard/SaaS/SalesByCountry";
import LatestTransactions from "@/components/Dashboard/SaaS/LatestTransactions";
import UpgradePlans from "@/components/Dashboard/SaaS/UpgradePlans";
import ProductTradeConditions from "@/components/Dashboard/SaaS/ProductTradeConditions";
import ActiveUsersList from "@/components/Dashboard/SaaS/ActiveUsersList";

export default function Page() {
  return (
    <>
      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 9 }}>
          <TodaysPayment />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 3 }}>
          <Grid container columnSpacing={{ xs: 3 }}>
            <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 12 }}>
              <ActiveUser />
            </Grid>

            <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 12 }}>
              <Revenue />
            </Grid>

            <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 12 }}>
              <Conversion />
            </Grid>
          </Grid>
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 4 }}>
          <TopRefers />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 8 }}>
          <ActiveUsers />
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 8, lg: 8, xl: 9 }}>
          <LatestTransactions />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 4, lg: 4, xl: 3 }}>
          <UpgradePlans />
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 4, lg: 4, xl: 4 }}>
          <ActiveUsersList />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 8, lg: 8, xl: 8 }}>
          <ProductTradeConditions />
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 8 }}>
          <GrossRevenue />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 4 }}>
          <SalesByCountry />
        </Grid>
      </Grid>
    </>
  );
}

// svelte-bootstrap/src/routes/dashboard/saas/+page.svelte
<script>
	import ActiveUser from '$lib/components/Dashboard/SaaS/ActiveUser.svelte';
	import ActiveUsers from '$lib/components/Dashboard/SaaS/ActiveUsers.svelte';
	import Conversion from '$lib/components/Dashboard/SaaS/Conversion.svelte';
	import GrossRevenue from '$lib/components/Dashboard/SaaS/GrossRevenue.svelte';
	import LatestTransaction from '$lib/components/Dashboard/SaaS/LatestTransaction.svelte';
	import ProductTradeCondition from '$lib/components/Dashboard/SaaS/ProductTradeCondition.svelte';
	import RecentActiveUsers from '$lib/components/Dashboard/SaaS/RecentActiveUsers.svelte';
	import Revenue from '$lib/components/Dashboard/SaaS/Revenue.svelte';
	import SalesByCountry from '$lib/components/Dashboard/SaaS/SalesByCountry.svelte';

	import TodaysPayment from '$lib/components/Dashboard/SaaS/TodaysPayment.svelte';
	import TopReferers from '$lib/components/Dashboard/SaaS/TopReferers.svelte';
	import UpgradePlans from '$lib/components/Dashboard/SaaS/UpgradePlans.svelte';
</script>

<svelte:head>
	<title>SaaS | Trezo - Svelte & Bootsrap 5 Admin Dashboard Template</title>
</svelte:head>

<div class="row">
	<div class="col-lg-8 col-xxl-9">
		<TodaysPayment />
	</div>
	<div class="col-lg-4 col-xxl-3">
		<ActiveUser />
		<Revenue />
		<Conversion />
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<div class="card bg-white border-0 rounded-3 mb-4">
			<TopReferers />
		</div>
	</div>
	<div class="col-lg-8">
		<div class="card bg-white border-0 rounded-3 mb-4">
			<ActiveUsers />
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-8">
		<LatestTransaction />
	</div>
	<div class="col-lg-4">
		<UpgradePlans />
	</div>
</div>

<div class="row">
	<div class="col-lg-4">
		<RecentActiveUsers />
	</div>
	<div class="col-lg-8">
		<div class="card bg-white border-0 rounded-3 mb-4">
			<ProductTradeCondition />
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-8">
		<GrossRevenue />
	</div>
	<div class="col-lg-4">
		<SalesByCountry />
	</div>
</div>
