// react-nextjs-material-ui/src/components/Dashboard/Hotel/PopularRooms.tsx
"use client";

import { useState, useEffect } from "react";
import { Box, Typography, Card } from "@mui/material";
import Image from "next/image";
import Link from "next/link";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from "swiper/modules";

interface Room {
  id: string;
  name: string;
  code: string;
  imageUrl: string;
  status: "available" | "booked";
  price?: number;
  rating?: number;
  link: string;
}

const PopularRooms = () => {
  const [rooms, setRooms] = useState<Room[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  // Fetch rooms data
  useEffect(() => {
    const fetchRooms = async () => {
      try {
        setLoading(true);
        // Simulate API call with mock data
        await new Promise((resolve) => setTimeout(resolve, 800));

        const mockRooms: Room[] = [
          {
            id: "1",
            name: "The Velvet - F - 32045",
            code: "SJ-32056",
            imageUrl: "/images/rooms/room6.jpg",
            status: "booked",
            price: 299,
            rating: 4.8,
            link: "/hotel/room-details",
          },
          {
            id: "2",
            name: "Deluxe Room - G - 3215",
            code: "SJ-32057",
            imageUrl: "/images/rooms/room7.jpg",
            status: "available",
            price: 249,
            rating: 4.5,
            link: "/hotel/room-details",
          },
          {
            id: "3",
            name: "Executive Suite - A - 2001",
            code: "SJ-32058",
            imageUrl: "/images/rooms/room8.jpg",
            status: "available",
            price: 349,
            rating: 4.9,
            link: "/hotel/room-details",
          },
          {
            id: "4",
            name: "Presidential Suite - P - 5001",
            code: "SJ-32059",
            imageUrl: "/images/rooms/room9.jpg",
            status: "booked",
            price: 599,
            rating: 5.0,
            link: "/hotel/room-details",
          },
          {
            id: "5",
            name: "Garden View Room - V - 1502",
            code: "SJ-32060",
            imageUrl: "/images/rooms/room6.jpg",
            status: "available",
            price: 199,
            rating: 4.2,
            link: "/hotel/room-details",
          },
        ];

        setRooms(mockRooms);
      } catch (error) {
        console.error("Failed to fetch rooms:", error);
      } finally {
        setLoading(false);
      }
    };

    fetchRooms();
  }, []);

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            flexWrap: "wrap",
            gap: "15px",
            mb: "20px",
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Popular Rooms
          </Typography>
        </Box>

        {loading ? (
          <Box sx={{ textAlign: "center", py: 4 }}>
            <Typography>Loading rooms...</Typography>
          </Box>
        ) : rooms.length === 0 ? (
          <Box sx={{ textAlign: "center", py: 4 }}>
            <Typography>No popular rooms available</Typography>
          </Box>
        ) : (
          <Swiper
            spaceBetween={25}
            pagination={{
              clickable: true,
            }}
            breakpoints={{
              0: {
                slidesPerView: 1,
              },
              506: {
                slidesPerView: 2,
              },
              668: {
                slidesPerView: 3,
              },
              705: {
                slidesPerView: 4,
              },
            }}
            autoplay={{
              delay: 5000,
              disableOnInteraction: false, 
              pauseOnMouseEnter: true,
            }}
            modules={[Pagination, Autoplay]}
            className="hotel-popular-rooms"
          >
            {rooms.map((room) => (
              <SwiperSlide key={room.id}>
                <Box>
                  <Box sx={{ position: "relative", mb: "10px" }}>
                    <Link
                      href={room.link}
                      className="border-radius"
                      style={{
                        display: "block",
                      }}
                    >
                      <Image
                        src={room.imageUrl}
                        className="border-radius"
                        alt={`${room.name} image`}
                        width={500}
                        height={500}
                      />
                    </Link>

                    <Box
                      className="po-right-10"
                      sx={{
                        position: "absolute",
                        top: "10px",
                        borderRadius: "30px",
                        backgroundColor:
                          room.status === "available"
                            ? "success.100"
                            : "error.50",
                        color:
                          room.status === "available"
                            ? "success.main"
                            : "error.main",
                        borderColor:
                          room.status === "available"
                            ? "success.300"
                            : "error.40",
                        border: "1px solid",
                        lineHeight: 1,
                        fontSize: "12px",
                        display: "inline-block",
                        fontWeight: 500,
                        p: "3.5px 10px",
                        textTransform: "capitalize",
                      }}
                    >
                      {room.status}
                    </Box>
                  </Box>

                  <Typography
                    variant="h5"
                    sx={{ fontWeight: 600, fontSize: "16px", mb: "5px" }}
                  >
                    <Link
                      href={room.link}
                      className="text-black hover-text-color"
                    >
                      {room.name}
                    </Link>
                  </Typography>

                  <Typography sx={{ mb: "5px" }}>
                    Code <strong>{room.code}</strong>
                  </Typography>

                  {room.price && (
                    <Typography sx={{ fontWeight: 600, color: "primary.main" }}>
                      ${room.price}{" "}
                      <span
                        style={{ fontWeight: 400, color: "text.secondary" }}
                      >
                        / night
                      </span>
                    </Typography>
                  )}
                </Box>
              </SwiperSlide>
            ))}
          </Swiper>
        )}
      </Card>
    </>
  );
};

export default PopularRooms;

// vuejs-bootstrap/src/components/Dashboard/Hotel/PopularRooms.vue
<template>
  <div
    class="border-0 rounded-3 bg-white position-relative z-1 mb-4 p-25 popular-rooms-bg"
  >
    <div
      class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"
    >
      <h5 class="mb-0">Popular Rooms</h5>
      <div class="">
        <div class="swiper-pagination-popular-rooms"></div>
      </div>
    </div>

    <Swiper
      :slidesPerView="1"
      :spaceBetween="30"
      :centeredSlides="false"
      :preventClicks="true"
      :loop="false"
      :autoplay="{
        delay: 5000,
        disableOnInteraction: false,
        pauseOnMouseEnter: true,
      }"
      :pagination="{
        el: '.swiper-pagination-popular-rooms',
        clickable: true,
      }"
      :breakpoints="{
        0: {
          slidesPerView: 1,
        },
        576: {
          slidesPerView: 2,
        },
        768: {
          slidesPerView: 2,
        },
        992: {
          slidesPerView: 3,
        },
        1200: {
          slidesPerView: 4,
        },
        1440: {
          slidesPerView: 4,
        },
        1850: {
          slidesPerView: 4,
        },
      }"
      :modules="modules"
      class="popular-rooms-slide"
    >
      <SwiperSlide v-for="(room, index) in rooms" :key="index">
        <RouterLink
          :to="`/hotel/room-details/${room.id}`"
          class="text-decoration-none position-relative d-block"
        >
          <img :src="room.image" class="rounded-3" :alt="room.name" />

          <h3 class="mt-3 mb-6 fs-16 fw-semibold hover">
            {{ room.name }}
          </h3>
          <span class="text-body">
            Code
            <strong class="fw-semibold">{{ room.code }}</strong>
          </span>
          <div class="position-absolute top-0 end-0 m-2">
            <span
              :class="`d-inline-block ${room.status.class} border px-2 rounded-pill ${room.status.textClass} fs-12 fw-medium`"
            >
              {{ room.status.text }}
            </span>
          </div>
        </RouterLink>
      </SwiperSlide>
    </Swiper>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Swiper, SwiperSlide } from "swiper/vue";
import { Autoplay, Pagination } from "swiper/modules";

export default defineComponent({
  name: "PopularRooms",
  components: {
    Swiper,
    SwiperSlide,
  },
  setup() {
    const rooms = [
      {
        id: 1,
        name: "The Velvet - F - 32045",
        code: "SJ-32056",
        image: require("@/assets/images/room-1.jpg"),
        status: {
          text: "Booked",
          class: "bg-card-text-c border-danger-50",
          textClass: "text-danger-50",
        },
      },
      {
        id: 2,
        name: "Duluxe Room - G - 3215",
        code: "SJ-32057",
        image: require("@/assets/images/room-2.jpg"),
        status: {
          text: "Available",
          class: "bg-success-80 border-success-60",
          textClass: "text-success-60",
        },
      },
      {
        id: 3,
        name: "The Garden Suite 101",
        code: "SJ-32058",
        image: require("@/assets/images/room-3.jpg"),
        status: {
          text: "Booked",
          class: "bg-card-text-c border-danger-50",
          textClass: "text-danger-50",
        },
      },
      {
        id: 4,
        name: "The Tranquil S-02",
        code: "SJ-32059",
        image: require("@/assets/images/room-4.jpg"),
        status: {
          text: "Available",
          class: "bg-success-80 border-success-60",
          textClass: "text-success-60",
        },
      },
      {
        id: 5,
        name: "The Velvet - F - 32045",
        code: "SJ-32056",
        image: require("@/assets/images/room-1.jpg"),
        status: {
          text: "Booked",
          class: "bg-card-text-c border-danger-50",
          textClass: "text-danger-50",
        },
      },
      {
        id: 6,
        name: "Duluxe Room - G - 3215",
        code: "SJ-32057",
        image: require("@/assets/images/room-2.jpg"),
        status: {
          text: "Available",
          class: "bg-success-80 border-success-60",
          textClass: "text-success-60",
        },
      },
      {
        id: 7,
        name: "The Garden Suite 101",
        code: "SJ-32058",
        image: require("@/assets/images/room-3.jpg"),
        status: {
          text: "Booked",
          class: "bg-card-text-c border-danger-50",
          textClass: "text-danger-50",
        },
      },
      {
        id: 8,
        name: "The Tranquil S-02",
        code: "SJ-32059",
        image: require("@/assets/images/room-4.jpg"),
        status: {
          text: "Available",
          class: "bg-success-80 border-success-60",
          textClass: "text-success-60",
        },
      },
    ];

    return {
      modules: [Autoplay, Pagination],
      rooms,
    };
  },
});
</script>
