// react-nextjs-material-ui/src/components/Dashboard/Hotel/UpcomingVIPReservations/index.tsx
"use client";

import { useState, useEffect } from "react";
import {
  Box,
  Typography,
  Card,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Paper,
  Button,
  TableHead,
  IconButton,
  Link,
} from "@mui/material";
import CustomDropdown from "./CustomDropdown";

interface Reservation {
  code: string;
  room: string;
  customer: string;
  duration: string;
}

const UpcomingVIPReservations = () => {
  // Mock data (replace with API call in a real application)
  const mockReservations: Reservation[] = [
    {
      code: "TRZ-32",
      room: "Deluxe Room - G - 3215",
      customer: "Angela Carter",
      duration: "10 Dec - 15 Dec",
    },
    {
      code: "TRZ-33",
      room: "Suite - A - 1001",
      customer: "John Doe",
      duration: "12 Dec - 18 Dec",
    },
    {
      code: "TRZ-34",
      room: "Penthouse - B - 5001",
      customer: "Jane Smith",
      duration: "15 Dec - 20 Dec",
    },
    {
      code: "TRZ-35",
      room: "Executive Suite - E - 2202",
      customer: "Michael Johnson",
      duration: "18 Dec - 22 Dec",
    },
    {
      code: "TRZ-36",
      room: "Presidential Suite - P - 7001",
      customer: "Olivia Williams",
      duration: "20 Dec - 25 Dec",
    },
    {
      code: "TRZ-37",
      room: "Junior Suite - J - 1205",
      customer: "Liam Brown",
      duration: "22 Dec - 26 Dec",
    },
    {
      code: "TRZ-38",
      room: "Standard Room - S - 2109",
      customer: "Emma Davis",
      duration: "24 Dec - 28 Dec",
    },
    {
      code: "TRZ-39",
      room: "Deluxe Room - D - 3312",
      customer: "Noah Miller",
      duration: "26 Dec - 30 Dec",
    },
    {
      code: "TRZ-40",
      room: "Royal Suite - R - 4500",
      customer: "Sophia Wilson",
      duration: "28 Dec - 02 Jan",
    },
    {
      code: "TRZ-41",
      room: "Economy Room - E - 1111",
      customer: "James Anderson",
      duration: "30 Dec - 03 Jan",
    },
  ];

  // State management with TypeScript types
  const [reservations, setReservations] = useState<Reservation[]>([]);
  const [currentPage, setCurrentPage] = useState<number>(1);
  const [itemsPerPage] = useState<number>(5); // Set to 2 for demonstration; adjust as needed

  // Simulate data fetching
  useEffect(() => {
    setReservations(mockReservations);
  }, []);

  // Pagination calculations
  const totalItems: number = reservations.length;
  const totalPages: number = Math.ceil(totalItems / itemsPerPage);
  const indexOfLastItem: number = currentPage * itemsPerPage;
  const indexOfFirstItem: number = indexOfLastItem - itemsPerPage;
  const currentItems: Reservation[] = reservations.slice(
    indexOfFirstItem,
    indexOfLastItem
  );

  // Generate page numbers
  const pageNumbers: number[] = [];
  for (let i = 1; i <= totalPages; i++) {
    pageNumbers.push(i);
  }

  // Handle page change with type safety
  const handlePageChange = (page: number): void => {
    if (page >= 1 && page <= totalPages) {
      setCurrentPage(page);
    }
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            flexWrap: "wrap",
            gap: "15px",
            mb: "10px",
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Upcoming VIP Reservations
          </Typography>

          <CustomDropdown
            options={["Daily", "Weekly", "Monthly", "Yearly"]} // Need to change the options also in CustomDropdown file
            onSelect={(value) => console.log(value)}
            defaultLabel="Monthly"
          />
        </Box>

        <TableContainer
          component={Paper}
          sx={{
            boxShadow: "none",
            borderRadius: "0",
          }}
          className="rmui-table"
        >
          <Table sx={{ minWidth: 800 }}>
            <TableHead>
              <TableRow
                className="border-bottom"
                sx={{
                  "& th": {
                    fontSize: "10px",
                    fontWeight: 700,
                    color: "text.primary",
                    padding: "15px 8px",
                  },
                }}
              >
                <th className="text-start">CODE</th>

                <th className="text-start">ROOM</th>

                <th className="text-start">CUSTOMER</th>

                <th className="text-start">DURATION</th>

                <th className="text-end">ACTION</th>
              </TableRow>
            </TableHead>

            <TableBody>
              {currentItems.map((reservation, index) => (
                <TableRow
                  key={index}
                  sx={{
                    "& td": {
                      padding: "13px 8px",
                      fontSize: "12px",
                      fontWeight: 600,
                    },
                  }}
                >
                  <TableCell className="border-bottom">
                    {reservation.code}
                  </TableCell>

                  <TableCell className="border-bottom">
                    <Link
                      href="#"
                      sx={{
                        fontSize: { xs: "13px", md: "14px" },
                        fontWeight: 600,
                        mb: 0,
                        color: "#3a4252",

                        "&:hover": {
                          color: "primary.main",
                        },
                      }}
                    >
                      {reservation.room}
                    </Link>
                  </TableCell>

                  <TableCell className="border-bottom">
                    {reservation.customer}
                  </TableCell>

                  <TableCell className="border-bottom">
                    <Box
                      sx={{
                        backgroundColor: "primary.50",
                        color: "primary.main",
                        fontSize: "12px",
                        borderRadius: "4px",
                        padding: "3.5px 10px",
                        display: "inline-block",
                      }}
                    >
                      {reservation.duration}
                    </Box>
                  </TableCell>

                  <TableCell className="border-bottom">
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "end",
                      }}
                    >
                      <IconButton
                        aria-label="view"
                        color="primary"
                        sx={{ padding: "5px" }}
                      >
                        <i
                          className="material-symbols-outlined"
                          style={{ fontSize: "16px" }}
                        >
                          visibility
                        </i>
                      </IconButton>

                      <IconButton
                        aria-label="edit"
                        color="secondary"
                        sx={{ padding: "5px" }}
                      >
                        <i
                          className="material-symbols-outlined"
                          style={{ fontSize: "16px" }}
                        >
                          edit
                        </i>
                      </IconButton>

                      <IconButton
                        aria-label="delete"
                        color="error"
                        sx={{ padding: "5px" }}
                      >
                        <i
                          className="material-symbols-outlined"
                          style={{ fontSize: "16px" }}
                        >
                          delete
                        </i>
                      </IconButton>
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>

          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              flexWrap: "wrap",
              gap: "15px",
              mt: "15px",
            }}
          >
            <Typography fontSize={"12px"} fontWeight={500} mb={"0"}>
              Showing {indexOfFirstItem + 1}-
              {Math.min(indexOfLastItem, totalItems)} of {totalItems} results
            </Typography>

            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: "5px",
              }}
            >
              <Button
                className="border text-body"
                sx={{
                  minWidth: "auto",
                  padding: "0",
                  width: { xs: "28px", md: "34px" },
                  height: { xs: "28px", md: "34px" },
                }}
                onClick={() => handlePageChange(currentPage - 1)}
                disabled={currentPage === 1}
              >
                <i className="material-symbols-outlined">keyboard_arrow_left</i>
              </Button>

              {pageNumbers.map((number) => (
                <Button
                  key={number}
                  onClick={() => handlePageChange(number)}
                  className="border"
                  sx={{
                    minWidth: "auto",
                    padding: "0",
                    width: { xs: "28px", md: "34px" },
                    height: { xs: "28px", md: "34px" },
                    backgroundColor:
                      number === currentPage ? "primary.main" : "transparent",
                    color: number === currentPage ? "white !important" : "text.primary",
                  }}
                >
                  {number}
                </Button>
              ))}

              <Button
                onClick={() => handlePageChange(currentPage + 1)}
                disabled={currentPage === pageNumbers.length}
                className="border text-body"
                sx={{
                  minWidth: "auto",
                  padding: "0",
                  width: { xs: "28px", md: "34px" },
                  height: { xs: "28px", md: "34px" },
                }}
              >
                <i className="material-symbols-outlined">
                  keyboard_arrow_right
                </i>
              </Button>
            </Box>
          </Box>
        </TableContainer>
      </Card>
    </>
  );
};

export default UpcomingVIPReservations;

// vuejs-bootstrap/src/components/Dashboard/Hotel/UpcomingVIPReservations.vue
<template>
  <div class="card border-0 rounded-3 bg-white position-relative z-1 mb-4 p-25">
    <div
      class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-1"
    >
      <h5 class="mb-0">Upcoming VIP Reservations</h5>
      <div class="dropdown select-dropdown">
        <button
          class="dropdown-toggle border text-body rounded-2 bg-gray-100"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          Monthly
        </button>
        <ul
          class="dropdown-menu dropdown-menu-end bg-white border-0 box-shadow py-3"
        >
          <li>
            <button class="dropdown-item text-secondary py-2 px-3">
              Weekly
            </button>
          </li>
          <li>
            <button class="dropdown-item text-secondary py-2 px-3">
              Monthly
            </button>
          </li>
          <li>
            <button class="dropdown-item text-secondary py-2 px-3">
              Yearly
            </button>
          </li>
        </ul>
      </div>
    </div>

    <div class="default-table-area style-two upcoming-vip-reservations-table">
      <div class="table-responsive">
        <table class="table align-middle border-0">
          <thead>
            <tr class="border-bottom">
              <th class="bg-transparent text-body fw-medium">
                <span class="fs-10 fw-bold">CODE</span>
              </th>
              <th class="bg-transparent text-body fw-medium">
                <span class="fs-10 fw-bold">ROOM</span>
              </th>
              <th class="bg-transparent text-body fw-medium">
                <span class="fs-10 fw-bold">CUSTOMER</span>
              </th>
              <th class="bg-transparent text-body fw-medium">
                <span class="fs-10 fw-bold">DURATION</span>
              </th>
              <th class="text-end bg-transparent text-body fw-medium">
                <span class="fs-10 fw-bold opacity-0">ACTION</span>
              </th>
            </tr>
          </thead>

          <tbody>
            <tr v-for="reservation in paginatedData" :key="reservation.code">
              <td class="fs-12 fw-semibold text-body">
                {{ reservation.code }}
              </td>
              <td>
                <RouterLink
                  to="/hotel/room-details"
                  class="fs-14 fw-semibold text-secondary"
                >
                  {{ reservation.room }}
                </RouterLink>
              </td>
              <td class="fs-12 fw-semibold text-body-color-50">
                {{ reservation.customer }}
              </td>
              <td>
                <span
                  class="bg-border-color-50 fs-12 fw-medium text-primary d-inline-block rounded-1"
                  style="padding: 3px 8px"
                >
                  {{ reservation.duration }}
                </span>
              </td>
              <td class="text-end">
                <div
                  class="d-flex justify-content-end align-items-center gap-2"
                >
                  <button class="ps-0 border-0 bg-transparent lh-1">
                    <i class="material-symbols-outlined fs-16 text-primary">
                      visibility
                    </i>
                  </button>
                  <button class="ps-0 border-0 bg-transparent lh-1">
                    <i
                      class="material-symbols-outlined fs-16 text-primary-div-50"
                    >
                      edit
                    </i>
                  </button>
                  <button class="ps-0 border-0 bg-transparent lh-1">
                    <i class="material-symbols-outlined fs-16 text-danger">
                      delete
                    </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap mt-10"
      >
        <span class="fs-12 fw-medium">
          Showing {{ paginatedData.length }} of
          {{ reservations.length }} Results
        </span>
        <nav aria-label="Page navigation">
          <ul class="pagination mb-0 justify-content-center">
            <li class="page-item" :class="{ disabled: currentPage === 1 }">
              <button
                class="page-link icon hover-bg"
                @click="goToPage(currentPage - 1)"
              >
                <i class="material-symbols-outlined">keyboard_arrow_left</i>
              </button>
            </li>
            <li
              v-for="page in totalPages"
              :key="page"
              class="page-item"
              :class="{ active: currentPage === page }"
            >
              <button class="page-link" @click="goToPage(page)">
                {{ page }}
              </button>
            </li>
            <li
              class="page-item"
              :class="{ disabled: currentPage === totalPages }"
            >
              <button
                class="page-link icon hover-bg"
                @click="goToPage(currentPage + 1)"
              >
                <i class="material-symbols-outlined">keyboard_arrow_right</i>
              </button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { ref, computed } from "vue";

interface Reservation {
  code: string;
  room: string;
  customer: string;
  duration: string;
}

const reservations = ref<Reservation[]>([
  {
    code: "TRZ-32",
    room: "Duluxe Room - G - 3215",
    customer: "Angela Carter",
    duration: "10 Dec - 15 Dec",
  },
  {
    code: "TRZ-34",
    room: "Sweet Suite - S - 1265",
    customer: "Walter White",
    duration: "12 Dec - 16 Dec",
  },
  {
    code: "TRZ-42",
    room: "The Queensland - Q32",
    customer: "Zennifer Loren",
    duration: "15 Dec - 20 Dec",
  },
  {
    code: "TRZ-15",
    room: "Sweet Suite - S - 3214",
    customer: "Johna Mandala",
    duration: "11 Dec - 14 Dec",
  },
  {
    code: "TRZ-29",
    room: "Duluxe Room - F - 7213",
    customer: "Viktor James",
    duration: "10 Dec - 15 Dec",
  },
  {
    code: "TRZ-55",
    room: "Presidential Suite - P - 9000",
    customer: "Bruce Wayne",
    duration: "20 Dec - 25 Dec",
  },
  {
    code: "TRZ-61",
    room: "Garden View - G - 3301",
    customer: "Clark Kent",
    duration: "13 Dec - 17 Dec",
  },
]);

const currentPage = ref(1);
const itemsPerPage = 5;

const totalPages = computed(() =>
  Math.ceil(reservations.value.length / itemsPerPage)
);

const paginatedData = computed(() => {
  const start = (currentPage.value - 1) * itemsPerPage;
  return reservations.value.slice(start, start + itemsPerPage);
});

function goToPage(page: number) {
  if (page >= 1 && page <= totalPages.value) {
    currentPage.value = page;
  }
}
</script>
