// vuejs-vuetify/src/components/Dashboard/Restaurant/CustomerRatings.vue
<template>
  <v-card
    class="customer-ratings-card trezo-card bg-white border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Customer Ratings</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius bg-gray border-0"
          >
            Weekly
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            Weekly
          </button>
          <button type="button" class="bg-transparent border-none">
            Monthly
          </button>
          <button type="button" class="bg-transparent border-none">
            Yearly
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="trezo-table basic-table table-responsive">
        <table class="table mb-0">
          <thead>
            <tr>
              <th scope="col" class="fw-bold">User ID</th>
              <th scope="col" class="fw-bold">Customer Name</th>
              <th scope="col" class="fw-bold">Ratings</th>
              <th scope="col" class="fw-bold">Reviews</th>
              <th scope="col" class="fw-bold">Date</th>
              <th scope="col" class="fw-bold"></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="rating in paginatedRatings" :key="rating.id">
              <td class="fw-semibold text-body">{{ rating.id }}</td>
              <td>
                <div class="employee-info d-flex align-items-center">
                  <div class="img rounded-circle">
                    <v-img
                      :src="rating.image"
                      alt="user-image"
                      class="rounded-circle"
                    />
                  </div>
                  <div>
                    <span class="d-block fw-semibold">{{ rating.name }}</span>
                  </div>
                </div>
              </td>
              <td class="fw-semibold text-body">
                <div class="ratings lh-1">
                  <i class="ri-star-fill"></i>
                  <span class="d-inline-block lh-1 text-xs text-body">
                    {{ rating.rating }}
                  </span>
                </div>
              </td>
              <td class="reviews">
                <div class="reviews">
                  <span class="d-block fw-semibold">
                    {{ rating.reviewTitle }}
                  </span>
                  <p>{{ rating.review }}</p>
                </div>
              </td>
              <td class="fw-semibold text-body">{{ rating.date }}</td>
              <td>
                <div class="action-buttons d-flex align-items-center">
                  <button type="button">
                    <i class="material-symbols-outlined"> visibility </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined"> edit </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined"> delete </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        class="d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
      >
        <span class="fs-12 fw-medium">
          Showing {{ startIndex + 1 }} to {{ endIndex }} of
          {{ ratings.length }} Results
        </span>

        <nav aria-label="Page navigation example">
          <ul class="pagination mb-0 justify-content-center">
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Previous"
                @click="prevPage"
                :disabled="currentPage === 1"
              >
                <i class="material-symbols-outlined">keyboard_arrow_left</i>
              </button>
            </li>
            <li class="page-item" v-for="page in totalPages" :key="page">
              <button
                class="page-link"
                :class="{ active: page === currentPage }"
                @click="goToPage(page)"
              >
                {{ page }}
              </button>
            </li>
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Next"
                @click="nextPage"
                :disabled="currentPage === totalPages"
              >
                <i class="material-symbols-outlined">keyboard_arrow_right</i>
              </button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

export default defineComponent({
  name: "CustomerRatings",
  setup() {
    const currentPage = ref(1);
    const itemsPerPage = ref(3);

    const ratings = ref([
      {
        id: "#001",
        name: "Joanna Watson",
        image: require("@/assets/images/users/user58.jpg"),
        rating: 5.0,
        reviewTitle: "Amazing Ambiance and Delicious Food!",
        review:
          "Trezo was a fantastic dining experience. The ambiance is warm and inviting, perfect for a date night or celebration. I ordered the truffle pasta, which was rich and perfectly seasoned. The service was impeccable, and the staff made us feel like family. Highly recommend!",
        date: "13 Nov, 25",
      },
      {
        id: "#002",
        name: "Jenelia Anderson",
        image: require("@/assets/images/users/user59.jpg"),
        rating: 4.9,
        reviewTitle: "Best Brunch Spot in Town",
        review:
          "Visited Trezo for brunch with friends, and it exceeded our expectations. The avocado toast was fresh, and their mimosas were spot-on. Our server was attentive without being intrusive. Definitely coming back!",
        date: "14 Nov, 25",
      },
      {
        id: "#003",
        name: "Jonathon Ronan",
        image: require("@/assets/images/users/user60.jpg"),
        rating: 4.0,
        reviewTitle: "Good Food, Slow Service",
        review:
          "The food at Trezo was delicious, but the service was a bit slow. We had to wait a while for our appetizers, and our main course was delayed. It’s a nice spot, but they could work on speeding up their service.",
        date: "15 Nov, 25",
      },
      {
        id: "#004",
        name: "Jenelia Anderson",
        image: require("@/assets/images/users/user59.jpg"),
        rating: 4.9,
        reviewTitle: "Best Brunch Spot in Town",
        review:
          "Visited Trezo for brunch with friends, and it exceeded our expectations. The avocado toast was fresh, and their mimosas were spot-on. Our server was attentive without being intrusive. Definitely coming back!",
        date: "14 Nov, 25",
      },
      {
        id: "#005",
        name: "Jonathon Ronan",
        image: require("@/assets/images/users/user60.jpg"),
        rating: 4.0,
        reviewTitle: "Good Food, Slow Service",
        review:
          "The food at Trezo was delicious, but the service was a bit slow. We had to wait a while for our appetizers, and our main course was delayed. It’s a nice spot, but they could work on speeding up their service.",
        date: "15 Nov, 25",
      },
    ]);

    const totalPages = computed(() =>
      Math.ceil(ratings.value.length / itemsPerPage.value)
    );

    const paginatedRatings = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage.value;
      const end = start + itemsPerPage.value;
      return ratings.value.slice(start, end);
    });

    const startIndex = computed(
      () => (currentPage.value - 1) * itemsPerPage.value
    );
    const endIndex = computed(() =>
      Math.min(currentPage.value * itemsPerPage.value, ratings.value.length)
    );

    const goToPage = (page: number) => {
      currentPage.value = page;
    };

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    return {
      currentPage,
      itemsPerPage,
      ratings,
      paginatedRatings,
      totalPages,
      startIndex,
      endIndex,
      goToPage,
      nextPage,
      prevPage,
    };
  },
});
</script>

<style lang="scss" scoped>
.customer-ratings-card {
  .trezo-card-content {
    .basic-table {
      table,
      .table {
        thead {
          tr {
            background-color: transparent !important;

            th {
              font-size: 10px;
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              text-align: left;
              padding: {
                bottom: 15px;
                top: 0;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              vertical-align: top;
              font-size: 12px;
              padding: {
                top: 15px;
                bottom: 15px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 30px;
                }
                span {
                  &:nth-child(1) {
                    margin-bottom: 1px;
                    font-size: var(--fontSize);
                  }
                }
              }
              .reviews {
                white-space: normal;
                width: 620px;

                span {
                  margin-bottom: 5px;
                }
              }
              .action-buttons {
                justify-content: right;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
              }
            }
          }
        }
      }
    }
  }
}
</style>

// angular-material/src/app/dashboard/restaurant/customer-ratings/customer-ratings.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatMenuModule } from '@angular/material/menu';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-customer-ratings',
    imports: [MatCardModule, MatButtonModule, MatMenuModule, MatTableModule, MatPaginatorModule],
    templateUrl: './customer-ratings.component.html',
    styleUrl: './customer-ratings.component.scss'
})
export class CustomerRatingsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}
        
    displayedColumns: string[] = ['userID', 'customerName', 'ratings', 'reviews', 'date', 'action'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);
    
    @ViewChild(MatPaginator) paginator!: MatPaginator;

    ngAfterViewInit() {
        this.dataSource.paginator = this.paginator;
    }

}

export interface PeriodicElement {
    userID: string;
    customerName: any;
    ratings: any;
    reviews: any;
    date: string;
    action: string;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        userID: '#001',
        customerName: {
            img: 'images/users/user58.jpg',
            name: 'Joanna Watson'
        },
        ratings: {
            star: 'ri-star-fill',
            number: '5.0'
        },
        reviews: {
            title: 'Amazing Ambiance and Delicious Food!',
            desc: 'Trezo was a fantastic dining experience. The ambiance is warm and inviting, perfect for a date night or celebration. I ordered the truffle pasta, which was rich and perfectly seasoned. The service was impeccable, and the staff made us feel like family. Highly recommend!'
        },
        date: '13 Nov, 25',
        action: "ri-more-2-fill"
    },
    {
        userID: '#002',
        customerName: {
            img: 'images/users/user59.jpg',
            name: 'Jenelia Anderson'
        },
        ratings: {
            star: 'ri-star-fill',
            number: '5.0'
        },
        reviews: {
            title: 'Best Brunch Spot in Town',
            desc: 'Visited Trezo for brunch with friends, and it exceeded our expectations. The avocado toast was fresh, and their mimosas were spot-on. Our server was attentive without being intrusive. Definitely coming back!'
        },
        date: '13 Nov, 25',
        action: "ri-more-2-fill"
    },
    {
        userID: '#003',
        customerName: {
            img: 'images/users/user60.jpg',
            name: 'Jonathon Ronan'
        },
        ratings: {
            star: 'ri-star-fill',
            number: '5.0'
        },
        reviews: {
            title: 'Good Food, Slow Service',
            desc: 'The food at Trezo was delicious, but the service was a bit slow. We had to wait a while for our appetizers, and our main course was delayed. It’s a nice spot, but they could work on speeding up their service.'
        },
        date: '13 Nov, 25',
        action: "ri-more-2-fill"
    },
    {
        userID: '#002',
        customerName: {
            img: 'images/users/user59.jpg',
            name: 'Jenelia Anderson'
        },
        ratings: {
            star: 'ri-star-fill',
            number: '5.0'
        },
        reviews: {
            title: 'Best Brunch Spot in Town',
            desc: 'Visited Trezo for brunch with friends, and it exceeded our expectations. The avocado toast was fresh, and their mimosas were spot-on. Our server was attentive without being intrusive. Definitely coming back!'
        },
        date: '13 Nov, 25',
        action: "ri-more-2-fill"
    },
    {
        userID: '#003',
        customerName: {
            img: 'images/users/user60.jpg',
            name: 'Jonathon Ronan'
        },
        ratings: {
            star: 'ri-star-fill',
            number: '5.0'
        },
        reviews: {
            title: 'Good Food, Slow Service',
            desc: 'The food at Trezo was delicious, but the service was a bit slow. We had to wait a while for our appetizers, and our main course was delayed. It’s a nice spot, but they could work on speeding up their service.'
        },
        date: '13 Nov, 25',
        action: "ri-more-2-fill"
    },
    {
        userID: '#001',
        customerName: {
            img: 'images/users/user58.jpg',
            name: 'Joanna Watson'
        },
        ratings: {
            star: 'ri-star-fill',
            number: '5.0'
        },
        reviews: {
            title: 'Amazing Ambiance and Delicious Food!',
            desc: 'Trezo was a fantastic dining experience. The ambiance is warm and inviting, perfect for a date night or celebration. I ordered the truffle pasta, which was rich and perfectly seasoned. The service was impeccable, and the staff made us feel like family. Highly recommend!'
        },
        date: '13 Nov, 25',
        action: "ri-more-2-fill"
    }
];
<mat-card
    class="customer-ratings-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Customer Ratings
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="card-header-menu bg-gray border-none d-inline-block border-radius">
                Monthly
            </button>
            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                <ul class="p-0 mt-0 mb-0 list-unstyled">
                    <li>
                        <button mat-menu-item>
                            Weekly
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            Monthly
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            Yearly
                        </button>
                    </li>
                </ul>
            </mat-menu>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <div class="table-style-five">
            <div class="table-responsive">
                <table mat-table [dataSource]="dataSource">

                    <!-- User ID Column -->
                    <ng-container matColumnDef="userID">
                        <th mat-header-cell *matHeaderCellDef>
                            User ID
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.userID}}
                        </td>
                    </ng-container>

                    <!-- Customer Name Column -->
                    <ng-container matColumnDef="customerName">
                        <th mat-header-cell *matHeaderCellDef>
                            Customer Name
                        </th>
                        <td mat-cell *matCellDef="let element">
                            <div class="employee-info d-flex align-items-center">
                                <img [src]="element.customerName.img" class="rounded-circle" alt="user-image">
                                <span class="d-block text-black fw-semibold">
                                    {{element.customerName.name}}
                                </span>
                            </div>
                        </td>
                    </ng-container>

                    <!-- Ratings Column -->
                    <ng-container matColumnDef="ratings">
                        <th mat-header-cell *matHeaderCellDef>
                            Ratings
                        </th>
                        <td mat-cell *matCellDef="let element">
                            <div class="ratings d-flex align-items-center">
                                <i class="{{element.ratings.star}}"></i>
                                <div class="number fw-bold text-body position-relative">
                                    {{element.ratings.number}}
                                </div>
                            </div>
                        </td>
                    </ng-container>

                    <!-- Reviews Column -->
                    <ng-container matColumnDef="reviews">
                        <th mat-header-cell *matHeaderCellDef>
                            Reviews
                        </th>
                        <td class="text-body fw-medium" mat-cell *matCellDef="let element">
                            <div class="reviews">
                                <span class="d-block text-black fw-bold">
                                    {{element.reviews.title}}
                                </span>
                                <p>
                                    {{element.reviews.desc}}
                                </p>
                            </div>
                        </td>
                    </ng-container>

                    <!-- Date Column -->
                    <ng-container matColumnDef="date">
                        <th mat-header-cell *matHeaderCellDef>
                            Date
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.date}}
                        </td>
                    </ng-container>

                    <!-- Action Column -->
                    <ng-container matColumnDef="action">
                        <th mat-header-cell *matHeaderCellDef></th>
                        <td mat-cell *matCellDef="let element">
                            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                                <i class="{{element.action}}"></i>
                            </button>
                            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                                <ul class="p-0 mt-0 mb-0 list-unstyled">
                                    <li>
                                        <button mat-menu-item>
                                            View
                                        </button>
                                    </li>
                                    <li>
                                        <button mat-menu-item>
                                            Edit
                                        </button>
                                    </li>
                                    <li>
                                        <button mat-menu-item>
                                            Delete
                                        </button>
                                    </li>
                                </ul>
                            </mat-menu>
                        </td>
                    </ng-container>

                    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
                    <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>

                </table>
            </div>
            <mat-paginator [pageSizeOptions]="[3]" showFirstLastButtons></mat-paginator>
        </div>
    </mat-card-content>
</mat-card>
