// angular-material/src/app/pages/finance-page/f-wallet/total-expenses/total-expenses.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { CustomizerSettingsService } from '../../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-total-expenses:not(0)',
    imports: [MatCardModule],
    templateUrl: './total-expenses.component.html',
    styleUrl: './total-expenses.component.scss'
})
export class TotalExpensesComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<mat-card
    class="total-expenses-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-content>
        <div class="info d-flex justify-content-between">
            <div>
                <span class="d-block">
                    Total Expenses
                </span>
                <h3 class="mb-0">
                    $251,952
                </h3>
            </div>
            <div class="icon text-purple rounded-circle d-flex align-items-center justify-content-center">
                <i class="material-symbols-outlined">
                    account_balance_wallet
                </i>
            </div>
        </div>
        <div class="gap-10 d-flex align-items-center">
            <span class="trezo-badge down with-border">
                -28.5%
            </span>
            <span class="d-block text-xs">
                Last 30 days
            </span>
        </div>
    </mat-card-content>
</mat-card>

// laravel-vuetify/resources/components/Pages/Finance/Wallet/TotalExpenses.vue
<template>
    <v-card
        class="trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="d-flex mb-4">
            <div class="flex-grow-1">
                <span class="d-block mb-1">Total Expenses</span>
                <h4 class="fs-20 mb-0">$251,952</h4>
            </div>
            <div class="flex-shrink-0 ms-3">
                <i
                    class="ri-wallet-2-line fs-24 text-primary-div for dark-bg d-inline-block text-center rounded-circle"
                    style="
                        width: 60px;
                        height: 60px;
                        line-height: 60px;
                        background-color: #ecf0ff;
                    "
                ></i>
            </div>
        </div>
        <div class="d-flex align-items-center">
            <span
                class="d-inline-block px-3 bg-danger bg-opacity-10 text-danger border border-danger rounded-pill fs-12 fw-medium"
            >
                -28.5%
            </span>
            <span class="ms-2 fs-12">Last 30 days</span>
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
    name: "TotalExpenses",
});
</script>

<style lang="scss" scoped>
.bg-danger {
    background-color: rgb(253 88 18 / 10%) !important;
}
.text-primary-div {
    color: rgb(173 99 246) !important;
}
.mb-1 {
    margin-bottom: 0.25rem !important;
}
.mb-4 {
    margin-bottom: 1.5rem !important;
}
</style>
