// vuejs-vuetify/src/components/Dashboard/Doctor/RecentLabReports.vue
<template>
  <v-card
    class="recent-lab-reports-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Recent Lab Reports</h5>
    </div>

    <div class="trezo-card-content">
      <div class="trezo-table basic-table table-responsive">
        <table class="table mb-0">
          <tbody>
            <tr v-for="(report, index) in labReports" :key="index">
              <td>
                <div class="employee-info d-flex">
                  <div class="img">
                    <v-img :src="getIcon(report.type)" alt="user-image" />
                  </div>
                  <div>
                    <span class="d-block fw-semibold text-black">
                      {{ report.name }}
                    </span>
                    <span class="d-block text-body">
                      submitted by
                      <strong class="fw-normal text-black">
                        {{ report.submittedBy }}
                      </strong>
                    </span>
                  </div>
                </div>
              </td>
              <td>
                <button
                  type="button"
                  class="download-btn d-inline-block border-0 bg-transparent p-0"
                >
                  <i class="ri-download-2-line"></i>
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "RecentLabReports",
  data() {
    return {
      labReports: [
        { name: "Blood Report.pdf", type: "pdf", submittedBy: "Andrew" },
        { name: "X-ray Report.jpg", type: "jpg", submittedBy: "Joanna" },
        { name: "Creatinine Report.pdf", type: "pdf", submittedBy: "David" },
        { name: "Blood Report.pdf", type: "pdf", submittedBy: "Zinia" },
        { name: "ECG Report.doc", type: "doc", submittedBy: "Bella" },
        { name: "Blood Report.pdf", type: "pdf", submittedBy: "Jonathon" },
      ],
    };
  },
  methods: {
    getIcon(type: string) {
      return require(`@/assets/images/icons/${type}.png`);
    },
  },
});
</script>

<style lang="scss" scoped>
.recent-lab-reports-card {
  .trezo-card-content {
    margin-bottom: -14px;

    .basic-table {
      table,
      .table {
        thead {
          tr {
            th {
              font-size: 10px;
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              padding: {
                bottom: 14px;
                top: 0;
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
                text-align: end;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              font-size: 12px;
              padding: {
                top: 13px !important;
                bottom: 13px !important;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 28px;
                }
                span {
                  &:nth-child(1) {
                    font-size: var(--fontSize);
                    margin: {
                      bottom: 5px;
                      top: -2px;
                    }
                  }
                }
              }
              .download-btn {
                i {
                  font-size: 20px;
                  color: var(--primaryColor);
                }
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
                text-align: end;
              }
            }
            &:first-child {
              td {
                border-top-width: 0;
                padding-top: 0 !important;
              }
            }
            &:last-child {
              td {
                border-bottom-width: 0;
              }
            }
          }
        }
      }
    }
  }
}
</style>

// react-bootstrap/src/components/Dashboard/Doctor/RecentLabReports.js
"use client";

import React, { useEffect, useState } from "react";
import { Card } from "react-bootstrap";

const RecentLabReports = () => {
  const [reports, setReports] = useState([]);

  useEffect(() => {
    // Simulate fetching data from an API
    setTimeout(() => {
      setReports([
        { id: 1, name: "Blood Report.pdf", type: "pdf", submittedBy: "Andrew" },
        { id: 2, name: "X-ray Report.jpg", type: "jpg", submittedBy: "Joanna" },
        { id: 3, name: "Creatinine.pdf", type: "pdf", submittedBy: "David" },
        { id: 4, name: "Blood Report.pdf", type: "pdf", submittedBy: "Zinia" },
        { id: 5, name: "Blood Report.doc", type: "doc", submittedBy: "Andrew" },
        { id: 6, name: "ECG Report.doc", type: "doc", submittedBy: "Bella" },
        {
          id: 7,
          name: "Blood Report.pdf",
          type: "pdf",
          submittedBy: "Jonathon",
        },
      ]);
    }, 1000);
  }, []);

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <h3 className="mb-4">Recent Lab Report</h3>

          <div
            className="last-child-none"
            style={{
              maxHeight: "407px",
              overflowY: "auto",
            }}
          >
            {reports.length > 0 ? (
              reports.map((report) => (
                <div
                  key={report.id}
                  className="child border-bottom pb-3 mb-3 d-flex flex-wrap gap-2 justify-content-between"
                >
                  <div className="d-flex align-items-center">
                    <div className="flex-shrink-0">
                      <img
                        src={`/images/${report.type}.png`}
                        alt="pdf"
                        width={30}
                        height={30}
                      />
                    </div>
                    <div className="flex-grow-1 ms-2">
                      <h3 className="fw-semibold fs-14 mb-0">{report.name}</h3>
                      <span className="fs-12">
                        submitted by{" "}
                        <span className="text-secondary">
                          {report.submittedBy}
                        </span>
                      </span>
                    </div>
                  </div>
                  <button className="p-0 border-0 bg-transparent text-primary">
                    <span className="material-symbols-outlined">download</span>
                  </button>
                </div>
              ))
            ) : (
              <p className="text-center">Loading reports...</p>
            )}
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default RecentLabReports;
