// vuejs-vuetify/src/components/Dashboard/RealEstateAgent/RecentClients.vue
<template>
  <v-card
    class="recent-clients-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Recent Clients</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-2-fill"></i>
          </button>
        </template>

        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <ul class="m-0 p-0 list-unstyled">
        <li
          class="d-flex align-items-center position-relative"
          v-for="client in clients"
          :key="client.id"
        >
          <div class="image position-relative">
            <v-img :src="client.avatar" alt="user" class="rounded-circle" />
            <span
              :class="[
                'active-status',
                client.status === 'online' ? 'online' : 'offline',
              ]"
            ></span>
          </div>
          <div class="content">
            <span class="d-block fw-semibold text-black"> Johhna Loren </span>
            <span class="d-block"> Doctor </span>
          </div>
          <RouterLink to="/social/profile" class="link-btn lh-1">
            <i class="ri-arrow-right-line"></i>
          </RouterLink>
        </li>
      </ul>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Client {
  id: number;
  name: string;
  profession: string;
  avatar: string;
  status: "online" | "offline";
}

export default defineComponent({
  name: "RecentClients",
  setup() {
    const clients: Client[] = [
      {
        id: 1,
        name: "Johhna Loren",
        profession: "Doctor",
        avatar: require("@/assets/images/user-177.png"),
        status: "online",
      },
      {
        id: 2,
        name: "Zinia Watson",
        profession: "Lawyer",
        avatar: require("@/assets/images/user-157.png"),
        status: "online",
      },
      {
        id: 3,
        name: "Angela Carter",
        profession: "Businesswoman",
        avatar: require("@/assets/images/user-158.png"),
        status: "online",
      },
      {
        id: 4,
        name: "Skyler White",
        profession: "Enterpreuner",
        avatar: require("@/assets/images/user-159.png"),
        status: "offline",
      },
      {
        id: 5,
        name: "Jane Ronan",
        profession: "Editor",
        avatar: require("@/assets/images/user-160.png"),
        status: "online",
      },
      {
        id: 6,
        name: "Viktor James",
        profession: "Editor",
        avatar: require("@/assets/images/user-154.png"),
        status: "offline",
      },
    ];

    return {
      clients,
    };
  },
});
</script>

<style scoped lang="scss">
.recent-clients-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        gap: 12px;
        padding: {
          top: 10px;
          bottom: 10px;
        }
        .image {
          padding: {
            right: 2px;
            bottom: 2px;
          }
          img {
            width: 35px;
          }
          .active-status {
            right: 0;
            bottom: 0;
            width: 12px;
            height: 12px;
            border-radius: 50%;
            position: absolute;
            background: var(--successColor);
            border: 1px solid var(--whiteColor);

            &.offline {
              background: #8695aa;
            }
          }
        }
        .content {
          span {
            &:nth-child(2) {
              font-size: 12px;
              margin-top: 2px;
            }
          }
        }
        .link-btn {
          top: 50%;
          right: 0;
          font-size: 18px;
          position: absolute;
          color: var(--bodyColor);
          transform: translateY(-50%);

          &:hover {
            color: var(--primaryColor);
          }
        }
        &:first-child {
          border-top: 1px solid var(--borderColor);
        }
      }
    }
  }
}
</style>

// angular-tailwindcss/src/app/dashboard/real-estate-agent/recent-clients/recent-clients.component.ts
import { NgIf } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Component, HostListener } from '@angular/core';

@Component({
    selector: 'app-recent-clients',
    imports: [NgIf, RouterLink],
    templateUrl: './recent-clients.component.html',
    styleUrl: './recent-clients.component.scss'
})
export class RecentClientsComponent {

    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-dropdown')) {
            this.isCardHeaderOpen = false;
        }
    }

}
<div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
        <div class="trezo-card-title">
            <h5 class="!mb-0">
                Recent Clients
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-dropdown relative ltr:-mr-[7px] rtl:-ml-[7px]">
                <button type="button" class="trezo-card-dropdown-btn inline-block transition-all text-[22px] text-gray-500 dark:text-gray-400 leading-none hover:text-primary-500" (click)="toggleCardHeaderMenu()">
                    <i class="ri-more-2-fill"></i>
                </button>
                <ul class="trezo-card-dropdown-menu transition-all bg-white shadow-3xl rounded-md top-full py-[15px] absolute ltr:right-0 rtl:left-0 w-[195px] z-[5] dark:bg-dark dark:shadow-none" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Day
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Week
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Month
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            This Year
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <ul>
            <li class="relative flex items-center gap-[12px] py-[10.5px] border-b first:border-t border-primary-50 dark:border-[#172036]">
                <div class="relative ltr:pr-[2px] rtl:pl-[2px] pb-[2px]">
                    <img src="images/users/user48.jpg" alt="user-image" class="rounded-full w-[35px]">
                    <span class="absolute ltr:right-0 rtl:left-0 bottom-0 w-[12px] h-[12px] rounded-full bg-success-500 border-[1px] border-white dark:border-[#0c1427]"></span>
                </div>
                <div>
                    <span class="block font-semibold text-gray-900 dark:text-gray-400">
                        Johhna Loren
                    </span>
                    <span class="block text-xs mt-[3px]">
                        Doctor
                    </span>
                </div>
                <a routerLink="." class="absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 text-lg inline-block transition-all hover:text-primary-500">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="relative flex items-center gap-[12px] py-[10.5px] border-b first:border-t border-primary-50 dark:border-[#172036]">
                <div class="relative ltr:pr-[2px] rtl:pl-[2px] pb-[2px]">
                    <img src="images/users/user37.jpg" alt="user-image" class="rounded-full w-[35px]">
                    <span class="absolute ltr:right-0 rtl:left-0 bottom-0 w-[12px] h-[12px] rounded-full bg-success-500 border-[1px] border-white dark:border-[#0c1427]"></span>
                </div>
                <div>
                    <span class="block font-semibold text-gray-900 dark:text-gray-400">
                        Zinia Watson
                    </span>
                    <span class="block text-xs mt-[3px]">
                        Lawyer
                    </span>
                </div>
                <a routerLink="." class="absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 text-lg inline-block transition-all hover:text-primary-500">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="relative flex items-center gap-[12px] py-[10.5px] border-b first:border-t border-primary-50 dark:border-[#172036]">
                <div class="relative ltr:pr-[2px] rtl:pl-[2px] pb-[2px]">
                    <img src="images/users/user38.jpg" alt="user-image" class="rounded-full w-[35px]">
                    <span class="absolute ltr:right-0 rtl:left-0 bottom-0 w-[12px] h-[12px] rounded-full bg-success-500 border-[1px] border-white dark:border-[#0c1427]"></span>
                </div>
                <div>
                    <span class="block font-semibold text-gray-900 dark:text-gray-400">
                        Angela Carter
                    </span>
                    <span class="block text-xs mt-[3px]">
                        Businesswoman
                    </span>
                </div>
                <a routerLink="." class="absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 text-lg inline-block transition-all hover:text-primary-500">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="relative flex items-center gap-[12px] py-[10.5px] border-b first:border-t border-primary-50 dark:border-[#172036]">
                <div class="relative ltr:pr-[2px] rtl:pl-[2px] pb-[2px]">
                    <img src="images/users/user39.jpg" alt="user-image" class="rounded-full w-[35px]">
                    <span class="absolute ltr:right-0 rtl:left-0 bottom-0 w-[12px] h-[12px] rounded-full bg-gray-400 border-[1px] border-white dark:border-[#0c1427]"></span>
                </div>
                <div>
                    <span class="block font-semibold text-gray-900 dark:text-gray-400">
                        Skyler White
                    </span>
                    <span class="block text-xs mt-[3px]">
                        Enterpreuner
                    </span>
                </div>
                <a routerLink="." class="absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 text-lg inline-block transition-all hover:text-primary-500">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="relative flex items-center gap-[12px] py-[10.5px] border-b first:border-t border-primary-50 dark:border-[#172036]">
                <div class="relative ltr:pr-[2px] rtl:pl-[2px] pb-[2px]">
                    <img src="images/users/user40.jpg" alt="user-image" class="rounded-full w-[35px]">
                    <span class="absolute ltr:right-0 rtl:left-0 bottom-0 w-[12px] h-[12px] rounded-full bg-success-500 border-[1px] border-white dark:border-[#0c1427]"></span>
                </div>
                <div>
                    <span class="block font-semibold text-gray-900 dark:text-gray-400">
                        Jane Ronan
                    </span>
                    <span class="block text-xs mt-[3px]">
                        Editor
                    </span>
                </div>
                <a routerLink="." class="absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 text-lg inline-block transition-all hover:text-primary-500">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="relative flex items-center gap-[12px] py-[10.5px] border-b first:border-t border-primary-50 dark:border-[#172036]">
                <div class="relative ltr:pr-[2px] rtl:pl-[2px] pb-[2px]">
                    <img src="images/users/user42.jpg" alt="user-image" class="rounded-full w-[35px]">
                    <span class="absolute ltr:right-0 rtl:left-0 bottom-0 w-[12px] h-[12px] rounded-full bg-gray-400 border-[1px] border-white dark:border-[#0c1427]"></span>
                </div>
                <div>
                    <span class="block font-semibold text-gray-900 dark:text-gray-400">
                        Viktor James
                    </span>
                    <span class="block text-xs mt-[3px]">
                        Businessman
                    </span>
                </div>
                <a routerLink="." class="absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 text-lg inline-block transition-all hover:text-primary-500">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
        </ul>
    </div>
</div>
