// landing-pages/angular-tailwindcss/src/app/ecommerce-demo/common/testimonials/testimonials.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-testimonials',
    imports: [RouterLink],
    templateUrl: './testimonials.component.html',
    styleUrl: './testimonials.component.scss'
})
export class TestimonialsComponent {}
<div class="pb-[70px] md:pb-[90px] lg:pb-[110px] xl:pb-[150px] 2xl:pb-[180px] relative z-[1]">
    <div class="container sm:max-w-[540px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1308px] mx-auto px-[12px]">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-[18px] md:gap-[22px] mb-[35px] md:mb-[45px] lg:mb-[55px] xl:mb-[65px] items-center">
            <div>
                <span class="inline-block py-[4.5px] px-[15px] text-primary-600 bg-primary-50 dark:bg-gray-900 rounded-[100px] mb-[12px]">
                    Customer Testimonials
                </span>
                <h2 class="!text-gray-900 dark:!text-white !font-medium md:-tracking-[1px] !text-xl md:!text-3xl lg:!text-4xl xl:!text-5xl xl:max-w-[570px] !leading-[1.2] !mb-[11px] md:!mb-[13px] lg:!mb-[15px]">
                    What Store Owners Say About Trezo
                </h2>
                <p class="!leading-[1.6]">
                    Real feedback from real users — building better eCommerce with Trezo.
                </p>
            </div>
            <div class="ltr:lg:text-right rtl:lg:text-left">
                <a routerLink="/testimonials" class="inline-block py-[9px] px-[25px] md:py-[10.5px] md:px-[30px] font-medium text-white bg-primary-500 rounded-[100px] border border-primary-500 transition-all hover:bg-primary-600 hover:border-primary-600">
                    View All Feedback
                </a>
            </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[25px]">
            <div class="px-[20px] py-[30px] md:px-[30px] md:py-[40px] lg:px-[40px] lg:py-[50px] xl:px-[50px] xl:py-[60px] bg-white dark:bg-[#0a0e19] rounded-[15px] relative z-[1]">
                <div class="flex items-center text-orange-400 leading-none text-md lg:text-lg gap-[3px] mb-[18px] md:mb-[22px] lg:mb-[30px]">
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                </div>
                <p class="md:text-[15px] lg:text-md !leading-[1.6]">
                    Trezo has completely transformed how we run our store. The real-time dashboard gives us a clear view of sales and stock, and the marketing tools helped us scale faster than expected. It’s like having a full team behind us.
                </p>
                <div class="flex items-center gap-[12px] mt-[20px] md:mt-[25px] lg:mt-[40px] xl:mt-[50px]">
                    <img src="images/ecommerce/users/user1.jpg" class="rounded-full w-[42px]" alt="user-image">
                    <div>
                        <h5 class="!text-base !mb-[4px] !font-semibold !text-gray-800 dark:!text-gray-100">
                            Alex H.
                        </h5>
                        <span class="block">
                            Apparel Store Owner
                        </span>
                    </div>
                </div>
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.20) 100%), linear-gradient(180deg, #FAF5FF 0%, #ECF0FF 100%);"
                ></div>
            </div>
            <div class="px-[20px] py-[30px] md:px-[30px] md:py-[40px] lg:px-[40px] lg:py-[50px] xl:px-[50px] xl:py-[60px] bg-white dark:bg-[#0a0e19] rounded-[15px] relative z-[1]">
                <div class="flex items-center text-orange-400 leading-none text-md lg:text-lg gap-[3px] mb-[18px] md:mb-[22px] lg:mb-[30px]">
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                </div>
                <p class="md:text-[15px] lg:text-md !leading-[1.6]">
                    We were juggling multiple tools for sales tracking, email, & product analytics — until we found Trezo. Now everything’s in one place. It saves time, reduces errors, & helps us grow smarter. Highly recommended for serious store owners.
                </p>
                <div class="flex items-center gap-[12px] mt-[20px] md:mt-[25px] lg:mt-[40px] xl:mt-[50px]">
                    <img src="images/ecommerce/users/user2.jpg" class="rounded-full w-[42px]" alt="user-image">
                    <div>
                        <h5 class="!text-base !mb-[4px] !font-semibold !text-gray-800 dark:!text-gray-100">
                            Monica R.
                        </h5>
                        <span class="block">
                            Shopify Seller
                        </span>
                    </div>
                </div>
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.20) 100%), linear-gradient(180deg, #FAF5FF 0%, #ECF0FF 100%);"
                ></div>
            </div>
            <div class="px-[20px] py-[30px] md:px-[30px] md:py-[40px] lg:px-[40px] lg:py-[50px] xl:px-[50px] xl:py-[60px] bg-white dark:bg-[#0a0e19] rounded-[15px] relative z-[1]">
                <div class="flex items-center text-orange-400 leading-none text-md lg:text-lg gap-[3px] mb-[18px] md:mb-[22px] lg:mb-[30px]">
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                </div>
                <p class="md:text-[15px] lg:text-md !leading-[1.6]">
                    I love how intuitive Trezo is. Even my team members with no tech background can use it easily. The analytics are easy to digest, and the automation features are powerful. We’ve seen a big jump in engagement and retention.
                </p>
                <div class="flex items-center gap-[12px] mt-[20px] md:mt-[25px] lg:mt-[40px] xl:mt-[50px]">
                    <img src="images/ecommerce/users/user3.jpg" class="rounded-full w-[42px]" alt="user-image">
                    <div>
                        <h5 class="!text-base !mb-[4px] !font-semibold !text-gray-800 dark:!text-gray-100">
                            Daniel K.
                        </h5>
                        <span class="block">
                            Fitness Gear Retailer
                        </span>
                    </div>
                </div>
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, rgba(255, 255, 255, 0.20) 0%, rgba(255, 255, 255, 0.20) 100%), linear-gradient(180deg, #FAF5FF 0%, #ECF0FF 100%);"
                ></div>
            </div>
        </div>
    </div>
</div>

// landing-pages/react-bootstrap/ecommerce-landing/src/components/Common/Testimonials.js
"use client";

import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

const Testimonials = () => {
  // Testimonial data state
  const [testimonials, setTestimonials] = useState([]);
  const [header, setHeader] = useState({});
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Fetch testimonial data
  useEffect(() => {
    const fetchTestimonials = async () => {
      try {
        // In a real app, this would be an API call:
        // const response = await fetch('/api/testimonials');
        // const data = await response.json();

        // Mock data (replace with actual API call)
        const data = {
          header: {
            title: "Customer Testimonials",
            heading: "What Store Owners Say About Trezo",
            description:
              "Real feedback from real users — building better eCommerce with Trezo.",
          },
          testimonials: [
            {
              id: 1,
              rating: 5,
              content:
                "Trezo has completely transformed how we run our store. The real-time dashboard gives us a clear view of sales and stock, and the marketing tools helped us scale faster than expected. It's like having a full team behind us.",
              author: {
                name: "Alex H.",
                role: "Apparel Store Owner",
                image: "/images/users/user1.jpg",
              },
            },
            {
              id: 2,
              rating: 5,
              content:
                "We were juggling multiple tools for sales tracking, email, & product analytics — until we found Trezo. Now everything's in one place. It saves time, reduces errors, & helps us grow smarter. Highly recommended for serious store owners.",
              author: {
                name: "Monica R.",
                role: "Shopify Seller",
                image: "/images/users/user2.jpg",
              },
            },
            {
              id: 3,
              rating: 5,
              content:
                "As a small business, Trezo gave us enterprise-level tools at an affordable price. The inventory management alone saved us thousands in lost sales from stockouts. Customer support is incredibly responsive too.",
              author: {
                name: "Daniel K.",
                role: "Fitness Gear Retailer",
                image: "/images/users/user3.jpg",
              },
            },
          ],
        };

        setHeader(data.header);
        setTestimonials(data.testimonials);
      } catch (err) {
        setError(err.message);
        console.error("Failed to load testimonials:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchTestimonials();
  }, []);

  // Render star ratings
  const renderStars = (rating) => {
    return Array.from({ length: 5 }, (_, i) => (
      <i
        key={i}
        className={`ri-star-fill fs-18 ${
          i < rating ? "text-rating-color" : "text-muted"
        } lh-1`}
      />
    ));
  };

  if (loading)
    return <div className="text-center py-10">Loading testimonials...</div>;
  if (error)
    return (
      <div className="text-center py-10 text-danger">
        Error loading testimonials
      </div>
    );

  return (
    <>
      <div className="testimonials-area position-relative z-2 pb-180">
        <Container className="cmw-1308">
          <div className="d-flex justify-content-between flex-wrap gap-3 align-items-center mb-65">
            <div className="section-title2 m-0">
              <span className="top-title2">{header.title}</span>
              <h2>{header.heading}</h2>
              <p>{header.description}</p>
            </div>

            <Link
              to="/testimonials"
              className="btn bg-primary text-white fw-medium fs-14 rounded-pill hover-bg landing-page-btn"
            >
              View All Feedback
            </Link>
          </div>

          <Row className="g-4 justify-content-center">
            {testimonials.map((testimonial) => (
              <Col key={testimonial.id} md={6} lg={4}>
                <div className="testimonials-single-item-ecommerce">
                  <div className="d-flex mb-25" style={{ gap: "2px" }}>
                    {renderStars(testimonial.rating)}
                  </div>
                  <p className="fs-16">{testimonial.content}</p>

                  <div
                    className="d-flex align-items-center mt-50"
                    style={{ gap: "12px" }}
                  >
                    <div className="flex-shrink-0">
                      <img
                        src={testimonial.author.image}
                        className="rounded-circle"
                        alt={testimonial.author.name}
                        width={42}
                        height={42}
                      />
                    </div>
                    <div className="flex-grow-1">
                      <span
                        className="text-secondary fw-semibold d-block s-14"
                        style={{ marginBottom: "4px" }}
                      >
                        {testimonial.author.name}
                      </span>
                      <span>{testimonial.author.role}</span>
                    </div>
                  </div>
                </div>
              </Col>
            ))}
          </Row>
        </Container>
      </div>
    </>
  );
};

export default Testimonials;
