// landing-pages/react-nextjs-bootstrap/marketing-landing/src/components/Common/Partners.js
"use client";

import React from "react";
import Image from "next/image";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay } from "swiper/modules";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

const Partners = () => {
  // Dynamic data for customer avatars
  const customers = [
    { id: 1, image: "/images/users/user1.jpg", alt: "Customer 1" },
    { id: 2, image: "/images/users/user2.jpg", alt: "Customer 2" },
    { id: 3, image: "/images/users/user3.jpg", alt: "Customer 3" },
    { id: 4, image: "/images/users/user4.jpg", alt: "Customer 4" },
  ];

  // Dynamic data for partners logos
  const partners = [
    { id: 1, logo: "/images/partners/partner1.svg", alt: "Partner 1" },
    { id: 2, logo: "/images/partners/partner2.svg", alt: "Partner 2" },
    { id: 3, logo: "/images/partners/partner3.svg", alt: "Partner 3" },
    { id: 4, logo: "/images/partners/partner4.svg", alt: "Partner 4" },
    { id: 5, logo: "/images/partners/partner5.svg", alt: "Partner 5" },
  ];

  // Swiper configuration
  const swiperConfig = {
    spaceBetween: 30,
    autoplay: {
      delay: 5000,
      disableOnHover: true,
    },
    breakpoints: {
      0: { slidesPerView: 2 },
      400: { slidesPerView: 2 },
      576: { slidesPerView: 3 },
      768: { slidesPerView: 4 },
      992: { slidesPerView: 4 },
      1200: { slidesPerView: 5 },
    },
  };

  return (
    <>
      <div className="customers-growing-area">
        <Container className="cmw-1308">
          <Row className="g-4">
            <Col lg={3}>
              <div className="customers-info">
                <ul className="p-0 list-unstyled d-flex justify-content-center">
                  {customers.map((customer) => (
                    <li key={customer.id}>
                      <Image
                        src={customer.image}
                        alt={customer.alt}
                        width={40}
                        height={40}
                        className="rounded-circle"
                      />
                    </li>
                  ))}
                </ul>
                <span className="fs-14 fw-medium">50k+ Trusted Customers</span>
              </div>
            </Col>

            <Col lg={9}>
              <div className="growing-info text-center">
                <span className="fw-medium fs-16">
                  From Startups to Industry Leaders — Everyone&apos;s Growing with
                  Trezo
                </span>

                <Swiper
                  {...swiperConfig}
                  modules={[Autoplay]}
                  className="partners-slide2 z-0"
                >
                  {[...partners, ...partners].map((partner, index) => (
                    <SwiperSlide key={`${partner.id}-${index}`}>
                      <Image
                        src={partner.logo}
                        alt={partner.alt}
                        width={120}
                        height={50}
                      />
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>
            </Col>
          </Row>
        </Container>
      </div>
    </>
  );
};

export default Partners;

// landing-pages/angular-bootstrap/src/app/marketing-demo/common/partners/partners.component.ts
import { Component } from '@angular/core';
import { ToggleService } from '../../../settings/toggle.service';

@Component({
    selector: 'app-partners',
    imports: [],
    templateUrl: './partners.component.html',
    styleUrl: './partners.component.scss'
})
export class PartnersComponent {

    constructor(
        public toggleService: ToggleService
    ) {}


}
<div
    class="partners-area"
    [class.component-dark]="toggleService.isLandingDark()"
>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="trusted-customers-box text-center">
                    <div class="customers-list d-flex align-items-center justify-content-center">
                        <img src="images/marketing/users/user1.jpg" alt="user-image" class="rounded-circle">
                        <img src="images/marketing/users/user2.jpg" alt="user-image" class="rounded-circle">
                        <img src="images/marketing/users/user4.jpg" alt="user-image" class="rounded-circle">
                        <img src="images/marketing/users/user3.jpg" alt="user-image" class="rounded-circle">
                    </div>
                    <span class="d-block fw-medium">
                        50k+ Trusted Customers
                    </span>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="partners-box text-center">
                    <span class="title d-block fw-medium">
                        From Startups to Industry Leaders — Everyone’s Growing with Trezo
                    </span>
                    <div class="grid">
                        <div class="text-center">
                            <img src="images/marketing/partners/partner1.svg" alt="partner-image">
                        </div>
                        <div class="text-center">
                            <img src="images/marketing/partners/partner2.svg" alt="partner-image">
                        </div>
                        <div class="text-center">
                            <img src="images/marketing/partners/partner3.svg" alt="partner-image">
                        </div>
                        <div class="text-center">
                            <img src="images/marketing/partners/partner4.svg" alt="partner-image">
                        </div>
                        <div class="text-center">
                            <img src="images/marketing/partners/partner5.svg" alt="partner-image">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
