// vuejs-vuetify/src/components/Dashboard/RealEstateAgent/MyFeaturedListings.vue
<template>
  <v-card
    class="my-featured-listings-card trezo-card border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">My Featured Listings</h5>

      <div class="">
        <div class="swiper-pagination-my-featured-listings"></div>
      </div>
    </div>

    <div class="trezo-card-content">
      <Swiper
        :slidesPerView="1"
        :spaceBetween="30"
        :centeredSlides="false"
        :preventClicks="true"
        :loop="false"
        :autoplay="{
          delay: 5000,
          disableOnInteraction: false,
          pauseOnMouseEnter: true,
        }"
        :pagination="{
          el: '.swiper-pagination-my-featured-listings',
          clickable: true,
        }"
        :breakpoints="{
          0: {
            slidesPerView: 1,
          },
          576: {
            slidesPerView: 1,
          },
          768: {
            slidesPerView: 2,
          },
          992: {
            slidesPerView: 2,
          },
          1200: {
            slidesPerView: 2,
          },
          1440: {
            slidesPerView: 2,
          },
          1850: {
            slidesPerView: 2,
          },
        }"
        :modules="modules"
        class="my-featured-listings-slide"
      >
        <SwiperSlide
          v-for="(property, index) in featuredProperties"
          :key="index"
        >
          <div
            class="image position-relative"
            :style="{
              'background-image': `url(${property.image})`,
            }"
          >
            <span class="trezo-badge rejected">
              {{ property.type }}
            </span>
          </div>
          <div class="content bg-white">
            <h6 class="fw-semibold">
              <RouterLink to="/real-estate-agent/property-details">
                {{ property.title }}
              </RouterLink>
            </h6>
            <span class="d-block text-body">
              {{ property.location }}
            </span>
            <ul
              class="p-0 mb-0 list-unstyled d-flex align-items-center justify-content-between"
            >
              <li class="text-xs text-black position-relative">
                <i class="material-symbols-outlined"> open_run </i>
                {{ property.area }} Sft
              </li>
              <li class="text-xs text-black position-relative">
                <i class="material-symbols-outlined"> bed </i>
                {{ property.bedrooms }} Bed
              </li>
              <li class="text-xs text-black position-relative">
                <i class="material-symbols-outlined"> bathtub </i>
                {{ property.bathrooms }} Bath
              </li>
            </ul>
            <div class="info d-flex align-items-center justify-content-between">
              <div class="price lh-1 fw-bold text-black">
                ${{ property.price }}/m
              </div>
              <RouterLink
                to="/real-estate-agent/property-details"
                class="link-btn d-flex align-items-center justify-content-center rounded-circle"
              >
                <i class="ri-arrow-right-line"></i>
              </RouterLink>
            </div>
          </div>
        </SwiperSlide>
      </Swiper>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { Swiper, SwiperSlide } from "swiper/vue";
import { Autoplay, Pagination } from "swiper/modules";

interface Property {
  id: number;
  image: string;
  type: string;
  title: string;
  location: string;
  area: number;
  bedrooms: number;
  bathrooms: number;
  price: number;
}

export default defineComponent({
  name: "MyFeaturedListings",
  components: {
    Swiper,
    SwiperSlide,
  },
  setup() {
    const featuredProperties = ref<Property[]>([
      {
        id: 1,
        image: require("@/assets/images/property-1.jpg"),
        type: "For Rent",
        title: "Luxury Comfort Villa",
        location: "London, United Kingdom",
        area: 425,
        bedrooms: 3,
        bathrooms: 2,
        price: 4274,
      },
      {
        id: 2,
        image: require("@/assets/images/property-2.jpg"),
        type: "For Rent",
        title: "White House Villa",
        location: "New Castle, United Kingdom",
        area: 321,
        bedrooms: 2,
        bathrooms: 1,
        price: 4274,
      },
      {
        id: 3,
        image: require("@/assets/images/property-1.jpg"),
        type: "For Rent",
        title: "Luxury Comfort Villa",
        location: "London, United Kingdom",
        area: 425,
        bedrooms: 3,
        bathrooms: 2,
        price: 4274,
      },
      {
        id: 4,
        image: require("@/assets/images/property-2.jpg"),
        type: "For Rent",
        title: "White House Villa",
        location: "New Castle, United Kingdom",
        area: 321,
        bedrooms: 2,
        bathrooms: 1,
        price: 4274,
      },
    ]);

    return {
      modules: [Autoplay, Pagination],
      featuredProperties,
    };
  },
});
</script>

<style scoped lang="scss">
.my-featured-listings-card {
  &.v-card {
    &.trezo-card {
      background-color: #ffe8d4 !important;
    }
  }

  .trezo-card-content {
    .image {
      height: 202px;
      border-radius: 7px 7px 0 0;
      background: {
        position: center center;
        repeat: no-repeat;
        size: cover;
      }
      .trezo-badge {
        top: 10px;
        left: 10px;
        position: absolute;
      }
    }
    .content {
      padding: 20px;
      border-radius: 0 0 7px 7px;

      h6 {
        font-size: 16px;
        margin-bottom: 5px;
      }
      ul {
        margin-top: 13px;

        li {
          padding-left: 23px;

          i {
            left: 0;
            top: 50%;
            font-size: 18px;
            position: absolute;
            color: var(--bodyColor);
            transform: translateY(-50%);
          }
        }
      }
      .info {
        border-top: 1px solid var(--borderColor);
        padding-top: 13px;
        margin-top: 13px;

        .price {
          font-size: 16px;
        }
        .link-btn {
          width: 30px;
          height: 30px;
          color: var(--bodyColor);
          background-color: var(--borderColor);

          &:hover {
            color: var(--whiteColor);
            background-color: var(--primaryColor);
          }
        }
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .my-featured-listings-card {
    .trezo-card-content {
      .content {
        padding: 17px;
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
  .my-featured-listings-card {
    .trezo-card-content {
      .content {
        padding: 20px;
      }
    }
  }
}
</style>

// react-bootstrap/src/components/Dashboard/RealEstateAgent/MyFeaturedListings.js
"use client";

import React, { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from "swiper/modules";

const MyFeaturedListings = () => {
  // State for listings data
  const [listings, setListings] = useState([]);

  // Fetch listings data (mock API call)
  useEffect(() => {
    const fetchListings = async () => {
      try {
        // Simulated API response
        const mockData = [
          {
            id: 1,
            title: "Luxury Comfort Villa",
            location: "London, United Kingdom",
            image: "/images/property-1.jpg",
            status: "For Rent",
            size: "425 Sft",
            beds: "3 Bed",
            baths: "2 Bath",
            price: "$4,274/m",
            link: "/real-estate-agent/property-details/",
          },
          {
            id: 2,
            title: "White House Villa",
            location: "New Castle, United Kingdom",
            image: "/images/property-2.jpg",
            status: "For Rent",
            size: "321 Sft",
            beds: "2 Bed",
            baths: "1 Bath",
            price: "$4,274/m",
            link: "/real-estate-agent/property-details/",
          },
          {
            id: 3,
            title: "Luxury Comfort Villa",
            location: "London, United Kingdom",
            image: "/images/property-1.jpg",
            status: "For Rent",
            size: "425 Sft",
            beds: "3 Bed",
            baths: "2 Bath",
            price: "$4,274/m",
            link: "/real-estate-agent/property-details/",
          },
          {
            id: 4,
            title: "White House Villa",
            location: "New Castle, United Kingdom",
            image: "/images/property-2.jpg",
            status: "For Rent",
            size: "321 Sft",
            beds: "2 Bed",
            baths: "1 Bath",
            price: "$4,274/m",
            link: "/real-estate-agent/property-details/",
          },
        ];

        setListings(mockData);
      } catch (error) {
        console.error("Error fetching listings:", error);
      }
    };

    fetchListings();
  }, []);

  return (
    <>
      <div className="border-0 rounded-3 position-relative p-25 bg-card-text-c my-featured-listings-bg">
        <div className="d-flex justify-content-between align-items-center flex-wrap gap-1 mb-4">
          <h3 className="mb-0">My Featured Listings</h3>
        </div>

        <Swiper
          spaceBetween={25}
          pagination={{
            clickable: true,
          }}
          autoplay={{
            delay: 5000,
            disableOnInteraction: false,
            pauseOnMouseEnter: true,
          }}
          breakpoints={{
            0: {
              slidesPerView: 1,
            },
            576: {
              slidesPerView: 1,
            },
            768: {
              slidesPerView: 2,
            },
          }}
          modules={[Pagination, Autoplay]}
          className="my-featured-listings-slide z-0"
        >
          {listings.map((listing) => (
            <SwiperSlide key={listing.id}>
              <Link
                to={listing.link}
                className="text-decoration-none position-relative d-block"
              >
                <div
                  className="position-relative z-1 bg-img rounded-top-2"
                  style={{
                    backgroundImage: `url(${listing.image})`,
                    height: "202px",
                  }}
                >
                  <div className="position-absolute top-0 start-0 m-2">
                    <span
                      className="d-inline-block bg-card-text-c px-2 rounded-1 text-danger-50 fs-12 fw-medium"
                      style={{
                        paddingTop: "3px",
                        paddingBottom: "3px",
                      }}
                    >
                      {listing.status}
                    </span>
                  </div>
                </div>

                <div
                  className="bg-white rounded-bottom-2"
                  style={{
                    padding: "20px",
                  }}
                >
                  <h3
                    className="fs-16 fw-semibold"
                    style={{ marginBottom: "6px" }}
                  >
                    {listing.title}
                  </h3>

                  <span className="text-body">{listing.location}</span>

                  <ul
                    className="px-0 border-bottom list-unstyled d-flex justify-content-between align-items-center"
                    style={{
                      paddingBottom: "13px",
                      marginBottom: "13px",
                      marginTop: "13px",
                    }}
                  >
                    <li className="d-flex align-items-center gap-1 text-body">
                      <i className="material-symbols-outlined fs-18">
                        open_run{" "}
                      </i>
                      <span>{listing.size}</span>
                    </li>

                    <li className="d-flex align-items-center gap-1 text-body">
                      <i className="material-symbols-outlined fs-18">bed </i>
                      <span>{listing.beds}</span>
                    </li>

                    <li className="d-flex align-items-center gap-1 text-body">
                      <i className="material-symbols-outlined fs-18">
                        bathtub{" "}
                      </i>
                      <span>{listing.baths}</span>
                    </li>
                  </ul>

                  <div className="d-flex justify-content-between align-items-center">
                    <h3 className="mb-0">{listing.price}</h3>
                    <i className="ri-arrow-right-line wh-30 d-flex justify-content-center align-items-center bg-border-color rounded-circle hover-bg lh-1"></i>
                  </div>
                </div>
              </Link>
            </SwiperSlide>
          ))}
        </Swiper>
      </div>
    </>
  );
};

export default MyFeaturedListings;
