// landing-pages/react-nextjs-bootstrap/ecommerce-landing/src/components/Layout/Footer.js
"use client";

import React from "react";
import Image from "next/image";
import Link from "next/link";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

const Footer = () => {
  return (
    <>
      <div
        className="footer-area-ecommerce ptb-180"
        style={{
          background: " linear-gradient(180deg, #FFFFFF 0%, #DDE4FF 100%)",
        }}
      >
        <Container className="cmw-1308">
          <Row className="g-4 justify-content-center">
            <Col sm={6} lg={3}>
              <div className="footer-single-item-ecommerce">
                <Link href="/" className="logo">
                  <Image
                    src="/images/black-logo.svg"
                    className="black-logo"
                    alt="black-logo"
                    width={132}
                    height={34}
                  />
                  <Image
                    src="/images/white-logo.svg"
                    className="d-none white-logo"
                    alt="white-logo"
                    width={132}
                    height={34}
                  />
                </Link>

                <p className="dec">
                  Your all-in-one marketing command center — built to help you
                  grow, scale, and win smarter.
                </p>

                <ul
                  className="d-flex align-items-center p-0 mb-0 list-unstyled social-link"
                  style={{
                    gap: "8px",
                  }}
                >
                  <li>
                    <a href="https://www.facebook.com/" target="_blank">
                      <i className="ri-facebook-fill"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://www.twitter.com/" target="_blank">
                      <i className="ri-twitter-x-line"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://www.linkedin.com/" target="_blank">
                      <i className="ri-linkedin-fill"></i>
                    </a>
                  </li>
                  <li>
                    <a href="https://www.dribbble.com/" target="_blank">
                      <i className="ri-dribbble-line"></i>
                    </a>
                  </li>
                </ul>
              </div>
            </Col>

            <Col sm={6} lg={3}>
              <div className="footer-single-item-ecommerce pl-130">
                <h3>Quick Links</h3>
                <ul className="p-0 m-0 list-unstyled import-link">
                  <li>
                    <Link href="/">Home</Link>
                  </li>
                  <li>
                    <Link href="/features">Features</Link>
                  </li>
                  <li>
                    <Link href="/pricing">Pricing Plans</Link>
                  </li>
                  <li>
                    <Link href="/use-cases">Use Cases</Link>
                  </li>
                </ul>
              </div>
            </Col>

            <Col sm={6} lg={3}>
              <div className="footer-single-item-ecommerce pl-130">
                <h3>Resources</h3>
                <ul className="p-0 m-0 list-unstyled import-link">
                  <li>
                    <Link href="#">Help Center</Link>
                  </li>
                  <li>
                    <Link href="#">Documentation</Link>
                  </li>
                  <li>
                    <Link href="#">Blog</Link>
                  </li>
                  <li>
                    <Link href="#">Contact</Link>
                  </li>
                </ul>
              </div>
            </Col>

            <Col sm={6} lg={3}>
              <div className="footer-single-item-ecommerce pl-80">
                <h3>Get in Touch</h3>
                <ul className="p-0 m-0 list-unstyled info-link">
                  <li>
                    <span>Email:</span>{" "}
                    <a href="mailto:support@trezo.com">support@trezo.com</a>
                  </li>
                  <li>
                    <span>Phone:</span>{" "}
                    <a href="tel:+1(555)123-4567">+1 (555) 123-4567m</a>
                  </li>
                  <li>
                    <p>
                      <span>Location:</span> 123 Learning Ave, Knowledge City,
                      USA
                    </p>
                  </li>
                </ul>
              </div>
            </Col>
          </Row>
        </Container>
      </div>

      <div className="copyright-area-ecommerce">
        <Container className="cmw-1308">
          <div className="d-flex flex-wrap gap-2 justify-content-center justify-content-md-between align-items-center">
            <p className="fs-14 mb-0">
              © <span className="text-primary-div">Trezo</span> is Proudly Owned
              by{" "}
              <a
                href="https://envytheme.com/"
                target="_blank"
                className="text-decoration-none text-primary"
              >
                EnvyTheme
              </a>
            </p>
            <ul className="p-0 m-0 list-unstyled d-flex flex-wrap justify-content-center justify-content-md-end terms-info">
              <li>
                <Link href="#">Terms of Service</Link>
              </li>
              <li>
                <Link href="#">Privacy Policy</Link>
              </li>
              <li>
                <Link href="#">Cookie Policy</Link>
              </li>
            </ul>
          </div>
        </Container>
      </div>
    </>
  );
};

export default Footer;

// landing-pages/angular-bootstrap/src/app/marketing-demo/common/footer/footer.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ToggleService } from '../../../settings/toggle.service';

@Component({
    selector: 'app-footer',
    imports: [RouterLink],
    templateUrl: './footer.component.html',
    styleUrl: './footer.component.scss'
})
export class FooterComponent {

    constructor(
        public toggleService: ToggleService
    ) {}

}
<div class="container">
    <div
        class="border-top"
        [class.component-dark]="toggleService.isLandingDark()"
    ></div>
</div>

<footer
    class="footer-area pt-180 pb-155"
    [class.component-dark]="toggleService.isLandingDark()"
    [class.component-rtl]="toggleService.isLandingRtlEnabled()"
>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget">
                    <a routerLink="/marketing-demo" class="logo d-inline-block">
                        <img src="images/marketing/logo.svg" alt="logo">
                        <img src="images/marketing/white-logo.svg" class="d-none" alt="logo">
                    </a>
                    <p>
                        Your all-in-one marketing command center — built to help you grow, scale, and win smarter.
                    </p>
                    <div class="social-links">
                        <a href="#" target="_blank">
                            <i class="ri-facebook-fill"></i>
                        </a>
                        <a href="#" target="_blank">
                            <i class="ri-twitter-x-fill"></i>
                        </a>
                        <a href="#" target="_blank">
                            <i class="ri-linkedin-fill"></i>
                        </a>
                        <a href="#" target="_blank">
                            <i class="ri-dribbble-fill"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget">
                    <h3 class="fw-semibold">
                        Quick Links
                    </h3>
                    <ul class="custom-links m-0 p-0 list-unstyled">
                        <li>
                            <a routerLink=".">
                                Home
                            </a>
                        </li>
                        <li>
                            <a routerLink=".">
                                Features
                            </a>
                        </li>
                        <li>
                            <a routerLink=".">
                                Pricing Plans
                            </a>
                        </li>
                        <li>
                            <a routerLink=".">
                                Use Cases
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget">
                    <h3 class="fw-semibold">
                        Resources
                    </h3>
                    <ul class="custom-links m-0 p-0 list-unstyled">
                        <li>
                            <a routerLink=".">
                                Help Center
                            </a>
                        </li>
                        <li>
                            <a routerLink=".">
                                Documentation
                            </a>
                        </li>
                        <li>
                            <a routerLink=".">
                                Blog
                            </a>
                        </li>
                        <li>
                            <a routerLink=".">
                                Contact
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget">
                    <h3 class="fw-semibold">
                        Get in Touch
                    </h3>
                    <ul class="footer-info m-0 p-0 list-unstyled">
                        <li>
                            Email: <a href="mailto:support@trezo.com">support&#64;trezo.com</a>
                        </li>
                        <li>
                            Phone: <a href="tell:+1(555)123-4567">+1 (555) 123-4567</a>
                        </li>
                        <li>
                            Location: <span class="fw-semibold">123 Learning Ave, Knowledge City, USA</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<div
    class="copyright-area"
    [class.component-dark]="toggleService.isLandingDark()"
    [class.component-rtl]="toggleService.isLandingRtlEnabled()"
>
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <p>
                    © <span>Trezo</span> is Proudly Owned by <a href="https://envytheme.com/" target="_blank">EnvyTheme</a>
                </p>
            </div>
            <div class="col-lg-6">
                <ul class="p-0 m-0 list-unstyled">
                    <li class="position-relative d-inline-block">
                        <a routerLink=".">
                            Terms of Service
                        </a>
                    </li>
                    <li class="position-relative d-inline-block">
                        <a routerLink=".">
                            Privacy Policy
                        </a>
                    </li>
                    <li class="position-relative d-inline-block">
                        <a routerLink=".">
                            Cookie Policy
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
