// angular-material/src/app/dashboard/sales/recent-orders/recent-orders.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { NgIf } from '@angular/common';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-recent-orders',
    imports: [MatCardModule, MatButtonModule, MatMenuModule, MatTableModule, MatPaginatorModule, NgIf],
    templateUrl: './recent-orders.component.html',
    styleUrl: './recent-orders.component.scss'
})
export class RecentOrdersComponent {

    displayedColumns: string[] = ['orderID', 'customer', 'created', 'total', 'status'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

    @ViewChild(MatPaginator) paginator!: MatPaginator;

    ngAfterViewInit() {
        this.dataSource.paginator = this.paginator;
    }

    // Search Filter
    applyFilter(event: Event) {
        const filterValue = (event.target as HTMLInputElement).value;
        this.dataSource.filter = filterValue.trim().toLowerCase();
    }

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}

export interface PeriodicElement {
    orderID: string;
    customer: any;
    created: string;
    total: string;
    status: any;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        orderID: '#JAN-2345',
        customer: {
            img: 'images/users/user1.jpg',
            name: 'Sarah Johnson'
        },
        created: '12 Jun 2025',
        total: '$10,490',
        status: {
            confirmed: false,
            shipped: true,
            pending: false,
            rejected: false
        }
    },
    {
        orderID: '#JAN-1323',
        customer: {
            img: 'images/users/user2.jpg',
            name: 'Michael Smith'
        },
        created: '11 Jun 2025',
        total: '$6,575',
        status: {
            confirmed: true,
            shipped: false,
            pending: false,
            rejected: false
        }
    },
    {
        orderID: '#DEC-1234',
        customer: {
            img: 'images/users/user3.jpg',
            name: 'Emily Brown'
        },
        created: '10 Jun 2025',
        total: '$12,870',
        status: {
            confirmed: false,
            shipped: false,
            pending: true,
            rejected: false
        }
    },
    {
        orderID: '#DEC-3567',
        customer: {
            img: 'images/users/user4.jpg',
            name: 'Jason Lee'
        },
        created: '09 Jun 2025',
        total: '$7,895',
        status: {
            confirmed: false,
            shipped: true,
            pending: false,
            rejected: false
        }
    },
    {
        orderID: '#DEC-1098',
        customer: {
            img: 'images/users/user5.jpg',
            name: 'Ashley Davis'
        },
        created: '08 Jun 2025',
        total: '$4,680',
        status: {
            confirmed: false,
            shipped: false,
            pending: false,
            rejected: true
        }
    },
    {
        orderID: '#JAN-1323',
        customer: {
            img: 'images/users/user2.jpg',
            name: 'Michael Smith'
        },
        created: '11 Jun 2025',
        total: '$6,575',
        status: {
            confirmed: true,
            shipped: false,
            pending: false,
            rejected: false
        }
    },
    {
        orderID: '#JAN-2345',
        customer: {
            img: 'images/users/user1.jpg',
            name: 'Sarah Johnson'
        },
        created: '12 Jun 2025',
        total: '$10,490',
        status: {
            confirmed: false,
            shipped: false,
            pending: false,
            rejected: true
        }
    },
    {
        orderID: '#DEC-3567',
        customer: {
            img: 'images/users/user4.jpg',
            name: 'Jason Lee'
        },
        created: '09 Jun 2025',
        total: '$7,895',
        status: {
            confirmed: false,
            shipped: true,
            pending: false,
            rejected: false
        }
    },
    {
        orderID: '#DEC-1234',
        customer: {
            img: 'images/users/user3.jpg',
            name: 'Emily Brown'
        },
        created: '10 Jun 2025',
        total: '$12,870',
        status: {
            confirmed: true,
            shipped: false,
            pending: false,
            rejected: false
        }
    },
    {
        orderID: '#DEC-3567',
        customer: {
            img: 'images/users/user4.jpg',
            name: 'Jason Lee'
        },
        created: '09 Jun 2025',
        total: '$7,895',
        status: {
            confirmed: true,
            shipped: false,
            pending: false,
            rejected: false
        }
    }
];

// laravel-vuetify/resources/components/Modules/Tables/BasicTable/RecentOrders.vue
<template>
    <v-card
        class="recent-orders-card mb-25 trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Recent Orders</h5>
            <div class="d-flex align-items-center">
                <v-menu>
                    <template v-slot:activator="{ props }">
                        <button
                            type="button"
                            v-bind="props"
                            class="card-header-menu d-inline-block border-radius"
                        >
                            Show All
                        </button>
                    </template>
                    <v-list class="menu-content">
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Day
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Week
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Month
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Year
                        </button>
                    </v-list>
                </v-menu>
            </div>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th class="text-start">Order ID</th>
                            <th class="text-start">Customer</th>
                            <th class="text-start">Created</th>
                            <th class="text-start">Total</th>
                            <th class="text-start">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr
                            v-for="item in filteredItems.slice(0, 5)"
                            :key="item.orderID"
                        >
                            <td>{{ item.orderID }}</td>
                            <td class="text-start">
                                <div
                                    class="customer-info d-flex align-items-center"
                                >
                                    <div class="img">
                                        <v-img
                                            :src="item.customer.image"
                                            alt="customer"
                                        />
                                    </div>
                                    <span
                                        class="d-block text-black fw-medium"
                                        >{{ item.customer.name }}</span
                                    >
                                </div>
                            </td>
                            <td>{{ item.created }}</td>
                            <td>${{ item.total }}</td>
                            <td>
                                <span
                                    class="trezo-status-badge"
                                    :class="computeClass(item.status)"
                                >
                                    {{ item.status }}
                                </span>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref, computed } from "vue";

import user1 from "../../../../../public/images/users/user1.jpg";
import user2 from "../../../../../public/images/users/user2.jpg";
import user3 from "../../../../../public/images/users/user3.jpg";
import user4 from "../../../../../public/images/users/user4.jpg";
import user5 from "../../../../../public/images/users/user5.jpg";

export default defineComponent({
    name: "RecentOrders",
    setup() {
        const items = ref([
            {
                orderID: "#JAN-2345",
                customer: {
                    image: user1,
                    name: "Sarah Johnson",
                },
                created: "20 Jun, 2024",
                total: "10,490",
                status: "Shipped",
            },
            {
                orderID: "#JAN-1323",
                customer: {
                    image: user2,
                    name: "Michael Smith",
                },
                created: "19 Jun, 2024",
                total: "6,575",
                status: "Confirmed",
            },
            {
                orderID: "#DEC-1234",
                customer: {
                    image: user3,
                    name: "Emily Brown",
                },
                created: "18 Jun, 2024",
                total: "12,870",
                status: "Pending",
            },
            {
                orderID: "#DEC-3567",
                customer: {
                    image: user4,
                    name: "Jason Lee",
                },
                created: "17 Jun, 2024",
                total: "7,895",
                status: "Shipped",
            },
            {
                orderID: "#DEC-1098",
                customer: {
                    image: user5,
                    name: "Ashley Davis",
                },
                created: "16 Jun, 2024",
                total: "4,680",
                status: "Rejected",
            },
            {
                orderID: "#DEC-3567",
                customer: {
                    image: user4,
                    name: "Jason Lee",
                },
                created: "17 Jun, 2024",
                total: "7,895",
                status: "Shipped",
            },
            {
                orderID: "#DEC-1098",
                customer: {
                    image: user5,
                    name: "Ashley Davis",
                },
                created: "16 Jun, 2024",
                total: "4,680",
                status: "Rejected",
            },
            {
                orderID: "#JAN-2345",
                customer: {
                    image: user5,
                    name: "Sarah Johnson",
                },
                created: "20 Jun, 2024",
                total: "10,490",
                status: "Shipped",
            },
            {
                orderID: "#JAN-1323",
                customer: {
                    image: user4,
                    name: "Michael Smith",
                },
                created: "19 Jun, 2024",
                total: "6,575",
                status: "Confirmed",
            },
            {
                orderID: "#DEC-1234",
                customer: {
                    image: user3,
                    name: "Emily Brown",
                },
                created: "18 Jun, 2024",
                total: "12,870",
                status: "Pending",
            },
            {
                orderID: "#DEC-3567",
                customer: {
                    image: user2,
                    name: "Jason Lee",
                },
                created: "17 Jun, 2024",
                total: "7,895",
                status: "Shipped",
            },
            {
                orderID: "#DEC-1098",
                customer: {
                    image: user1,
                    name: "Ashley Davis",
                },
                created: "16 Jun, 2024",
                total: "4,680",
                status: "Rejected",
            },
        ]);

        const searchTerm = ref("");

        const filteredItems = computed(() => {
            return items.value.filter(
                (item) =>
                    item.orderID
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.customer.name
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.created
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.total
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.status
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase())
            );
        });

        const wordConfirmed = ref("Confirmed");
        const wordShipped = ref("Shipped");
        const wordPending = ref("Pending");
        const wordRejected = ref("Rejected");

        const computeClass = (classValue) => {
            return {
                confirmed: wordConfirmed.value === classValue,
                shipped: wordShipped.value === classValue,
                pending: wordPending.value === classValue,
                rejected: wordRejected.value === classValue,
            };
        };

        return {
            searchTerm,
            filteredItems,
            computeClass,
        };
    },
});
</script>
