// angular-material/src/app/dashboard/helpdesk/recent-customer-ratings/recent-customer-ratings.component.ts
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';

@Component({
    selector: 'app-recent-customer-ratings',
    imports: [MatCardModule, MatButtonModule, MatMenuModule, MatTableModule, MatPaginatorModule],
    templateUrl: './recent-customer-ratings.component.html',
    styleUrl: './recent-customer-ratings.component.scss'
})
export class RecentCustomerRatingsComponent {

    displayedColumns: string[] = ['user', 'date', 'ratings'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

    @ViewChild(MatPaginator) paginator!: MatPaginator;

    ngAfterViewInit() {
        this.dataSource.paginator = this.paginator;
    }

}

export interface PeriodicElement {
    user: any;
    date: string;
    ratings: any;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        user: {
            img: 'images/users/user13.jpg',
            name: 'Olivia Clark',
            email: 'Big Data'
        },
        date: '28 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user16.jpg',
            name: 'Ethan Parker',
            email: 'Python'
        },
        date: '25 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-half-fill'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user17.jpg',
            name: 'Ava Turner',
            email: 'UX/UI'
        },
        date: '23 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-line'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user18.jpg',
            name: 'Lucas Morgan',
            email: 'Developer'
        },
        date: '20 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-half-fill'
            },
            {
                star: 'ri-star-line'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user19.jpg',
            name: 'Isabella Cooper',
            email: 'Designer'
        },
        date: '15 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user19.jpg',
            name: 'Isabella Cooper',
            email: 'Designer'
        },
        date: '15 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user18.jpg',
            name: 'Lucas Morgan',
            email: 'Developer'
        },
        date: '20 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-half-fill'
            },
            {
                star: 'ri-star-line'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user16.jpg',
            name: 'Ethan Parker',
            email: 'Python'
        },
        date: '25 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-half-fill'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user17.jpg',
            name: 'Ava Turner',
            email: 'UX/UI'
        },
        date: '23 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-line'
            }
        ]
    },
    {
        user: {
            img: 'images/users/user13.jpg',
            name: 'Olivia Clark',
            email: 'Big Data'
        },
        date: '28 April 2025',
        ratings: [
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            },
            {
                star: 'ri-star-fill'
            }
        ]
    }
];

// laravel-vuetify/resources/components/Modules/Tables/BasicTable/RecentCustomerRatings.vue
<template>
    <v-card
        class="recent-customer-ratings-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Recent Customer Ratings</h5>
            <v-menu>
                <template v-slot:activator="{ props }">
                    <button
                        type="button"
                        v-bind="props"
                        class="position-relative dot-btn p-0 bg-transparent border-none"
                    >
                        <i class="ri-more-fill"></i>
                    </button>
                </template>
                <v-list class="menu-content">
                    <button type="button" class="bg-transparent border-none">
                        This Day
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Week
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Month
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Year
                    </button>
                </v-list>
            </v-menu>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Date</th>
                            <th>Ratings</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in items.slice(0, 5)" :key="item.id">
                            <td class="text-start">
                                <div
                                    class="user-info d-flex align-items-center"
                                >
                                    <div class="image">
                                        <v-img
                                            :src="item.user.image"
                                            alt="user-image"
                                        />
                                    </div>
                                    <div class="info">
                                        <span class="fw-medium d-block">
                                            {{ item.user.name }}
                                        </span>
                                        <span class="email d-block text-body">
                                            {{ item.user.email }}
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <td class="text-body">{{ item.date }}</td>
                            <td class="text-body">
                                <div class="ratings lh-1">
                                    <i
                                        v-for="rating in item.ratings"
                                        :key="rating.id"
                                        :class="rating.star"
                                    ></i>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";

import user13 from "../../../../../public/images/users/user13.jpg";
import user16 from "../../../../../public/images/users/user16.jpg";
import user17 from "../../../../../public/images/users/user17.jpg";
import user18 from "../../../../../public/images/users/user18.jpg";

export default defineComponent({
    name: "RecentCustomerRatings",
    data() {
        return {
            items: [
                {
                    id: 1,
                    user: {
                        image: user13,
                        name: "Olivia Clark",
                        email: "Big Data",
                    },
                    date: "28 August, 2024",
                    ratings: [
                        {
                            id: 1,
                            star: "ri-star-fill",
                        },
                        {
                            id: 2,
                            star: "ri-star-fill",
                        },
                        {
                            id: 3,
                            star: "ri-star-fill",
                        },
                        {
                            id: 4,
                            star: "ri-star-fill",
                        },
                        {
                            id: 5,
                            star: "ri-star-fill",
                        },
                    ],
                },
                {
                    id: 2,
                    user: {
                        image: user16,
                        name: "Ava Turner",
                        email: "UX/UI",
                    },
                    date: "27 August, 2024",
                    ratings: [
                        {
                            id: 1,
                            star: "ri-star-fill",
                        },
                        {
                            id: 2,
                            star: "ri-star-fill",
                        },
                        {
                            id: 3,
                            star: "ri-star-fill",
                        },
                        {
                            id: 4,
                            star: "ri-star-fill",
                        },
                        {
                            id: 5,
                            star: "ri-star-half-fill",
                        },
                    ],
                },
                {
                    id: 3,
                    user: {
                        image: user17,
                        name: "Lucas Morgan",
                        email: "Developer",
                    },
                    date: "26 August, 2024",
                    ratings: [
                        {
                            id: 1,
                            star: "ri-star-fill",
                        },
                        {
                            id: 2,
                            star: "ri-star-fill",
                        },
                        {
                            id: 3,
                            star: "ri-star-fill",
                        },
                        {
                            id: 4,
                            star: "ri-star-fill",
                        },
                        {
                            id: 5,
                            star: "ri-star-line",
                        },
                    ],
                },
                {
                    id: 4,
                    user: {
                        image: user18,
                        name: "Isabella Cooper",
                        email: "Designer",
                    },
                    date: "25 August, 2024",
                    ratings: [
                        {
                            id: 1,
                            star: "ri-star-fill",
                        },
                        {
                            id: 2,
                            star: "ri-star-fill",
                        },
                        {
                            id: 3,
                            star: "ri-star-fill",
                        },
                        {
                            id: 4,
                            star: "ri-star-fill",
                        },
                        {
                            id: 5,
                            star: "ri-star-half-fill",
                        },
                    ],
                },
                {
                    id: 5,
                    user: {
                        image: user13,
                        name: "Isabella Cooper",
                        email: "Designer",
                    },
                    date: "24 August, 2024",
                    ratings: [
                        {
                            id: 1,
                            star: "ri-star-fill",
                        },
                        {
                            id: 2,
                            star: "ri-star-fill",
                        },
                        {
                            id: 3,
                            star: "ri-star-fill",
                        },
                        {
                            id: 4,
                            star: "ri-star-fill",
                        },
                        {
                            id: 5,
                            star: "ri-star-half-fill",
                        },
                    ],
                },
            ],
        };
    },
});
</script>

<style lang="scss" scoped>
.recent-customer-ratings-card {
    .trezo-table-content {
        .trezo-table {
            margin: {
                left: -25px;
                right: -25px;
            }
            .v-table {
                table {
                    thead {
                        tr {
                            th {
                                background-color: #ecf0ff !important;

                                &:first-child {
                                    border-top-left-radius: 0 !important;
                                    padding-left: 25px;
                                }
                                &:last-child {
                                    border-top-right-radius: 0 !important;
                                    padding-right: 25px;
                                }
                            }
                        }
                    }
                    tbody {
                        tr {
                            td {
                                &:first-child {
                                    border-left-width: 0 !important;
                                    padding-left: 25px;
                                }
                                &:last-child {
                                    padding-right: 25px;
                                    border-right-width: 0 !important;
                                }
                                .user-info {
                                    .image {
                                        width: 44px;
                                        height: 44px;
                                        margin-right: 12px;
                                    }
                                }
                            }
                            &:first-child {
                                td {
                                    border-top-width: 0 !important;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
</style>
