// svelte-bootstrap/src/lib/components/Dashboard/LMS/StudentsProgress.svelte
<script>
	import { cubicOut } from 'svelte/easing';
	import { onMount } from 'svelte';
	import {
		BarChartIcon,
		CalendarIcon,
		ClockIcon,
		EyeIcon,
		MoreHorizontalIcon,
		PieChartIcon,
		RotateCwIcon,
		TrashIcon
	} from 'svelte-feather-icons';

	let open = false;
	let dropdownRef;

	function fadeScale(node, { delay = 0, duration = 150, easing = cubicOut, baseScale = 0.95 }) {
		const o = +getComputedStyle(node).opacity;
		const s = baseScale;

		return {
			delay,
			duration,
			easing,
			css: (t) => `
        opacity: ${t * o};
        transform: scale(${s + (1 - s) * t});
      `
		};
	}
</script>

<div class="col-xxl-4">
	<div class="card bg-white border-0 rounded-3 mb-4">
		<div class="card-body p-0">
			<div class="p-4">
				<div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
					<h3 class="mb-0">Student’s Progress</h3>
					<div class="dropdown action-opt" bind:this={dropdownRef}>
						<button
							class="btn bg-transparent p-0"
							type="button"
							aria-label="More options"
							on:click={() => (open = !open)}
						>
							<MoreHorizontalIcon />
						</button>

						{#if open}
							<ul
								class={`dropdown-menu dropdown-menu-end bg-white border box-shadow ${open ? 'show' : ''}`}
								transition:fadeScale
							>
								<li>
									<button on:click={() => (open = !open)} class="dropdown-item">
										<ClockIcon />
										Today
									</button>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}>
										<PieChartIcon />
										Last 7 Days
									</button>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><RotateCwIcon /> Last Month</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><CalendarIcon /> Last 1 Year</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><BarChartIcon /> All Time</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><EyeIcon /> View</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><TrashIcon /> Delete</button
									>
								</li>
							</ul>
						{/if}
					</div>
				</div>
			</div>

			<div class="default-table-area style-two top-instructors">
				<div class="table-responsive">
					<table class="table align-middle border-0">
						<thead>
							<tr>
								<th scope="col">Name</th>
								<th scope="col">Course Name</th>
								<th scope="col">Status</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<a href="instructors.html" class="d-flex align-items-center">
										<h6 class="mb-0 fs-14 fw-medium">Olivia Clark</h6>
									</a>
								</td>
								<td class="text-body">Web Design</td>
								<td>
									<div
										class="progress bg-opacity-10 bg-primary"
										role="progressbar"
										aria-label="Example with label"
										aria-valuenow="50"
										aria-valuemin="0"
										aria-valuemax="100"
										style="height: 5px;"
									>
										<div class="progress-bar rounded-pill" style="width: 50%; height: 5px;"></div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<a href="instructors.html" class="d-flex align-items-center">
										<h6 class="mb-0 fs-14 fw-medium">Alexander Garcia</h6>
									</a>
								</td>
								<td class="text-body">Python Dev.</td>
								<td>
									<div
										class="progress bg-opacity-10 bg-success"
										role="progressbar"
										aria-label="Example with label"
										aria-valuenow="80"
										aria-valuemin="0"
										aria-valuemax="100"
										style="height: 5px;"
									>
										<div
											class="progress-bar bg-success rounded-pill"
											style="width: 80%; height: 5px;"
										></div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<a href="instructors.html" class="d-flex align-items-center">
										<h6 class="mb-0 fs-14 fw-medium">Chloe Lewis</h6>
									</a>
								</td>
								<td class="text-body">Front-end</td>
								<td>
									<div
										class="progress bg-opacity-10 bg-primary-div"
										role="progressbar"
										aria-label="Example with label"
										aria-valuenow="30"
										aria-valuemin="0"
										aria-valuemax="100"
										style="height: 5px;"
									>
										<div
											class="progress-bar rounded-pill bg-primary-div"
											style="width: 30%; height: 5px;"
										></div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<a href="instructors.html" class="d-flex align-items-center">
										<h6 class="mb-0 fs-14 fw-medium">Ava Turner</h6>
									</a>
								</td>
								<td class="text-body">Back-end</td>
								<td>
									<div
										class="progress bg-opacity-10 bg-danger"
										role="progressbar"
										aria-label="Example with label"
										aria-valuenow="50"
										aria-valuemin="0"
										aria-valuemax="100"
										style="height: 5px;"
									>
										<div
											class="progress-bar bg-danger rounded-pill"
											style="width: 50%; height: 5px;"
										></div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<a href="instructors.html" class="d-flex align-items-center">
										<h6 class="mb-0 fs-14 fw-medium">Ryan Flores</h6>
									</a>
								</td>
								<td class="text-body">Data Analytics</td>
								<td>
									<div
										class="progress bg-opacity-10 bg-primary"
										role="progressbar"
										aria-label="Example with label"
										aria-valuenow="50"
										aria-valuemin="0"
										aria-valuemax="100"
										style="height: 5px;"
									>
										<div class="progress-bar rounded-pill" style="width: 50%; height: 5px;"></div>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<a href="instructors.html" class="d-flex align-items-center">
										<h6 class="mb-0 fs-14 fw-medium">John Doe</h6>
									</a>
								</td>
								<td class="text-body">Plugin Dev.</td>
								<td>
									<div
										class="progress bg-opacity-10 bg-primary"
										role="progressbar"
										aria-label="Example with label"
										aria-valuenow="50"
										aria-valuemin="0"
										aria-valuemax="100"
										style="height: 5px;"
									>
										<div class="progress-bar rounded-pill" style="width: 50%; height: 5px;"></div>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<div class="p-4">
				<div
					class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap"
				>
					<span class="fs-12 fw-medium">Items per pages: 5</span>

					<div class="d-flex align-items-center">
						<span class="fs-12 fw-medium me-2">1 - 5 of 12</span>
						<nav aria-label="Page navigation example">
							<ul class="pagination mb-0 justify-content-center">
								<li class="page-item">
									<a class="page-link icon" href="/dashboard/lms" aria-label="Previous">
										<i class="material-symbols-outlined">keyboard_arrow_left</i>
									</a>
								</li>
								<li class="page-item">
									<a class="page-link icon" href="/dashboard/lms" aria-label="Next">
										<i class="material-symbols-outlined">keyboard_arrow_right</i>
									</a>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

// laravel-vuetify/resources/components/Modules/Tables/BasicTable/StudentsProgress.vue
<template>
    <v-card
        class="students-progress-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Student's Progress</h5>
            <v-menu>
                <template v-slot:activator="{ props }">
                    <button
                        type="button"
                        v-bind="props"
                        class="position-relative dot-btn p-0 bg-transparent border-none"
                    >
                        <i class="ri-more-fill"></i>
                    </button>
                </template>
                <v-list class="menu-content">
                    <button type="button" class="bg-transparent border-none">
                        This Day
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Week
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Month
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Year
                    </button>
                </v-list>
            </v-menu>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Course Name</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in items.slice(0, 6)" :key="item.id">
                            <td class="text-start">
                                <a href="#" class="fw-medium">
                                    {{ item.name }}
                                </a>
                            </td>
                            <td class="text-body">{{ item.courseName }}</td>
                            <td>
                                <v-progress-linear
                                    :class="item.status.className"
                                    :model-value="item.status.percentage"
                                >
                                </v-progress-linear>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
    name: "StudentsProgress",
    data() {
        return {
            items: [
                {
                    id: 1,
                    name: "Olivia Clark",
                    courseName: "Web Design",
                    status: {
                        percentage: 55,
                        className: "primary",
                    },
                },
                {
                    id: 2,
                    name: "Alexander Garcia",
                    courseName: "Python Dev",
                    status: {
                        percentage: 80,
                        className: "success",
                    },
                },
                {
                    id: 3,
                    name: "Chloe Lewis",
                    courseName: "Front-end",
                    status: {
                        percentage: 25,
                        className: "purple",
                    },
                },
                {
                    id: 4,
                    name: "Ava Turner",
                    courseName: "Back-end",
                    status: {
                        percentage: 50,
                        className: "orange",
                    },
                },
                {
                    id: 5,
                    name: "Ryan Flores",
                    courseName: "Data Analytics",
                    status: {
                        percentage: 100,
                        className: "primary",
                    },
                },
                {
                    id: 6,
                    name: "John Doe",
                    courseName: "Plugin Dev",
                    status: {
                        percentage: 10,
                        className: "purple",
                    },
                },
                {
                    id: 7,
                    name: "Ryan Flores",
                    courseName: "Data Analytics",
                    status: {
                        percentage: 100,
                        className: "primary",
                    },
                },
            ],
        };
    },
});
</script>

<style lang="scss" scoped>
.students-progress-card {
    .trezo-table-content {
        .trezo-table {
            margin: {
                left: -25px;
                right: -25px;
            }
            .v-table {
                table {
                    thead {
                        tr {
                            th {
                                background-color: #ecf0ff !important;

                                &:first-child {
                                    border-top-left-radius: 0 !important;
                                    padding-left: 25px;
                                }
                                &:last-child {
                                    border-top-right-radius: 0 !important;
                                    padding-right: 25px;
                                }
                            }
                        }
                    }
                    tbody {
                        tr {
                            td {
                                padding: 13px 20px !important;
                                &:first-child {
                                    border-left-width: 0 !important;
                                    padding-left: 25px;
                                }
                                &:last-child {
                                    padding-right: 25px;
                                    border-right-width: 0 !important;
                                }
                            }
                            &:first-child {
                                td {
                                    border-top-width: 0 !important;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
</style>
