// landing-pages/angular-tailwindcss/src/app/ecommerce-demo/common/cta/cta.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-cta',
    imports: [RouterLink],
    templateUrl: './cta.component.html',
    styleUrl: './cta.component.scss'
})
export class CtaComponent {}
<div class="container sm:max-w-[540px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1308px] mx-auto px-[12px]">
    <div
        class="rounded-[15px] px-[20px] md:px-[30px] lg:px-[50px] py-[70px] md:py-[90px] lg:py-[110px] xl:py-[140px] text-center relative z-[1]"
        style="background: linear-gradient(278deg, #757DFF 23.88%, #4936F5 94.06%);"
    >
        <h2 class="!text-white !font-medium md:-tracking-[1px] !text-xl md:!text-3xl lg:!text-4xl xl:!text-5xl !leading-[1.2] !mb-[11px] md:!mb-[13px] lg:!mb-[15px]">
            Ready to Supercharge Your Store?
        </h2>
        <p class="text-white !leading-[1.6]">
            Start growing with real data, real automation, and real results.
        </p>
        <div class="-mt-[8px] md:mt-[30px] lg:mt-[35px] xl:mt-[40px]">
            <a href="https://trezo-twcss.envytheme.com/" class="inline-block py-[9px] px-[25px] md:py-[11.5px] md:px-[30px] font-medium text-primary-500 bg-white rounded-[100px] border border-primary-500 transition-all hover:bg-primary-600 hover:text-white hover:border-primary-600 mx-[7px] mt-[15px] md:mt-0">
                Start Free Trial
            </a>
            <a routerLink="/pricing" class="inline-block py-[9px] px-[25px] md:py-[11.5px] md:px-[30px] font-medium text-white rounded-[100px] border border-white transition-all hover:bg-primary-600 hover:border-primary-600 mx-[7px] mt-[15px] md:mt-0">
                Talk to Sales
            </a>
        </div>
        <div class="absolute bottom-[20%] ltr:left-[6.5%] rtl:right-[6.5%] -z-[1] hidden lg:block">
            <img src="images/ecommerce/shapes/shape1.png" alt="shape">
        </div>
        <div class="absolute bottom-[43%] ltr:left-[14%] rtl:right-[14%] -z-[1] hidden lg:block">
            <img src="images/ecommerce/shapes/shape2.png" alt="shape">
        </div>
        <div class="absolute top-[20%] ltr:right-[6.5%] rtl:left-[6.5%] -z-[1] -z-[1] hidden lg:block">
            <img src="images/ecommerce/shapes/shape3.png" alt="shape">
        </div>
        <div class="absolute top-[43%] ltr:right-[14%] rtl:left-[14%] -z-[1] hidden lg:block">
            <img src="images/ecommerce/shapes/shape4.png" alt="shape">
        </div>
    </div>
</div>

// landing-pages/react-nextjs-bootstrap/ecommerce-landing/src/components/Common/Cta.js
"use client";

import React from "react";
import Image from "next/image";
import Link from "next/link";
import Container from "react-bootstrap/Container";

const Cta = () => {
  return (
    <>
      <div className="supercharge-area">
        <Container className="cmw-1308">
          <div
            className="supercharge-content position-relative z-1"
            style={{
              background:
                "linear-gradient(278deg, #757DFF 23.88%, #4936F5 94.06%)",
            }}
          >
            <h2>Ready to Supercharge Your Store?</h2>
            <p>
              Start growing with real data, real automation, and real results.
            </p>

            <div
              className="d-flex flex-wrap justify-content-center mt-40"
              style={{
                gap: "14px",
              }}
            >
              <Link
                href="#"
                className="btn bg-white text-primary fw-medium fs-14 rounded-pill hover-bg landing-page-btn"
              >
                Start Free Trial
              </Link>
              <Link
                href="#"
                className="btn btn-outline-light text-white fw-medium fs-14 rounded-pill hover-bg landing-page-btn"
              >
                Talk to Sales
              </Link>
            </div>

            {/* Shape Images  */}
            <Image
              src="/images/shapes/shape1.png"
              className="position-absolute d-none d-xl-inline-block"
              style={{
                bottom: "85px",
                left: "85px",
              }}
              alt="shape"
              width={87}
              height={87}
            />
            <Image
              src="/images/shapes/shape2.png"
              className="position-absolute d-none d-xl-inline-block"
              style={{
                bottom: "187px",
                left: "180px",
              }}
              alt="shape"
              width={50}
              height={50}
            />
            <Image
              src="/images/shapes/shape3.png"
              className="position-absolute d-none d-xl-inline-block"
              style={{
                top: "88px",
                right: "106px",
              }}
              alt="shape"
              width={87}
              height={87}
            />
            <Image
              src="/images/shapes/shape4.png"
              className="position-absolute d-none d-xl-inline-block"
              style={{
                top: "195px",
                right: "193px",
              }}
              alt="shape"
              width={50}
              height={50}
            />
          </div>
        </Container>
      </div>
    </>
  );
};

export default Cta;
