// react-bootstrap/src/components/Dashboard/Doctor/Welcome.js
"use client";

import React from "react";

const Welcome = () => {
  return (
    <>
      <div
        className="doctor-welcome-card rounded-3 position-relative"
        style={{
          background: "linear-gradient(272deg, #1F64F1 31.27%, #123A8B 98.4%)",
        }}
      >
        <div className="d-flex flex-wrap justify-content-between align-items-center align-items-xl-end">
          <div className="py-xl-5">
            <span className="fs-18 text-white">Good Morning</span>

            <h2 className="fs-28 fw-900 text-white mt-2 mt-sm-2 my-2">
              Dr. Olivia John
            </h2>
            
            <div className="d-flex align-items-center gap-1 mb-1 mb-sm-2">
              <img
                src="/images/heart.png"
                alt="heart"
                width={18}
                height={18}
              />
              <span className="text-white fs-12 fw-medium">
                CARDIO SPECIALIST
              </span>
            </div>

            <p className="mb-2 mb-xl-4" style={{ color: "#B1BBC8" }}>
              Today you have <span className="text-white">15</span>{" "}
              Consultations and <span className="text-white">12</span>{" "}
              Operations.
            </p>
          </div>

          <img
            src="/images/andrew-rashel.png"
            className="mt-3 mt-sm-0"
            alt="andrew-rashel"
            width={210}
            height={240}
          />
        </div>

        <img
          src="/images/shape-11.png"
          className="position-absolute bottom-0 end-0"
          alt="shape"
          width={844}
          height={220}
        />
      </div>
    </>
  );
};

export default Welcome;

// svelte-bootstrap/src/lib/components/Dashboard/Sales/Welcome.svelte
<div class="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-4">
	<h3 class="fs-24 fw-normal mb-0">
		Welcome Back, <span class="text-primary">Olivia!</span>
		<img src="/assets/images/dog.svg" alt="dog" />
	</h3>
	<div class="d-flex flex-wrap gap-3 align-items-center">
		<div class="position-relative">
			<input
				type="text"
				class="form-control"
				id="range_datepicker"
				style="width: 230px; height: 36px; padding-left: 35px;"
				placeholder="29/10/2024 - 28/11/2024"
			/>
			<i class="ri-calendar-line position-absolute top-50 start-0 translate-middle-y ps-3"></i>
		</div>
		<button class="btn btn-primary py-1 px-3 rounded-3">
			<span class="d-inline-block py-1">
				<i class="ri-download-2-line text-white fs-16 me-1"></i>
				Export CSV
			</span>
		</button>
	</div>
</div>
