// svelte-bootstrap/src/lib/components/Dashboard/RealEstate/Revenue.svelte
<script>
	import { onMount } from 'svelte';

	let chartEl;

	onMount(async () => {
		const ApexCharts = (await import('apexcharts')).default;

		const options = {
			series: [
				{
					name: 'Income',
					data: [
						{
							x: '2019',
							y: 1292,
							goals: [{ name: 'Expenses', value: 1400, strokeHeight: 5, strokeColor: '#FFCEA9' }]
						},
						{
							x: '2018',
							y: 4432,
							goals: [{ name: 'Expenses', value: 5400, strokeHeight: 5, strokeColor: '#FFCEA9' }]
						},
						{
							x: '2020',
							y: 5423,
							goals: [{ name: 'Expenses', value: 5200, strokeHeight: 5, strokeColor: '#FFCEA9' }]
						},
						{
							x: '2021',
							y: 6653,
							goals: [{ name: 'Expenses', value: 6500, strokeHeight: 5, strokeColor: '#FFCEA9' }]
						},
						{
							x: '2022',
							y: 8133,
							goals: [{ name: 'Expenses', value: 6600, strokeHeight: 13, strokeColor: '#FFCEA9' }]
						},
						{
							x: '2023',
							y: 7132,
							goals: [{ name: 'Expenses', value: 7500, strokeHeight: 5, strokeColor: '#FFCEA9' }]
						},
						{
							x: '2024',
							y: 7332,
							goals: [{ name: 'Expenses', value: 8700, strokeHeight: 5, strokeColor: '#FFCEA9' }]
						}
					]
				}
			],
			chart: {
				height: 125,
				type: 'bar',
				toolbar: { show: false }
			},
			plotOptions: {
				bar: { columnWidth: '60%' }
			},
			colors: ['#FD5812'],
			dataLabels: { enabled: false },
			legend: {
				show: true,
				showForSingleSeries: true,
				customLegendItems: ['Income', 'Expenses'],
				position: 'right',
				fontSize: '12px',
				horizontalAlign: 'bottom',
				offsetX: -12,
				offsetY: 51,
				itemMargin: { horizontal: 0, vertical: 4 },
				labels: { colors: '#64748B' },
				markers: {
					width: 9,
					height: 9,
					shape: 'diamond',
					offsetX: -1,
					fillColors: ['#FD5812', '#FFCEA9']
				}
			},
			xaxis: {
				labels: { show: false },
				axisTicks: { show: false }
			},
			yaxis: {
				labels: { show: false }
			},
			grid: { show: false },
			tooltip: {
				y: {
					formatter: (val) => `$${val}K`
				}
			}
		};

		const chart = new ApexCharts(chartEl, options);
		chart.render();
	});
</script>

<div class="col-md-6 col-xxl-12">
	<div class="card rounded-3 bg-white border-0 mb-4">
		<div class="card-body p-4">
			<div class="d-flex">
				<div class="flex-grow-1 me-3">
					<div class="d-flex align-items-start">
						<div class="me-4">
							<span class="d-block mb-2">Revenue</span>
							<h3 class="mb-0 fs-20">$194,712</h3>
						</div>
						<span
							class="d-inline-block border-success border bg-success bg-opacity-10 text-success px-2 rounded-pill fs-12 fw-medium position-relative top-4"
							>+ 60%</span
						>
					</div>
				</div>

				<div class="flex-shrink-0">
					<span class="fs-12">Last 7 days</span>
				</div>
			</div>
			<div style="margin: -26px -23px -25px -22px;">
				<div id="property_revenue" bind:this={chartEl}></div>
			</div>
		</div>
	</div>
</div>

// nuxtjs-vuetify/components/Dashboard/Restaurant/Revenue.vue
<template>
  <v-card
    class="revenue-card trezo-card mb-25 bg-white border-radius d-block border-0 shadow-none"
  >
    <div class="trezo-card-content position-relative">
      <span class="d-block"> Revenue </span>
      <h3>$3M</h3>
      <span class="trezo-status-badge finished"> +3.4% </span>
      <span class="text-xs d-block"> vs previous 30 days </span>

      <div class="chart">
        <apexchart
          v-if="isClient"
          type="donut"
          height="90"
          :options="revenueChart"
          :series="revenue"
        ></apexchart>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from "vue";

export default defineComponent({
  // eslint-disable-next-line vue/multi-word-component-names
  name: "Revenue",
  setup() {
    const isClient = ref(false);
    const revenue = ref([80, 20]);
    const revenueChart = ref({
      chart: {
        height: 90,
        type: "donut",
      },
      labels: ["Revenue", "Revenue"],
      colors: ["#58F229", "#D8FFC8"],
      tooltip: {
        y: {
          formatter: function (val: any) {
            return "$" + val + "M";
          },
        },
      },
      stroke: {
        width: 0,
      },
      legend: {
        show: false,
        position: "top",
        fontSize: "12px",
        horizontalAlign: "center",
        itemMargin: {
          horizontal: 8,
          vertical: 0,
        },
        labels: {
          colors: "#64748B",
        },
        markers: {
          size: 7,
          offsetX: -2,
          offsetY: -0.5,
          shape: "diamond",
        },
      },
      dataLabels: {
        enabled: false,
      },
    });

    onMounted(() => {
      isClient.value = true;
    });

    return {
      isClient,
      revenue,
      revenueChart,
    };
  },
});
</script>

<style lang="scss" scoped>
.revenue-card {
  .trezo-card-content {
    h3 {
      font-size: 32px;
      letter-spacing: -0.5px;
      margin: {
        top: 2px;
        bottom: 5px;
      }
    }
    .trezo-status-badge {
      border-radius: 30px;
      margin-bottom: 5px;
      padding: {
        top: 1px;
        bottom: 1px;
      }
    }
    .text-xs {
      font-size: 12px;
    }
    .chart {
      top: 50%;
      right: -15px;
      margin-top: 2px;
      max-width: 120px;
      position: absolute;
      transform: translateY(-50%);
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .revenue-card {
    .trezo-card-content {
      h3 {
        font-size: 28px;
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .revenue-card {
    .trezo-card-content {
      h3 {
        font-size: 30px;
      }
    }
  }
}
</style>
