// angular-material/src/app/dashboard/restaurant/tickets/tickets.component.ts
import { NgIf } from '@angular/common';
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatMenuModule } from '@angular/material/menu';
import { MatButtonModule } from '@angular/material/button';
import { MatTableModule, MatTableDataSource } from '@angular/material/table';

@Component({
    selector: 'app-tickets',
    imports: [NgIf, MatCardModule, MatButtonModule, MatMenuModule, MatTableModule],
    templateUrl: './tickets.component.html',
    styleUrl: './tickets.component.scss'
})
export class TicketsComponent {
        
    displayedColumns: string[] = ['code', 'ticket', 'status'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);
    
}

export interface PeriodicElement {
    code: string;
    ticket: any;
    status: any;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        code: '#3242',
        ticket: {
            title: 'Order delayed for 5 mins',
            updatedAt: '17 Nov, 2025'
        },
        status: {
            solved: true,
            pending: false
        }
    },
    {
        code: '#3243',
        ticket: {
            title: 'Provide rotten Burger',
            updatedAt: '16 Nov, 2025'
        },
        status: {
            solved: false,
            pending: true
        }
    },
    {
        code: '#3244',
        ticket: {
            title: 'Too much salt in Pizza',
            updatedAt: '15 Nov, 2025'
        },
        status: {
            solved: true,
            pending: false
        }
    },
    {
        code: '#3245',
        ticket: {
            title: 'Order delayed for 3 mins',
            updatedAt: '14 Nov, 2025'
        },
        status: {
            solved: true,
            pending: false
        }
    },
    {
        code: '#3246',
        ticket: {
            title: 'Delivery man misbehaved',
            updatedAt: '13 Nov, 2025'
        },
        status: {
            solved: false,
            pending: true
        }
    },
    {
        code: '#3247',
        ticket: {
            title: 'App doesn’t work',
            updatedAt: '12 Nov, 2025'
        },
        status: {
            solved: true,
            pending: false
        }
    },
    {
        code: '#3244',
        ticket: {
            title: 'Too much salt in Pizza',
            updatedAt: '11 Nov, 2025'
        },
        status: {
            solved: true,
            pending: false
        }
    }
];
<mat-card class="tickets-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Tickets
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu style-two p-0 d-inline-block border-radius-0">
                <i class="ri-more-2-fill"></i>
            </button>
            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                <ul class="p-0 mt-0 mb-0 list-unstyled">
                    <li>
                        <button mat-menu-item>
                            This Day
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Week
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Month
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Year
                        </button>
                    </li>
                </ul>
            </mat-menu>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <div class="table-style-five">
            <div class="table-responsive">
                <table mat-table [dataSource]="dataSource">

                    <!-- Code Column -->
                    <ng-container matColumnDef="code">
                        <th mat-header-cell *matHeaderCellDef>
                            Code
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.code}}
                        </td>
                    </ng-container>

                    <!-- Ticket Column -->
                    <ng-container matColumnDef="ticket">
                        <th mat-header-cell *matHeaderCellDef>
                            Ticket
                        </th>
                        <td mat-cell *matCellDef="let element">
                            <span class="title d-block text-black fw-semibold">
                                {{element.ticket.title}}
                            </span>
                            <span class="text-xs text-body">
                                Updated on: {{element.ticket.updatedAt}}
                            </span>
                        </td>
                    </ng-container>

                    <!-- Status Column -->
                    <ng-container matColumnDef="status">
                        <th mat-header-cell *matHeaderCellDef>
                            Status
                        </th>
                        <td mat-cell *matCellDef="let element">
                            <span class="trezo-badge fw-semibold shipped" *ngIf="element.status.solved">
                                Solved
                            </span>
                            <span class="trezo-badge fw-semibold pPending" *ngIf="element.status.pending">
                                Pending
                            </span>
                        </td>
                    </ng-container>

                    <!-- <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr> -->
                    <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>

                </table>
            </div>
        </div>
    </mat-card-content>
</mat-card>

// nuxtjs-vuetify/components/Dashboard/Restaurant/Tickets.vue
<template>
  <v-card
    class="tickets-card trezo-card bg-white border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Tickets</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-2-fill"></i>
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="basic-table table-responsive">
        <table class="table mb-0">
          <tbody>
            <tr v-for="ticket in tickets.slice(0, 7)" :key="ticket.id">
              <td class="fw-semibold text-body">{{ ticket.id }}</td>
              <td class="reviews">
                <span class="ticket-title d-block fw-semibold">
                  {{ ticket.title }}
                </span>
                <p>Updated on: {{ ticket.updatedOn }}</p>
              </td>
              <td>
                <span :class="`trezo-status-badge ${ticket.statusClass}`">
                  {{ ticket.status }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  // eslint-disable-next-line vue/multi-word-component-names
  name: "Tickets",
  setup() {
    const tickets = ref([
      {
        id: "#3242",
        title: "Order delayed for 5 mins",
        updatedOn: "10 Nov, 2025",
        status: "Solved",
        statusClass: "finished",
      },
      {
        id: "#3243",
        title: "Provide rotten Burger",
        updatedOn: "10 Nov, 2025",
        status: "Pending",
        statusClass: "pPending",
      },
      {
        id: "#3244",
        title: "Too much salt in pizza",
        updatedOn: "10 Nov, 2025",
        status: "Solved",
        statusClass: "finished",
      },
      {
        id: "#3245",
        title: "Order delayed for 5 mins",
        updatedOn: "10 Nov, 2025",
        status: "Solved",
        statusClass: "finished",
      },
      {
        id: "#3246",
        title: "Delivery man misbehaved",
        updatedOn: "10 Nov, 2025",
        status: "Pending",
        statusClass: "pPending",
      },
      {
        id: "#3247",
        title: "App doesn’t work",
        updatedOn: "10 Nov, 2025",
        status: "Solved",
        statusClass: "finished",
      },
      {
        id: "#3248",
        title: "Missing items in order",
        updatedOn: "9 Nov, 2025",
        status: "Pending",
        statusClass: "pPending",
      },
    ]);

    return {
      tickets,
    };
  },
});
</script>

<style lang="scss" scoped>
.tickets-card {
  .trezo-card-content {
    margin-bottom: -15px;

    .basic-table {
      table,
      .table {
        thead {
          tr {
            th {
              font-size: 10px;
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              padding: {
                bottom: 15px;
                top: 0;
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              vertical-align: top;
              font-size: 12px;
              padding: {
                top: 10px;
                bottom: 10px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .ticket-title {
                font-size: var(--fontSize);
                margin: {
                  top: -1px;
                }
              }
              .trezo-status-badge {
                border-radius: 30px;
                padding: 1px 10px;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                text-align: end;
                padding-right: 0 !important;
              }
            }
            &:first-child {
              td {
                border-top-width: 0;
                padding-top: 0;
              }
            }
            &:last-child {
              td {
                border-bottom-width: 0;
              }
            }
          }
        }
      }
    }
  }
}
</style>
