// react-nextjs-material-ui/src/components/Dashboard/Restaurant/StaffPerformanceScores/index.tsx
"use client";

import React, { useState, useEffect } from "react";
import {
  Box,
  Typography,
  Card,
  Menu,
  MenuItem,
  IconButton,
} from "@mui/material";
import { MoreVert } from "@mui/icons-material";
import Image from "next/image";

type StaffPerformanceScore = {
  id: string;
  image: string;
  name: string;
  score: number;
};

const StaffPerformanceScores: React.FC = () => {
  // Dropdown
  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
  const open = Boolean(anchorEl);
  const handleClick = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };
  const handleClose = () => {
    setAnchorEl(null);
  };

  // data
  const [staffPerformanceScores, setStaffPerformanceScores] = useState<
    StaffPerformanceScore[]
  >([]);

  useEffect(() => {
    // Simulated API call to fetch low stock items
    const fetchStaffPerformanceScores = async () => {
      const mockStaffPerformanceScores: StaffPerformanceScore[] = [
        {
          id: "1",
          image: "/images/users/user58.jpg",
          name: "Thai Bean Soup",
          score: 98,
        },
        {
          id: "2",
          image: "/images/users/user59.jpg",
          name: "Angela Carter",
          score: 97,
        },
        {
          id: "3",
          image: "/images/users/user60.jpg",
          name: "Walter White",
          score: 96,
        },
        {
          id: "4",
          image: "/images/users/user61.jpg",
          name: "Gary Simon",
          score: 88,
        },
        {
          id: "5",
          image: "/images/users/user62.jpg",
          name: "Zinia Anderson",
          score: 85,
        },
        {
          id: "6",
          image: "/images/users/user63.jpg",
          name: "Loren Walter",
          score: 80,
        },
        {
          id: "7",
          image: "/images/users/user64.jpg",
          name: "Jessy Pinkman",
          score: 80,
        },
        {
          id: "8",
          image: "/images/users/user65.jpg",
          name: "Handy Curter",
          score: 77,
        },
        {
          id: "9",
          image: "/images/users/user66.jpg",
          name: "Skyler Lorensa",
          score: 75,
        },
      ];
      setStaffPerformanceScores(mockStaffPerformanceScores);
    };

    fetchStaffPerformanceScores();
  }, []);

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            mb: "25px",
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Staff Performance Scores
          </Typography>

          <Box>
            <IconButton
              onClick={handleClick}
              size="small"
              aria-controls={open ? "account-menu" : undefined}
              aria-haspopup="true"
              aria-expanded={open ? "true" : undefined}
              sx={{ p: "0" }}
              className="-right-10"
            >
              <MoreVert sx={{ fontSize: "25px" }} />
            </IconButton>

            <Menu
              anchorEl={anchorEl}
              id="account-menu"
              open={open}
              onClose={handleClose}
              onClick={handleClose}
              PaperProps={{
                elevation: 0,

                sx: {
                  overflow: "visible",
                  boxShadow: "0 4px 45px #0000001a",
                  mt: 0,
                  "& .MuiAvatar-root": {
                    width: 32,
                    height: 32,
                    ml: -0.5,
                    mr: 1,
                  },
                },
              }}
              transformOrigin={{ horizontal: "right", vertical: "top" }}
              anchorOrigin={{ horizontal: "right", vertical: "bottom" }}
            >
              <MenuItem>This Day</MenuItem>
              <MenuItem>This Week</MenuItem>
              <MenuItem>This Month</MenuItem>
              <MenuItem>This Year</MenuItem>
            </Menu>
          </Box>
        </Box>

        <Box
          sx={{
            ".border-bottom": {
              paddingBottom: "10px",
              marginBottom: "10px",

              "&:last-child": {
                paddingBottom: 0,
                marginBottom: 0,
                borderBottom: "none !important",
              },
            },
          }}
        >
          {staffPerformanceScores.slice(0, 9).map((staff) => (
            <Box
              key={staff.id}
              sx={{
                display: "flex",
                alignItems: "center",
                justifyContent: "space-between",
              }}
              className="border-bottom"
            >
              <Box
                sx={{
                  display: "flex",
                  alignItems: "center",
                  gap: "10px",
                }}
              >
                <Image
                  src={staff.image}
                  alt="Staff"
                  width={30}
                  height={30}
                  style={{ borderRadius: "50%" }}
                />
                <Typography
                  variant="h5"
                  sx={{ fontSize: "14px", fontWeight: 500 }}
                >
                  {staff.name}
                </Typography>
              </Box>

              <Typography>{staff.score}</Typography>
            </Box>
          ))}
        </Box>
      </Card>
    </>
  );
};

export default StaffPerformanceScores;

// vuejs-bootstrap/src/components/Dashboard/Restaurant/StaffPerformanceScores.vue
<template>
  <div
    class="staff-performance-scores-card card mb-4 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-2 mb-lg-20"
      >
        <h5 class="mb-0">Staff Performance Scores</h5>
        <div class="dropdown action-opt">
          <button
            class="btn bg-transparent p-0"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="ri-more-2-fill"></i>
          </button>
          <ul
            class="dropdown-menu dropdown-menu-end bg-white border box-shadow"
          >
            <li>
              <button class="dropdown-item">This Day</button>
            </li>
            <li>
              <button class="dropdown-item">This Week</button>
            </li>
            <li>
              <button class="dropdown-item">This Month</button>
            </li>
            <li>
              <button class="dropdown-item">This Year</button>
            </li>
          </ul>
        </div>
      </div>

      <div class="trezo-card-content">
        <div class="basic-table table-responsive">
          <table class="table mb-0">
            <tbody>
              <tr v-for="(employee, index) in employees" :key="index">
                <td>
                  <div class="employee-info d-flex align-items-center">
                    <div class="img rounded-circle">
                      <img
                        :alt="employee.name"
                        :src="employee.image"
                        class="rounded-circle"
                      />
                    </div>
                    <div>
                      <span class="d-block fw-medium">{{ employee.name }}</span>
                    </div>
                  </div>
                </td>
                <td class="text-body">{{ employee.score }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "StaffPerformanceScores",
  setup() {
    const employees = [
      {
        name: "Joanna Watson",
        image: require("@/assets/images/users/user58.jpg"),
        score: 98,
      },
      {
        name: "Angela Carter",
        image: require("@/assets/images/users/user59.jpg"),
        score: 97,
      },
      {
        name: "Walter White",
        image: require("@/assets/images/users/user60.jpg"),
        score: 96,
      },
      {
        name: "Gary Simon",
        image: require("@/assets/images/users/user61.jpg"),
        score: 88,
      },
      {
        name: "Zinia Anderson",
        image: require("@/assets/images/users/user62.jpg"),
        score: 85,
      },
      {
        name: "Loren Walter",
        image: require("@/assets/images/users/user63.jpg"),
        score: 82,
      },
      {
        name: "Jessy Pinkman",
        image: require("@/assets/images/users/user64.jpg"),
        score: 80,
      },
      {
        name: "Handy Curter",
        image: require("@/assets/images/users/user65.jpg"),
        score: 77,
      },
      {
        name: "Skyler Lorensa",
        image: require("@/assets/images/users/user66.jpg"),
        score: 75,
      },
    ];

    return {
      employees,
    };
  },
});
</script>

<style lang="scss" scoped>
.staff-performance-scores-card {
  .trezo-card-content {
    margin-bottom: -10px;

    .basic-table {
      table,
      .table {
        thead {
          tr {
            th {
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              padding: {
                bottom: 13px;
                top: 0;
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              padding: {
                top: 10px;
                bottom: 10px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 30px;
                }
                span {
                  &:nth-child(1) {
                    margin-bottom: 1px;
                    font-size: var(--fontSize);
                  }
                }
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
                text-align: end;
              }
            }
            &:first-child {
              td {
                padding-top: 0;
                border-top-width: 0;
              }
            }
            &:last-child {
              td {
                border-bottom-width: 0;
              }
            }
          }
        }
      }
    }
  }
}
</style>
