// landing-pages/angular-material/src/app/marketing-demo/common/pricing/pricing.component.ts
import { Component } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { ToggleService } from '../../../settings/toggle.service';

@Component({
    selector: 'app-pricing',
    imports: [MatButtonModule],
    templateUrl: './pricing.component.html',
    styleUrl: './pricing.component.scss'
})
export class PricingComponent {

    constructor(
        public toggleService: ToggleService
    ) {}

}
<div
    class="pricing-area pb-155"
    [class.component-dark]="toggleService.isLandingDark()"
    [class.component-rtl]="toggleService.isLandingRtlEnabled()"
>
    <div class="container">
        <div class="marketing-section-title text-center">
            <span class="sub-title d-inline-block">
                Pricing
            </span>
            <h2 class="fw-medium mx-auto">
                Flexible Plans That Scale With You
            </h2>
            <p>
                Trezo has a plan that fits your needs — and grows with you.
            </p>
        </div>
        <div class="row align-items-center justify-content-center">
            <div class="col-lg-4 col-sm-6">
                <div class="pricing-box">
                    <span class="d-block title fw-medium">
                        Free Trial
                    </span>
                    <div class="price fw-medium lh-1">
                        $0<span>/monthly</span>
                    </div>
                    <p>
                        Perfect for individuals or small teams
                    </p>
                    <a href="https://trezo-twcss.envytheme.com/" target="_blank" class="marketing-default-btn" mat-button>
                        <span class="d-inline-block position-relative">
                            <i class="material-symbols-outlined">
                                person
                            </i>
                            Get Started
                        </span>
                    </a>
                    <ul class="features-list mb-0 list-unstyled p-0">
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Access to core features
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            1 active project
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Up to 3 team members
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Email campaign builder
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Basic analytics
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            7-day activity history
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="pricing-box">
                    <span class="d-block title fw-medium">
                        Pro
                    </span>
                    <div class="price fw-medium lh-1">
                        $39<span>/monthly</span>
                    </div>
                    <p>
                        Ideal for growing teams and agencies
                    </p>
                    <a href="https://trezo-twcss.envytheme.com/" target="_blank" class="marketing-default-btn" mat-button>
                        <span class="d-inline-block position-relative">
                            <i class="material-symbols-outlined">
                                person
                            </i>
                            Get Started
                        </span>
                    </a>
                    <ul class="features-list mb-0 list-unstyled p-0">
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Everything in free trial
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Unlimited projects & campaigns
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Up to 15 team members
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Advanced analytics & reports
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Funnel tracking & segmentation
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Social & email integrations
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Priority email support
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-sm-6">
                <div class="pricing-box">
                    <span class="d-block title fw-medium">
                        Enterprise
                    </span>
                    <div class="price fw-medium lh-1">
                        $79<span>/monthly</span>
                    </div>
                    <p>
                        Built for large teams and custom needs
                    </p>
                    <a href="https://trezo-twcss.envytheme.com/" target="_blank" class="marketing-default-btn" mat-button>
                        <span class="d-inline-block position-relative">
                            <i class="material-symbols-outlined">
                                person
                            </i>
                            Get Started
                        </span>
                    </a>
                    <ul class="features-list mb-0 list-unstyled p-0">
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Everything in pro
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Unlimited team members
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Dedicated account manager
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Custom integrations
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            Advanced security & audit logs
                        </li>
                        <li class="position-relative">
                            <img src="images/marketing/icons/check.svg" alt="check">
                            24/7 priority support
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

// landing-pages/react-nextjs-tailwindcss/marketing-landing/src/components/Common/Pricing.tsx
"use client";

import React from "react";
import Image from "next/image";
import Link from "next/link";

interface PricingPlan {
  id: number;
  name: string;
  price: string;
  description: string;
  features: string[];
  buttonVariant: "outline" | "solid";
  order: string;
  gradient: string;
}

const Pricing: React.FC = () => {
  const pricingPlans: PricingPlan[] = [
    {
      id: 1,
      name: "Free Trial",
      price: "$0",
      description: "Perfect for individuals or small teams",
      features: [
        "Access to core features",
        "1 active project",
        "Up to 3 team members",
        "Email campaign builder",
        "Basic analytics",
        "7-day activity history",
      ],
      buttonVariant: "outline",
      order: "order-1 lg:order-1",
      gradient: "linear-gradient(180deg, #FAF5FF 0%, #EEF6FF 100%)",
    },
    {
      id: 2,
      name: "Pro",
      price: "$39",
      description: "Ideal for growing teams and agencies",
      features: [
        "Everything in free trial",
        "Unlimited projects & campaigns",
        "Up to 15 team members",
        "Advanced analytics & reports",
        "Funnel tracking & segmentation",
        "Social & email integrations",
        "Priority email support",
      ],
      buttonVariant: "solid",
      order: "order-3 lg:order-2",
      gradient: "linear-gradient(180deg, #FFF5ED 0%, #FAF5FF 100%)",
    },
    {
      id: 3,
      name: "Enterprise",
      price: "$79",
      description: "Built for large teams and custom needs",
      features: [
        "Everything in pro",
        "Unlimited team members",
        "Dedicated account manager",
        "Custom integrations",
        "Advanced security & audit logs",
        "24/7 priority support",
      ],
      buttonVariant: "outline",
      order: "order-2 lg:order-3",
      gradient: "linear-gradient(180deg, #EEF6FF 0%, #EEFFE5 100%)",
    },
  ];

  return (
    <>
      <div className="container sm:max-w-[540px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1308px] mx-auto px-[12px]">
        <div className="text-center mb-[30px] md:mb-[40px] lg:mb-[50px] xl:mb-[60px] 2xl:mb-[70px]">
          <span className="inline-block py-[4.5px] px-[15px] rounded-[100px] bg-orange-100 dark:bg-[#0a0e19] text-orange-700 mb-[12px]">
            Pricing
          </span>
          <h2 className="!text-gray-900 dark:!text-white md:-tracking-[1px] !font-medium !text-xl md:!text-3xl lg:!text-4xl xl:!text-5xl xl:max-w-[520px] mx-auto !leading-[1.2] !mb-[10px] lg:!mb-[12px]">
            Flexible Plans That Scale With You
          </h2>
          <p className="md:text-[15px] lg:text-md !leading-[1.6]">
            Trezo has a plan that fits your needs — and grows with you.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-[25px] items-center">
          {pricingPlans.map((plan) => (
            <div key={plan.id} className={plan.order}>
              <div className="dark:bg-[#0a0e19] px-[20px] py-[25px] md:px-[35px] md:py-[45px] xl:px-[55px] xl:py-[65px] relative z-[1] rounded-[25px]">
                <span className="block text-orange-600 font-medium text-md lg:text-lg mb-[10px] md:mb-[17px]">
                  {plan.name}
                </span>

                <div className="text-gray-700 dark:text-gray-100 font-medium text-4xl md:text-5xl mb-[15px] md:mb-[18px]">
                  {plan.price}{" "}
                  <span className="ltr:-ml-[8px] rtl:-mr-[8px] md:-tracking-[1px] text-base md:text-[15px] font-normal lg:text-md text-gray-500 dark:text-gray-400">
                    /monthly
                  </span>
                </div>

                <p className="!leading-[1.6] md:text-[15px] lg:text-md">
                  {plan.description}
                </p>

                <Link
                  href="#"
                  className={`inline-flex items-center gap-[8px] ${
                    plan.buttonVariant === "solid"
                      ? "text-white bg-orange-600 border-orange-600"
                      : "text-orange-600 border-orange-600 hover:text-white hover:bg-orange-500 hover:border-orange-500"
                  } py-[10.5px] px-[20px] rounded-[7px] transition-all font-medium border md:text-[15px] lg:text-md md:mt-[5px] lg:mt-[10px]`}
                >
                  <i className="ri-user-3-line font-bold"></i>
                  Get Started
                </Link>

                <ul className="mt-[20px] md:mt-[25px] lg:mt-[35px]">
                  {plan.features.map((feature, index) => (
                    <li
                      key={index}
                      className="text-gray-700 dark:text-gray-100 md:text-[15px] lg:text-md relative ltr:pl-[32px] rtl:pr-[32px] mb-[12px] md:mb-[15px] last:mb-0"
                    >
                      <Image
                        src="/images/icons/check.svg"
                        className="absolute top-1/2 ltr:left-0 rtl:right-0 -translate-y-1/2 dark:invert"
                        alt="check"
                        width={22}
                        height={22}
                      />
                      {feature}
                    </li>
                  ))}
                </ul>
                <div
                  className="rounded-[25px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                  style={{ background: plan.gradient }}
                ></div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Pricing;
