// laravel-vuetify/resources/components/Pages/Users/UsersList/index.vue
<template>
    <v-card
        class="users-list-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <form class="search-box position-relative" @submit.prevent>
                <input
                    type="text"
                    class="input-search d-block"
                    placeholder="Search user here....."
                    v-model="searchTerm"
                />
                <button type="submit">
                    <i class="material-symbols-outlined">search</i>
                </button>
            </form>
            <RouterLink class="add-btn" to="/users/add-user">
                <i class="material-symbols-outlined"> add </i>
                Add New User
            </RouterLink>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th class="text-start">User ID</th>
                            <th class="text-start">User</th>
                            <th class="text-start">Email</th>
                            <th class="text-start">Location</th>
                            <th class="text-start">Phone</th>
                            <th class="text-start">Projects</th>
                            <th class="text-start">Join Date</th>
                            <th class="text-start">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in filteredItems" :key="item.userID">
                            <td>
                                {{ item.userID }}
                            </td>
                            <td>
                                <div
                                    class="customer-info d-flex align-items-center"
                                >
                                    <div class="img">
                                        <v-img
                                            class="rounded-circle"
                                            :src="item.user.image"
                                            alt="user-image"
                                        />
                                    </div>
                                    <span class="d-block text-black fw-medium">
                                        {{ item.user.name }}
                                    </span>
                                </div>
                            </td>
                            <td>
                                {{ item.email }}
                            </td>
                            <td>{{ item.location }}</td>
                            <td>{{ item.phone }}</td>
                            <td>{{ item.projects }}</td>
                            <td>{{ item.joinDate }}</td>
                            <td>
                                <div
                                    class="action-buttons d-flex align-items-center"
                                >
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.view }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.edit }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.delete }}
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
                <PaginationTwo items="10" />
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref, computed } from "vue";
import PaginationTwo from "../../../Common/PaginationTwo.vue";

import user6 from "../../../../../public/images/users/user6.jpg";
import user7 from "../../../../../public/images/users/user7.jpg";
import user8 from "../../../../../public/images/users/user8.jpg";
import user9 from "../../../../../public/images/users/user9.jpg";
import user10 from "../../../../../public/images/users/user10.jpg";
import user11 from "../../../../../public/images/users/user11.jpg";
import user12 from "../../../../../public/images/users/user12.jpg";
import user13 from "../../../../../public/images/users/user13.jpg";
import user14 from "../../../../../public/images/users/user14.jpg";
import user15 from "../../../../../public/images/users/user15.jpg";
import user16 from "../../../../../public/images/users/user16.jpg";
import user17 from "../../../../../public/images/users/user17.jpg";
import user18 from "../../../../../public/images/users/user18.jpg";
import user19 from "../../../../../public/images/users/user19.jpg";

export default defineComponent({
    name: "UsersList",
    components: {
        PaginationTwo,
    },
    setup() {
        const items = ref([
            {
                userID: "#JAN-158",
                user: {
                    image: user6,
                    name: "Marcia Baker",
                },
                email: "marcia@trezo.com",
                location: "Washington D.C",
                phone: "+1 555-445-4455",
                projects: 6,
                joinDate: "01 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-325",
                user: {
                    image: user7,
                    name: "Carolyn Barnes",
                },
                email: "barnes@trezo.com",
                location: "Chicago",
                phone: "+1 555-455-9966",
                projects: 10,
                joinDate: "02 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-286",
                user: {
                    image: user8,
                    name: "Donna Miller",
                },
                email: "donna@trezo.com",
                location: "Oklahoma City",
                phone: "+1 555-555-9922",
                projects: 6,
                joinDate: "03 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-463",
                user: {
                    image: user9,
                    name: "Barbara Cross",
                },
                email: "cross@trezo.com",
                location: "San Diego",
                phone: "+1 555-445-7788",
                projects: 4,
                joinDate: "04 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-491",
                user: {
                    image: user10,
                    name: "Rebecca Block",
                },
                email: "block@trezo.com",
                location: "Los Angeles",
                phone: "+1 555-333-2288",
                projects: 2,
                joinDate: "05 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-860",
                user: {
                    image: user11,
                    name: "Ramiro McCarty",
                },
                email: "ramiro@trezo.com",
                location: "Las Vegas",
                phone: "+1 555-445-4455",
                projects: 8,
                joinDate: "06 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-431",
                user: {
                    image: user12,
                    name: "Robert Fairweather",
                },
                email: "robert@trezo.com",
                location: "San Francisco",
                phone: "+1 555-555-9922",
                projects: 6,
                joinDate: "07 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-998",
                user: {
                    image: user13,
                    name: "Marcelino Haddock",
                },
                email: "haddock@trezo.com",
                location: "Washington D.C",
                phone: "+1 555-455-9966",
                projects: 9,
                joinDate: "08 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-436",
                user: {
                    image: user14,
                    name: "Thomas Wilson",
                },
                email: "wildon@trezo.com",
                location: "San Diego",
                phone: "+1 555-333-2288",
                projects: 5,
                joinDate: "10 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                userID: "#JAN-125",
                user: {
                    image: user15,
                    name: "Nathaniel Hulsey",
                },
                email: "hulsey@trezo.com",
                location: "Chicago",
                phone: "+1 555-445-7788",
                projects: 6,
                joinDate: "11 Dec 2024",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
        ]);

        const searchTerm = ref("");

        const filteredItems = computed(() => {
            return items.value.filter(
                (item) =>
                    item.userID
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.user.name
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.email
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.location
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.phone
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.joinDate
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase())
            );
        });

        return {
            items,
            searchTerm,
            filteredItems,
        };
    },
});
</script>

<style lang="scss" scoped>
.users-list-card {
    padding-bottom: 8px !important;
    .trezo-table-content {
        .trezo-table {
            margin-left: -25px;
            margin-right: -25px;
            table {
                thead {
                    tr {
                        th {
                            background-color: #ecf0ff !important;
                            padding: {
                                top: 13px;
                                bottom: 13px;
                            }
                            &:first-child {
                                border-top-left-radius: 0 !important;
                                padding: {
                                    left: 25px;
                                    right: 0;
                                }
                            }
                            &:last-child {
                                border-top-right-radius: 0 !important;
                                padding-right: 25px;
                            }
                            .v-checkbox.v-input {
                                margin: -18px -9px -40px -10px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                    }
                }
                tbody {
                    tr {
                        td {
                            padding: {
                                top: 17px !important;
                                bottom: 17px !important;
                            }
                            &:first-child {
                                border-left-width: 0 !important;
                                padding: {
                                    left: 25px;
                                    right: 0;
                                }
                            }
                            &:last-child {
                                padding-right: 25px;
                                border-right-width: 0 !important;
                            }
                            .v-checkbox.v-input {
                                margin: -10px -30px -32px -10px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                        &:last-child {
                            td {
                                border-bottom-width: 0;
                            }
                        }
                        &:first-child {
                            td {
                                border-top-width: 0;
                            }
                        }
                    }
                }
            }
            .pagination-content {
                margin-top: 0;
                padding: 15px 20px;
                border-radius: 0 0 7px 7px;
                color: var(--blackColor) !important;
                background-color: transparent !important;
                border-top: 1px solid #eceef2;
            }
        }
    }
}
</style>

// react-nextjs-material-ui-starter/src/components/Users/UsersList/index.tsx
"use client";

import React, { useState } from "react";
import Image from "next/image";
import {
  Card,
  Box,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableFooter,
  TablePagination,
  TableRow,
  Paper,
  IconButton,
  TableHead,
  Button,
} from "@mui/material";
import Link from "next/link";
import { useTheme } from "@mui/material/styles";
import KeyboardArrowLeft from "@mui/icons-material/KeyboardArrowLeft";
import KeyboardArrowRight from "@mui/icons-material/KeyboardArrowRight";
import AddIcon from "@mui/icons-material/Add";
import { useParams } from "next/navigation";

interface TablePaginationActionsProps {
  count: number;
  page: number;
  rowsPerPage: number;
  onPageChange: (
    event: React.MouseEvent<HTMLButtonElement>,
    newPage: number
  ) => void;
}

function TablePaginationActions(props: TablePaginationActionsProps) {
  const theme = useTheme();
  const { count, page, rowsPerPage, onPageChange } = props;

  const handleBackButtonClick = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    onPageChange(event, page - 1);
  };

  const handleNextButtonClick = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    onPageChange(event, page + 1);
  };

  return (
    <Box
      sx={{
        flexShrink: 0,
        display: "flex",
        gap: "10px",
        padding: "14px 20px",
      }}
    >
      <IconButton
        onClick={handleBackButtonClick}
        disabled={page === 0}
        aria-label="previous page"
        sx={{
          borderRadius: "4px",
          padding: "6px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowRight />
        ) : (
          <KeyboardArrowLeft />
        )}
      </IconButton>

      <IconButton
        onClick={handleNextButtonClick}
        disabled={page >= Math.ceil(count / rowsPerPage) - 1}
        aria-label="next page"
        sx={{
          borderRadius: "4px",
          padding: "6px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowLeft />
        ) : (
          <KeyboardArrowRight />
        )}
      </IconButton>
    </Box>
  );
}

function createData(
  userId: string,
  userImage: string,
  userName: string,
  email: string,
  location: string,
  phone: string,
  projects: number,
  joinDate: string
) {
  return {
    userId,
    userImage,
    userName,
    email,
    location,
    phone,
    projects,
    joinDate,
  };
}

const rows = [
  createData(
    "#JAN-158",
    "/images/users/user6.jpg",
    "Marcia Baker",
    "marcia@trezo.com",
    "Washington D.C",
    "+1 555-445-4455",
    6,
    "01 Dec 2024"
  ),
  createData(
    "#JAN-157",
    "/images/users/user7.jpg",
    "Carolyn Barnes",
    "carolyn@trezo.com",
    "Chicago",
    "+1 555-455-9966",
    10,
    "02 Dec 2024"
  ),
  createData(
    "#JAN-156",
    "/images/users/user8.jpg",
    "Donna Miller",
    "donna@trezo.com",
    "San Diego",
    "+1 555-445-7788",
    4,
    "03 Dec 2024"
  ),
  createData(
    "#JAN-155",
    "/images/users/user9.jpg",
    "Barbara Cros",
    "barbara@trezo.com",
    "San Diego",
    "+1 555-445-778",
    4,
    "04 Dec 2024"
  ),
  createData(
    "#JAN-154",
    "/images/users/user10.jpg",
    "Rebecca Block",
    "rebecca@trezo.com",
    "Los Angeles",
    "+1 555-333-2288",
    2,
    "05 Dec 2024"
  ),
  createData(
    "#JAN-153",
    "/images/users/user11.jpg",
    "Ramiro McCarty",
    "ramiro@trezo.com",
    "Las Vegas",
    "+1 555-445-4455",
    8,
    "06 Dec 2024"
  ),
  createData(
    "#JAN-152",
    "/images/users/user12.jpg",
    "Robert Fairweather",
    "robert@trezo.com",
    "San Francisco",
    "+1 555-555-9922",
    6,
    "07 Dec 2024"
  ),
  createData(
    "#JAN-151",
    "/images/users/user13.jpg",
    "Marcelino Haddock",
    "marcelino@trezo.com",
    "Washington D.C",
    "+1 555-455-9966",
    9,
    "08 Dec 2024"
  ),
  createData(
    "#JAN-150",
    "/images/users/user14.jpg",
    "Thomas Wilson",
    "thomas@trezo.com",
    "San Dieg",
    "+1 555-333-2288",
    5,
    "09 Dec 2024"
  ),
  createData(
    "#JAN-149",
    "/images/users/user15.jpg",
    "Nathaniel Hulsey",
    "nathaniel@trezo.com",
    "Chicago",
    "+1 555-445-7788",
    6,
    "10 Dec 2024"
  ),
  createData(
    "#JAN-148",
    "/images/users/user16.jpg",
    "Marcia Baker",
    "marcia@trezo.com",
    "Washington D.C",
    "+1 555-543-4455",
    1,
    "11 Dec 2024"
  ),
  createData(
    "#JAN-147",
    "/images/users/user17.jpg",
    "Carolyn Barnes",
    "carolyn@trezo.com",
    "Chicago",
    "+1 555-763-9966",
    2,
    "12 Dec 2024"
  ),
  createData(
    "#JAN-146",
    "/images/users/user18.jpg",
    "Donna Miller",
    "donna@trezo.com",
    "San Diego",
    "+1 555-237-7788",
    3,
    "13 Dec 2024"
  ),
  createData(
    "#JAN-145",
    "/images/users/user19.jpg",
    "Barbara Cros",
    "barbara@trezo.com",
    "San Diego",
    "+1 555-963-778",
    4,
    "14 Dec 2024"
  ),
  createData(
    "#JAN-144",
    "/images/users/user20.jpg",
    "Rebecca Block",
    "rebecca@trezo.com",
    "Los Angeles",
    "+1 555-946-2288",
    5,
    "15 Dec 2024"
  ),
  createData(
    "#JAN-143",
    "/images/users/user21.jpg",
    "Ramiro McCarty",
    "ramiro@trezo.com",
    "Las Vegas",
    "+1 555-456-4455",
    6,
    "16 Dec 2024"
  ),
  createData(
    "#JAN-142",
    "/images/users/user22.jpg",
    "Robert Fairweather",
    "robert@trezo.com",
    "San Francisco",
    "+1 555-247-9922",
    7,
    "17 Dec 2024"
  ),
  createData(
    "#JAN-141",
    "/images/users/user23.jpg",
    "Marcelino Haddock",
    "marcelino@trezo.com",
    "Washington D.C",
    "+1 555-456-9966",
    8,
    "18 Dec 2024"
  ),
  createData(
    "#JAN-140",
    "/images/users/user24.jpg",
    "Thomas Wilson",
    "thomas@trezo.com",
    "San Dieg",
    "+1 555-987-2288",
    9,
    "19 Dec 2024"
  ),
  createData(
    "#JAN-139",
    "/images/users/user25.jpg",
    "Nathaniel Hulsey",
    "nathaniel@trezo.com",
    "Chicago",
    "+1 555-345-7788",
    6,
    "20 Dec 2024"
  ),
].sort((b, a) => (a.userId < b.userId ? -1 : 1));

const UsersList: React.FC = () => {
  const { lang } = useParams();

  // Table
  const [page, setPage] = React.useState(0);
  const [rowsPerPage, setRowsPerPage] = React.useState(10);

  // Avoid a layout jump when reaching the last page with empty rows.
  const emptyRows =
    page > 0 ? Math.max(0, (1 + page) * rowsPerPage - rows.length) : 0;

  const handleChangePage = (
    event: React.MouseEvent<HTMLButtonElement> | null,
    newPage: number
  ) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (
    event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  // Search
  const [searchQuery, setSearchQuery] = useState("");

  const filteredRows = rows.filter(
    (row) =>
      row.userId.toLowerCase().includes(searchQuery.toLowerCase()) ||
      row.userName.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box>
          <Box
            sx={{
              display: { xs: "block", sm: "flex" },
              alignItems: "center",
              justifyContent: "space-between",
              mb: "25px",
            }}
          >
            <Box
              component="form"
              className="t-search-form"
              sx={{
                width: "265px",
              }}
            >
              <label>
                <i className="material-symbols-outlined">search</i>
              </label>
              <input
                type="text"
                className="t-input"
                placeholder="Search here..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </Box>

            <Link href={`/${lang}/users/add-user`}>
              <Button
                variant="outlined"
                sx={{
                  textTransform: "capitalize",
                  borderRadius: "7px",
                  fontWeight: "500",
                  fontSize: "13px",
                  padding: "6px 13px",
                }}
                color="primary"
              >
                <AddIcon sx={{ position: "relative", top: "-1px" }} /> Add New
                User
              </Button>
            </Link>
          </Box>

          {/* Table */}
          <Box
            sx={{
              marginLeft: "-25px",
              marginRight: "-25px",
            }}
          >
            <TableContainer
              component={Paper}
              sx={{
                boxShadow: "none",
                borderRadius: "0",
              }}
              className="rmui-table"
            >
              <Table sx={{ minWidth: 1250 }} aria-label="Table">
                <TableHead className="bg-primary-50">
                  <TableRow>
                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      User ID
                    </TableCell>

                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      User
                    </TableCell>

                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      Email
                    </TableCell>

                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      Location
                    </TableCell>

                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      Phone
                    </TableCell>

                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      Projects
                    </TableCell>

                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      Join Date
                    </TableCell>

                    <TableCell
                      sx={{
                        fontWeight: "500",
                        padding: "10px 20px",
                        fontSize: "14px",
                      }}
                      className="text-black border-bottom"
                    >
                      Action
                    </TableCell>
                  </TableRow>
                </TableHead>

                <TableBody>
                  {(rowsPerPage > 0
                    ? filteredRows.slice(
                        page * rowsPerPage,
                        page * rowsPerPage + rowsPerPage
                      )
                    : rows
                  ).map((row) => (
                    <TableRow key={row.userId}>
                      <TableCell
                        sx={{
                          padding: "14px 20px",
                          fontSize: "14px",
                        }}
                        className="border-bottom"
                      >
                        {row.userId}
                      </TableCell>

                      <TableCell
                        sx={{
                          padding: "14px 20px",
                          fontSize: "14px",
                        }}
                        className="border-bottom"
                      >
                        <Box
                          sx={{
                            display: "flex",
                            alignItems: "center",
                            gap: "13px",
                          }}
                        >
                          <Box sx={{ flexShrink: "0" }}>
                            <Image
                              src={row.userImage}
                              alt="Product"
                              width={40}
                              height={40}
                              style={{ borderRadius: "100px" }}
                            />
                          </Box>

                          <Box>
                            <Typography
                              sx={{
                                fontSize: "15px",
                                fontWeight: "500",
                              }}
                              className="text-black"
                            >
                              {row.userName}
                            </Typography>
                          </Box>
                        </Box>
                      </TableCell>

                      <TableCell
                        sx={{
                          padding: "14px 20px",
                          fontSize: "14px",
                        }}
                        className="text-black border-bottom"
                      >
                        {row.email}
                      </TableCell>

                      <TableCell
                        sx={{
                          padding: "14px 20px",
                          fontSize: "14px",
                        }}
                        className="text-black border-bottom"
                      >
                        {row.location}
                      </TableCell>

                      <TableCell
                        sx={{
                          padding: "14px 20px",
                          fontSize: "14px",
                        }}
                        className="text-black border-bottom"
                      >
                        {row.phone}
                      </TableCell>

                      <TableCell
                        sx={{
                          padding: "14px 20px",
                          fontSize: "14px",
                        }}
                        className="text-black border-bottom"
                      >
                        {row.projects}
                      </TableCell>

                      <TableCell
                        sx={{
                          padding: "14px 20px",
                          fontSize: "14px",
                        }}
                        className="text-black border-bottom"
                      >
                        {row.joinDate}
                      </TableCell>

                      <TableCell
                        sx={{
                          padding: "14px 20px",
                        }}
                        className="border-bottom"
                      >
                        <Box
                          sx={{
                            display: "flex",
                            alignItems: "center",
                          }}
                        >
                          <IconButton
                            aria-label="view"
                            color="primary"
                            sx={{ padding: "5px" }}
                          >
                            <i
                              className="material-symbols-outlined"
                              style={{ fontSize: "16px" }}
                            >
                              visibility
                            </i>
                          </IconButton>

                          <IconButton
                            aria-label="edit"
                            color="secondary"
                            sx={{ padding: "5px" }}
                          >
                            <i
                              className="material-symbols-outlined"
                              style={{ fontSize: "16px" }}
                            >
                              edit
                            </i>
                          </IconButton>

                          <IconButton
                            aria-label="delete"
                            color="error"
                            sx={{ padding: "5px" }}
                          >
                            <i
                              className="material-symbols-outlined"
                              style={{ fontSize: "16px" }}
                            >
                              delete
                            </i>
                          </IconButton>
                        </Box>
                      </TableCell>
                    </TableRow>
                  ))}
                  {emptyRows > 0 && (
                    <TableRow style={{ height: 53 * emptyRows }}>
                      <TableCell className="border-bottom" colSpan={8} />
                    </TableRow>
                  )}
                </TableBody>

                <TableFooter>
                  <TableRow>
                    <TablePagination
                      rowsPerPageOptions={[
                        5,
                        10,
                        25,
                        { label: "All", value: -1 },
                      ]}
                      colSpan={8}
                      count={rows.length}
                      rowsPerPage={rowsPerPage}
                      page={page}
                      slotProps={{
                        select: {
                          inputProps: {
                            "aria-label": "rows per page",
                          },
                          native: true,
                        },
                      }}
                      onPageChange={handleChangePage}
                      onRowsPerPageChange={handleChangeRowsPerPage}
                      ActionsComponent={TablePaginationActions}
                      sx={{
                        border: "none",
                      }}
                    />
                  </TableRow>
                </TableFooter>
              </Table>
            </TableContainer>
          </Box>
        </Box>
      </Card>
    </>
  );
};

export default UsersList;
