// svelte-bootstrap/src/lib/components/Dashboard/ProjectManagement/AllProjects.svelte
<div class="card bg-white border-0 rounded-3 mb-4">
	<div class="card-body p-0">
		<div class="p-4">
			<div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
				<h3 class="mb-0">All Projects</h3>
				<select
					class="form-select month-select form-control p-0 h-auto border-0 w-90"
					style="background-position: right 0 center;"
					aria-label="Default select example"
				>
					<option selected>This Week</option>
					<option value="1">This Month</option>
					<option value="2">This Year</option>
				</select>
			</div>
		</div>

		<div class="default-table-area style-two all-projects">
			<div class="table-responsive">
				<table class="table align-middle">
					<thead>
						<tr>
							<th scope="col">ID</th>
							<th scope="col">Project Name</th>
							<th scope="col">Client</th>
							<th scope="col">Assignees</th>
							<th scope="col">Budget</th>
							<th scope="col">Start Date</th>
							<th scope="col">End Date</th>
							<th scope="col">Status</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="text-body">#854</td>
							<td>
								<a href="project-overview.html">Project CyberSphere</a>
							</td>
							<td>NovaTech Solutions</td>
							<td>
								<ul class="ps-0 mb-0 list-unstyled d-flex align-items-center">
									<li>
										<a href="my-profile.html">
											<img
												src="/assets/images/user-16.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-17.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-18.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-19.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a
											href="/dashboard/user-list"
											class="wh-34 lh-34 rounded-circle bg-primary d-block text-center text-decoration-none text-white fs-12 fw-medium border border-1 border-color-white"
											>+10</a
										>
									</li>
								</ul>
							</td>
							<td class="text-body">$4,500</td>
							<td class="text-body">25 Mar 2024</td>
							<td class="text-body">25 Apr 2024</td>
							<td>
								<span class="badge bg-success bg-opacity-10 text-success p-2 fs-12 fw-normal"
									>Finished</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">#855</td>
							<td>
								<a href="project-overview.html">Digital Oasis Initiative</a>
							</td>
							<td>AlphaWave Innovations</td>
							<td>
								<ul class="ps-0 mb-0 list-unstyled d-flex align-items-center">
									<li>
										<a href="my-profile.html">
											<img
												src="/assets/images/user-16.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-17.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-18.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a
											href="/dashboard/user-list"
											class="wh-34 lh-34 rounded-circle bg-primary d-block text-center text-decoration-none text-white fs-12 fw-medium border border-1 border-color-white"
											>+04</a
										>
									</li>
								</ul>
							</td>
							<td class="text-body">$6,800</td>
							<td class="text-body">20 Mar 2024</td>
							<td class="text-body">20 Apr 2024</td>
							<td>
								<span class="badge bg-danger bg-opacity-10 text-danger p-2 fs-12 fw-normal"
									>In Progress</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">#856</td>
							<td>
								<a href="project-overview.html">CloudScape Evolution</a>
							</td>
							<td>InnovateIQ Inc.</td>
							<td>
								<ul class="ps-0 mb-0 list-unstyled d-flex align-items-center">
									<li>
										<a href="my-profile.html">
											<img
												src="/assets/images/user-16.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-17.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a
											href="/dashboard/user-list"
											class="wh-34 lh-34 rounded-circle bg-primary d-block text-center text-decoration-none text-white fs-12 fw-medium border border-1 border-color-white"
											>+07</a
										>
									</li>
								</ul>
							</td>
							<td class="text-body">$2,500</td>
							<td class="text-body">15 Mar 2024</td>
							<td class="text-body">15 Apr 2024</td>
							<td>
								<span
									class="badge bg-primary-div bg-opacity-10 text-primary-div p-2 fs-12 fw-normal"
									>Pending</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">#857</td>
							<td>
								<a href="project-overview.html">Data Dynamo Drive</a>
							</td>
							<td>BlueSky Technologies</td>
							<td>
								<ul class="ps-0 mb-0 list-unstyled d-flex align-items-center">
									<li>
										<a href="my-profile.html">
											<img
												src="/assets/images/user-16.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-17.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-18.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-19.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a
											href="/dashboard/user-list"
											class="wh-34 lh-34 rounded-circle bg-primary d-block text-center text-decoration-none text-white fs-12 fw-medium border border-1 border-color-white"
											>+15</a
										>
									</li>
								</ul>
							</td>
							<td class="text-body">$7,500</td>
							<td class="text-body">10 Mar 2024</td>
							<td class="text-body">10 Apr 2024</td>
							<td>
								<span class="badge bg-danger bg-opacity-10 text-danger p-2 fs-12 fw-normal"
									>In Progress</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">#858</td>
							<td>
								<a href="project-overview.html">QuantumLeap Quest</a>
							</td>
							<td>NexGen Systems</td>
							<td>
								<ul class="ps-0 mb-0 list-unstyled d-flex align-items-center">
									<li>
										<a href="my-profile.html">
											<img
												src="/assets/images/user-16.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-17.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a href="my-profile.html">
											<img
												src="/assets/images/user-18.jpg"
												class="wh-34 lh-34 rounded-circle border border-1 border-color-white"
												alt="user"
											/>
										</a>
									</li>
									<li class="ms-m-15">
										<a
											href="/dashboard/user-list"
											class="wh-34 lh-34 rounded-circle bg-primary d-block text-center text-decoration-none text-white fs-12 fw-medium border border-1 border-color-white"
											>+03</a
										>
									</li>
								</ul>
							</td>
							<td class="text-body">$3,400</td>
							<td class="text-body">05 Mar 2024</td>
							<td class="text-body">05 Apr 2024</td>
							<td>
								<span class="badge bg-success bg-opacity-10 text-success p-2 fs-12 fw-normal"
									>Finished</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="p-4 pt-lg-4">
				<div
					class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap"
				>
					<span class="fs-12 fw-medium">Showing 5 of 30 Results</span>

					<nav aria-label="Page navigation example">
						<ul class="pagination mb-0 justify-content-center">
							<li class="page-item">
								<a
									class="page-link icon"
									href="/dashboard/project-management"
									aria-label="Previous"
								>
									<i class="material-symbols-outlined">keyboard_arrow_left</i>
								</a>
							</li>
							<li class="page-item">
								<a class="page-link active" href="/dashboard/project-management">1</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="/dashboard/project-management">2</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="/dashboard/project-management">3</a>
							</li>
							<li class="page-item">
								<a class="page-link" href="/dashboard/project-management">4</a>
							</li>
							<li class="page-item">
								<a class="page-link icon" href="/dashboard/project-management" aria-label="Next">
									<i class="material-symbols-outlined">keyboard_arrow_right</i>
								</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>

// angular-material/src/app/dashboard/project-management/all-projects/all-projects.component.ts
import { Component, ViewChild } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { NgIf } from '@angular/common';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';

@Component({
    selector: 'app-all-projects',
    imports: [RouterLink, MatCardModule, MatButtonModule, MatMenuModule, MatTableModule, MatPaginatorModule, NgIf],
    templateUrl: './all-projects.component.html',
    styleUrl: './all-projects.component.scss'
})
export class AllProjectsComponent {

    displayedColumns: string[] = ['id', 'projectName', 'client', 'assignees', 'budget', 'startDate', 'endDate', 'status', 'action'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

    @ViewChild(MatPaginator) paginator!: MatPaginator;

    ngAfterViewInit() {
        this.dataSource.paginator = this.paginator;
    }

}

export interface PeriodicElement {
    id: string;
    projectName: string;
    client: string;
    assignees: any;
    budget: string;
    startDate: string;
    endDate: string;
    status: any;
    action: any;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        id: '#854',
        projectName: 'Project CyberSphere',
        client: 'NovaTech Solutions',
        assignees: {
            images: [
                {
                    img: 'images/users/user15.jpg'
                },
                {
                    img: 'images/users/user11.jpg'
                },
                {
                    img: 'images/users/user6.jpg'
                },
                {
                    img: 'images/users/user9.jpg'
                }
            ],
            number: '+10'
        },
        budget: '$4,500',
        startDate: '25 Mar 2025',
        endDate: '25 Apr 2025',
        status: {
            finished: true,
            inProgress: false,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#853',
        projectName: 'Digital Oasis Initiative',
        client: 'AlphaWave Innovations',
        assignees: {
            images: [
                {
                    img: 'images/users/user7.jpg'
                },
                {
                    img: 'images/users/user8.jpg'
                },
                {
                    img: 'images/users/user9.jpg'
                }
            ],
            number: '+04'
        },
        budget: '$6,800',
        startDate: '20 Mar 2025',
        endDate: '20 Apr 2025',
        status: {
            finished: false,
            inProgress: true,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#852',
        projectName: 'CloudScape Evolution',
        client: 'InnovateIQ Inc.',
        assignees: {
            images: [
                {
                    img: 'images/users/user10.jpg'
                },
                {
                    img: 'images/users/user12.jpg'
                }
            ],
            number: '+07'
        },
        budget: '$2,500',
        startDate: '15 Mar 2025',
        endDate: '15 Apr 2025',
        status: {
            finished: false,
            inProgress: false,
            pending: true,
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#851',
        projectName: 'Data Dynamo Drive',
        client: 'BlueSky Technologies',
        assignees: {
            images: [
                {
                    img: 'images/users/user13.jpg'
                },
                {
                    img: 'images/users/user14.jpg'
                },
                {
                    img: 'images/users/user15.jpg'
                },
                {
                    img: 'images/users/user12.jpg'
                }
            ],
            number: '+15'
        },
        budget: '$7,500',
        startDate: '10 Mar 2025',
        endDate: '10 Apr 2025',
        status: {
            finished: false,
            inProgress: true,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#849',
        projectName: 'QuantumLeap Quest',
        client: 'NexGen Systems',
        assignees: {
            images: [
                {
                    img: 'images/users/user7.jpg'
                },
                {
                    img: 'images/users/user9.jpg'
                },
                {
                    img: 'images/users/user6.jpg'
                }
            ],
            number: '+03'
        },
        budget: '$3,400',
        startDate: '05 Mar 2025',
        endDate: '05 Apr 2025',
        status: {
            finished: true,
            inProgress: false,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#849',
        projectName: 'QuantumLeap Quest',
        client: 'NexGen Systems',
        assignees: {
            images: [
                {
                    img: 'images/users/user7.jpg'
                },
                {
                    img: 'images/users/user9.jpg'
                },
                {
                    img: 'images/users/user6.jpg'
                }
            ],
            number: '+03'
        },
        budget: '$3,400',
        startDate: '05 Mar 2025',
        endDate: '05 Apr 2025',
        status: {
            finished: true,
            inProgress: false,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#851',
        projectName: 'Data Dynamo Drive',
        client: 'BlueSky Technologies',
        assignees: {
            images: [
                {
                    img: 'images/users/user13.jpg'
                },
                {
                    img: 'images/users/user14.jpg'
                },
                {
                    img: 'images/users/user15.jpg'
                },
                {
                    img: 'images/users/user12.jpg'
                }
            ],
            number: '+15'
        },
        budget: '$7,500',
        startDate: '10 Mar 2025',
        endDate: '10 Apr 2025',
        status: {
            finished: false,
            inProgress: true,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#853',
        projectName: 'Digital Oasis Initiative',
        client: 'AlphaWave Innovations',
        assignees: {
            images: [
                {
                    img: 'images/users/user7.jpg'
                },
                {
                    img: 'images/users/user8.jpg'
                },
                {
                    img: 'images/users/user9.jpg'
                }
            ],
            number: '+04'
        },
        budget: '$6,800',
        startDate: '20 Mar 2025',
        endDate: '20 Apr 2025',
        status: {
            finished: false,
            inProgress: true,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#854',
        projectName: 'Project CyberSphere',
        client: 'NovaTech Solutions',
        assignees: {
            images: [
                {
                    img: 'images/users/user15.jpg'
                },
                {
                    img: 'images/users/user11.jpg'
                },
                {
                    img: 'images/users/user6.jpg'
                },
                {
                    img: 'images/users/user9.jpg'
                }
            ],
            number: '+10'
        },
        budget: '$4,500',
        startDate: '25 Mar 2025',
        endDate: '25 Apr 2025',
        status: {
            finished: true,
            inProgress: false,
            pending: false
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    },
    {
        id: '#852',
        projectName: 'CloudScape Evolution',
        client: 'InnovateIQ Inc.',
        assignees: {
            images: [
                {
                    img: 'images/users/user10.jpg'
                },
                {
                    img: 'images/users/user12.jpg'
                }
            ],
            number: '+07'
        },
        budget: '$2,500',
        startDate: '15 Mar 2025',
        endDate: '15 Apr 2025',
        status: {
            finished: false,
            inProgress: false,
            pending: true,
        },
        action: {
            view: 'visibility',
            edit: 'edit',
            delete: 'delete'
        }
    }
];
