// angular-material/src/app/dashboard/social-media/suggestions/suggestions.component.ts
import { Component } from '@angular/core';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatMenuModule } from '@angular/material/menu';

@Component({
    selector: 'app-suggestions',
    imports: [MatCardModule, MatButtonModule, MatMenuModule],
    templateUrl: './suggestions.component.html',
    styleUrl: './suggestions.component.scss'
})
export class SuggestionsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<mat-card
    class="suggestions-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0 fw-semibold">
                Suggestions
            </h5>
            <p class="fw-normal">
                People may you know
            </p>
        </mat-card-title>
        <mat-card-subtitle>
            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu style-two p-0 d-inline-block border-radius-0">
                <i class="ri-more-2-fill"></i>
            </button>
            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                <ul class="p-0 mt-0 mb-0 list-unstyled">
                    <li>
                        <button mat-menu-item>
                            This Day
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Week
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Month
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Year
                        </button>
                    </li>
                </ul>
            </mat-menu>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <ul class="p-0 m-0 list-unstyled">
            <li class="d-flex align-items-center justify-content-between">
                <div class="user d-flex align-items-center">
                    <img src="images/users/user40.jpg" class="rounded-circle" alt="user-image">
                    <div>
                        <span class="d-block fw-medium text-black">
                            Sophia Adams
                        </span>
                        <span class="text-xs d-block">
                            12 mutual friends
                        </span>
                    </div>
                </div>
                <div class="action d-flex align-items-center">
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-delete-bin-7-line"></i>
                    </button>
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-user-add-line"></i>
                    </button>
                </div>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="user d-flex align-items-center">
                    <img src="images/users/user37.jpg" class="rounded-circle" alt="user-image">
                    <div>
                        <span class="d-block fw-medium text-black">
                            Liam Roberts
                        </span>
                        <span class="text-xs d-block">
                            8 mutual friends
                        </span>
                    </div>
                </div>
                <div class="action d-flex align-items-center">
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-delete-bin-7-line"></i>
                    </button>
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-user-add-line"></i>
                    </button>
                </div>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="user d-flex align-items-center">
                    <img src="images/users/user54.jpg" class="rounded-circle" alt="user-image">
                    <div>
                        <span class="d-block fw-medium text-black">
                            Olivia Martinez
                        </span>
                        <span class="text-xs d-block">
                            15 mutual friends
                        </span>
                    </div>
                </div>
                <div class="action d-flex align-items-center">
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-delete-bin-7-line"></i>
                    </button>
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-user-add-line"></i>
                    </button>
                </div>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="user d-flex align-items-center">
                    <img src="images/users/user41.jpg" class="rounded-circle" alt="user-image">
                    <div>
                        <span class="d-block fw-medium text-black">
                            Ethan Clarke
                        </span>
                        <span class="text-xs d-block">
                            10 mutual friends
                        </span>
                    </div>
                </div>
                <div class="action d-flex align-items-center">
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-delete-bin-7-line"></i>
                    </button>
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-user-add-line"></i>
                    </button>
                </div>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="user d-flex align-items-center">
                    <img src="images/users/user43.jpg" class="rounded-circle" alt="user-image">
                    <div>
                        <span class="d-block fw-medium text-black">
                            Isabella Cruz
                        </span>
                        <span class="text-xs d-block">
                            7 mutual friends
                        </span>
                    </div>
                </div>
                <div class="action d-flex align-items-center">
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-delete-bin-7-line"></i>
                    </button>
                    <button type="button" mat-button class="p-0 rounded-circle">
                        <i class="ri-user-add-line"></i>
                    </button>
                </div>
            </li>
        </ul>
    </mat-card-content>
</mat-card>

// nuxtjs-vuetify/components/Dashboard/SocialMedia/Suggestions.vue
<template>
  <v-card
    class="suggestions-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <div class="header-title">
        <h5 class="mb-0 fw-semibold">Suggestions</h5>
        <p class="fw-normal">People you may know</p>
      </div>
      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-2-fill"></i>
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <ul class="p-0 m-0 list-unstyled">
        <li
          v-for="(user, index) in users"
          :key="index"
          class="d-flex align-items-center justify-content-between"
        >
          <div class="user d-flex align-items-center">
            <v-img :src="user.image" class="rounded-circle" alt="user-image" />
            <div>
              <span class="d-block fw-medium text-black">
                {{ user.name }}
              </span>
              <span class="text-xs">
                {{ user.mutualFriends }} mutual friends
              </span>
            </div>
          </div>
          <div class="action d-flex align-items-center">
            <button
              type="button"
              class="d-flex align-items-center justify-content-center p-0 rounded-circle"
              @click="removeUser(index)"
            >
              <i class="ri-delete-bin-7-line"></i>
            </button>
            <button
              type="button"
              class="d-flex align-items-center justify-content-center p-0 rounded-circle"
              @click="addUser(user)"
            >
              <i class="ri-user-add-line"></i>
            </button>
          </div>
        </li>
      </ul>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

import image1 from "@/assets/images/users/user40.jpg";
import image2 from "@/assets/images/users/user37.jpg";
import image3 from "@/assets/images/users/user54.jpg";
import image4 from "@/assets/images/users/user41.jpg";
import image5 from "@/assets/images/users/user43.jpg";

interface User {
  name: string;
  image: string;
  mutualFriends: number;
}

export default defineComponent({
  // eslint-disable-next-line vue/multi-word-component-names
  name: "Suggestions",
  setup() {
    const users = ref<User[]>([
      {
        name: "Sophia Adams",
        image: image1,
        mutualFriends: 12,
      },
      {
        name: "Liam Roberts",
        image: image2,
        mutualFriends: 8,
      },
      {
        name: "Olivia Martinez",
        image: image3,
        mutualFriends: 15,
      },
      {
        name: "Ethan Clarke",
        image: image4,
        mutualFriends: 10,
      },
      {
        name: "Isabella Cruz",
        image: image5,
        mutualFriends: 7,
      },
    ]);

    const removeUser = (index: number) => {
      users.value.splice(index, 1);
    };

    const addUser = (user: User) => {
      console.log("Added user:", user);
      // You can implement logic to add the user to your network
    };

    return {
      users,
      removeUser,
      addUser,
    };
  },
});
</script>

<style lang="scss" scoped>
.suggestions-card {
  .v-card-header {
    margin-bottom: 20px;

    .header-title {
      h5 {
        font-size: 20px;
      }
      p {
        color: #8695aa;
      }
    }
  }
  .trezo-card-content {
    margin: {
      left: -25px;
      right: -25px;
    }
    ul {
      li {
        margin-bottom: 10.7px;
        border-bottom: 1px solid #f6f7f9;
        padding: {
          left: 25px;
          right: 25px;
          bottom: 10.7px;
        }
        .user {
          gap: 10px;

          .v-img {
            width: 44px;
          }
          span {
            &.text-xs {
              font-size: 12px;
            }
          }
        }
        .action {
          gap: 5px;

          button {
            width: 34px;
            height: 34px;
            font-size: 16px;
            color: var(--orangeColor);
            border: 1px solid #ffc8c0;
            background-color: transparent;
            transition: var(--transition);

            &:hover {
              color: var(--whiteColor);
              border-color: var(--orangeColor);
              background-color: var(--orangeColor);
            }
            &:nth-child(2) {
              color: var(--primaryColor);
              border-color: #c2cdff;

              &:hover {
                color: var(--whiteColor);
                border-color: var(--primaryColor);
                background-color: var(--primaryColor);
              }
            }
          }
        }
        &:last-child {
          margin-bottom: 0;
          padding-bottom: 0;
          border-bottom-width: 0;
        }
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .suggestions-card {
    .v-card-header {
      .header-title {
        h5 {
          font-size: 16px;
        }
        p {
          margin-top: 2px;
        }
      }
    }
    .trezo-card-content {
      margin: {
        left: -17px;
        right: -17px;
      }
      ul {
        li {
          padding: {
            left: 17px;
            right: 17px;
          }
        }
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
  .suggestions-card {
    .trezo-card-content {
      margin: {
        left: -20px;
        right: -20px;
      }
      ul {
        li {
          padding: {
            left: 20px;
            right: 20px;
          }
        }
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .suggestions-card {
    .v-card-header {
      .header-title {
        h5 {
          font-size: 18px;
        }
        p {
          margin-top: 1px;
        }
      }
    }
  }
}
</style>
