// vuejs-bootstrap/src/components/Dashboard/SocialMedia/Suggestions.vue
<template>
  <div
    class="suggestions-card card mb-4 border-0 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="trezo-card-header d-flex align-items-center justify-content-between"
      >
        <div class="trezo-card-title">
          <h5 class="mb-0 fw-semibold">Suggestions</h5>
          <p class="fw-normal">People you may know</p>
        </div>

        <div class="trezo-card-subtitle">
          <div class="trezo-card-header-menu position-relative">
            <div class="dropdown action-opt">
              <button
                class="btn bg-transparent p-0"
                type="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                <i class="ri-more-2-fill"></i>
              </button>

              <ul
                class="dropdown-menu dropdown-menu-end bg-white border box-shadow"
              >
                <li>
                  <a class="dropdown-item" href="javascript:;"> This Day </a>
                </li>
                <li>
                  <a class="dropdown-item" href="javascript:;"> This Week </a>
                </li>
                <li>
                  <a class="dropdown-item" href="javascript:;"> This Month </a>
                </li>
                <li>
                  <a class="dropdown-item" href="javascript:;"> This Year </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="trezo-card-content">
        <ul class="p-0 m-0 list-unstyled">
          <li
            v-for="(user, index) in users"
            :key="index"
            class="d-flex align-items-center justify-content-between"
          >
            <div class="user d-flex align-items-center">
              <img :src="user.image" class="rounded-circle" alt="user-image" />
              <div>
                <span class="d-block fw-medium text-black">
                  {{ user.name }}
                </span>
                <span class="text-xs">
                  {{ user.mutualFriends }} mutual friends
                </span>
              </div>
            </div>
            <div class="action d-flex align-items-center">
              <button
                type="button"
                class="d-flex align-items-center justify-content-center p-0 rounded-circle"
                @click="removeUser(index)"
              >
                <i class="ri-delete-bin-7-line"></i>
              </button>
              <button
                type="button"
                class="d-flex align-items-center justify-content-center p-0 rounded-circle"
                @click="addUser(user)"
              >
                <i class="ri-user-add-line"></i>
              </button>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

interface User {
  name: string;
  image: string;
  mutualFriends: number;
}

export default defineComponent({
  // eslint-disable-next-line vue/multi-word-component-names
  name: "Suggestions",
  setup() {
    const users = ref<User[]>([
      {
        name: "Sophia Adams",
        image: require("@/assets/images/users/user40.jpg"),
        mutualFriends: 12,
      },
      {
        name: "Liam Roberts",
        image: require("@/assets/images/users/user37.jpg"),
        mutualFriends: 8,
      },
      {
        name: "Olivia Martinez",
        image: require("@/assets/images/users/user54.jpg"),
        mutualFriends: 15,
      },
      {
        name: "Ethan Clarke",
        image: require("@/assets/images/users/user41.jpg"),
        mutualFriends: 10,
      },
      {
        name: "Isabella Cruz",
        image: require("@/assets/images/users/user43.jpg"),
        mutualFriends: 7,
      },
    ]);

    const removeUser = (index: number) => {
      users.value.splice(index, 1);
    };

    const addUser = (user: User) => {
      console.log("Added user:", user);
      // You can implement logic to add the user to your network
    };

    return {
      users,
      removeUser,
      addUser,
    };
  },
});
</script>

<style lang="scss" scoped>
.suggestions-card {
  .trezo-card-header {
    margin-bottom: 20px;

    .trezo-card-title {
      h5 {
        font-size: 20px;
      }
      p {
        color: #8695aa;
      }
    }
  }
  .trezo-card-content {
    margin: {
      left: -25px;
      right: -25px;
    }
    ul {
      li {
        margin-bottom: 10.7px;
        border-bottom: 1px solid #f6f7f9;
        padding: {
          left: 25px;
          right: 25px;
          bottom: 10.7px;
        }
        .user {
          gap: 10px;

          img {
            width: 44px;
          }
          span {
            &.text-xs {
              font-size: 12px;
            }
          }
        }
        .action {
          gap: 5px;

          button {
            width: 34px;
            height: 34px;
            font-size: 16px;
            color: var(--orangeColor);
            border: 1px solid #ffc8c0;
            background-color: transparent;
            transition: var(--transition);

            &:hover {
              color: var(--whiteColor);
              border-color: var(--orangeColor);
              background-color: var(--orangeColor);
            }
            &:nth-child(2) {
              color: var(--primaryColor);
              border-color: #c2cdff;

              &:hover {
                color: var(--whiteColor);
                border-color: var(--primaryColor);
                background-color: var(--primaryColor);
              }
            }
          }
        }
        &:last-child {
          margin-bottom: 0;
          padding-bottom: 0;
          border-bottom-width: 0;
        }
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .suggestions-card {
    .trezo-card-header {
      .trezo-card-title {
        h5 {
          font-size: 16px;
        }
        p {
          margin-top: 2px;
        }
      }
    }
    .trezo-card-content {
      margin: {
        left: -17px;
        right: -17px;
      }
      ul {
        li {
          padding: {
            left: 17px;
            right: 17px;
          }
        }
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
  .suggestions-card {
    .trezo-card-content {
      margin: {
        left: -20px;
        right: -20px;
      }
      ul {
        li {
          padding: {
            left: 20px;
            right: 20px;
          }
        }
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .suggestions-card {
    .trezo-card-header {
      .trezo-card-title {
        h5 {
          font-size: 18px;
        }
        p {
          margin-top: 1px;
        }
      }
    }
  }
}
</style>

// react-bootstrap/src/components/Dashboard/SocialMedia/Suggestions.js
"use client";

import { Card, Dropdown } from "react-bootstrap";

// Sample dynamic data for suggested users
const suggestedUsersData = [
  {
    id: 1,
    name: "Sophia Adams",
    profileImage: "/images/user-113.png",
    mutualFriends: 12,
  },
  {
    id: 2,
    name: "Liam Roberts",
    profileImage: "/images/user-114.png",
    mutualFriends: 8,
  },
  {
    id: 3,
    name: "Olivia Martinez",
    profileImage: "/images/user-115.png",
    mutualFriends: 15,
  },
  {
    id: 4,
    name: "Ethan Clarke",
    profileImage: "/images/user-116.png",
    mutualFriends: 10,
  },
  {
    id: 5,
    name: "Isabella Cruz",
    profileImage: "/images/user-117.png",
    mutualFriends: 7,
  },
];

const Suggestions = () => {
  return (
    <Card className="custom-shadow rounded-3 bg-white border mb-4 pb-3">
      <div className="p-4">
        <div className="d-flex justify-content-between align-items-center gap-1 mb-3 mb-lg-4">
          <div>
            <h3 className="mb-0 fs-20 fw-semibold">Suggestions</h3>
            <span className="fw-normal fs-14" style={{ color: "#8695aa" }}>
              People you may know
            </span>
          </div>

          <Dropdown className="action-opt -right-10">
            <Dropdown.Toggle
              variant="secondary"
              id="dropdown-basic"
              className="bg-transparent p-0"
            >
              <i className="material-symbols-outlined">more_vert</i>
            </Dropdown.Toggle>

            <Dropdown.Menu className="bg-white border box-shadow">
              <Dropdown.Item href="#">
                <i className="material-symbols-outlined">schedule</i>
                Today
              </Dropdown.Item>
              <Dropdown.Item href="#">
                <i className="material-symbols-outlined">pie_chart</i>
                Last 7 Days
              </Dropdown.Item>
              <Dropdown.Item href="#">
                <i className="material-symbols-outlined">refresh</i>
                Last Month
              </Dropdown.Item>
              <Dropdown.Item href="#">
                <i className="material-symbols-outlined">calendar_today</i>
                Last 1 Year
              </Dropdown.Item>
              <Dropdown.Item href="#">
                <i className="material-symbols-outlined">bar_chart</i>
                All Time
              </Dropdown.Item>
              <Dropdown.Item href="#">
                <i className="material-symbols-outlined">visibility</i>
                View
              </Dropdown.Item>
              <Dropdown.Item href="#">
                <i className="material-symbols-outlined">delete</i>
                Delete
              </Dropdown.Item>
            </Dropdown.Menu>
          </Dropdown>
        </div>

        <div>
          {suggestedUsersData.map((user) => (
            <div
              key={user.id}
              className="d-flex justify-content-between align-items-center lcbmp-none"
              style={{ marginBottom: "20px" }}
            >
              <div className="d-flex align-items-center gap-2">
                <div className="flex-shrink-0">
                  <img
                    src={user.profileImage}
                    className="rounded-circle"
                    alt={user.name}
                    width={44}
                    height={44}
                  />
                </div>
                <div className="flex-grow-1">
                  <h4 className="fs-14 fw-medium mb-0">{user.name}</h4>
                  <span className="fs-12">
                    {user.mutualFriends} mutual friends
                  </span>
                </div>
              </div>

              <div className="d-flex flex-wrap gap-1">
                <button
                  className="bg-transparent p-0 d-inline-block border border-danger rounded-circle text-danger hover-bg-danger border-opacity-50"
                  style={{
                    width: "34px",
                    height: "34px",
                    lineHeight: "32px",
                  }}
                >
                  <i className="ri-delete-bin-7-line fs-16"></i>
                </button>

                <button
                  className="bg-transparent p-0 d-inline-block border border-primary rounded-circle text-primary hover-bg border-opacity-50"
                  style={{
                    width: "34px",
                    height: "34px",
                    lineHeight: "32px",
                  }}
                >
                  <i className="ri-user-add-line fs-16"></i>
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    </Card>
  );
};

export default Suggestions;
