// react-nextjs-material-ui/src/app/dashboard/marketing/page.tsx
import * as React from "react";
import { Grid } from "@mui/material";
import AdSpend from "@/components/Dashboard/Marketing/AdSpend";
import CostPerThousand from "@/components/Dashboard/Marketing/CostPerThousand";
import CostPerClick from "@/components/Dashboard/Marketing/CostPerClick";
import ClickThroughRate from "@/components/Dashboard/Marketing/ClickThroughRate";
import PerformanceOverview from "@/components/Dashboard/Marketing/PerformanceOverview";
import DownloadMobileApp from "@/components/Dashboard/Marketing/DownloadMobileApp";
import Highlights from "@/components/Dashboard/Marketing/Highlights";
import Channels from "@/components/Dashboard/Marketing/Channels";
import NewMarketingTool from "@/components/Dashboard/Marketing/NewMarketingTool";
import InstagramSubscriber from "@/components/Dashboard/Marketing/InstagramSubscriber";
import ExternalLinks from "@/components/Dashboard/Marketing/ExternalLinks";
import InstagramCampaigns from "@/components/Dashboard/Marketing/InstagramCampaigns";
import Campaigns from "@/components/Dashboard/Marketing/Campaigns";

export default function Page() {
  return (
    <>
      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 3 }}>
          <AdSpend />
        </Grid>

        <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 3 }}>
          <CostPerThousand />
        </Grid>

        <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 3 }}>
          <CostPerClick />
        </Grid>

        <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 3 }}>
          <ClickThroughRate />
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 8 }}>
          <PerformanceOverview />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 4 }}>
          <DownloadMobileApp />
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 4 }}>
          <Highlights />

          <Channels />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 8 }}>
          <Campaigns />

          <Grid container columnSpacing={{ xs: 3 }}>
            <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 6 }}>
              <ExternalLinks />
            </Grid>

            <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 6 }}>
              <InstagramCampaigns />
            </Grid>
          </Grid>
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 3 }}>
          <NewMarketingTool />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 9 }}>
          <InstagramSubscriber />
        </Grid>
      </Grid>
    </>
  );
}

// svelte-bootstrap/src/routes/dashboard/marketing/+page.svelte
<script>
	import Campaigns from '$lib/components/Dashboard/Marketing/Campaigns.svelte';
	import Channels from '$lib/components/Dashboard/Marketing/Channels.svelte';
	import ExternalLinks from '$lib/components/Dashboard/Marketing/ExternalLinks.svelte';
	import Highlights from '$lib/components/Dashboard/Marketing/Highlights.svelte';
	import InstagramCampaigns from '$lib/components/Dashboard/Marketing/InstagramCampaigns.svelte';
	import InstagramSubscriber from '$lib/components/Dashboard/Marketing/InstagramSubscriber.svelte';
	import MarketingTool from '$lib/components/Dashboard/Marketing/MarketingTool.svelte';
	import MobileApp from '$lib/components/Dashboard/Marketing/MobileApp.svelte';
	import PerformanceOverview from '$lib/components/Dashboard/Marketing/PerformanceOverview.svelte';
	import Statistics from '$lib/components/Dashboard/Marketing/Statistics.svelte';
</script>

<svelte:head>
	<title>Marketing | Trezo - Svelte & Bootsrap 5 Admin Dashboard Template</title>
</svelte:head>

<div class="row">
	<Statistics />
</div>
<div class="row">
	<PerformanceOverview />
	<MobileApp />
</div>

<div class="row">
	<div class="col-lg-4">
		<Highlights />
		<Channels />
	</div>
	<div class="col-lg-8">
		<Campaigns />
		<div class="row">
			<ExternalLinks />
			<InstagramCampaigns />
		</div>
	</div>
</div>

<div class="row">
	<MarketingTool />
	<InstagramSubscriber />
</div>
