// react-nextjs-material-ui/src/components/Dashboard/CallCenter/AgentsPerformanceOverview/index.tsx
"use client";

import React, { useState, useEffect } from "react";
import {
  Card,
  Typography,
  Grid,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Paper,
  Box,
} from "@mui/material";
import CustomDropdown from "./CustomDropdown";
import Image from "next/image";

interface Agent {
  id: number;
  name: string;
  calls: number;
  avgCallDuration: string;
  fcr: number;
  csat: number;
  statusColor: string;
  image: string;
}

const AgentsPerformanceOverview: React.FC = () => {
  const [data, setData] = useState<Agent[]>([]);
  const [topAgent, setTopAgent] = useState<Agent | null>(null);
  const [timeRange, setTimeRange] = useState("Last Month");

  useEffect(() => {
    const fetchData = async () => {
      const agentsData: Agent[] = [
        {
          id: 1,
          name: "John Smith",
          calls: 380,
          avgCallDuration: "3 mins 45 secs",
          fcr: 92,
          csat: 92,
          statusColor: "success.500",
          image: "/images/users/user61.jpg",
        },
        {
          id: 2,
          name: "Sarah Davis",
          calls: 65,
          avgCallDuration: "4 mins 10 secs",
          fcr: 85,
          csat: 90,
          statusColor: "success.500",
          image: "/images/users/user62.jpg",
        },
        {
          id: 3,
          name: "Michael Brown",
          calls: 58,
          avgCallDuration: "5 mins 20 secs",
          fcr: 82,
          csat: 87,
          statusColor: "orange.500",
          image: "/images/users/user63.jpg",
        },
        {
          id: 4,
          name: "Emily Johnson",
          calls: 72,
          avgCallDuration: "4 mins 30 secs",
          fcr: 88,
          csat: 90,
          statusColor: "success.500",
          image: "/images/users/user64.jpg",
        },
        {
          id: 5,
          name: "David Lee",
          calls: 53,
          avgCallDuration: "3 mins 50 secs",
          fcr: 80,
          csat: 85,
          statusColor: "orange.500",
          image: "/images/users/user65.jpg",
        },
      ];

      setData(agentsData);

      const topAgent = agentsData.reduce((prev, current) =>
        prev.csat > current.csat ? prev : current
      );
      setTopAgent(topAgent);
    };

    fetchData();
  }, [timeRange]);

  return (
    <Card
      sx={{
        boxShadow: "none",
        borderRadius: "7px",
        mb: "25px",
        px: { xs: "18px", sm: "20px", lg: "25px" },
        pt: { xs: "18px", sm: "20px", lg: "25px" },
        pb: { xs: "13px", sm: "15px", lg: "20px" },
      }}
      className="rmui-card"
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: "25px",
        }}
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
          }}
          className="text-black"
        >
          Agents Performance Overview
        </Typography>

        <Box>
          <CustomDropdown
            options={["This Day", "This Week", "This Month", "This Year"]} // Need to change the options also in CustomDropdown file
            onSelect={(value) => console.log(value)}
            defaultLabel="This Year"
          />
        </Box>
      </Box>

      <Box>
        {topAgent && (
          <Box>
            <Typography
              component={"span"}
              sx={{ display: "block", mb: "10px" }}
            >
              Top Performing Agent
            </Typography>

            <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
              <Grid size={{ xs: 12, sm: 12, md: 5 }}>
                <Box
                  sx={{ display: "flex", alignItems: "center", gap: "10px" }}
                >
                  <Box sx={{ position: "relative" }}>
                    <Image
                      src={topAgent.image}
                      alt={topAgent.name}
                      width={40}
                      height={40}
                      style={{ borderRadius: "4px" }}
                    />

                    <Box
                      className="po-right-0 -mr-4"
                      sx={{
                        position: "absolute",
                        top: "50%",
                        transform: "translateY(-50%)",
                        width: "8px",
                        height: "8px",
                        borderRadius: "50%",
                        bgcolor: `${topAgent.statusColor}`,
                      }}
                    ></Box>
                  </Box>

                  <Box>
                    <Typography
                      variant="h5"
                      className="text-black"
                      sx={{
                        fontWeight: 600,
                        fontSize: "14px",
                        mb: "0",
                      }}
                    >
                      {topAgent.name}
                    </Typography>

                    <Typography className="text-black">
                      {topAgent.calls} Calls
                    </Typography>
                  </Box>
                </Box>
              </Grid>

              <Grid size={{ xs: 12, sm: 12, md: 7 }}>
                <Box sx={{ mt: { xs: "10px", md: "0" } }}>
                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "space-between",
                      mb: "5px",
                    }}
                  >
                    <Typography>Customer Satisfaction (CSAT)</Typography>
                    <Typography>{topAgent.csat}%</Typography>
                  </Box>

                  <Box
                    sx={{
                      display: "flex",
                      width: "100%",
                      height: "6px",
                      overflow: "hidden",
                      borderRadius: "4px",
                      bgcolor: "grey.100",
                    }}
                  >
                    <Box
                      sx={{
                        display: "flex",
                        justifyContent: "center",
                        height: "6px",
                        overflow: "hidden",
                        borderRadius: "4px",
                        bgcolor: `${topAgent.statusColor}`,
                      }}
                      style={{ width: `${topAgent.csat}%` }}
                    ></Box>
                  </Box>
                </Box>
              </Grid>
            </Grid>
          </Box>
        )}

        <TableContainer
          component={Paper}
          sx={{
            boxShadow: "none",
            borderRadius: "0",
            mt: { xs: "15px", md: "20px" },
          }}
          className="rmui-table"
        >
          <Table sx={{ minWidth: 500 }}>
            <TableBody>
              {data.map((agent) => (
                <React.Fragment key={agent.id}>
                  <TableRow
                    key={agent.id}
                    sx={{
                      td: {
                        padding: "8px 9px",
                        fontSize: { xs: "12px", md: "14px" },
                      },
                    }}
                  >
                    <TableCell className="border-none bg-gray-50">
                      <Box
                        sx={{
                          display: "flex",
                          alignItems: "center",
                          gap: "10px",
                        }}
                      >
                        <Box sx={{ position: "relative", flexShrink: 0 }}>
                          <Image
                            src={agent.image}
                            alt={agent.name}
                            width={40}
                            height={40}
                            style={{ borderRadius: "4px" }}
                          />

                          <Box
                            className="po-right-0 -mr-4"
                            sx={{
                              position: "absolute",
                              top: "50%",
                              transform: "translateY(-50%)",
                              width: "8px",
                              height: "8px",
                              borderRadius: "50%",
                              bgcolor: `${agent.statusColor}`,
                            }}
                          ></Box>
                        </Box>

                        <Box>
                          <Typography
                            variant="h5"
                            className="text-black"
                            sx={{
                              fontWeight: 500,
                              fontSize: "14px",
                              mb: "0",
                            }}
                          >
                            {agent.name}
                          </Typography>
                          <Typography className="text-black">
                            {agent.calls} Calls
                          </Typography>
                        </Box>
                      </Box>
                    </TableCell>

                    <TableCell className="border-none bg-gray-50">
                      <Typography>Avg. Call Duration</Typography>

                      <Typography
                        className="text-black"
                        sx={{ fontWeight: 500 }}
                      >
                        {agent.avgCallDuration}
                      </Typography>
                    </TableCell>

                    <TableCell className="border-none bg-gray-50">
                      <Typography>FCR</Typography>

                      <Typography
                        className="text-black"
                        sx={{ fontWeight: 500 }}
                      >
                        {agent.fcr}%
                      </Typography>
                    </TableCell>

                    <TableCell className="border-none bg-gray-50">
                      <Typography>CSAT</Typography>

                      <Typography
                        className="text-black"
                        sx={{ fontWeight: 500 }}
                      >
                        {agent.csat}%
                      </Typography>
                    </TableCell>
                  </TableRow>

                  {/* Empty Row for Gap */}
                  <TableRow
                    sx={{
                      td: {
                        padding: "5px",
                      },
                    }}
                  >
                    <TableCell colSpan={4} className="border-none" />
                  </TableRow>
                </React.Fragment>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </Box>
    </Card>
  );
};

export default AgentsPerformanceOverview;

// laravel-vuetify/resources/components/Dashboard/CallCenter/AgentsPerformanceOverview.vue
<template>
    <v-card
        class="agents-performance-overview-card trezo-card mb-25 border border-radius d-block bg-white custom-shadow"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Agents Performance Overview</h5>
            <v-menu>
                <template v-slot:activator="{ props }">
                    <button
                        type="button"
                        v-bind="props"
                        class="card-header-menu border-none d-inline-block border-radius"
                    >
                        Last Month
                    </button>
                </template>
                <v-list class="menu-content">
                    <button type="button" class="bg-transparent border-none">
                        Today
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        Last Week
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        Last Month
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        Last Year
                    </button>
                </v-list>
            </v-menu>
        </div>

        <div class="row mb-4 pb-2">
            <div class="col-lg-12">
                <span class="d-block mb-3 fw-normal">Top Performing Agent</span>
            </div>
            <div class="col-sm-4">
                <div class="d-flex align-items-center">
                    <div class="flex-shrink-0 position-relative z-1">
                        <v-img
                            src="/images/user-161.png"
                            class="rounded-2"
                            alt="user"
                        />
                        <span
                            class="bg-success rounded-circle d-inline-block position-absolute top-50 start-100 translate-middle"
                            style="width: 8px; height: 8px"
                        ></span>
                    </div>
                    <div class="flex-grow-1 ms-10">
                        <h4 class="fs-14 fw-semibold mb-0">John Smith</h4>
                        <span>380 Calls</span>
                    </div>
                </div>
            </div>
            <div class="col-sm-8 mt-2 mt-sm-0">
                <div class="ms-sm-4 ps-sm-3">
                    <div
                        class="d-flex justify-content-between align-items-center mb-2"
                    >
                        <span>Customer Satisfaction (CSAT)</span>
                        <span>92%</span>
                    </div>
                    <div
                        class="progress bg-border-color"
                        role="progressbar"
                        aria-label="Success example"
                        aria-valuenow="92"
                        aria-valuemin="0"
                        aria-valuemax="100"
                        style="height: 6px"
                    >
                        <div
                            class="progress-bar bg-success-60 rounded-pill"
                            style="width: 92%; height: 6px"
                        ></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="default-table-area style-three agents-performance-overview">
            <div class="table-responsive">
                <table
                    class="table align-middle border-0"
                    border="0"
                    cellspacing="0"
                    cellpadding="0"
                >
                    <tbody>
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                    <div
                                        class="flex-shrink-0 position-relative z-1"
                                    >
                                        <v-img
                                            src="/images/user-162.png"
                                            class="rounded-2"
                                            alt="user"
                                        />
                                        <span
                                            class="bg-success rounded-circle d-inline-block position-absolute top-50 start-100 translate-middle"
                                            style="width: 8px; height: 8px"
                                        ></span>
                                    </div>
                                    <div class="flex-grow-1 ms-10">
                                        <h4 class="fs-14 fw-medium mb-0">
                                            Sarah Davis
                                        </h4>
                                        <span>65 Calls</span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <span class="text-body"
                                    >Avg. Call Duration</span
                                >
                                <span class="fw-medium d-block"
                                    >4 mins 10 secs</span
                                >
                            </td>
                            <td>
                                <span class="text-body">FCR</span>
                                <span class="fw-medium d-block">85%</span>
                            </td>
                            <td>
                                <span class="text-body">CSAT</span>
                                <span class="fw-medium d-block">90%</span>
                            </td>
                        </tr>
                        <tr>
                            <td
                                class="bg-white"
                                style="padding: 5px !important"
                            ></td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                    <div
                                        class="flex-shrink-0 position-relative z-1"
                                    >
                                        <v-img
                                            src="/images/user-163.png"
                                            class="rounded-2"
                                            alt="user"
                                        />
                                        <span
                                            class="bg-danger rounded-circle d-inline-block position-absolute top-50 start-100 translate-middle"
                                            style="width: 8px; height: 8px"
                                        ></span>
                                    </div>
                                    <div class="flex-grow-1 ms-10">
                                        <h4 class="fs-14 fw-medium mb-0">
                                            Michael Brown
                                        </h4>
                                        <span>58 Calls</span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <span class="text-body"
                                    >Avg. Call Duration</span
                                >
                                <span class="fw-medium d-block"
                                    >5 mins 20 secs</span
                                >
                            </td>
                            <td>
                                <span class="text-body">FCR</span>
                                <span class="fw-medium d-block">82%</span>
                            </td>
                            <td>
                                <span class="text-body">CSAT</span>
                                <span class="fw-medium d-block">87%</span>
                            </td>
                        </tr>
                        <tr>
                            <td
                                class="bg-white"
                                style="padding: 5px !important"
                            ></td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                    <div
                                        class="flex-shrink-0 position-relative z-1"
                                    >
                                        <v-img
                                            src="/images/user-164.png"
                                            class="rounded-2"
                                            alt="user"
                                        />
                                        <span
                                            class="bg-success rounded-circle d-inline-block position-absolute top-50 start-100 translate-middle"
                                            style="width: 8px; height: 8px"
                                        ></span>
                                    </div>
                                    <div class="flex-grow-1 ms-10">
                                        <h4 class="fs-14 fw-medium mb-0">
                                            Emily Johnson
                                        </h4>
                                        <span>72 Calls</span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <span class="text-body"
                                    >Avg. Call Duration</span
                                >
                                <span class="fw-medium d-block"
                                    >4 mins 30 secs</span
                                >
                            </td>
                            <td>
                                <span class="text-body">FCR</span>
                                <span class="fw-medium d-block">88%</span>
                            </td>
                            <td>
                                <span class="text-body">CSAT</span>
                                <span class="fw-medium d-block">90%</span>
                            </td>
                        </tr>
                        <tr>
                            <td
                                class="bg-white"
                                style="padding: 5px !important"
                            ></td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex align-items-center">
                                    <div
                                        class="flex-shrink-0 position-relative z-1"
                                    >
                                        <v-img
                                            src="/images/user-165.png"
                                            class="rounded-2"
                                            alt="user"
                                        />
                                        <span
                                            class="bg-danger rounded-circle d-inline-block position-absolute top-50 start-100 translate-middle"
                                            style="width: 8px; height: 8px"
                                        ></span>
                                    </div>
                                    <div class="flex-grow-1 ms-10">
                                        <h4 class="fs-14 fw-medium mb-0">
                                            David Lee
                                        </h4>
                                        <span>53 Calls</span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <span class="text-body"
                                    >Avg. Call Duration</span
                                >
                                <span class="fw-medium d-block"
                                    >3 mins 50 secs</span
                                >
                            </td>
                            <td>
                                <span class="text-body">FCR</span>
                                <span class="fw-medium d-block">80%</span>
                            </td>
                            <td>
                                <span class="text-body">CSAT</span>
                                <span class="fw-medium d-block">85%</span>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
    name: "AgentsPerformanceOverview",
});
</script>

<style lang="scss" scoped>
.agents-performance-overview-card {
    &.border {
        border: 1px solid #edeff5 !important;
    }
    .progress {
        display: flex;
        background-color: #e9ecef !important;

        .bg-success {
            background-color: var(--successColor) !important;
        }
        .bg-success-60 {
            background-color: rgb(37 176 3) !important;
        }
    }
    .mb-4 {
        margin-bottom: 1.3rem !important;
    }
    .mb-3 {
        margin-bottom: 1rem !important;
    }
}
</style>
