// vuejs-bootstrap/src/components/Dashboard/CreditCard/MyCards.vue
<template>
  <div
    class="card border-0 rounded-3 bg-white p-25 bg-img debit-card-bg-for-dark-mode"
    :style="{ 'background-image': `url(${debitCardBg})` }"
  >
    <div
      class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"
    >
      <h5 class="mb-0">My Cards</h5>

      <button
        class="btn btn-outline-primary d-flex align-items-center gap-1 hover-bg"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal"
      >
        <i
          class="material-symbols-outlined fs-22"
          style="position: relative; margin-left: -2px"
        >
          add
        </i>
        <span>Add Card</span>
      </button>
    </div>

    <div class="row g-4">
      <div class="col-sm-6">
        <div
          class="bg-img p-4 rounded-3"
          :style="{ 'background-image': `url(${debitCard1})` }"
        >
          <div class="d-flex align-content-center justify-content-between">
            <div>
              <span class="text-white fs-12 fw-medium d-block mb-12">
                Credit Card
              </span>
              <img src="@/assets/images/board-1.png" alt="board" />
            </div>
            <i class="ri-visa-fill fs-35 text-white lh-1"></i>
          </div>

          <h5
            class="fw-semibold text-white mb-12 d-flex gap-1 lh-1"
            style="margin-top: 40px"
          >
            <span>****</span><span>****</span><span>****</span><span>1784</span>
          </h5>
          <div class="d-flex align-content-center justify-content-between">
            <span class="text-white">Russell McCray</span>
            <span class="text-white fs-12">EXP : 12/30</span>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div
          class="bg-img p-4 rounded-3"
          :style="{ 'background-image': `url(${debitCard2})` }"
        >
          <div class="d-flex align-content-center justify-content-between">
            <div>
              <span class="text-white fs-12 fw-medium d-block mb-12">
                Credit Card
              </span>
              <img src="@/assets/images/board-1.png" alt="board" />
            </div>
            <i class="ri-mastercard-fill fs-35 text-white lh-1"></i>
          </div>

          <h5
            class="fw-semibold text-white mb-12 d-flex gap-1 lh-1"
            style="margin-top: 40px"
          >
            <span>****</span><span>****</span><span>****</span><span>1794</span>
          </h5>
          <div class="d-flex align-content-center justify-content-between">
            <span class="text-white">Russell McCray</span>
            <span class="text-white fs-12">EXP : 12/30</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal Card Add -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" style="max-width: 738px">
        <div class="modal-content p-4 p-md-5">
          <div class="modal-header p-0 border-0">
            <h3 class="mb-0">Add Card Detail</h3>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body p-0 pt-4">
            <form>
              <div class="row">
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">Full Name</label>
                    <input
                      type="text"
                      class="form-control h-55"
                      placeholder="Enter name"
                    />
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">Card Number</label>
                    <input
                      type="text"
                      class="form-control h-55"
                      placeholder="Enter card number"
                    />
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">Expiry Date</label>
                    <input type="date" class="form-control h-55" />
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">CVV</label>
                    <input
                      type="number"
                      class="form-control h-55"
                      placeholder="212"
                    />
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer border-0 p-0">
            <button
              type="button"
              class="btn btn-danger text-white px-3"
              data-bs-dismiss="modal"
            >
              Cancel
            </button>
            <button type="button" class="btn btn-primary hover-bg px-3">
              Add Card
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
// import debitCardBg from "@/assets/images/debit-card-bg.jpg";
// import debitCard1 from "@/assets/images/debit-card-2.jpg";
// import debitCard2 from "@/assets/images/debit-card-3.jpg";

export default defineComponent({
  name: "MyCards",
  setup() {
    return {
      debitCardBg: require("@/assets/images/debit-card-bg.jpg"),
      debitCard1: require("@/assets/images/debit-card-2.jpg"),
      debitCard2: require("@/assets/images/debit-card-3.jpg"),
    };
  },
});
</script>

// react-bootstrap/src/components/Dashboard/CreditCard/MyCards.js
"use client";

import React, { useState } from "react";
import { Card, Row, Col, Form, Button } from "react-bootstrap";

const MyCards = () => {
  // Modal
  const [isShowModal, setShowModal] = useState("false");
  const handleToggleShowModal = () => {
    setShowModal(!isShowModal);
  };

  return (
    <>
      <Card
        className="border-0 rounded-3 bg-white p-25 bg-img cc-card"
        style={{
          backgroundImage: "url(/images/debit-card-bg.jpg)",
        }}
      >
        <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4">
          <h3 className="mb-0">My Cards</h3>

          <button
            className="btn btn-outline-primary d-flex align-items-center gap-1 hover-bg"
            onClick={handleToggleShowModal}
          >
            <i className="material-symbols-outlined fs-22">add</i>
            <span>Add Card</span>
          </button>
        </div>

        <Row className="g-4">
          <Col sm={6}>
            <div
              className="bg-img p-4 rounded-3"
              style={{
                backgroundImage: "url(/images/debit-card-2.jpg)",
              }}
            >
              <div className="d-flex align-content-center justify-content-between">
                <div>
                  <span className="text-white fs-12 fw-medium d-block mb-3">
                    Credit Card
                  </span>
                  <img
                    src="/images/board-1.png"
                    alt="board"
                    width={45}
                    height={30}
                  />
                </div>
                <i className="ri-visa-fill fs-35 text-white lh-1"></i>
              </div>

              <h3
                className="fw-semibold mb-12 d-flex gap-1 lh-1"
                style={{
                  marginTop: "40px",
                }}
              >
                <span className="text-white">****</span>
                <span className="text-white">****</span>
                <span className="text-white">****</span>
                <span className="text-white">1784</span>
              </h3>

              <div className="d-flex align-content-center justify-content-between">
                <span className="text-white">Russell McCray</span>
                <span className="text-white fs-12">EXP : 12/30</span>
              </div>
            </div>
          </Col>

          <Col sm={6}>
            <div
              className="bg-img p-4 rounded-3"
              style={{
                backgroundImage: "url(/images/debit-card-3.jpg)",
              }}
            >
              <div className="d-flex align-content-center justify-content-between">
                <div>
                  <span className="text-white fs-12 fw-medium d-block mb-3">
                    Credit Card
                  </span>
                  <img
                    src="/images/board-1.png"
                    alt="board"
                    width={45}
                    height={30}
                  />
                </div>
                <i className="ri-mastercard-fill fs-35 text-white lh-1"></i>
              </div>

              <h3
                className="fw-semibold mb-12 d-flex gap-1 lh-1"
                style={{
                  marginTop: "40px",
                }}
              >
                <span className="text-white">****</span>
                <span className="text-white">****</span>
                <span className="text-white">****</span>
                <span className="text-white">1794</span>
              </h3>

              <div className="d-flex align-content-center justify-content-between">
                <span className="text-white">Russell McCray</span>
                <span className="text-white fs-12">EXP : 12/30</span>
              </div>
            </div>
          </Col>
        </Row>
      </Card>

      {/* Modal */}
      <div className={`custom-modal right ${isShowModal ? "" : "show"}`}>
        <div className="custom-modal-content position-relative z-3">
          <div className="border-bottom py-3 px-4 d-flex align-items-center justify-content-between">
            <h3 className="fs-18 mb-0">Add Card Detail</h3>

            <div className="close-link" onClick={handleToggleShowModal}>
              <span className="material-symbols-outlined">close</span>
            </div>
          </div>

          <div className="p-4">
            <Form>
              <Row>
                <Col sm={12}>
                  <Form.Group className="mb-4">
                    <Form.Label className="label">Full Name</Form.Label>
                    <Form.Control
                      type="text"
                      className="text-dark"
                      placeholder="Enter Name"
                    />
                  </Form.Group>
                </Col>

                <Col sm={12}>
                  <Form.Group className="mb-4">
                    <Form.Label className="label">Card Number</Form.Label>
                    <Form.Control
                      type="text"
                      className="text-dark"
                      placeholder="Enter card number"
                    />
                  </Form.Group>
                </Col>

                <Col sm={12}>
                  <Form.Group className="mb-4">
                    <Form.Label className="label">Expiry Date</Form.Label>
                    <Form.Control
                      type="date"
                      className="text-dark" 
                    />
                  </Form.Group>
                </Col>

                <Col sm={12}>
                  <Form.Group className="mb-4">
                    <Form.Label className="label">CVV</Form.Label>
                    <Form.Control
                      type="text"
                      className="text-dark" 
                      placeholder="Enter CVV"
                    />
                  </Form.Group>
                </Col> 
              </Row>

              <Form.Group className="d-flex gap-3">
                <Button
                  variant="primary"
                  type="submit"
                  className="text-white fw-semibold py-2 px-2 px-sm-3"
                >
                  <span className="py-sm-1 d-block">
                    <i className="ri-add-line text-white"></i>{" "}
                    <span>Add Card</span>
                  </span>
                </Button>
              </Form.Group>
            </Form>
          </div>
        </div>

        <div className="close-outside" onClick={handleToggleShowModal}></div>
      </div>
    </>
  );
};

export default MyCards;
