// vuejs-vuetify/src/components/Dashboard/CreditCard/RecentTransactions.vue
<template>
  <v-card
    class="trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Recent Transactions</h5>
      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius"
          >
            {{ selectedFilter }}
          </button>
        </template>
        <v-list class="menu-content">
          <v-list-item v-for="filter in dateFilters" :key="filter">
            <v-list-item-title
              @click="changeFilter(filter)"
              style="cursor: pointer"
            >
              {{ filter }}
            </v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="table-style-two">
        <div class="basic-table table-responsive">
          <table class="table mb-0" border="0" cellspacing="0" cellpadding="0">
            <thead>
              <tr>
                <th scope="col" class="fw-medium">Date</th>
                <th scope="col" class="fw-medium">Description</th>
                <th scope="col" class="fw-medium">Category</th>
                <th scope="col" class="fw-medium">Amount ($)</th>
                <th scope="col" class="fw-medium">Status</th>
                <th scope="col" class="fw-medium">Action</th>
              </tr>
            </thead>

            <tbody>
              <tr
                v-for="transaction in paginatedTransactions"
                :key="transaction.id"
              >
                <td class="text-body">{{ formatDate(transaction.date) }}</td>
                <td class="text-body">{{ transaction.description }}</td>
                <td class="text-body">{{ transaction.category }}</td>
                <td class="text-body">
                  ${{ transaction.amount.toLocaleString() }}
                </td>
                <td>
                  <span
                    class="trezo-badge py-0 with-border border-radius"
                    :class="statusClasses(transaction.status)"
                  >
                    {{ transaction.status }}
                  </span>
                </td>
                <td>
                  <div class="action-buttons d-flex align-items-center">
                    <button
                      type="button"
                      class="p-0 bg-transparent d-inline-block lh-1 border-0"
                      @click="viewTransaction(transaction)"
                    >
                      <i class="material-symbols-outlined"> visibility </i>
                    </button>
                    <button
                      type="button"
                      class="p-0 bg-transparent d-inline-block lh-1 border-0"
                      @click="editTransaction(transaction)"
                    >
                      <i class="material-symbols-outlined"> edit </i>
                    </button>
                    <button
                      type="button"
                      class="p-0 bg-transparent d-inline-block lh-1 border-0"
                      @click="deleteTransaction(transaction.id)"
                    >
                      <i class="material-symbols-outlined"> delete </i>
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div
          class="trezo-card-pagination d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
        >
          <span class="fs-12 fw-medium">
            Showing {{ showingRange }} of
            {{ filteredTransactions.length }} Results
          </span>

          <nav aria-label="Page navigation example">
            <ul class="pagination mb-0 justify-content-center">
              <li class="page-item" :class="{ disabled: currentPage === 1 }">
                <button
                  class="page-link icon"
                  aria-label="Previous"
                  @click="prevPage"
                  :disabled="currentPage === 1"
                >
                  <i class="material-symbols-outlined">keyboard_arrow_left</i>
                </button>
              </li>
              <li class="page-item" v-for="page in totalPages" :key="page">
                <button
                  class="page-link"
                  :class="{ active: currentPage === page }"
                  @click="goToPage(page)"
                >
                  {{ page }}
                </button>
              </li>
              <li
                class="page-item"
                :class="{ disabled: currentPage === totalPages }"
              >
                <button
                  class="page-link icon"
                  aria-label="Next"
                  @click="nextPage"
                  :disabled="currentPage === totalPages"
                >
                  <i class="material-symbols-outlined">keyboard_arrow_right</i>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onMounted } from "vue";

interface Transaction {
  id: number;
  date: Date;
  description: string;
  category: string;
  amount: number;
  status: "Completed" | "Pending" | "Cancelled" | "Rejected";
}

export default defineComponent({
  name: "RecentTransactions",
  setup() {
    const transactions = ref<Transaction[]>([]);
    const dateFilters = ["Last 7 Days", "Last 15 Days", "Last 30 Days"];
    const selectedFilter = ref("Last 15 Days");
    const itemsPerPage = 6;
    const currentPage = ref(1);

    // Generate mock transactions
    const generateTransactions = (count: number): Transaction[] => {
      const categories = [
        "Dining",
        "Groceries",
        "Transportation",
        "Utilities",
        "Entertainment",
        "Sports",
      ];
      const statuses: ("Completed" | "Pending" | "Cancelled" | "Rejected")[] = [
        "Completed",
        "Pending",
        "Cancelled",
        "Rejected",
      ];

      return Array.from({ length: count }, (_, i) => {
        const daysAgo = Math.floor(Math.random() * 30);
        const date = new Date();
        date.setDate(date.getDate() - daysAgo);

        return {
          id: i + 1,
          date,
          description: `Transaction ${i + 1}`,
          category: categories[Math.floor(Math.random() * categories.length)],
          amount: parseFloat((Math.random() * 1000).toFixed(2)),
          status: statuses[Math.floor(Math.random() * statuses.length)],
        };
      });
    };

    // Filter transactions based on selected date range
    const filteredTransactions = computed(() => {
      const today = new Date();
      let cutoffDate = new Date();

      if (selectedFilter.value === "Last 7 Days") {
        cutoffDate.setDate(today.getDate() - 7);
      } else if (selectedFilter.value === "Last 15 Days") {
        cutoffDate.setDate(today.getDate() - 15);
      } else {
        // Last 30 Days
        cutoffDate.setDate(today.getDate() - 30);
      }

      return transactions.value
        .filter((t) => t.date >= cutoffDate)
        .sort((a, b) => b.date.getTime() - a.date.getTime());
    });

    // Pagination
    const totalPages = computed(() =>
      Math.ceil(filteredTransactions.value.length / itemsPerPage)
    );

    const paginatedTransactions = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage;
      const end = start + itemsPerPage;
      return filteredTransactions.value.slice(start, end);
    });

    const showingRange = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage + 1;
      const end = Math.min(
        currentPage.value * itemsPerPage,
        filteredTransactions.value.length
      );
      return `${start}-${end}`;
    });

    // Methods
    const changeFilter = (filter: string) => {
      selectedFilter.value = filter;
      currentPage.value = 1; // Reset to first page when filter changes
    };

    const formatDate = (date: Date) => {
      return date.toLocaleDateString("en-US", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      });
    };

    const statusClasses = (status: string) => {
      switch (status) {
        case "Completed":
          return "finished";
        case "Pending":
          return "sPending";
        case "Cancelled":
          return "cancelled";
        case "Rejected":
          return "rejected";
        default:
          return "";
      }
    };

    const viewTransaction = (transaction: Transaction) => {
      console.log("Viewing transaction:", transaction);
      // Implement view logic
    };

    const editTransaction = (transaction: Transaction) => {
      console.log("Editing transaction:", transaction);
      // Implement edit logic
    };

    const deleteTransaction = (id: number) => {
      if (confirm("Are you sure you want to delete this transaction?")) {
        transactions.value = transactions.value.filter((t) => t.id !== id);
      }
    };

    const goToPage = (page: number) => {
      currentPage.value = page;
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    // Initialize
    onMounted(() => {
      transactions.value = generateTransactions(36);
    });

    return {
      transactions,
      dateFilters,
      selectedFilter,
      currentPage,
      filteredTransactions,
      paginatedTransactions,
      totalPages,
      showingRange,
      changeFilter,
      formatDate,
      statusClasses,
      viewTransaction,
      editTransaction,
      deleteTransaction,
      goToPage,
      prevPage,
      nextPage,
    };
  },
});
</script>

<style scoped lang="scss">
.basic-table {
  table,
  .table {
    tbody {
      tr {
        td {
          padding: {
            bottom: 19px;
            top: 19px;
          }
        }
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .basic-table {
    table,
    .table {
      tbody {
        tr {
          td {
            padding: {
              bottom: 15px;
              top: 15px;
            }
          }
        }
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .basic-table {
    table,
    .table {
      tbody {
        tr {
          td {
            padding: {
              bottom: 17px;
              top: 17px;
            }
          }
        }
      }
    }
  }
}
</style>

// react-bootstrap/src/components/Dashboard/CreditCard/RecentTransactions.js
"use client";

import React, { useState } from "react";
import { Dropdown, Card, Table } from "react-bootstrap";

const RecentTransactions = () => {
  // Sample transaction data
  const transactionsData = [
    {
      id: 1,
      date: "30 Apr 2025",
      description: "Starbucks Coffee",
      category: "Dining",
      amount: "$500,000",
      status: "completed",
    },
    {
      id: 2,
      date: "29 Apr 2025",
      description: "Whole Foods",
      category: "Groceries",
      amount: "$90.50",
      status: "pending",
    },
    {
      id: 3,
      date: "28 Apr 2025",
      description: "Gas Station",
      category: "Transportation",
      amount: "$15.00",
      status: "cancelled",
    },
    {
      id: 4,
      date: "27 Apr 2025",
      description: "Electric Bill",
      category: "Utilities",
      amount: "$150.00",
      status: "completed",
    },
    {
      id: 5,
      date: "26 Apr 2025",
      description: "Spotify Subscription",
      category: "Entertainment",
      amount: "$10.00",
      status: "rejected",
    },
    {
      id: 6,
      date: "25 Apr 2025",
      description: "Football Ticket",
      category: "Sports",
      amount: "$99.99",
      status: "completed",
    },
    {
      id: 7,
      date: "24 Apr 2025",
      description: "Amazon Purchase",
      category: "Shopping",
      amount: "$75.25",
      status: "pending",
    },
    {
      id: 8,
      date: "23 Apr 2025",
      description: "Netflix Subscription",
      category: "Entertainment",
      amount: "$14.99",
      status: "completed",
    },
    {
      id: 9,
      date: "22 Apr 2025",
      description: "Car Insurance",
      category: "Insurance",
      amount: "$120.00",
      status: "completed",
    },
    {
      id: 10,
      date: "21 Apr 2025",
      description: "Dinner Reservation",
      category: "Dining",
      amount: "$85.00",
      status: "cancelled",
    },
    {
      id: 11,
      date: "25 Apr 2025",
      description: "Football Ticket",
      category: "Sports",
      amount: "$99.99",
      status: "completed",
    },
    {
      id: 12,
      date: "24 Apr 2025",
      description: "Amazon Purchase",
      category: "Shopping",
      amount: "$75.25",
      status: "pending",
    },
  ];

  // State for pagination
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 6;

  // Calculate pagination
  const totalItems = transactionsData.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = transactionsData.slice(
    indexOfFirstItem,
    indexOfLastItem
  );

  // Change page
  const paginate = (pageNumber) => setCurrentPage(pageNumber);
  const nextPage = () =>
    setCurrentPage((prev) => Math.min(prev + 1, totalPages));
  const prevPage = () => setCurrentPage((prev) => Math.max(prev - 1, 1));

  // Status styling
  const getStatusStyle = (status) => {
    switch (status.toLowerCase()) {
      case "completed":
        return {
          bg: "bg-success-60 bg-opacity-10",
          border: "border-success-60",
          text: "text-success-60",
        };
      case "pending":
        return {
          bg: "bg-card-bg-c bg-opacity-10",
          border: "border-card-bg-c",
          text: "text-card-bg-c",
        };
      case "cancelled":
        return {
          bg: "bg-danger-50 bg-opacity-10",
          border: "border-danger-50",
          text: "text-danger-50",
        };
      case "rejected":
        return {
          bg: "bg-danger-80 bg-opacity-10",
          border: "border-danger-80",
          text: "text-danger-80",
        };
      default:
        return {
          bg: "bg-gray-100 bg-opacity-10",
          border: "border-gray-100",
          text: "text-gray-100",
        };
    }
  };

  // Capitalize first letter
  const capitalize = (str) => {
    return str.charAt(0).toUpperCase() + str.slice(1);
  };

  return (
    <>
      <Card className="bg-white border-0 rounded-3">
        <Card.Body className="p-0">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-2 p-4">
            <h3 className="mb-0">Recent Transactions</h3>

            <Dropdown className="dropdown select-dropdown">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="dropdown-toggle border text-body rounded-2 bg-transparent"
              >
                Last 30 Days <i className="ri-arrow-down-s-line"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Last 7 Days
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Last 15 Days
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Last 30 Days
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <div className="default-table-area style-two cc-recent-transactions py-19">
            <div className="table-responsive">
              <Table className="align-middle">
                <thead>
                  <tr>
                    <th scope="col" className="text-secondary">
                      Date
                    </th>
                    <th scope="col" className="text-secondary">
                      Description
                    </th>
                    <th scope="col" className="text-secondary">
                      Category
                    </th>
                    <th scope="col" className="text-secondary">
                      Amount ($)
                    </th>
                    <th scope="col" className="text-secondary">
                      Status
                    </th>
                    <th scope="col" className="text-secondary">
                      Action
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {currentItems.map((transaction) => {
                    const statusStyle = getStatusStyle(transaction.status);
                    return (
                      <tr key={transaction.id}>
                        <td className="text-body">{transaction.date}</td>
                        <td className="text-body">{transaction.description}</td>
                        <td className="text-body">{transaction.category}</td>
                        <td className="text-body">{transaction.amount}</td>
                        <td>
                          {/* <span
                        className="d-inline-block bg-success-60 bg-opacity-10 border-success-60 border rounded-pill text-success-60 fs-12 fw-medium"
                        style={{
                          padding: "1px 10px",
                        }}
                      >
                        Completed
                      </span> */}

                          <span
                            className={`d-inline-block ${statusStyle.bg} ${statusStyle.border} border rounded-pill ${statusStyle.text} fs-12 fw-medium`}
                            style={{ padding: "1px 10px" }}
                          >
                            {capitalize(transaction.status)}
                          </span>
                        </td>

                        <td>
                          <div className="d-flex align-items-center gap-1">
                            <button className="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
                              <i className="material-symbols-outlined fs-16 text-primary">
                                visibility
                              </i>
                            </button>
                            <button className="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
                              <i className="material-symbols-outlined fs-16 text-body">
                                edit
                              </i>
                            </button>
                            <button className="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
                              <i className="material-symbols-outlined fs-16 text-danger">
                                delete
                              </i>
                            </button>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </Table>
            </div>

            <div className="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap p-4 pt-3">
              <span className="fs-13">
                {" "}
                Showing {indexOfFirstItem + 1}-
                {Math.min(indexOfLastItem, totalItems)} of {totalItems} Results
              </span>

              <nav aria-label="Page navigation example">
                <ul className="pagination mb-0 justify-content-center">
                  <li className="page-item">
                    <button
                      className="page-link icon hover-bg"
                      aria-label="Previous"
                      onClick={prevPage}
                      disabled={currentPage === 1}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_left
                      </i>
                    </button>
                  </li>
                  {Array.from({ length: totalPages }, (_, i) => i + 1).map(
                    (number) => (
                      <li key={number} className="page-item">
                        <button
                          className={`page-link ${
                            currentPage === number ? "active" : ""
                          }`}
                          onClick={() => paginate(number)}
                        >
                          {number}
                        </button>
                      </li>
                    )
                  )}
                  <li className="page-item">
                    <button
                      className="page-link icon hover-bg"
                      aria-label="Next"
                      onClick={nextPage}
                      disabled={currentPage === totalPages}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_right
                      </i>
                    </button>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default RecentTransactions;
