// react-nextjs-material-ui/src/components/Dashboard/Restaurant/RevenueByBranches/index.tsx
"use client";

import React, { useState, useEffect } from "react";
import {
  Box,
  Typography,
  Card,
  Menu,
  MenuItem,
  IconButton,
} from "@mui/material";
import { MoreVert } from "@mui/icons-material";
import Image from "next/image";
import WorldMap from "react-svg-worldmap";

interface CountryData {
  country: string;
  value: number;
}

interface BranchData {
  id: string;
  countryCode: string;
  countryName: string;
  flagImage: string;
  percentage: number;
  color: string;
}

const RevenueByBranches: React.FC = () => {
  // Dropdown
  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
  const open = Boolean(anchorEl);
  const handleClick = (event: React.MouseEvent<HTMLElement>) => {
    setAnchorEl(event.currentTarget);
  };
  const handleClose = () => {
    setAnchorEl(null);
  };

  // CountryData for WorldMap
  const data: CountryData[] = [
    { country: "us", value: 331883986 }, // United States
    { country: "de", value: 83129285 }, // Germany
    { country: "gb", value: 67886011 }, // United Kingdom
    { country: "ca", value: 38005238 }, // Canada
    { country: "pt", value: 10196709 }, // Portugal
    { country: "es", value: 47351567 }, // Spain
    { country: "fr", value: 65273511 }, // France
  ];

  // Branch Data
  const [branches, setBranches] = useState<BranchData[]>([]);

  useEffect(() => {
    // Simulated API call
    const fetchBranches = async () => {
      const mockBranches: BranchData[] = [
        {
          id: "1",
          countryCode: "pt",
          countryName: "Portugal",
          flagImage: "/images/flags/portugal.svg",
          percentage: 85,
          color: "primary.main",
        },
        {
          id: "2",
          countryCode: "de",
          countryName: "Germany",
          flagImage: "/images/flags/germany.svg",
          percentage: 65,
          color: "secondary.main",
        },
        {
          id: "3",
          countryCode: "es",
          countryName: "Spain",
          flagImage: "/images/flags/spain.svg",
          percentage: 45,
          color: "purple.main",
        },
        {
          id: "4",
          countryCode: "ca",
          countryName: "Canada",
          flagImage: "/images/flags/canada.svg",
          percentage: 75,
          color: "success.main",
        },
        {
          id: "5",
          countryCode: "us",
          countryName: "USA",
          flagImage: "/images/flags/usa.svg",
          percentage: 20,
          color: "error.main",
        },
      ];
      setBranches(mockBranches);
    };

    fetchBranches();
  }, []);

  return (
    <Card
      sx={{
        boxShadow: "none",
        borderRadius: "7px",
        mb: "25px",
        padding: { xs: "18px", sm: "20px", lg: "25px" },
      }}
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: "25px",
        }}
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
          }}
        >
          Revenue by Branches
        </Typography>

        <Box>
          <IconButton
            onClick={handleClick}
            size="small"
            aria-controls={open ? "account-menu" : undefined}
            aria-haspopup="true"
            aria-expanded={open ? "true" : undefined}
            sx={{ p: "0" }}
            className="-right-10"
          >
            <MoreVert sx={{ fontSize: "25px" }} />
          </IconButton>

          <Menu
            anchorEl={anchorEl}
            id="account-menu"
            open={open}
            onClose={handleClose}
            onClick={handleClose}
            PaperProps={{
              elevation: 0,
              sx: {
                overflow: "visible",
                boxShadow: "0 4px 45px #0000001a",
                mt: 0,
              },
            }}
            transformOrigin={{ horizontal: "right", vertical: "top" }}
            anchorOrigin={{ horizontal: "right", vertical: "bottom" }}
          >
            <MenuItem>This Day</MenuItem>
            <MenuItem>This Week</MenuItem>
            <MenuItem>This Month</MenuItem>
            <MenuItem>This Year</MenuItem>
          </Menu>
        </Box>
      </Box>

      <Box className="text-center" sx={{ mt: "-5px", mb: "-5px" }}>
        <WorldMap
          backgroundColor="transparent"
          color="blue"
          value-suffix="people"
          size="sm"
          data={data}
        />
      </Box>

      <Box
        sx={{
          ".border-bottom": {
            paddingTop: "12.4px",
            paddingBottom: "12.4px",
          },
        }}
      >
        {branches.map((branch) => (
          <Box
            key={branch.id}
            sx={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
            }}
            className="border-bottom"
          >
            <Box sx={{ display: "flex", alignItems: "center", gap: "8px" }}>
              <Image
                src={branch.flagImage}
                alt={branch.countryName}
                width={24}
                height={24}
              />
              <Typography fontWeight={"500"}>{branch.countryName}</Typography>
            </Box>

            <Box sx={{ display: "flex", alignItems: "center", gap: "12px" }}>
              <Box
                sx={{
                  background: "#ECF0FF",
                  height: "5px",
                  width: "100px",
                  borderRadius: "30px",
                }}
              >
                <Box
                  sx={{
                    bgcolor: branch.color,
                    borderRadius: "30px",
                    height: "5px",
                    width: `${branch.percentage}%`,
                  }}
                ></Box>
              </Box>
              <Typography>{branch.percentage}%</Typography>
            </Box>
          </Box>
        ))}
      </Box>
    </Card>
  );
};

export default RevenueByBranches;

// vuejs-vuetify/src/components/Dashboard/Restaurant/RevenueByBranches.vue
<template>
  <v-card
    class="revenue-by-branches-card trezo-card bg-white border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Revenue by Branches</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-2-fill"></i>
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="map-image text-center">
        <v-img src="@/assets/images/map.svg" alt="map" />
      </div>
      <ul class="p-0 mb-0 list-unstyled">
        <li
          v-for="(item, index) in items"
          :key="index"
          class="d-flex align-items-center justify-content-between"
        >
          <div class="flag d-flex align-items-center">
            <v-img :src="item.flag" :alt="item.country" />
            <span class="d-block fw-medium">{{ item.country }}</span>
          </div>
          <div class="percentage-progress d-flex align-items-center">
            <div
              class="progress trezo-progress w-100"
              role="progressbar"
              :aria-valuenow="item.percentage"
              aria-valuemin="0"
              aria-valuemax="100"
            >
              <div
                class="progress-bar"
                :class="getProgressBarClass(item.percentage)"
                :style="{ width: item.percentage + '%' }"
              ></div>
            </div>
            <span class="d-block">{{ item.percentage }}%</span>
          </div>
        </li>
      </ul>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

interface StockData {
  country: string;
  flag: string;
  percentage: number;
}

export default defineComponent({
  name: "RevenueByBranches",
  setup() {
    const items = ref<StockData[]>([
      {
        country: "Portugal",
        flag: require("@/assets/images/flags/portugal.svg"),
        percentage: 85,
      },
      {
        country: "Germany",
        flag: require("@/assets/images/flags/germany.svg"),
        percentage: 65,
      },
      {
        country: "Spain",
        flag: require("@/assets/images/flags/spain.svg"),
        percentage: 45,
      },
      {
        country: "Canada",
        flag: require("@/assets/images/flags/canada.svg"),
        percentage: 75,
      },
      {
        country: "USA",
        flag: require("@/assets/images/flags/usa.svg"),
        percentage: 20,
      },
    ]);

    const getProgressBarClass = (percentage: number) => {
      if (percentage >= 75) return "bg-success";
      if (percentage >= 50) return "bg-secondary";
      if (percentage >= 25) return "bg-purple";
      return "bg-danger";
    };

    return {
      items,
      getProgressBarClass,
    };
  },
});
</script>

<style lang="scss" scoped>
.revenue-by-branches-card {
  .trezo-card-content {
    .map-image {
      .v-img {
        justify-content: center;
      }
    }
    ul {
      margin-top: 25px;

      li {
        border-top: 1px solid var(--borderColor);
        padding: {
          top: 12px;
          bottom: 12px;
        }
        .flag {
          gap: 8px;

          .v-img {
            width: 24px;
          }
        }
        .percentage-progress {
          width: 150px;
          gap: 12px;

          .trezo-progress {
            height: 5px;
            background: #ecf0ff;
            border-radius: 50px;
            overflow: hidden;

            .progress-bar {
              color: #fff;
              background-color: var(--primaryColor);
              transition: var(--transition);
              height: 5px;
            }
          }
          .percentage {
            font-size: 12px;
          }
        }
        &:last-child {
          border-bottom: 1px solid var(--borderColor);
        }
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .revenue-by-branches-card {
    .trezo-card-content {
      ul {
        margin-top: 17px;

        li {
          padding: {
            top: 10px;
            bottom: 10px;
          }
          .percentage-progress {
            width: 130px;
          }
        }
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
  .revenue-by-branches-card {
    .trezo-card-content {
      ul {
        margin-top: 20px;
      }
    }
  }
}
</style>
