// nuxtjs-vuetify/components/Dashboard/Restaurant/StaffPerformanceScores.vue
<template>
  <v-card
    class="staff-performance-scores-card trezo-card bg-white border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Staff Performance Scores</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-2-fill"></i>
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="trezo-table basic-table table-responsive">
        <table class="table mb-0">
          <tbody>
            <tr v-for="(employee, index) in employees" :key="index">
              <td>
                <div class="employee-info d-flex align-items-center">
                  <div class="img rounded-circle">
                    <v-img
                      :alt="employee.name"
                      :src="employee.image"
                      class="rounded-circle"
                    />
                  </div>
                  <div>
                    <span class="d-block fw-medium">{{ employee.name }}</span>
                  </div>
                </div>
              </td>
              <td class="text-body">{{ employee.score }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import image1 from "@/assets/images/users/user58.jpg";
import image2 from "@/assets/images/users/user59.jpg";
import image3 from "@/assets/images/users/user60.jpg";
import image4 from "@/assets/images/users/user61.jpg";
import image5 from "@/assets/images/users/user62.jpg";
import image6 from "@/assets/images/users/user63.jpg";
import image7 from "@/assets/images/users/user64.jpg";
import image8 from "@/assets/images/users/user65.jpg";
import image9 from "@/assets/images/users/user66.jpg";

export default defineComponent({
  name: "StaffPerformanceScores",
  setup() {
    const employees = [
      {
        name: "Joanna Watson",
        image: image1,
        score: 98,
      },
      {
        name: "Angela Carter",
        image: image2,
        score: 97,
      },
      {
        name: "Walter White",
        image: image3,
        score: 96,
      },
      {
        name: "Gary Simon",
        image: image4,
        score: 88,
      },
      {
        name: "Zinia Anderson",
        image: image5,
        score: 85,
      },
      {
        name: "Loren Walter",
        image: image6,
        score: 82,
      },
      {
        name: "Jessy Pinkman",
        image: image7,
        score: 80,
      },
      {
        name: "Handy Curter",
        image: image8,
        score: 77,
      },
      {
        name: "Skyler Lorensa",
        image: image9,
        score: 75,
      },
    ];

    return {
      employees,
    };
  },
});
</script>

<style lang="scss" scoped>
.staff-performance-scores-card {
  .trezo-card-content {
    margin-bottom: -10px;

    .basic-table {
      table,
      .table {
        thead {
          tr {
            th {
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              padding: {
                bottom: 13px;
                top: 0;
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              padding: {
                top: 10px;
                bottom: 10px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 27px;
                }
                span {
                  &:nth-child(1) {
                    margin-bottom: 1px;
                    font-size: var(--fontSize);
                  }
                }
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
                text-align: end;
              }
            }
            &:first-child {
              td {
                padding-top: 0;
                border-top-width: 0;
              }
            }
            &:last-child {
              td {
                border-bottom-width: 0;
              }
            }
          }
        }
      }
    }
  }
}
</style>

// angular-material/src/app/dashboard/restaurant/staff-performance-scores/staff-performance-scores.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatMenuModule } from '@angular/material/menu';
import { MatButtonModule } from '@angular/material/button';
import { MatTableModule, MatTableDataSource } from '@angular/material/table';

@Component({
    selector: 'app-staff-performance-scores',
    imports: [MatCardModule, MatButtonModule, MatMenuModule, MatTableModule],
    templateUrl: './staff-performance-scores.component.html',
    styleUrl: './staff-performance-scores.component.scss'
})
export class StaffPerformanceScoresComponent {

    displayedColumns: string[] = ['client', 'score'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);
    
}

export interface PeriodicElement {
    client: any;
    score: string;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        client: {
            img: 'images/users/user58.jpg',
            name: 'Joanna Watson'
        },
        score: '98'
    },
    {
        client: {
            img: 'images/users/user59.jpg',
            name: 'Angela Carter'
        },
        score: '97'
    },
    {
        client: {
            img: 'images/users/user60.jpg',
            name: 'Walter White'
        },
        score: '96'
    },
    {
        client: {
            img: 'images/users/user61.jpg',
            name: 'Gary Simon'
        },
        score: '88'
    },
    {
        client: {
            img: 'images/users/user62.jpg',
            name: 'Zinia Anderson'
        },
        score: '85'
    },
    {
        client: {
            img: 'images/users/user63.jpg',
            name: 'Loren Walter'
        },
        score: '82'
    },
    {
        client: {
            img: 'images/users/user64.jpg',
            name: 'Jessy Pinkman'
        },
        score: '80'
    },
    {
        client: {
            img: 'images/users/user65.jpg',
            name: 'Handy Curter'
        },
        score: '77'
    },
    {
        client: {
            img: 'images/users/user66.jpg',
            name: 'Skyler Lorensa'
        },
        score: '75'
    }
];
<mat-card class="staff-performance-scores-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Staff Performance Scores
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu style-two p-0 d-inline-block border-radius-0">
                <i class="ri-more-2-fill"></i>
            </button>
            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                <ul class="p-0 mt-0 mb-0 list-unstyled">
                    <li>
                        <button mat-menu-item>
                            This Day
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Week
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Month
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Year
                        </button>
                    </li>
                </ul>
            </mat-menu>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <div class="table-responsive">
            <table mat-table [dataSource]="dataSource">

                <!-- Staff Column -->
                <ng-container matColumnDef="client">
                    <th mat-header-cell *matHeaderCellDef>
                        Staff
                    </th>
                    <td mat-cell *matCellDef="let element">
                        <div class="employee-info d-flex align-items-center">
                            <div class="img rounded-circle">
                                <img [src]="element.client.img" class="rounded-circle" alt="user-image">
                            </div>
                            <span class="d-block text-black fw-semibold">
                                {{element.client.name}}
                            </span>
                        </div>
                    </td>
                </ng-container>

                <!-- Score Column -->
                <ng-container matColumnDef="score">
                    <th mat-header-cell *matHeaderCellDef>
                        Score
                    </th>
                    <td class="text-body fw-medium" mat-cell *matCellDef="let element">
                        {{element.score}}
                    </td>
                </ng-container>

                <!-- <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr> -->
                <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>

            </table>
        </div>
    </mat-card-content>
</mat-card>
