// landing-pages/angular-tailwindcss/src/app/lms-courses-demo/common/page-banner/page-banner.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-page-banner',
    imports: [RouterLink],
    templateUrl: './page-banner.component.html',
    styleUrl: './page-banner.component.scss'
})
export class PageBannerComponent {

    @Input() pageTitle: string = '';

}
<div class="pt-[115px] pb-[60px] md:pt-[140px] md:pb-[80px] lg:pt-[175px] lg:pb-[110px]">
    <div class="container sm:max-w-[540px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1308px] mx-auto px-[12px]">
        <div class="text-center">
            <h1 class="!text-xl md:!text-3xl lg:!text-4xl xl:!text-5xl md:-tracking-[1px] !text-gray-800 dark:!text-gray-100 !mb-[15px] md:!mb-[20px] lg:!mb-[25px]">
                {{ pageTitle }}
            </h1>
            <div class="inline-block">
                <ul class="flex items-center justify-center gap-[5px] md:gap-[10px] py-[5px] px-[18px] bg-[#ffef99] dark:bg-[#0a0e19] rounded-[100px]">
                    <li>
                        <a routerLink="/lms-courses-demo" class="transition-all text-gray-900 dark:text-gray-200 hover:text-primary-500">
                            Home
                        </a>
                    </li>
                    <li class="text-gray-900 dark:text-gray-200 text-[20px] leading-none rtl:-scale-x-[1]">
                        <i class="ri-arrow-right-s-line"></i>
                    </li>
                    <li class="text-gray-900 dark:text-gray-200">
                        {{ pageTitle }}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

// landing-pages/react-bootstrap/marketing-landing/src/components/Common/PageBanner.js
"use client";

import React from "react";
import {Link} from "react-router-dom";

const PageBanner = ({ pageTitle, homePageUrl, homePageText }) => {
  return (
    <>
      <div className="page-banner-area-lms bg-fffef8">
        <div className="container cmw-1704">
          <div className="page-banner-content-lms text-center">
            <h2 className="text-secondary">{pageTitle}</h2>

            <div className="d-inline-block">
              <ul className="m-0 list-unstyled d-flex align-items-center justify-content-center breadcrumb-lms">
                <li>
                  <Link to={homePageUrl}>{homePageText}</Link>
                </li>
                <li>
                  <i className="ri-arrow-right-s-line"></i>
                </li>
                <li>
                  <span>{pageTitle}</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default PageBanner;
