// landing-pages/angular-tailwindcss/src/app/marketing-demo/common/testimonials/testimonials.component.ts
import { NgIf } from '@angular/common';
import { Component } from '@angular/core';

@Component({
    selector: 'app-testimonials',
    imports: [NgIf],
    templateUrl: './testimonials.component.html',
    styleUrl: './testimonials.component.scss'
})
export class TestimonialsComponent {

    // Video Popup
	isOpen = false;
    openPopup(): void {
        this.isOpen = true;
    }
    closePopup(): void {
        this.isOpen = false;
    }

}
<div class="py-[70px] md:py-[90px] lg:py-[110px] xl:py-[150px] 2xl:py-[180px] relative z-[1]">
    <div class="container sm:max-w-[540px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1308px] mx-auto px-[12px]">
        <div class="text-center mb-[30px] md:mb-[40px] lg:mb-[50px] xl:mb-[60px] 2xl:mb-[70px]">
            <span class="inline-block py-[4.5px] px-[15px] rounded-[100px] bg-orange-100 dark:bg-[#0a0e19] text-orange-700 mb-[12px]">
                Testimonials
            </span>
            <h2 class="!text-gray-900 dark:!text-white md:-tracking-[1px] !font-medium !text-xl md:!text-3xl lg:!text-4xl xl:!text-5xl xl:max-w-[520px] mx-auto !leading-[1.2] !mb-[10px] lg:!mb-[12px]">
                What Marketers Say About Trezo
            </h2>
            <p class="md:text-[15px] lg:text-md !leading-[1.6]">
                From campaign tracking to performance insights — we’ve got you covered.
            </p>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[25px] mb-[25px]">
            <div class="px-[20px] py-[30px] md:px-[30px] md:py-[40px] lg:px-[40px] lg:py-[50px] xl:px-[50px] xl:py-[60px] bg-white dark:bg-[#0a0e19] rounded-[15px] relative z-[1]">
                <div class="flex items-center text-orange-400 leading-none text-md lg:text-lg gap-[3px] mb-[18px] md:mb-[22px] lg:mb-[30px]">
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                </div>
                <p class="font-medium text-gray-900 dark:text-gray-100 text-[15px] md:text-md lg:text-[17px] xl:text-lg !leading-[1.6]">
                    “Trezo changed the way we manage campaigns. Everything’s faster, and way more collaborative. Our ROI improved within weeks.”
                </p>
                <div class="flex items-center gap-[12px] mt-[18px] md:mt-[25px] lg:mt-[40px] xl:mt-[50px]">
                    <img src="images/marketing/users/user5.jpg" class="rounded-full w-[42px]" alt="user-image">
                    <div>
                        <h5 class="!text-base !mb-[4px] !font-semibold !text-gray-800 dark:!text-gray-100">
                            Rachel Nguyen
                        </h5>
                        <span class="block">
                            Growth Marketing Lead, BrightDash
                        </span>
                    </div>
                </div>
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(180deg, #FFF 0%, #EEF6FF 100%);"
                ></div>
            </div>
            <div class="px-[20px] py-[30px] md:px-[30px] md:py-[40px] lg:px-[40px] lg:py-[50px] xl:px-[50px] xl:py-[60px] bg-white dark:bg-[#0a0e19] rounded-[15px] relative z-[1]">
                <div class="flex items-center text-orange-400 leading-none text-md lg:text-lg gap-[3px] mb-[18px] md:mb-[22px] lg:mb-[30px]">
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                </div>
                <p class="font-medium text-gray-900 dark:text-gray-100 text-[15px] md:text-md lg:text-[17px] xl:text-lg !leading-[1.6]">
                    “I’ve used dozens of marketing tools — Trezo is the only one that actually simplifies my workflow instead of complicating it.”
                </p>
                <div class="flex items-center gap-[12px] mt-[18px] md:mt-[25px] lg:mt-[40px] xl:mt-[50px]">
                    <img src="images/marketing/users/user6.jpg" class="rounded-full w-[42px]" alt="user-image">
                    <div>
                        <h5 class="!text-base !mb-[4px] !font-semibold !text-gray-800 dark:!text-gray-100">
                            Michael Brooks
                        </h5>
                        <span class="block">
                            Senior Digital Strategist, Amply Media
                        </span>
                    </div>
                </div>
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(180deg, #FFF 0%, #FAF5FF 100%);"
                ></div>
            </div>
            <div class="px-[20px] py-[30px] md:px-[30px] md:py-[40px] lg:px-[40px] lg:py-[50px] xl:px-[50px] xl:py-[60px] bg-white dark:bg-[#0a0e19] rounded-[15px] relative z-[1]">
                <div class="flex items-center text-orange-400 leading-none text-md lg:text-lg gap-[3px] mb-[18px] md:mb-[22px] lg:mb-[30px]">
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                    <i class="ri-star-fill"></i>
                </div>
                <p class="font-medium text-gray-900 dark:text-gray-100 text-[15px] md:text-md lg:text-[17px] xl:text-lg !leading-[1.6]">
                    “The real-time dashboard and funnel visualization features are a game-changer. My team finally has the clarity we needed.”
                </p>
                <div class="flex items-center gap-[12px] mt-[18px] md:mt-[25px] lg:mt-[40px] xl:mt-[50px]">
                    <img src="images/marketing/users/user7.jpg" class="rounded-full w-[42px]" alt="user-image">
                    <div>
                        <h5 class="!text-base !mb-[4px] !font-semibold !text-gray-800 dark:!text-gray-100">
                            Lila Fernandez
                        </h5>
                        <span class="block">
                            Head of Marketing, Corelytics
                        </span>
                    </div>
                </div>
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(180deg, #FFF 0%, #EEFFE5 100%);"
                ></div>
            </div>
        </div>
        <div class="mx-auto max-w-[848px]">
            <div class="px-[20px] py-[30px] md:px-[30px] md:py-[40px] lg:px-[40px] lg:py-[50px] xl:px-[50px] xl:py-[60px] bg-white dark:bg-[#0a0e19] rounded-[15px] relative z-[1]">
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-[20px] md:gap-[25px]">
                    <div>
                        <div class="flex items-center text-orange-400 leading-none text-md lg:text-lg gap-[3px] mb-[18px] md:mb-[22px] lg:mb-[30px]">
                            <i class="ri-star-fill"></i>
                            <i class="ri-star-fill"></i>
                            <i class="ri-star-fill"></i>
                            <i class="ri-star-fill"></i>
                            <i class="ri-star-fill"></i>
                        </div>
                        <p class="font-medium text-gray-900 dark:text-gray-100 text-[15px] md:text-md lg:text-[17px] xl:text-lg !leading-[1.6]">
                            “Trezo’s impact on our marketing operations has been incredible. It’s now at the center of everything we do.”
                        </p>
                        <div class="flex items-center gap-[12px] mt-[18px] md:mt-[25px] lg:mt-[40px] xl:mt-[50px]">
                            <img src="images/marketing/users/user5.jpg" class="rounded-full w-[42px]" alt="user-image">
                            <div>
                                <h5 class="!text-base !mb-[4px] !font-semibold !text-gray-800 dark:!text-gray-100">
                                    Olivia Smith
                                </h5>
                                <span class="block">
                                    Performance Marketing Lead, BrightDash
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="relative">
                        <img src="images/marketing/man.jpg" class="inline-block rounded-[15px]" alt="man">
                        <button
                            type="button"
                            (click)="openPopup()"
                            class="flex items-center justify-center w-[55px] h-[55px] bg-orange-300 rounded-full absolute left-0 right-0 top-1/2 -translate-y-1/2 mx-auto text-[35px] text-black transition-all hover:bg-orange-400"
                        >
                            <i class="ri-play-fill"></i>
                        </button>
                    </div>
                </div>
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(180deg, #FFF 0%, #FFE4E4 100%);"
                ></div>
            </div>
        </div>
    </div>
    <div
        class="absolute top-0 left-0 w-full h-full bg-no-repeat bg-cover bg-center -z-1 dark:hidden"
        style="background-image: url(images/marketing/gradient-bg2.jpg);"
    ></div>
</div>

<!-- Vide Popup -->
<div
    class="mfp-wrap mfp-close-btn-in mfp-auto-cursor mfp-fade mfp-ready"
    *ngIf="isOpen"
    tabindex="-1"
>
    <div class="mfp-container mfp-iframe-holder">
        <div class="mfp-content">
            <div class="mfp-iframe-scaler">
                <button
                    (click)="closePopup()"
                    title="Close (Esc)"
                    type="button"
                    class="mfp-close"
                >
                    ×
                </button>
                <iframe src="https://www.youtube.com/embed/_ZppXdKk4c8" title="Introducing Trezo | The Next-Generation Multi-Framework Admin Dashboard Template" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>
<div class="mfp-bg mfp-fade mfp-ready" *ngIf="isOpen"></div>

// landing-pages/react-bootstrap/marketing-landing/src/components/Common/Testimonials.js
"use client";

import React, { useState } from "react";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

const testimonialsData = [
  {
    id: 1,
    rating: 5,
    quote:
      "Trezo changed the way we manage campaigns. Everything's faster, clearer, and way more collaborative. Our ROI improved within weeks.",
    name: "Rachel Nguyen",
    position: "Growth Marketing Lead, BrightDash",
    image: "/images/users/user5.jpg",
    background: "linear-gradient(#fff 0%, #eef6ff 100%)",
    isWide: false,
  },
  {
    id: 2,
    rating: 5,
    quote:
      "I've used dozens of marketing tools — Trezo is the only one that actually simplifies my workflow instead of complicating it.",
    name: "Michael Brooks",
    position: "Senior Digital Strategist, Amply Media",
    image: "/images/users/user6.jpg",
    background: "linear-gradient(180deg, #FFF 0%, #FAF5FF 100%)",
    isWide: false,
  },
  {
    id: 3,
    rating: 5,
    quote:
      "The real-time dashboard and funnel visualization features are a game-changer. My team finally has the clarity we needed.",
    name: "Lila Fernandez",
    position: "Head of Marketing, Corelytics",
    image: "/images/users/user7.jpg",
    background: "linear-gradient(180deg, #FFF 0%, #EEFFE5 100%)",
    isWide: false,
  },
  {
    id: 4,
    rating: 5,
    quote:
      "Trezo's impact on our marketing operations has been incredible. It's now at the center of everything we do.",
    name: "Olivia Smith",
    position: "Performance Marketing Lead, BrightDash",
    image: "/images/users/user5.jpg",
    background: "linear-gradient(180deg, #FFF 0%, #FFE4E4 100%)",
    isWide: true,
    hasVideo: true,
    videoId: "_ZppXdKk4c8",
    thumbnail: "/images/man.jpg",
  },
];

const renderStars = (rating) => {
  return Array(rating)
    .fill()
    .map((_, i) => (
      <i key={i} className="ri-star-fill fs-18 text-rating-color lh-1"></i>
    ));
};

const Testimonials = () => {
  const [showVideo, setShowVideo] = useState(false);
  const [currentVideo, setCurrentVideo] = useState("");

  const toggleVideo = (videoId = "") => {
    setCurrentVideo(videoId);
    setShowVideo(!showVideo);
  };

  return (
    <div
      className="testimonials-marketing-area bg-img ptb-180"
      style={{ backgroundImage: "url(/images/gradient-bg2.jpg)" }}
    >
      <Container className="cmw-1308">
        <div className="section-title2 text-center mx-auto mw-100 mb-70">
          <span className="top-title2 bg-card-text-c text-danger-90">
            Testimonials
          </span>
          <h2 className="mx-auto" style={{ maxWidth: "520px" }}>
            What Marketers Say About Trezo
          </h2>
          <p className="dec">
            From campaign tracking to performance insights — we&apos;ve got you
            covered.
          </p>
        </div>

        <Row className="g-4 justify-content-center">
          {testimonialsData.map((testimonial) => (
            <Col key={testimonial.id} md={6} lg={testimonial.isWide ? 8 : 4}>
              <div
                className={`testimonials-single-item-marketing h-100 ${
                  testimonial.isWide ? "bg-4" : ""
                }`}
                style={{ background: testimonial.background }}
              >
                {testimonial.isWide ? (
                  <Row className="align-content-center g-4">
                    <Col md={6}>
                      <div className="d-flex mb-25" style={{ gap: "2px" }}>
                        {renderStars(testimonial.rating)}
                      </div>
                      <p className="fs-16">
                        <q>{testimonial.quote}</q>
                      </p>
                      <div
                        className="d-flex align-items-center mt-50"
                        style={{ gap: "12px" }}
                      >
                        <div className="flex-shrink-0">
                          <img
                            src={testimonial.image}
                            className="rounded-circle user"
                            alt={testimonial.name}
                            width={42}
                            height={42}
                          />
                        </div>
                        <div className="flex-grow-1">
                          <span
                            className="text-secondary fw-semibold d-block s-14"
                            style={{ marginBottom: "4px" }}
                          >
                            {testimonial.name}
                          </span>
                          <span>{testimonial.position}</span>
                        </div>
                      </div>
                    </Col>
                    <Col md={6}>
                      <div className="position-relative z-1">
                        <img
                          src={testimonial.thumbnail}
                          style={{ borderRadius: "15px" }}
                          alt="marketing"
                          width={726}
                          height={566}
                        />
                        {testimonial.hasVideo && (
                          <button
                            onClick={() => toggleVideo(testimonial.videoId)}
                            className="marketing-play text-decoration-none text-secondary-50 d-flex justify-content-center align-content-center rounded-circle position-absolute top-50 start-50 translate-middle border-0 p-0"
                            style={{ width: "55px", height: "55px" }}
                          >
                            <i className="ri-play-fill fs-35"></i>
                          </button>
                        )}
                      </div>
                    </Col>
                  </Row>
                ) : (
                  <>
                    <div className="d-flex mb-25" style={{ gap: "2px" }}>
                      {renderStars(testimonial.rating)}
                    </div>
                    <p className="fs-16">
                      <q>{testimonial.quote}</q>
                    </p>
                    <div
                      className="d-flex align-items-center mt-50"
                      style={{ gap: "12px" }}
                    >
                      <div className="flex-shrink-0">
                        <img
                          src={testimonial.image}
                          className="rounded-circle user"
                          alt={testimonial.name}
                          width={42}
                          height={42}
                        />
                      </div>
                      <div className="flex-grow-1">
                        <span
                          className="text-secondary fw-semibold d-block s-14"
                          style={{ marginBottom: "4px" }}
                        >
                          {testimonial.name}
                        </span>
                        <span>{testimonial.position}</span>
                      </div>
                    </div>
                  </>
                )}
              </div>
            </Col>
          ))}
        </Row>
      </Container>

      {/* Video Popup Modal */}
      {showVideo && (
        <div
          className="position-fixed top-0 bg-black bg-opacity-75 d-flex align-items-center justify-content-center p-4 w-100 h-100"
          style={{ zIndex: "9999" }}
        >
          <div
            className="relative mx-auto"
            style={{ maxWidth: "800px", width: "100%" }}
          >
            <div className="text-end">
              <button
                onClick={() => toggleVideo("")}
                className="border-0 bg-transparent text-white fs-17"
              >
                <i className="ri-close-large-line"></i>
              </button>
            </div>
            <div className="ratio ratio-16x9">
              <iframe
                src={`https://www.youtube.com/embed/${currentVideo}?autoplay=1`}
                title="Trezo - Intro"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Testimonials;
