// landing-pages/react-bootstrap/lms-landing/src/components/Courses/CoursesYouMayLike.js
"use client";

import React from "react";
import { Link } from "react-router-dom";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

const courses = [
  {
    id: 1,
    title: "Data Science with Python",
    image: "/images/courses/course2.jpg",
    rating: 4.7,
    ratingsCount: 980,
    price: 69,
    lessons: 38,
    enrolled: 6300,
    viewLink: "/courses/details",
  },
  {
    id: 2,
    title: "Graphic Design Masterclass",
    image: "/images/courses/course3.jpg",
    rating: 4.9,
    ratingsCount: 10200,
    price: 99,
    lessons: 52,
    enrolled: 10200,
    viewLink: "/courses/details",
  },
  {
    id: 3,
    title: "Mindfulness & Stress Management",
    image: "/images/courses/course4.jpg",
    rating: 4.0,
    ratingsCount: 750,
    price: 79,
    lessons: 20,
    enrolled: 400,
    viewLink: "/courses/details",
  },
];

const renderStars = (rating) => {
  const stars = [];
  const fullStars = Math.floor(rating);
  const hasHalfStar = rating % 1 >= 0.5;

  for (let i = 1; i <= 5; i++) {
    if (i <= fullStars) {
      stars.push(
        <i key={i} className="ri-star-fill fs-16 text-rating-color"></i>
      );
    } else if (i === fullStars + 1 && hasHalfStar) {
      stars.push(
        <i key={i} className="ri-star-half-fill fs-16 text-rating-color"></i>
      );
    } else {
      stars.push(
        <i key={i} className="ri-star-line fs-16 text-rating-color"></i>
      );
    }
  }

  return stars;
};

const CoursesYouMayLike = () => {
  return (
    <>
      <div className="popular-courses-lms-area related bg-fffef8">
        <Container className="cmw-1308">
          <h2 className="text-secondary">Courses You May Like</h2>

          <Row className="g-4 justify-content-center">
            {courses.map((course) => (
              <Col lg={4} md={6} key={course.id}>
                <div className="single-course-lms-item border-0 style-two bg-white">
                  <Link
                    to={course.viewLink}
                    className="d-block text-decoration-none"
                  >
                    <img
                      src={course.image}
                      alt={course.title}
                      width={684}
                      height={440}
                    />
                  </Link>
                  <div className="single-course-lms-content">
                    <Link
                      to={course.viewLink}
                      className="d-block text-decoration-none"
                    >
                      <h3 className="mb-3">{course.title}</h3>
                    </Link>

                    <div
                      className="d-flex align-items-center"
                      style={{ gap: "8px" }}
                    >
                      <div
                        className="d-flex align-items-center"
                        style={{ gap: "2px" }}
                      >
                        {renderStars(course.rating)}
                      </div>
                      <span className="fs-16 text-dark">
                        {course.rating.toFixed(1)} (
                        {course.ratingsCount.toLocaleString()} ratings)
                      </span>
                    </div>

                    <span className="price">${course.price}</span>

                    <ul className="d-flex align-items-center p-0 m-0 info">
                      <li className="d-flex align-items-center">
                        <i className="material-symbols-outlined fs-24">
                          menu_book
                        </i>
                        <span className="fs-16">{course.lessons} Lessons</span>
                      </li>
                      <li className="d-flex align-items-center">
                        <i className="material-symbols-outlined fs-24">group</i>
                        <span className="fs-16">
                          {course.enrolled.toLocaleString()}+ Enrolled
                        </span>
                      </li>
                    </ul>
                  </div>
                </div>
              </Col>
            ))}
          </Row>
        </Container>
      </div>
    </>
  );
};

export default CoursesYouMayLike;

// landing-pages/angular-tailwindcss/src/app/lms-courses-demo/lcd-course-details/courses-you-may-like/courses-you-may-like.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-courses-you-may-like',
    imports: [RouterLink],
    templateUrl: './courses-you-may-like.component.html',
    styleUrl: './courses-you-may-like.component.scss'
})
export class CoursesYouMayLikeComponent {}
<div class="py-[70px] md:py-[90px] lg:py-[110px] xl:py-[140px]">
    <div class="container sm:max-w-[540px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1308px] mx-auto px-[12px]">
        <div class="mb-[30px] md:mb-[40px] lg:mb-[50px]">
            <h2 class="!text-xl md:!text-3xl !font-semibold -tracking-[1px] mt-[15px] !mb-0 !text-gray-800 dark:!text-gray-100">
                Courses You May Like
            </h2>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-[25px]">
            <div class="bg-white dark:bg-[#0a0e19] border border-gray-200 dark:border-[#202c4b] rounded-[15px] p-[20px] md:p-[25px] lg:p-[30px] 2xl:p-[35px]">
                <a routerLink="/lms-courses-demo/course-details" class="d-block rounded-[10px]">
                    <img src="images/lms-courses/courses/course4.jpg" alt="course-image" class="rounded-[10px] inline-block">
                </a>
                <h3 class="!text-[18px] md:!text-[19px] lg:!text-[20px] !font-semibold mt-[18px] md:mt-[22px] lg:mt-[28px] !mb-[15px]">
                    <a routerLink="/lms-courses-demo/course-details" class="text-gray-800 dark:text-gray-100 transition-all hover:text-primary-500">
                        Mindfulness & Stress Management
                    </a>
                </h3>
                <div class="flex items-center gap-[8px]">
                    <div class="flex items-center text-orange-400 leading-none lg:text-md gap-[2px] relative -top-px">
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-line"></i>
                    </div>
                    <span class="block lg:text-md leading-none">
                        4.0 (750 ratings)
                    </span>
                </div>
                <div class="mt-[20px] lg:mt-[25px] text-primary-600 leading-none text-md md:text-[20px] font-semibold">
                    $79
                </div>
                <ul class="flex items-center gap-[15px] lg:gap-[20px] 2xl:gap-[25px] md:text-[15px] xl:text-md mt-[15px] md:mt-[20px] lg:mt-[22px]">
                    <li class="relative inline-block ltr:pl-[25px] rtl:pr-[25px] ltr:lg:pl-[32px] rtl:lg:pr-[32px] text-gray-700 dark:text-gray-200">
                        <i class="material-symbols-outlined absolute top-1/2 -translate-y-1/2 ltr:left-0 rtl:right-0 !text-lg lg:!text-xl">
                            book_ribbon
                        </i>
                        20 Lessons
                    </li>
                    <li class="relative inline-block">
                        <div class="w-[1px] h-[19px] bg-gray-200 dark:bg-[#202c4b]"></div>
                    </li>
                    <li class="relative inline-block ltr:pl-[25px] rtl:pr-[25px] ltr:lg:pl-[32px] rtl:lg:pr-[32px] text-gray-700 dark:text-gray-200">
                        <i class="material-symbols-outlined absolute top-1/2 -translate-y-1/2 ltr:left-0 rtl:right-0 !text-lg lg:!text-xl">
                            group
                        </i>
                        4,00+ Enrolled
                    </li>
                </ul>
            </div>
            <div class="bg-white dark:bg-[#0a0e19] border border-gray-200 dark:border-[#202c4b] rounded-[15px] p-[20px] md:p-[25px] lg:p-[30px] 2xl:p-[35px]">
                <a routerLink="/lms-courses-demo/course-details" class="d-block rounded-[10px]">
                    <img src="images/lms-courses/courses/course9.jpg" alt="course-image" class="rounded-[10px] inline-block">
                </a>
                <h3 class="!text-[18px] md:!text-[19px] lg:!text-[20px] !font-semibold mt-[18px] md:mt-[22px] lg:mt-[28px] !mb-[15px]">
                    <a routerLink="/lms-courses-demo/course-details" class="text-gray-800 dark:text-gray-100 transition-all hover:text-primary-500">
                        Financial Planning & Investing
                    </a>
                </h3>
                <div class="flex items-center gap-[8px]">
                    <div class="flex items-center text-orange-400 leading-none lg:text-md gap-[2px] relative -top-px">
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-half-fill"></i>
                    </div>
                    <span class="block lg:text-md leading-none">
                        4.5 (1,310 ratings)
                    </span>
                </div>
                <div class="mt-[20px] lg:mt-[25px] text-primary-600 leading-none text-md md:text-[20px] font-semibold">
                    $79
                </div>
                <ul class="flex items-center gap-[15px] lg:gap-[20px] 2xl:gap-[25px] md:text-[15px] xl:text-md mt-[15px] md:mt-[20px] lg:mt-[22px]">
                    <li class="relative inline-block ltr:pl-[25px] rtl:pr-[25px] ltr:lg:pl-[32px] rtl:lg:pr-[32px] text-gray-700 dark:text-gray-200">
                        <i class="material-symbols-outlined absolute top-1/2 -translate-y-1/2 ltr:left-0 rtl:right-0 !text-lg lg:!text-xl">
                            book_ribbon
                        </i>
                        32 Lessons
                    </li>
                    <li class="relative inline-block">
                        <div class="w-[1px] h-[19px] bg-gray-200 dark:bg-[#202c4b]"></div>
                    </li>
                    <li class="relative inline-block ltr:pl-[25px] rtl:pr-[25px] ltr:lg:pl-[32px] rtl:lg:pr-[32px] text-gray-700 dark:text-gray-200">
                        <i class="material-symbols-outlined absolute top-1/2 -translate-y-1/2 ltr:left-0 rtl:right-0 !text-lg lg:!text-xl">
                            group
                        </i>
                        6,800+ Enrolled
                    </li>
                </ul>
            </div>
            <div class="bg-white dark:bg-[#0a0e19] border border-gray-200 dark:border-[#202c4b] rounded-[15px] p-[20px] md:p-[25px] lg:p-[30px] 2xl:p-[35px]">
                <a routerLink="/lms-courses-demo/course-details" class="d-block rounded-[10px]">
                    <img src="images/lms-courses/courses/course7.jpg" alt="course-image" class="rounded-[10px] inline-block">
                </a>
                <h3 class="!text-[18px] md:!text-[19px] lg:!text-[20px] !font-semibold mt-[18px] md:mt-[22px] lg:mt-[28px] !mb-[15px]">
                    <a routerLink="/lms-courses-demo/course-details" class="text-gray-800 dark:text-gray-100 transition-all hover:text-primary-500">
                        Digital Marketing Mastery
                    </a>
                </h3>
                <div class="flex items-center gap-[8px]">
                    <div class="flex items-center text-orange-400 leading-none lg:text-md gap-[2px] relative -top-px">
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-fill"></i>
                        <i class="ri-star-line"></i>
                    </div>
                    <span class="block lg:text-md leading-none">
                        4.7 (1,980 ratings)
                    </span>
                </div>
                <div class="mt-[20px] lg:mt-[25px] text-primary-600 leading-none text-md md:text-[20px] font-semibold">
                    $79
                </div>
                <ul class="flex items-center gap-[15px] lg:gap-[20px] 2xl:gap-[25px] md:text-[15px] xl:text-md mt-[15px] md:mt-[20px] lg:mt-[22px]">
                    <li class="relative inline-block ltr:pl-[25px] rtl:pr-[25px] ltr:lg:pl-[32px] rtl:lg:pr-[32px] text-gray-700 dark:text-gray-200">
                        <i class="material-symbols-outlined absolute top-1/2 -translate-y-1/2 ltr:left-0 rtl:right-0 !text-lg lg:!text-xl">
                            book_ribbon
                        </i>
                        35 Lessons
                    </li>
                    <li class="relative inline-block">
                        <div class="w-[1px] h-[19px] bg-gray-200 dark:bg-[#202c4b]"></div>
                    </li>
                    <li class="relative inline-block ltr:pl-[25px] rtl:pr-[25px] ltr:lg:pl-[32px] rtl:lg:pr-[32px] text-gray-700 dark:text-gray-200">
                        <i class="material-symbols-outlined absolute top-1/2 -translate-y-1/2 ltr:left-0 rtl:right-0 !text-lg lg:!text-xl">
                            group
                        </i>
                        11,00+ Enrolled
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
