// laravel-vuetify/resources/components/Pages/CRM/Contacts/index.vue
<template>
    <v-card
        class="crm-contacts-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <form class="search-box position-relative" @submit.prevent>
                <input
                    type="text"
                    class="input-search d-block"
                    placeholder="Search contact here....."
                    v-model="searchTerm"
                />
                <button type="submit">
                    <i class="material-symbols-outlined">search</i>
                </button>
            </form>
            <AddNewContacts />
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th class="text-start">
                                <v-checkbox color="primary"></v-checkbox>
                            </th>
                            <th class="text-start">ID</th>
                            <th class="text-start">User</th>
                            <th class="text-start">Email</th>
                            <th class="text-start">Phone</th>
                            <th class="text-start">Last Contacted</th>
                            <th class="text-start">Company</th>
                            <th class="text-start">Lead Score</th>
                            <th class="text-start">Status</th>
                            <th class="text-end">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in filteredItems" :key="item.id">
                            <td><v-checkbox color="primary"></v-checkbox></td>
                            <td>
                                {{ item.id }}
                            </td>
                            <td>
                                <div
                                    class="customer-info d-flex align-items-center"
                                >
                                    <div class="img">
                                        <v-img
                                            :src="item.user.image"
                                            alt="user-image"
                                        />
                                    </div>
                                    <span class="d-block text-black fw-medium">
                                        {{ item.user.name }}
                                    </span>
                                </div>
                            </td>
                            <td>
                                {{ item.email }}
                            </td>
                            <td class="text-body">{{ item.phone }}</td>
                            <td class="text-body">{{ item.lastContacted }}</td>
                            <td class="text-body">{{ item.company }}</td>
                            <td class="text-body">{{ item.leadScore }}</td>
                            <td>
                                <span
                                    class="trezo-status-badge"
                                    v-if="item.status.active"
                                >
                                    Active
                                </span>
                                <span
                                    class="trezo-status-badge cancelled"
                                    v-if="item.status.deactive"
                                >
                                    Deactive
                                </span>
                            </td>
                            <td>
                                <div
                                    class="action-buttons d-flex align-items-center"
                                >
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.view }}
                                        </i>
                                    </button>
                                    <EditContact />
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.delete }}
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
                <PaginationTwo items="10" />
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref, computed } from "vue";
import AddNewContacts from "./AddNewContacts.vue";
import EditContact from "./EditContact.vue";
import PaginationTwo from "../../../Common/PaginationTwo.vue";

import user6 from "../../../../../public/images/users/user6.jpg";
import user7 from "../../../../../public/images/users/user7.jpg";
import user8 from "../../../../../public/images/users/user8.jpg";
import user9 from "../../../../../public/images/users/user9.jpg";
import user10 from "../../../../../public/images/users/user10.jpg";
import user11 from "../../../../../public/images/users/user11.jpg";
import user12 from "../../../../../public/images/users/user12.jpg";
import user13 from "../../../../../public/images/users/user13.jpg";
import user14 from "../../../../../public/images/users/user14.jpg";
import user15 from "../../../../../public/images/users/user15.jpg";

export default defineComponent({
    // eslint-disable-next-line vue/multi-word-component-names
    name: "Contacts",
    components: {
        AddNewContacts,
        EditContact,
        PaginationTwo,
    },
    setup() {
        const items = ref([
            {
                id: "#854",
                user: {
                    image: user6,
                    name: "Oliver Khan",
                },
                email: "oliver@trezo.com",
                phone: "+1 555-123-4567",
                lastContacted: "Jun 19, 2024",
                company: "ABC Corporation",
                leadScore: 50,
                status: {
                    active: true,
                    deactive: false,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#853",
                user: {
                    image: user7,
                    name: "Carolyn Barnes",
                },
                email: "carolyn@trezo.com",
                phone: "+1 555-987-6543",
                lastContacted: "Jun 18, 2024",
                company: "XYZ Ltd",
                leadScore: 35,
                status: {
                    active: true,
                    deactive: false,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#852",
                user: {
                    image: user8,
                    name: "Donna Miller",
                },
                email: "donna@trezo.com",
                phone: "+1 555-456-7890",
                lastContacted: "Jun 17, 2024",
                company: "Tech Solutions",
                leadScore: 40,
                status: {
                    active: false,
                    deactive: true,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#851",
                user: {
                    image: user9,
                    name: "Barbara Cross",
                },
                email: "barbara@trezo.com",
                phone: "+1 555-369-7878",
                lastContacted: "Jun 16, 2024",
                company: "Global Solutions",
                leadScore: 25,
                status: {
                    active: true,
                    deactive: false,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#850",
                user: {
                    image: user10,
                    name: "Rebecca Block",
                },
                email: "rebecca@trezo.com",
                phone: "+1 555-658-4488",
                lastContacted: "Jun 15, 2024",
                company: "Acma Industries",
                leadScore: 27,
                status: {
                    active: false,
                    deactive: true,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#849",
                user: {
                    image: user11,
                    name: "Ramiro McCarty",
                },
                email: "ramiro@trezo.com",
                phone: "+1 555-558-9966",
                lastContacted: "Jun 14, 2024",
                company: "Synergy Ltd",
                leadScore: 16,
                status: {
                    active: true,
                    deactive: false,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#848",
                user: {
                    image: user12,
                    name: "Robert Fairweather",
                },
                email: "robert@trezo.com",
                phone: "+1 555-357-5888",
                lastContacted: "Jun 13, 2024",
                company: "Summit Solutions",
                leadScore: 38,
                status: {
                    active: true,
                    deactive: false,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#847",
                user: {
                    image: user13,
                    name: "Marcelino Haddock",
                },
                email: "marcelino@trezo.com",
                phone: "+1 555-456-8877",
                lastContacted: "Jun 12, 2024",
                company: "Strategies Ltd",
                leadScore: 15,
                status: {
                    active: true,
                    deactive: false,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#846",
                user: {
                    image: user14,
                    name: "Thomas Wilson",
                },
                email: "thomas@trezo.com",
                phone: "+1 555-622-4488",
                lastContacted: "Jun 11, 2024",
                company: "Tech Enterprises",
                leadScore: 41,
                status: {
                    active: false,
                    deactive: true,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "#845",
                user: {
                    image: user15,
                    name: "Nathaniel Hulsey",
                },
                email: "nathaniel@trezo.com",
                phone: "+1 555-225-4488",
                lastContacted: "Jun 10, 2024",
                company: "Synetic Solutions",
                leadScore: 29,
                status: {
                    active: true,
                    deactive: false,
                },
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
        ]);

        const searchTerm = ref("");

        const filteredItems = computed(() => {
            return items.value.filter(
                (item) =>
                    item.id
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.user.name
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.email
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.phone
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.lastContacted
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase()) ||
                    item.company
                        .toLowerCase()
                        .includes(searchTerm.value.toLowerCase())
            );
        });

        return {
            items,
            searchTerm,
            filteredItems,
        };
    },
});
</script>

<style lang="scss" scoped>
.crm-contacts-card {
    padding-bottom: 8px !important;
    .trezo-table-content {
        .trezo-table {
            margin-left: -25px;
            margin-right: -25px;
            table {
                thead {
                    tr {
                        th {
                            background-color: #ecf0ff !important;
                            padding: {
                                top: 13px;
                                bottom: 13px;
                            }
                            &:first-child {
                                border-top-left-radius: 0 !important;
                                padding: {
                                    left: 25px !important;
                                    right: 0;
                                }
                            }
                            &:last-child {
                                border-top-right-radius: 0;
                                padding-right: 25px;
                            }
                            .v-checkbox.v-input {
                                margin: -27px -9px -30px -10px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                    }
                }
                tbody {
                    tr {
                        td {
                            padding: {
                                top: 17px !important;
                                bottom: 17px !important;
                            }
                            &:first-child {
                                border-left: 0 !important;
                                padding: {
                                    left: 25px !important;
                                    right: 0;
                                }
                            }
                            &:last-child {
                                border-right: 0 !important;
                                padding-right: 25px;
                                text-align: end;
                            }
                            .action-buttons.d-flex.align-items-center {
                                justify-content: end;
                            }
                            .v-checkbox.v-input {
                                margin: -10px -30px -30px -10px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                        &:first-child {
                            td {
                                border-top-width: 0;
                            }
                        }
                    }
                }
            }
            .pagination-content {
                margin-top: 0;
                padding: 15px 20px;
                color: var(--blackColor) !important;
                background-color: transparent !important;
            }
        }
    }
}
</style>

// svelte-bootstrap/src/routes/dashboard/apps/contacts/+page.svelte
<script>
	import BreadCrumb from '$lib/components/Common/BreadCrumb.svelte';
</script>

<svelte:head>
	<title>Contacts | Trezo - Svelte & Bootsrap 5 Admin Dashboard Template</title>
</svelte:head>

<BreadCrumb page="Contacts List" category="APPS" parentLink="/dashboard" />

<div class="card bg-white border-0 rounded-3 mb-4">
	<div class="card-body p-0">
		<div class="d-flex justify-content-between align-items-center flex-wrap gap-2 p-4">
			<form class="position-relative table-src-form me-0">
				<input type="text" class="form-control" placeholder="Search here" />
				<i class="material-symbols-outlined position-absolute top-50 start-0 translate-middle-y"
					>search</i
				>
			</form>
			<select class="form-select month-select form-control" aria-label="Default select example">
				<option selected>All</option>
				<option value="1">Admin</option>
				<option value="2">Mamber</option>
			</select>
		</div>

		<div class="default-table-area style-two default-table-width">
			<div class="table-responsive">
				<table class="table align-middle">
					<thead>
						<tr>
							<th scope="col">
								<div class="form-check">
									<input
										class="form-check-input position-relative top-1"
										type="checkbox"
										value=""
										id="flexCheckDefault7"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault7">ID</label>
								</div>
							</th>
							<th scope="col">User</th>
							<th scope="col">Email</th>
							<th scope="col">Phone</th>
							<th scope="col">Last Contacted</th>
							<th scope="col">Company</th>
							<th scope="col">Lead Score</th>
							<th scope="col">Status</th>
							<th scope="col">Action</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#854</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-42.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Oliver Khan</h6>
									</div>
								</a>
							</td>
							<td>oliver@trezo.com</td>
							<td class="text-body">+1 555-123-4567</td>
							<td class="text-body">Jun 19, 2024</td>
							<td class="text-body">ABC Corporation</td>
							<td class="text-body">50</td>
							<td>
								<span class="badge bg-primary bg-opacity-10 text-primary p-2 fs-12 fw-normal"
									>Active</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#853</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-7.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Carolyn Barnes</h6>
									</div>
								</a>
							</td>
							<td>carolyn@trezo.com</td>
							<td class="text-body">+1 555-987-6543</td>
							<td class="text-body">Jun 18, 2024</td>
							<td class="text-body">XYZ Ltd</td>
							<td class="text-body">35</td>
							<td>
								<span class="badge bg-primary bg-opacity-10 text-primary p-2 fs-12 fw-normal"
									>Active</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#852</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-8.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Donna Miller</h6>
									</div>
								</a>
							</td>
							<td>donna@trezo.com</td>
							<td class="text-body">+1 555-456-7890</td>
							<td class="text-body">Jun 17, 2024</td>
							<td class="text-body">Tech Solutions</td>
							<td class="text-body">40</td>
							<td>
								<span class="badge bg-danger bg-opacity-10 text-danger p-2 fs-12 fw-normal"
									>Deactive</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#851</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-9.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Barbara Cross</h6>
									</div>
								</a>
							</td>
							<td>barbara@trezo.com</td>
							<td class="text-body">+1 555-369-7878</td>
							<td class="text-body">Jun 16, 2024</td>
							<td class="text-body">Global Solutions</td>
							<td class="text-body">25</td>
							<td>
								<span class="badge bg-primary bg-opacity-10 text-primary p-2 fs-12 fw-normal"
									>Active</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#850</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-10.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Rebecca Block</h6>
									</div>
								</a>
							</td>
							<td>rebecca@trezo.com</td>
							<td class="text-body">+1 555-658-4488</td>
							<td class="text-body">Jun 15, 2024</td>
							<td class="text-body">Acma Industries</td>
							<td class="text-body">27</td>
							<td>
								<span class="badge bg-danger bg-opacity-10 text-danger p-2 fs-12 fw-normal"
									>Deactive</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#849</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-11.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Ramiro McCarty</h6>
									</div>
								</a>
							</td>
							<td>ramiro@trezo.com</td>
							<td class="text-body">+1 555-558-9966</td>
							<td class="text-body">Jun 14, 2024</td>
							<td class="text-body">Synergy Ltd</td>
							<td class="text-body">16</td>
							<td>
								<span class="badge bg-primary bg-opacity-10 text-primary p-2 fs-12 fw-normal"
									>Active</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#848</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-12.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Robert Fairweather</h6>
									</div>
								</a>
							</td>
							<td>robert@trezo.com</td>
							<td class="text-body">+1 555-357-5888</td>
							<td class="text-body">Jun 13, 2024</td>
							<td class="text-body">Summit Solutions</td>
							<td class="text-body">38</td>
							<td>
								<span class="badge bg-primary bg-opacity-10 text-primary p-2 fs-12 fw-normal"
									>Active</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#847</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-13.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Marcelino Haddock</h6>
									</div>
								</a>
							</td>
							<td>marcelino@trezo.com</td>
							<td class="text-body">+1 555-456-8877</td>
							<td class="text-body">Jun 12, 2024</td>
							<td class="text-body">Strategies Ltd</td>
							<td class="text-body">15</td>
							<td>
								<span class="badge bg-primary bg-opacity-10 text-primary p-2 fs-12 fw-normal"
									>Active</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#846</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-15.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Thomas Wilson</h6>
									</div>
								</a>
							</td>
							<td>thomas@trezo.com</td>
							<td class="text-body">+1 555-622-4488</td>
							<td class="text-body">Jun 11, 2024</td>
							<td class="text-body">Tech Enterprises</td>
							<td class="text-body">41</td>
							<td>
								<span class="badge bg-danger bg-opacity-10 text-danger p-2 fs-12 fw-normal"
									>Deactive</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
						<tr>
							<td class="text-body">
								<div class="form-check">
									<input
										class="form-check-input"
										type="checkbox"
										value=""
										id="flexCheckDefault12"
									/>
									<label class="position-relative top-2 ms-1" for="flexCheckDefault12">#845</label>
								</div>
							</td>
							<td>
								<a href="agents.html" class="d-flex align-items-center">
									<div class="flex-shrink-0">
										<img src="/assets/images/user-16.jpg" class="wh-34 rounded-circle" alt="user" />
									</div>
									<div class="flex-grow-1 ms-2 position-relative top-1">
										<h6 class="mb-0 fs-14 fw-medium">Nathaniel Hulsey</h6>
									</div>
								</a>
							</td>
							<td>nathaniel@trezo.com</td>
							<td class="text-body">+1 555-225-4488</td>
							<td class="text-body">Jun 10, 2024</td>
							<td class="text-body">Synetic Solutions</td>
							<td class="text-body">29</td>
							<td>
								<span class="badge bg-primary bg-opacity-10 text-primary p-2 fs-12 fw-normal"
									>Active</span
								>
							</td>
							<td>
								<div class="d-flex align-items-center gap-1">
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-body">edit</i>
									</button>
									<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
										<i class="material-symbols-outlined fs-16 text-danger">delete</i>
									</button>
								</div>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="p-4 pt-lg-4">
				<div
					class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap"
				>
					<span class="fs-12 fw-medium">Showing 10 of 30 Results</span>

					<nav aria-label="Page navigation example">
						<ul class="pagination mb-0 justify-content-center">
							<li class="page-item">
								<a class="page-link icon" href="/dashboard/apps/contacts" aria-label="Previous">
									<i class="material-symbols-outlined">keyboard_arrow_left</i>
								</a>
							</li>
							<li class="page-item">
								<a class="page-link active" href="/dashboard/apps/contacts">1</a>
							</li>
							<li class="page-item"><a class="page-link" href="/dashboard/apps/contacts">2</a></li>
							<li class="page-item"><a class="page-link" href="/dashboard/apps/contacts">3</a></li>
							<li class="page-item"><a class="page-link" href="/dashboard/apps/contacts">4</a></li>
							<li class="page-item">
								<a class="page-link icon" href="/dashboard/apps/contacts" aria-label="Next">
									<i class="material-symbols-outlined">keyboard_arrow_right</i>
								</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
