// vuejs-bootstrap/src/components/Dashboard/BeautySalon/CustomersFromChannels.vue
<template>
  <div
    class="customers-from-channels-card card mb-4 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-30"
      >
        <h5 class="mb-0">Customers From Channels</h5>
      </div>

      <div class="trezo-card-content">
        <ul class="p-0 m-0 list-unstyled">
          <li
            v-for="channel in channels"
            :key="channel.name"
            class="d-flex align-items-center justify-content-between"
          >
            <div class="title d-flex align-items-center">
              <img :src="channel.icon" :alt="channel.name" />
              <div>
                <span class="d-block fw-semibold text-black">
                  {{ channel.name }}
                </span>
                <span class="d-block">{{ channel.description }}</span>
              </div>
            </div>
            <div class="percentage-progress d-flex align-items-center">
              <div
                class="progress trezo-progress w-100"
                role="progressbar"
                :aria-valuenow="channel.percentage"
                aria-valuemin="0"
                aria-valuemax="100"
              >
                <div
                  class="progress-bar"
                  :class="channel.progressBarClass"
                  :style="{ width: channel.percentage + '%' }"
                ></div>
              </div>
              <span class="d-block percentage">{{ channel.percentage }}%</span>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CustomersFromChannels",
  data() {
    return {
      channels: [
        {
          name: "Facebook",
          description: "Community",
          icon: require("@/assets/images/icons/facebook3.svg"),
          percentage: 50,
          progressBarClass: "",
        },
        {
          name: "Dribbble",
          description: "Community",
          icon: require("@/assets/images/icons/dribbble2.svg"),
          percentage: 75,
          progressBarClass: "bg-secondary",
        },
        {
          name: "Instagram",
          description: "Reels",
          icon: require("@/assets/images/icons/instagram2.svg"),
          percentage: 30,
          progressBarClass: "bg-orange",
        },
        {
          name: "Google",
          description: "SEO & PPC",
          icon: require("@/assets/images/icons/google3.svg"),
          percentage: 20,
          progressBarClass: "bg-success",
        },
      ],
    };
  },
});
</script>

<style lang="scss" scoped>
.customers-from-channels-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        padding-bottom: 14px;
        margin-bottom: 14px;

        .title {
          gap: 15px;

          span {
            &:nth-child(2) {
              font-size: 12px;
              margin-top: 2px;
            }
          }
        }
        .percentage-progress {
          width: 150px;
          gap: 12px;

          .trezo-progress {
            --bs-progress-height: 8px;
            .bg-secondary {
              background-color: var(--secondaryColor) !important;
            }
            .bg-orange {
              background-color: var(--orangeColor) !important;
            }
          }
          .percentage {
            font-size: 12px;
          }
        }
        &:last-child {
          margin-bottom: 0;
          padding-bottom: 0;
          border-bottom-width: 0;
        }
      }
    }
  }
}

/* Min width 992px to Max width 1199px */
@media only screen and (min-width: 992px) and (max-width: 1199px) {
  .customers-from-channels-card {
    .trezo-card-content {
      ul {
        li {
          .percentage-progress {
            width: 130px;
          }
        }
      }
    }
  }
}

/* Min width 1200px to Max width 1399px */
@media only screen and (min-width: 1200px) and (max-width: 1399px) {
  .customers-from-channels-card {
    .trezo-card-content {
      ul {
        li {
          .percentage-progress {
            width: 120px;
          }
        }
      }
    }
  }
}
</style>

// react-nextjs-material-ui/src/components/Dashboard/BeautySalon/CustomersFromChannels.tsx
"use client";

import { Card, Box, Typography } from "@mui/material";
import Image from "next/image";

// Define the type for a channel
interface Channel {
  id: number;
  icon: string;
  name: string;
  type: string;
  progress: number;
  progressBarColor: string;
  progressBgColor: string;
}

const channelsData: Channel[] = [
  {
    id: 1,
    icon: "/images/beauty-salon/facebook.svg",
    name: "Facebook",
    type: "Community",
    progress: 50,
    progressBarColor: "#757DFF",
    progressBgColor: "#DDE4FF",
  },
  {
    id: 2,
    icon: "/images/beauty-salon/dribbble.svg",
    name: "Dribbble",
    type: "Community",
    progress: 75,
    progressBarColor: "#5DA8FF",
    progressBgColor: "#DAEBFF",
  },
  {
    id: 3,
    icon: "/images/beauty-salon/instagram.svg",
    name: "Instagram",
    type: "Reel",
    progress: 30,
    progressBarColor: "#FE7A36",
    progressBgColor: "#FFE8D4",
  },
  {
    id: 4,
    icon: "/images/beauty-salon/google2.svg",
    name: "Google",
    type: "SEO & PPC",
    progress: 20,
    progressBarColor: "#58F229",
    progressBgColor: "#D8FFC8",
  },
];

const CustomersFromChannels: React.FC = () => {
  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box sx={{ mb: "10px", pb: "10px" }}>
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Customers From Channels
          </Typography>
        </Box>

        <>
          {channelsData.map((channel) => (
            <Box
              key={channel.id}
              className="border-bottom lcbpm-none"
              sx={{
                mb: "21px",
                pb: "21px",
              }}
            >
              <Box
                sx={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  gap: "10px",
                }}
              >
                <Box sx={{ flexShrink: 0 }}>
                  <Box sx={{ display: "flex", gap: "10px" }}>
                    <Image
                      src={channel.icon}
                      alt={channel.name}
                      width={30}
                      height={30}
                    />

                    <Box>
                      <Typography
                        variant="h3"
                        sx={{
                          fontSize: "14px",
                          fontWeight: 600,
                          lineHeight: 1,
                          mb: "2px",
                        }}
                      >
                        {channel.name}
                      </Typography>

                      <Typography fontSize={"12px"}>{channel.type}</Typography>
                    </Box>
                  </Box>
                </Box>

                <Box>
                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "flex-end",
                      gap: "10px",
                    }}
                  >
                    <Box sx={{ width: { xs: "80px", sm: "120px" } }}>
                      <Box
                        sx={{
                          borderRadius: "30px",
                          height: "8px",
                          backgroundColor: channel.progressBgColor,
                        }}
                      >
                        <Box
                          sx={{
                            width: `${channel.progress}%`,
                            height: "8px",
                            backgroundColor: channel.progressBarColor,
                            borderRadius: "30px",
                          }}
                        ></Box>
                      </Box>
                    </Box>

                    <span className="count text-body fs-12">
                      {channel.progress}%
                    </span>
                  </Box>
                </Box>
              </Box>
            </Box>
          ))}
        </>
      </Card>
    </>
  );
};

export default CustomersFromChannels;
