// vuejs-bootstrap/src/components/Dashboard/BeautySalon/FeaturedServices.vue
<template>
  <div
    class="featured-services-card card mb-4 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-30"
      >
        <h5 class="mb-0">Featured Services</h5>
      </div>

      <div class="trezo-card-content">
        <ul class="p-0 m-0 list-unstyled">
          <li
            v-for="(service, index) in services"
            :key="service.id"
            class="d-flex align-items-center justify-content-between"
          >
            <div class="info d-flex align-items-center">
              <img :src="service.icon" :alt="service.name" />
              <div>
                <span class="d-block text-black fw-semibold">
                  {{ service.name }}
                </span>
                <span class="d-block text-body">
                  {{ service.served }} Served this week
                </span>
              </div>
            </div>
            <span
              class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center"
            >
              {{ index + 1 }}
            </span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "FeaturedServices",
  setup() {
    const services = [
      {
        id: 1,
        name: "Hair Cut",
        icon: require("@/assets/images/icons/hair-cutting.svg"),
        served: 132,
      },
      {
        id: 2,
        name: "Manicure",
        icon: require("@/assets/images/icons/manicure.svg"),
        served: 102,
      },
      {
        id: 3,
        name: "Pedicure",
        icon: require("@/assets/images/icons/pedicure.svg"),
        served: 99,
      },
      {
        id: 4,
        name: "Nail Art",
        icon: require("@/assets/images/icons/nail-polish.svg"),
        served: 89,
      },
      {
        id: 5,
        name: "Facial Treatment",
        icon: require("@/assets/images/icons/woman.svg"),
        served: 72,
      },
    ];
    return {
      services,
    };
  },
});
</script>

<style lang="scss" scoped>
.featured-services-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        padding-bottom: 12px;
        margin-bottom: 12px;

        .info {
          gap: 15px;

          span {
            font-size: 12px;

            &:nth-child(1) {
              font-size: var(--fontSize);
              margin-bottom: 2px;
            }
          }
        }
        .number {
          width: 25px;
          height: 25px;
          font-size: 12px;
          background-color: #dde4ff;
        }
        &:last-child {
          border-bottom-width: 0;
          padding-bottom: 0;
          margin-bottom: 0;
        }
      }
    }
  }
}
</style>

// react-nextjs-material-ui/src/components/Dashboard/BeautySalon/FeaturedServices.tsx
"use client";

import { Card, Box, Typography } from "@mui/material";
import Image from "next/image";

interface Service {
  id: number;
  image: string;
  name: string;
  served: string;
  rank: string;
}

const featuredServicesData: Service[] = [
  {
    id: 1,
    image: "/images/beauty-salon/featured-1.png",
    name: "Hair Cut",
    served: "132 Served this week",
    rank: "01",
  },
  {
    id: 2,
    image: "/images/beauty-salon/featured-2.png",
    name: "Manicure",
    served: "102 Served this week",
    rank: "02",
  },
  {
    id: 3,
    image: "/images/beauty-salon/featured-3.png",
    name: "Pedicure",
    served: "99 Served this week",
    rank: "03",
  },
  {
    id: 4,
    image: "/images/beauty-salon/featured-4.png",
    name: "Nail Art",
    served: "89 Served this week",
    rank: "04",
  },
  {
    id: 5,
    image: "/images/beauty-salon/featured-5.png",
    name: "Facial Treatment",
    served: "72 Served this week",
    rank: "05",
  },
];

const FeaturedServices: React.FC = () => {
  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box sx={{ mb: "10px", pb: "10px" }}>
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Featured Services
          </Typography>
        </Box>

        <>
          {featuredServicesData.map((service) => (
            <Box
              key={service.id}
              className="border-bottom lcbpm-none"
              sx={{
                paddingBottom: "18px",
                marginBottom: "18px",
              }}
            >
              <Box
                sx={{
                  display: "flex",
                  flexWrap: "wrap",
                  gap: "5px",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <Box
                  sx={{ display: "flex", gap: "10px", alignItems: "center" }}
                >
                  <Image
                    src={service.image}
                    alt={service.name}
                    width={32}
                    height={32}
                  />

                  <Box>
                    <Typography
                      variant="h3"
                      sx={{ fontSize: "14px", fontWeight: 600, mb: "0" }}
                    >
                      {service.name}
                    </Typography>

                    <Typography fontSize={"12px"}>{service.served}</Typography>
                  </Box>
                </Box>

                <Box 
                  sx={{
                    bgcolor: "#605dff1a",
                    color: "primary.main",
                    fontSize: "12px",
                    fontWeight: 500,
                    width: "20px",
                    height: "20px",
                    lineHeight: "20px",
                    textAlign: "center",
                    borderRadius: "50%",
                    display: "inline-block",
                  }}
                >
                  {service.rank}
                </Box>
              </Box>
            </Box>
          ))}
        </>
      </Card>
    </>
  );
};

export default FeaturedServices;
