// laravel-vuetify/resources/components/Modules/Tables/DataTable/RecentLeads.vue
<template>
    <v-card
        class="recent-leads-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Recent Leads</h5>
            <div class="d-flex align-items-center">
                <v-menu>
                    <template v-slot:activator="{ props }">
                        <button
                            type="button"
                            v-bind="props"
                            class="card-header-menu border-none d-inline-block border-radius"
                        >
                            This Day
                        </button>
                    </template>
                    <v-list class="menu-content">
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Day
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Week
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Month
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            This Year
                        </button>
                    </v-list>
                </v-menu>
            </div>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th class="text-start">
                                <v-checkbox color="primary"></v-checkbox>
                            </th>
                            <th class="text-start">Customer</th>
                            <th class="text-start">Email</th>
                            <th class="text-start">Source</th>
                            <th class="text-start">Status</th>
                            <th class="text-start">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in items.slice(0, 5)" :key="item.id">
                            <td><v-checkbox color="primary"></v-checkbox></td>
                            <td class="text-start">
                                <div
                                    class="customer-info d-flex align-items-center"
                                >
                                    <div class="img">
                                        <v-img
                                            class="rounded-circle"
                                            :src="item.customer.image"
                                            alt="customer"
                                        />
                                    </div>
                                    <span class="d-block text-black fw-medium">
                                        {{ item.customer.name }}
                                    </span>
                                </div>
                            </td>
                            <td>{{ item.email }}</td>
                            <td>{{ item.source }}</td>
                            <td>
                                <span
                                    class="trezo-status-badge"
                                    :class="computeClass(item.status)"
                                >
                                    {{ item.status }}
                                </span>
                            </td>
                            <td>
                                <div
                                    class="action-buttons d-flex align-items-center"
                                >
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.view }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.edit }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.delete }}
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </div>
            <PaginationTwo items="5" />
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref } from "vue";
import PaginationTwo from "../../../Common/PaginationTwo.vue";

import user6 from "../../../../../public/images/users/user6.jpg";
import user7 from "../../../../../public/images/users/user7.jpg";
import user8 from "../../../../../public/images/users/user8.jpg";
import user9 from "../../../../../public/images/users/user9.jpg";
import user10 from "../../../../../public/images/users/user10.jpg";

export default defineComponent({
    name: "RecentLeads",
    components: {
        PaginationTwo,
    },
    setup() {
        const items = ref([
            {
                id: "1",
                customer: {
                    image: user6,
                    name: "David Brown",
                },
                email: "david@trezo.com",
                source: "Organic",
                status: "Confirmed",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "2",
                customer: {
                    image: user7,
                    name: "Sarah Miller",
                },
                email: "sara@trezo.com",
                source: "Social",
                status: "Pending",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "3",
                customer: {
                    image: user8,
                    name: "Amanda Clark",
                },
                email: "amanda@trezo.com",
                source: "Paid",
                status: "In Progress",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "4",
                customer: {
                    image: user9,
                    name: "Jennifer Taylor",
                },
                email: "taylor@trezo.com",
                source: "Others",
                status: "Confirmed",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "5",
                customer: {
                    image: user10,
                    name: "Sarah Miller",
                },
                email: "sara@trezo.com",
                source: "Social",
                status: "Rejected",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "6",
                customer: {
                    image: user9,
                    name: "David Brown",
                },
                email: "david@trezo.com",
                source: "Organic",
                status: "Confirmed",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "7",
                customer: {
                    image: user8,
                    name: "Sarah Miller",
                },
                email: "sara@trezo.com",
                source: "Social",
                status: "Pending",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "8",
                customer: {
                    image: user10,
                    name: "Amanda Clark",
                },
                email: "amanda@trezo.com",
                source: "Paid",
                status: "In Progress",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "9",
                customer: {
                    image: user6,
                    name: "Jennifer Taylor",
                },
                email: "taylor@trezo.com",
                source: "Others",
                status: "Confirmed",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "10",
                customer: {
                    image: user7,
                    name: "Sarah Miller",
                },
                email: "sara@trezo.com",
                source: "Social",
                status: "Rejected",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "11",
                customer: {
                    image: user10,
                    name: "Sarah Miller",
                },
                email: "sara@trezo.com",
                source: "Social",
                status: "Rejected",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "12",
                customer: {
                    image: user9,
                    name: "David Brown",
                },
                email: "david@trezo.com",
                source: "Organic",
                status: "Confirmed",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
            {
                id: "13",
                customer: {
                    image: user8,
                    name: "Sarah Miller",
                },
                email: "sara@trezo.com",
                source: "Social",
                status: "Pending",
                action: {
                    view: "visibility",
                    edit: "edit",
                    delete: "delete",
                },
            },
        ]);

        const wordConfirmed = ref("Confirmed");
        const wordInProgress = ref("In Progress");
        const wordPending = ref("Pending");
        const wordRejected = ref("Rejected");

        const computeClass = (classValue) => {
            return {
                confirmed: wordConfirmed.value === classValue,
                inProgress: wordInProgress.value === classValue,
                pending: wordPending.value === classValue,
                rejected: wordRejected.value === classValue,
            };
        };

        return {
            items,
            computeClass,
        };
    },
});
</script>

<style lang="scss" scoped>
.recent-leads-card {
    .trezo-table-content {
        .trezo-table {
            margin-left: -25px;
            margin-right: -25px;
            table {
                thead {
                    tr {
                        th {
                            background-color: #ecf0ff !important;
                            &:first-child {
                                border-top-left-radius: 0 !important;
                                padding-left: 25px;
                                padding-right: 0;
                            }
                            .v-checkbox.v-input {
                                margin: -28px -30px -30px -7px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                    }
                }
                tbody {
                    tr {
                        td {
                            &:first-child {
                                padding-left: 25px;
                                border-left: none !important;
                            }
                            &:last-child {
                                border-right: none !important;
                            }
                            .v-checkbox.v-input {
                                margin: -26px -30px -30px -7px;
                            }
                            .v-input__details {
                                display: none !important;
                            }
                            .v-selection-control__input {
                                width: 0 !important;
                                height: 0 !important;
                            }
                        }
                    }
                }
            }
        }
    }
}
</style>

// svelte-bootstrap/src/lib/components/Dashboard/CRM/RecentLeads.svelte
<div class="col-xxl-8 col-xl-7 col-lg-7">
	<div class="card bg-white border-0 rounded-3 mb-4">
		<div class="card-body p-0">
			<div class="d-flex justify-content-between align-items-center flex-wrap gap-3 p-4">
				<h3 class="mb-0">Recent Leads</h3>
				<select
					class="form-select month-select form-control p-0 h-auto border-0 w-90"
					style="background-position: right 0 center;"
					aria-label="Default select example"
				>
					<option selected>This Week</option>
					<option value="1">This Month</option>
					<option value="2">This Year</option>
				</select>
			</div>

			<div class="default-table-area style-two recent-leads">
				<div class="table-responsive">
					<table class="table align-middle">
						<thead>
							<tr>
								<th scope="col">
									<div class="form-check">
										<input
											class="form-check-input"
											type="checkbox"
											value=""
											id="flexCheckDefault"
										/>
									</div>
								</th>
								<th scope="col">Customer</th>
								<th scope="col">Email</th>
								<th scope="col">Source</th>
								<th scope="col">Status</th>
								<th scope="col">Action</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>
									<div class="form-check">
										<input
											class="form-check-input"
											type="checkbox"
											value=""
											id="flexCheckDefault2"
										/>
									</div>
								</td>
								<td>
									<a href="my-profile.html" class="d-flex align-items-center">
										<img src="/assets/images/user-11.jpg" class="wh-44 rounded-circle" alt="user" />
										<div class="ms-2">
											<h6 class="fw-medium fs-14">David Brown</h6>
										</div>
									</a>
								</td>
								<td>david@trezo.com</td>
								<td>Organic</td>
								<td>
									<span class="badge bg-info bg-opacity-10 text-info p-2 fs-12 fw-normal"
										>Confirmed</span
									>
								</td>
								<td>
									<div class="d-flex align-items-center gap-1">
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-body">edit</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-danger">delete</i>
										</button>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="form-check">
										<input
											class="form-check-input"
											type="checkbox"
											value=""
											id="flexCheckDefault3"
										/>
									</div>
								</td>
								<td>
									<a href="my-profile.html" class="d-flex align-items-center">
										<img src="/assets/images/user-12.jpg" class="wh-44 rounded-circle" alt="user" />
										<div class="ms-2">
											<h6 class="fw-medium fs-14">Sarah Miller</h6>
										</div>
									</a>
								</td>
								<td>sara@trezo.com</td>
								<td>Social</td>
								<td>
									<span class="badge bg-warning bg-opacity-10 text-warning p-2 fs-12 fw-normal"
										>Pending</span
									>
								</td>
								<td>
									<div class="d-flex align-items-center gap-1">
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-body">edit</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-danger">delete</i>
										</button>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="form-check">
										<input
											class="form-check-input"
											type="checkbox"
											value=""
											id="flexCheckDefault4"
										/>
									</div>
								</td>
								<td>
									<a href="my-profile.html" class="d-flex align-items-center">
										<img src="/assets/images/user-13.jpg" class="wh-44 rounded-circle" alt="user" />
										<div class="ms-2">
											<h6 class="fw-medium fs-14">Michael Wilson</h6>
										</div>
									</a>
								</td>
								<td>micheal@trezo.com</td>
								<td>Website</td>
								<td>
									<span class="badge bg-success bg-opacity-10 text-success p-2 fs-12 fw-normal"
										>In Progress</span
									>
								</td>
								<td>
									<div class="d-flex align-items-center gap-1">
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-body">edit</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-danger">delete</i>
										</button>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="form-check">
										<input
											class="form-check-input"
											type="checkbox"
											value=""
											id="flexCheckDefault5"
										/>
									</div>
								</td>
								<td>
									<a href="my-profile.html" class="d-flex align-items-center">
										<img src="/assets/images/user-14.jpg" class="wh-44 rounded-circle" alt="user" />
										<div class="ms-2">
											<h6 class="fw-medium fs-14">Amanda Clark</h6>
										</div>
									</a>
								</td>
								<td>amanda@trezo.com</td>
								<td>Paid</td>
								<td>
									<span class="badge bg-info bg-opacity-10 text-info p-2 fs-12 fw-normal"
										>Confirmed</span
									>
								</td>
								<td>
									<div class="d-flex align-items-center gap-1">
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-body">edit</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-danger">delete</i>
										</button>
									</div>
								</td>
							</tr>
							<tr>
								<td>
									<div class="form-check">
										<input
											class="form-check-input"
											type="checkbox"
											value=""
											id="flexCheckDefault6"
										/>
									</div>
								</td>
								<td>
									<a href="my-profile.html" class="d-flex align-items-center">
										<img src="/assets/images/user-15.jpg" class="wh-44 rounded-circle" alt="user" />
										<div class="ms-2">
											<h6 class="fw-medium fs-14">David Brown</h6>
										</div>
									</a>
								</td>
								<td>Jennifer Taylor</td>
								<td>Others</td>
								<td>
									<span class="badge bg-danger bg-opacity-10 text-danger p-2 fs-12 fw-normal"
										>Rejected</span
									>
								</td>
								<td>
									<div class="d-flex align-items-center gap-1">
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-body">edit</i>
										</button>
										<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
											<i class="material-symbols-outlined fs-16 text-danger">delete</i>
										</button>
									</div>
								</td>
							</tr>
						</tbody>
					</table>
				</div>

				<div
					class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap p-4"
				>
					<span class="fs-12 fw-medium">Showing 5 of 30 Results</span>

					<nav aria-label="Page navigation example">
						<ul class="pagination mb-0 justify-content-center">
							<li class="page-item">
								<a class="page-link icon" href="/dashboard/crm" aria-label="Previous">
									<i class="material-symbols-outlined">keyboard_arrow_left</i>
								</a>
							</li>
							<li class="page-item"><a class="page-link active" href="/dashboard/crm">1</a></li>
							<li class="page-item"><a class="page-link" href="/dashboard/crm">2</a></li>
							<li class="page-item"><a class="page-link" href="/dashboard/crm">3</a></li>
							<li class="page-item"><a class="page-link" href="/dashboard/crm">4</a></li>
							<li class="page-item">
								<a class="page-link icon" href="/dashboard/crm" aria-label="Next">
									<i class="material-symbols-outlined">keyboard_arrow_right</i>
								</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
