// laravel-vuetify/resources/components/Dashboard/Podcast/PopularHosts.vue
<template>
    <v-card
        class="popular-hosts-card trezo-card custom-shadow rounded-3 bg-white p-0"
        style="padding-bottom: 24px"
    >
        <div class="v-card-header mb-0" style="padding: 20px 25px">
            <h3 class="mb-0 fs-18 fw-semibold">Popular Hosts</h3>
            <button
                class="bg-transparent border-0 p-0 d-flex align-items-center text-decoration-none position-relative right-for-rtl text-body"
                style="right: -8px"
            >
                <span>View All</span>
                <i
                    class="ri-arrow-right-s-line fs-24 position-relative top-1 lh-1 text-body"
                ></i>
            </button>
        </div>

        <div class="default-table-area style-three popular-hosts pb-20">
            <div class="table-responsive">
                <table class="table align-middle border-0">
                    <tbody>
                        <tr v-for="host in hosts" :key="host.id">
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <div class="flex-shrink-0">
                                        <v-img
                                            :src="host.image"
                                            style="width: 40px; height: 40px"
                                            class="rounded-circle"
                                            alt="user"
                                        />
                                    </div>
                                    <div class="flex-grow-1 ms-10">
                                        <h4 class="fs-14 fw-medium mb-0">
                                            {{ host.name }}
                                        </h4>
                                        <span class="fs-12 text-body fw-normal">
                                            {{ host.category }}
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <td class="border-bottom">
                                <span class="d-block fs-14 fw-medium">{{
                                    host.hosted
                                }}</span>
                                <span class="d-block fs-12 fw-normal text-body"
                                    >Hosted</span
                                >
                            </td>
                            <td class="text-end border-bottom">
                                <button
                                    @click="toggleFollow(host)"
                                    :class="[
                                        'border-0 text-primary follow-button fs-14',
                                        { followed: host.isFollowing },
                                    ]"
                                    style="
                                        background-color: #ecf0ff;
                                        padding: 4.5px 10px;
                                        border-radius: 4px;
                                    "
                                >
                                    <span
                                        class="follow-text position-relative"
                                        style="top: -1px"
                                    >
                                        {{
                                            host.isFollowing
                                                ? "Following"
                                                : "Follow"
                                        }}
                                    </span>
                                </button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref } from "vue";

import user124 from "../../../../public/images/user-124.png";
import user125 from "../../../../public/images/user-125.png";
import user126 from "../../../../public/images/user-126.png";
import user127 from "../../../../public/images/user-127.png";
import user128 from "../../../../public/images/user-128.png";

export default defineComponent({
    name: "PopularHosts",
    setup() {
        const hosts = ref([
            {
                id: 1,
                name: "Sarah W.",
                category: "Marketing",
                hosted: 25,
                image: user124,
                isFollowing: false,
            },
            {
                id: 2,
                name: "Tom R.",
                category: "Blogging",
                hosted: 30,
                image: user125,
                isFollowing: false,
            },
            {
                id: 3,
                name: "Amanda G.",
                category: "Branding",
                hosted: 28,
                image: user126,
                isFollowing: true,
            },
            {
                id: 4,
                name: "Lisa Kim",
                category: "Storytelling",
                hosted: 20,
                image: user127,
                isFollowing: false,
            },
            {
                id: 5,
                name: "David C.",
                category: "Social Media",
                hosted: 18,
                image: user128,
                isFollowing: false,
            },
        ]);

        // Toggle Follow button state
        const toggleFollow = (host) => {
            host.isFollowing = !host.isFollowing;
        };

        return {
            hosts,
            toggleFollow,
        };
    },
});
</script>

<style lang="scss" scoped>
.v-card {
    &.trezo-card {
        border: 1px solid var(--borderColor) !important;
    }
}
.follow-button {
    .followed {
        transition: var(--transition);
    }
    &.followed {
        background-color: var(--primaryColor) !important;
        color: var(--whiteColor) !important;
    }
}
</style>

// angular-material/src/app/dashboard/podcast/popular-hosts/popular-hosts.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-popular-hosts',
    imports: [RouterLink, MatCardModule, MatButtonModule, MatTableModule],
    templateUrl: './popular-hosts.component.html',
    styleUrl: './popular-hosts.component.scss'
})
export class PopularHostsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}
    
    displayedColumns: string[] = ['name', 'hosted', 'action'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);

}

export interface PeriodicElement {
    name: any;
    hosted: number;
    action: any;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        name: {
            img: 'images/users/user54.jpg',
            name: 'Sarah W.',
            email: 'Marketing'
        },
        hosted: 25,
        action: {
            text: "Follow",
            className: 'follow'
        }
    },
    {
        name: {
            img: 'images/users/user53.jpg',
            name: 'Tom R.',
            email: 'Blogging'
        },
        hosted: 30,
        action: {
            text: "Follow",
            className: 'follow'
        }
    },
    {
        name: {
            img: 'images/users/user55.jpg',
            name: 'Amanda G.',
            email: 'Branding'
        },
        hosted: 28,
        action: {
            text: "Following",
            className: 'following'
        }
    },
    {
        name: {
            img: 'images/users/user41.jpg',
            name: 'Lisa Kim',
            email: 'Storytelling'
        },
        hosted: 20,
        action: {
            text: "Follow",
            className: 'follow'
        }
    },
    {
        name: {
            img: 'images/users/user43.jpg',
            name: 'David C.',
            email: 'Social Media'
        },
        hosted: 18,
        action: {
            text: "Follow",
            className: 'follow'
        }
    }
];
<mat-card
    class="popular-hosts-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0 fw-semibold">
                Popular Hosts
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <a routerLink="." mat-button class="view-all-btn p-0 d-inline-block">
                View All
                <i class="ri-arrow-right-s-line"></i>
            </a>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <div class="table-style-two">
            <div class="table-responsive">
                <table mat-table [dataSource]="dataSource">

                    <!-- Name Column -->
                    <ng-container matColumnDef="name">
                        <td mat-cell *matCellDef="let element">
                            <div class="employee-info d-flex align-items-center">
                                <div class="img rounded-circle">
                                    <img alt="user-image" [src]="element.name.img" class="rounded-circle">
                                </div>
                                <div>
                                    <span class="d-block fw-medium">
                                        {{element.name.name}}
                                    </span>
                                    <span class="d-block text-body">
                                        {{element.name.email}}
                                    </span>
                                </div>
                            </div>
                        </td>
                    </ng-container>

                    <!-- Hosted Column -->
                    <ng-container matColumnDef="hosted">
                        <td mat-cell *matCellDef="let element">
                            <div class="employee-info">
                                <div>
                                    <span class="d-block fw-medium">
                                        {{element.hosted}}
                                    </span>
                                    <span class="d-block text-body">
                                        Hosted
                                    </span>
                                </div>
                            </div>
                        </td>
                    </ng-container>

                    <!-- Action Column -->
                    <ng-container matColumnDef="action">
                        <td mat-cell *matCellDef="let element">
                            <button type="button" mat-button class="{{element.action.className}}">
                                {{element.action.text}}
                            </button>
                        </td>
                    </ng-container>

                    <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>

                </table>
            </div>
        </div>
    </mat-card-content>
</mat-card>
