// svelte-bootstrap/src/routes/dashboard/sales/+page.svelte
<script>
	import GrossEarnings from '$lib/components/Dashboard/Sales/GrossEarnings.svelte';
	import RealTimeSales from '$lib/components/Dashboard/Sales/RealTimeSales.svelte';
	import RecentEarnings from '$lib/components/Dashboard/Sales/RecentEarnings.svelte';
	import RecentOrders from '$lib/components/Dashboard/Sales/RecentOrders.svelte';
	import SalesByLocations from '$lib/components/Dashboard/Sales/SalesByLocations.svelte';
	import SalesOverview from '$lib/components/Dashboard/Sales/SalesOverview.svelte';
	import TotalOrders from '$lib/components/Dashboard/Sales/TotalOrders.svelte';
	import TotalProfit from '$lib/components/Dashboard/Sales/TotalProfit.svelte';
	import TotalRevenue from '$lib/components/Dashboard/Sales/TotalRevenue.svelte';
	import TotalSales from '$lib/components/Dashboard/Sales/TotalSales.svelte';
	import TransactionHistory from '$lib/components/Dashboard/Sales/TransactionHistory.svelte';
	import Welcome from '$lib/components/Dashboard/Sales/Welcome.svelte';
</script>

<svelte:head>
	<title>Sales | Trezo - Svelte & Bootsrap 5 Admin Dashboard Template</title>
</svelte:head>

<div class="card bg-white border-0 rounded-3 p-4 pb-0 mb-4">
	<Welcome />
	<div class="row">
		<TotalSales />
		<TotalOrders />
		<TotalProfit />
		<TotalRevenue />
	</div>
	<div class="row">
		<RecentEarnings />
		<SalesByLocations />
	</div>
</div>

<div class="row justify-content-center">
	<TransactionHistory />
	<RecentOrders />
</div>

<div class="row">
	<RealTimeSales />
	<SalesOverview />
	<GrossEarnings />
</div>

// react-nextjs-material-ui/src/app/dashboard/sales/page.tsx
import * as React from "react";
import { Grid, Card } from "@mui/material";
import Stats from "@/components/Dashboard/Sales/Stats";
import RecentEarnings from "@/components/Dashboard/Sales/RecentEarnings";
import SalesByLocations from "@/components/Dashboard/Sales/SalesByLocations";
import TransactionHistory from "@/components/Dashboard/Sales/TransactionHistory";
import RecentOrders from "@/components/Dashboard/Sales/RecentOrders";
import RealTimeSales from "@/components/Dashboard/Sales/RealTimeSales";
import SalesOverview from "@/components/Dashboard/Sales/SalesOverview";
import GrossEarnings from "@/components/Dashboard/Sales/GrossEarnings";

export default function Page() {
  return (
    <>
      <Card
        sx={{
          position: "relative",
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          paddingTop: { xs: "18px", sm: "20px", lg: "25px" },
          paddingX: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Stats />

        <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
          <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 8 }}>
            <RecentEarnings />
          </Grid>

          <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 4 }}>
            <SalesByLocations />
          </Grid>
        </Grid>
      </Card>

      <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 4 }}>
          <TransactionHistory />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 8 }}>
          <RecentOrders />
        </Grid>
      </Grid>

      <Grid
        container
        columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}
        justifyContent="center"
      >
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 12, xl: 4 }}>
          <RealTimeSales />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 12, xl: 4 }}>
          <SalesOverview />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 12, xl: 4 }}>
          <GrossEarnings />
        </Grid>
      </Grid>
    </>
  );
}
