// svelte-bootstrap/src/lib/components/App/Footer.svelte
<div class="footers-area pb-125 position-relative z-2">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4">
					<a href="/" class="footer-logo d-inline-block mb-4">
						<img src="/assets/images/landing/logo.svg" alt="logo" />
					</a>
					<p class="mb-4 pb-lg-2">
						With customizable dashboards tailored to your needs, collaborate effortlessly with your
						team and stay ahead with real-time updates.
					</p>

					<ul class="ps-0 mb-0 list-unstyled d-flex flex-wrap gap-3">
						<li>
							<a
								href="https://www.facebook.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="Facebook"
							>
								<i class="ri-facebook-fill"></i>
							</a>
						</li>
						<li>
							<a
								href="https://www.twitter.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="Twitter"
							>
								<i class="ri-twitter-x-line"></i>
							</a>
						</li>
						<li>
							<a
								href="https://www.linkedin.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="LinkedIn"
							>
								<i class="ri-linkedin-fill"></i>
							</a>
						</li>
						<li>
							<a
								href="https://www.dribbble.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="Dribble"
							>
								<i class="ri-dribbble-line"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4 ms-lg-5 ps-lg-5">
					<h3 class="mb-md-4 mb-3 fw-semibold">Our Products</h3>
					<ul class="ps-0 mb-0 list-unstyled">
						<li class="mb-2 pb-1">
							<a href="/dahsboard" class="text-decoration-none">Trezo Dashboard</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/" class="text-decoration-none">Tagus Admin</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/" class="text-decoration-none">eCademy LMS</a>
						</li>
						<li class="mb-0">
							<a href="/" class="text-decoration-none">Admash Template</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4 ms-lg-5 ps-lg-4">
					<h3 class="mb-md-4 mb-3 fw-semibold">Quick Links</h3>
					<ul class="ps-0 mb-0 list-unstyled">
						<li class="mb-2 pb-1">
							<a href="/" class="text-decoration-none">Home</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/features" class="text-decoration-none">Features</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/faqs" class="text-decoration-none">Testimonials</a>
						</li>
						<li class="mb-0">
							<a href="/our-team" class="text-decoration-none">Our Team</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4">
					<h3 class="mb-md-4 mb-3 fw-semibold">Privacy Policy</h3>
					<ul class="ps-0 mb-0 list-unstyled">
						<li class="mb-2 pb-1">
							<a href="/#" class="text-decoration-none">Terms & Conditions</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/#" class="text-decoration-none">Cookie Policy</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/#" class="text-decoration-none">Notice at Collection</a>
						</li>
						<li class="mb-0">
							<a href="/#" class="text-decoration-none">Privacy Policy</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

// react-nextjs-material-ui-starter/src/components/FrontPages/Common/Footer.tsx
"use client";

import * as React from "react";
import { Grid, Box, Link } from "@mui/material";
import Image from "next/image";
import { useParams } from "next/navigation";

const Footer: React.FC = () => {
  const { lang } = useParams();

  return (
    <>
      <Box
        className="fp-footer"
        sx={{
          pt: { xs: "60px", sm: "60px", md: "80px", lg: "100px", xl: "150px" },
        }}
      >
        <Box
          sx={{
            maxWidth: {
              xs: "100%",
              sm: "700px",
              md: "720px",
              lg: "1140px",
              xl: "1320px",
            },
            mx: "auto",
            px: "12px",
          }}
        >
          <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
            <Grid
              size={{ xs: 12, sm: 6, md: 6, lg: 3 }}
              className="fp-grid-item"
            >
              <div className="single-footer-widget">
                <Link href={`/${lang}`} className="logo">
                  <Image
                    src="/images/logo-big.svg"
                    alt="logo"
                    width={100}
                    height={26}
                  />
                  <Image
                    src="/images/white-logo-big.svg"
                    className="d-none"
                    alt="logo"
                    width={142}
                    height={38}
                  />
                </Link>

                <p>
                  With customizable dashboards tailored to your needs,
                  collaborate effortlessly with your team and stay ahead with
                  real-time updates.
                </p>

                <div className="socials">
                  <a href="https://www.facebook.com/" target="_blank">
                    <i className="ri-facebook-fill"></i>
                  </a>
                  <a href="https://www.twitter.com/" target="_blank">
                    <i className="ri-twitter-x-fill"></i>
                  </a>
                  <a href="https://www.linkedin.com/" target="_blank">
                    <i className="ri-linkedin-fill"></i>
                  </a>
                  <a href="https://www.dribbble.com/" target="_blank">
                    <i className="ri-dribbble-fill"></i>
                  </a>
                </div>
              </div>
            </Grid>

            <Grid
              size={{ xs: 12, sm: 6, md: 6, lg: 3 }}
              className="fp-grid-item"
            >
              <div className="single-footer-widget">
                <h3>Our Products</h3>
                <ul className="custom-links">
                  <li>
                    <Link href="#">Trezo Dashboard</Link>
                  </li>
                  <li>
                    <Link href="#">Tagus Admin</Link>
                  </li>
                  <li>
                    <Link href="#">eCademy LMS</Link>
                  </li>
                  <li>
                    <Link href="#">Admash Template</Link>
                  </li>
                </ul>
              </div>
            </Grid>

            <Grid
              size={{ xs: 12, sm: 6, md: 6, lg: 3 }}
              className="fp-grid-item"
            >
              <div className="single-footer-widget">
                <h3>Quick Links</h3>

                <ul className="custom-links">
                  <li>
                    <Link href="#">Home</Link>
                  </li>
                  <li>
                    <Link href="#">Features</Link>
                  </li>
                  <li>
                    <Link href="#">Testimonials</Link>
                  </li>
                  <li>
                    <Link href="#">Our Team</Link>
                  </li>
                </ul>
              </div>
            </Grid>

            <Grid
              size={{ xs: 12, sm: 6, md: 6, lg: 3 }}
              className="fp-grid-item"
            >
              <div className="single-footer-widget">
                <h3>Privacy Policy</h3>
                <ul className="custom-links">
                  <li>
                    <Link href="#">Terms & Conditions</Link>
                  </li>
                  <li>
                    <Link href="#">Cookie Policy</Link>
                  </li>
                  <li>
                    <Link href="#">Notice at Collection</Link>
                  </li>
                  <li>
                    <Link href="#">Privacy Policy</Link>
                  </li>
                </ul>
              </div>
            </Grid>
          </Grid>
        </Box>

        <div className="copyright-area bg-white text-center">
          <div className="container">
            <p>
              © <span>Trezo</span> is Proudly Owned by{" "}
              <a href="https://envytheme.com/" target="_blank">
                EnvyTheme
              </a>
            </p>
          </div>
        </div>
      </Box>
    </>
  );
};

export default Footer;
