// react-bootstrap/src/components/Dashboard/StoreAnalytics/GrossRevenue.js
"use client";

import React, { useEffect, useState } from "react";
import { Card, Dropdown } from "react-bootstrap";

const GrossRevenue = () => {
  const [Chart, setChart] = useState();
  useEffect(() => {
    import("react-apexcharts").then((mod) => {
      setChart(() => mod.default);
    });
  }, []);

  const series = [
    {
      name: "Sales Revenue",
      data: [35, 50, 55, 60, 50, 60, 55, 60, 78, 40],
    },

    {
      name: "Sales Volume",
      data: [80, 60, 50, 50, 72, 65, 90, 50, 70, 63],
    },
    {
      name: "Order Value",
      data: [70, 50, 40, 40, 95, 52, 80, 40, 60, 53],
    },
  ];

  const options = {
    chart: {
      zoom: {
        enabled: false,
      },
      toolbar: {
        show: false,
      },
    },
    colors: ["#757DFF", "#E9D5FF", "#37D80A"],
    dataLabels: {
      enabled: false,
    },
    stroke: {
      curve: "straight",
      width: [3, 3, 3],
      dashArray: [0, 6, 6],
    },
    grid: {
      borderColor: "#ECF0FF",
    },
    fill: {
      type: "gradient",
      gradient: {
        stops: [0, 90, 100],
        shadeIntensity: 1,
        opacityFrom: 0,
        opacityTo: 0,
      },
    },
    xaxis: {
      categories: [
        "Oct 01",
        "Oct 04",
        "Oct 08",
        "Oct 12",
        "Oct 16",
        "Oct 20",
        "Oct 24",
        "Oct 28",
        "Nov 02",
        "Nov 06",
      ],
      axisTicks: {
        show: false,
        color: "#B1BBC8",
      },
      axisBorder: {
        show: false,
        color: "#B1BBC8",
      },
      labels: {
        style: {
          colors: "#8695AA",
          fontSize: "12px",
          fontFamily: "Inter",
        },
      },
    },
    yaxis: {
      tickAmount: 5,
      max: 100,
      min: 0,
      labels: {
        formatter: (val) => {
          return "$" + val / 1 + "K";
        },
        style: {
          colors: "#8695AA",
          fontSize: "12px",
          fontFamily: "Inter",
        },
      },
    },
    legend: {
      show: true,
      position: "bottom",
      fontSize: "12px",
      horizontalAlign: "center",
      fontFamily: "Inter",
      fontWeight: 400,
      offsetY: 10,
      itemMargin: {
        horizontal: 8,
        vertical: 10,
      },
      labels: {
        colors: "#64748B",
      },
      markers: {
        width: 9,
        height: 9,
        offsetX: -2,
        offsetY: -0.5,
        radius: 2,
        shape: "diamond",
      },
    },
    tooltip: {
      y: {
        formatter: function (val) {
          return "$" + val + "k";
        },
      },
    },
  };

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <div className="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-1">
            <h3 className="mb-0">Gross Revenue</h3>

            <Dropdown className="dropdown select-dropdown">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="dropdown-toggle bg-border-color border text-body rounded-2"
              >
                Monthly <i className="ri-arrow-down-s-line"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Monthly
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Weekly
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Yearly
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <div className="d-flex align-items-center mb-2">
            <h3 className="fs-32 fw-bold text-secondary mb-0">$1,528</h3>
            <span className="fw-medium fs-12 text-success bg-success bg-opacity-10 border border-success px-2 rounded-pill ms-2">
              +5.4%
              <i className="ri-arrow-up-line"></i>
            </span>
          </div>

          <span className="fs-12 d-block mb-4">vs previous 30 days</span>

          <div style={{ margin: "-24px -24px -20px -17px" }}>
            {Chart && (
              <Chart
                options={options}
                series={series}
                type="area"
                height={340}
              />
            )}
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default GrossRevenue;

// vuejs-vuetify/src/components/Dashboard/StoreAnalysis/GrossRevenue.vue
<template>
  <v-card
    class="sa-gross-revenue-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <div class="trezo-card-title">
        <span class="d-block">Gross Revenue</span>
        <div class="revenue d-flex align-items-center">
          <h3 class="mb-0 lh-1">$1,528</h3>
          <span class="trezo-status-badge shipped">+5.4%</span>
        </div>
        <span class="text-xs d-block">vs previous 30 days</span>
      </div>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius bg-gray border-0"
          >
            {{ selectedTimeframe }}
          </button>
        </template>
        <v-list class="menu-content">
          <v-list-item
            v-for="timeframe in timeframes"
            :key="timeframe"
            @click="updateTimeframe(timeframe)"
          >
            <v-list-item-title>{{ timeframe }}</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="chart">
        <apexchart
          v-if="isClient && chartOptions"
          type="line"
          height="315"
          :options="chartOptions"
          :series="series"
        ></apexchart>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from "vue";

interface SeriesData {
  name: string;
  data: number[];
}

interface ChartData {
  series: SeriesData[];
  categories: string[];
}

export default defineComponent({
  name: "GrossRevenue",
  setup() {
    const isClient = ref(false);
    const timeframes = ["Weekly", "Monthly", "Yearly"] as const;
    type Timeframe = (typeof timeframes)[number];
    const selectedTimeframe = ref<Timeframe>("Weekly");
    const series = ref<SeriesData[]>([]);
    const chartOptions = ref<any>(null);

    const chartData: Record<Timeframe, ChartData> = {
      Weekly: {
        series: [
          { name: "Sales Revenue", data: [108, 110, 105, 120, 115, 125, 130] },
          { name: "Sales Volume", data: [125, 135, 145, 125, 130, 115, 140] },
          { name: "Order Value", data: [125, 130, 115, 140, 125, 135, 145] },
        ],
        categories: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      },
      Monthly: {
        series: [
          {
            name: "Sales Revenue",
            data: [108, 130, 110, 140, 130, 115, 125, 115, 125, 140, 140, 130],
          },
          {
            name: "Sales Volume",
            data: [140, 120, 125, 130, 110, 145, 135, 110, 130, 120, 130, 145],
          },
          {
            name: "Order Value",
            data: [125, 115, 128, 120, 125, 130, 135, 130, 135, 145, 120, 125],
          },
        ],
        categories: [
          "Jan",
          "Feb",
          "Mar",
          "Apr",
          "May",
          "Jun",
          "Jul",
          "Aug",
          "Sep",
          "Oct",
          "Nov",
          "Dec",
        ],
      },
      Yearly: {
        series: [
          { name: "Sales Revenue", data: [150, 175, 190, 200, 220] },
          { name: "Sales Volume", data: [240, 250, 170, 200, 210] },
          { name: "Order Value", data: [170, 200, 210, 240, 250] },
        ],
        categories: ["2019", "2020", "2021", "2022", "2023"],
      },
    };

    const initializeChartOptions = (categories: string[]) => {
      return {
        chart: {
          type: "line",
          height: 315,
          toolbar: {
            show: false,
          },
        },
        colors: ["#757DFF", "#AD63F6", "#37D80A"],
        stroke: {
          width: 3,
          curve: "straight",
          dashArray: [0, 8],
        },
        grid: {
          show: true,
          borderColor: "#ECF0FF",
        },
        dataLabels: {
          enabled: false,
        },
        xaxis: {
          categories: categories,
          axisTicks: {
            show: false,
            color: "#DDE4FF",
          },
          axisBorder: {
            show: false,
            color: "#DDE4FF",
          },
          labels: {
            show: true,
            style: {
              colors: "#8695AA",
              fontSize: "12px",
            },
          },
        },
        yaxis: {
          labels: {
            formatter: (val: number) => `$${val}K`,
            style: {
              colors: "#8695AA",
              fontSize: "12px",
            },
          },
          axisBorder: {
            show: false,
            color: "#DDE4FF",
          },
          axisTicks: {
            show: false,
            color: "#DDE4FF",
          },
        },
        tooltip: {
          y: {
            formatter: (val: number) => `${val}k`,
          },
        },
        legend: {
          show: true,
          fontSize: "12px",
          position: "bottom",
          horizontalAlign: "center",
          itemMargin: {
            horizontal: 8,
            vertical: 8,
          },
          labels: {
            colors: "#64748B",
          },
          markers: {
            size: 6,
            offsetX: -2,
            offsetY: -0.5,
            shape: "square",
          },
        },
      };
    };

    const updateTimeframe = (timeframe: Timeframe) => {
      selectedTimeframe.value = timeframe;
      const data = chartData[timeframe];
      series.value = [...data.series];
      chartOptions.value = initializeChartOptions(data.categories);
    };

    onMounted(() => {
      isClient.value = true;
      updateTimeframe(selectedTimeframe.value);
    });

    return {
      isClient,
      series,
      chartOptions,
      selectedTimeframe,
      timeframes,
      updateTimeframe,
    };
  },
});
</script>

<style lang="scss" scoped>
.sa-gross-revenue-card {
  .v-card-header {
    .trezo-card-title {
      h3 {
        font-size: 32px;
      }
      .revenue {
        gap: 10px;
        margin: {
          top: 9px;
          bottom: 10px;
        }
      }
      .trezo-status-badge {
        border-radius: 30px;
        padding: {
          left: 11px;
          right: 11px;
        }
      }
      .text-xs {
        font-size: 12px;
      }
    }
  }

  .trezo-card-content {
    .chart {
      margin: {
        top: -18px;
        left: -14px;
        bottom: -18px;
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .sa-gross-revenue-card {
    .v-card-header {
      .trezo-card-title {
        h3 {
          font-size: 26px;
        }
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .sa-gross-revenue-card {
    .v-card-header {
      .trezo-card-title {
        h3 {
          font-size: 28px;
        }
      }
    }
  }
}
</style>
