// svelte-bootstrap/src/routes/dashboard/lms/+page.svelte
<script>
	import Courses from '$lib/components/Dashboard/LMS/Courses.svelte';
	import CoursesSales from '$lib/components/Dashboard/LMS/CoursesSales.svelte';
	import EnrolledByCountries from '$lib/components/Dashboard/LMS/EnrolledByCountries.svelte';
	import GroupLessons from '$lib/components/Dashboard/LMS/GroupLessons.svelte';
	import InterestedTopics from '$lib/components/Dashboard/LMS/InterestedTopics.svelte';
	import StudentsProgress from '$lib/components/Dashboard/LMS/StudentsProgress.svelte';
	import TimeSpent from '$lib/components/Dashboard/LMS/TimeSpent.svelte';
	import TopCourses from '$lib/components/Dashboard/LMS/TopCourses.svelte';
	import TopInstructors from '$lib/components/Dashboard/LMS/TopInstructors.svelte';
	import TotalCourses from '$lib/components/Dashboard/LMS/TotalCourses.svelte';
	import TotalEnrolled from '$lib/components/Dashboard/LMS/TotalEnrolled.svelte';
	import TotalMentors from '$lib/components/Dashboard/LMS/TotalMentors.svelte';
	import Welcome from '$lib/components/Dashboard/LMS/Welcome.svelte';
</script>

<svelte:head>
	<title>LMS | Trezo - Svelte & Bootsrap 5 Admin Dashboard Template</title>
</svelte:head>

<div class="row justify-content-center">
	<div class="col-xxl-6">
		<Welcome />
	</div>
	<div class="col-xxl-6">
		<div class="row justify-content-center">
			<TotalCourses />
			<TotalEnrolled />
			<TotalMentors />
		</div>
	</div>
</div>

<div class="row justify-content-center">
	<div class="col-xxl-7 col-lg-6">
		<InterestedTopics />
	</div>
	<div class="col-xxl-5 col-lg-6">
		<TopInstructors />
	</div>
</div>

<div class="row justify-content-center">
	<StudentsProgress />
	<GroupLessons />
	<EnrolledByCountries />
</div>

<div class="card bg-white border-0 rounded-3 mb-4">
	<Courses />
</div>

<div class="row justify-content-center">
	<CoursesSales />
	<TimeSpent />
	<TopCourses />
</div>

// react-nextjs-material-ui/src/app/dashboard/lms/page.tsx
import * as React from "react";
import Grid from "@mui/material/Grid";
import Welcome from "@/components/Dashboard/LMS/Welcome";
import TotalCourses from "@/components/Dashboard/LMS/TotalCourses";
import TotalEnrolled from "@/components/Dashboard/LMS/TotalEnrolled";
import TotalMentors from "@/components/Dashboard/LMS/TotalMentors";
import StudentsInterestedTopics from "@/components/Dashboard/LMS/StudentsInterestedTopics";
import TopInstructors from "@/components/Dashboard/LMS/TopInstructors";
import StudentsProgress from "@/components/Dashboard/LMS/StudentsProgress";
import GroupLessons from "@/components/Dashboard/LMS/GroupLessons";
import EnrolledByCountries from "@/components/Dashboard/LMS/EnrolledByCountries";
import Courses from "@/components/Dashboard/LMS/Courses";
import CoursesSales from "@/components/Dashboard/LMS/CoursesSales";
import TimeSpent from "@/components/Dashboard/LMS/TimeSpent";
import OurTopCourses from "@/components/Dashboard/LMS/OurTopCourses";

export default function Page() {
  return (
    <>
      <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 6 }}>
          <Welcome />
        </Grid>

        <Grid size={{ xs: 12, sm: 4, md: 4, lg: 4, xl: 2 }}>
          <TotalCourses />
        </Grid>

        <Grid size={{ xs: 12, sm: 4, md: 4, lg: 4, xl: 2 }}>
          <TotalEnrolled />
        </Grid>

        <Grid size={{ xs: 12, sm: 4, md: 4, lg: 4, xl: 2 }}>
          <TotalMentors />
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 6, xl: 7 }}>
          <StudentsInterestedTopics />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 6, xl: 5 }}>
          <TopInstructors />
        </Grid>
      </Grid>

      <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 4 }}>
          <StudentsProgress />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 6, xl: 4 }}>
          <GroupLessons />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 6, xl: 4 }}>
          <EnrolledByCountries />
        </Grid>
      </Grid>

      <Courses />

      <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 4 }}>
          <CoursesSales />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 4 }}>
          <TimeSpent />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 4 }}>
          <OurTopCourses />
        </Grid>
      </Grid>
    </>
  );
}
