// laravel-vuetify/resources/components/Modules/Tables/BasicTable/GroupLessons.vue
<template>
    <v-card
        class="group-lessons-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Group Lessons</h5>
            <v-menu>
                <template v-slot:activator="{ props }">
                    <button
                        type="button"
                        v-bind="props"
                        class="position-relative dot-btn p-0 bg-transparent border-none"
                    >
                        <i class="ri-more-fill"></i>
                    </button>
                </template>
                <v-list class="menu-content">
                    <button type="button" class="bg-transparent border-none">
                        This Day
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Week
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Month
                    </button>
                    <button type="button" class="bg-transparent border-none">
                        This Year
                    </button>
                </v-list>
            </v-menu>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <tbody>
                        <tr v-for="item in items.slice(0, 6)" :key="item.id">
                            <td>
                                <div
                                    class="group-lesson d-flex align-items-center"
                                >
                                    <div
                                        class="users d-flex align-items-center"
                                    >
                                        <div
                                            class="rounded-circle"
                                            v-for="image in item.group.images"
                                            :key="image.id"
                                        >
                                            <v-img
                                                :src="image.image"
                                                class="rounded-circle"
                                                alt="user-image"
                                            />
                                        </div>
                                    </div>
                                    <div class="info">
                                        <span class="fw-medium d-block">
                                            {{ item.group.name }}
                                        </span>
                                        <span
                                            class="date text-body fw-medium d-block"
                                        >
                                            {{ item.group.date }}
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <a
                                    href="#"
                                    class="link-btn d-inline-block rounded-circle position-relative"
                                >
                                    <i class="material-symbols-outlined">
                                        {{ item.link }}
                                    </i>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";

import user6 from "../../../../../public/images/users/user6.jpg";
import user20 from "../../../../../public/images/users/user20.jpg";
import user21 from "../../../../../public/images/users/user21.jpg";
import user22 from "../../../../../public/images/users/user22.jpg";
import user23 from "../../../../../public/images/users/user23.jpg";
import user24 from "../../../../../public/images/users/user24.jpg";
import user25 from "../../../../../public/images/users/user25.jpg";
import user26 from "../../../../../public/images/users/user26.jpg";
import user27 from "../../../../../public/images/users/user27.jpg";
import user28 from "../../../../../public/images/users/user28.jpg";
import user29 from "../../../../../public/images/users/user29.jpg";
import user30 from "../../../../../public/images/users/user30.jpg";

export default defineComponent({
    name: "GroupLessons",
    data() {
        return {
            items: [
                {
                    id: 1,
                    group: {
                        images: [
                            {
                                id: 1,
                                image: user20,
                            },
                            {
                                id: 2,
                                image: user21,
                            },
                            {
                                id: 3,
                                image: user6,
                            },
                        ],
                        name: "Digital Marketing",
                        date: "15 March, 2024",
                    },
                    link: "arrow_outward",
                },
                {
                    id: 2,
                    group: {
                        images: [
                            {
                                id: 1,
                                image: user22,
                            },
                            {
                                id: 2,
                                image: user23,
                            },
                            {
                                id: 3,
                                image: user24,
                            },
                        ],
                        name: "Web Development",
                        date: "10 March, 2024",
                    },
                    link: "arrow_outward",
                },
                {
                    id: 3,
                    group: {
                        images: [
                            {
                                id: 1,
                                image: user25,
                            },
                            {
                                id: 2,
                                image: user26,
                            },
                            {
                                id: 3,
                                image: user27,
                            },
                        ],
                        name: "UX/UI Design",
                        date: "05 March, 2024",
                    },
                    link: "arrow_outward",
                },
                {
                    id: 4,
                    group: {
                        images: [
                            {
                                id: 1,
                                image: user28,
                            },
                            {
                                id: 2,
                                image: user29,
                            },
                            {
                                id: 3,
                                image: user30,
                            },
                        ],
                        name: "Content Writer",
                        date: "02 March, 2024",
                    },
                    link: "arrow_outward",
                },
            ],
        };
    },
});
</script>

<style lang="scss" scoped>
.group-lessons-card {
    .trezo-table-content {
        .trezo-table {
            .v-table {
                table {
                    tbody {
                        tr {
                            td {
                                padding: 18px 0 !important;
                                &:first-child {
                                    padding-left: 0;
                                    border-left-width: 0 !important;
                                }
                                &:last-child {
                                    text-align: end;
                                    padding-right: 0;
                                    border-right-width: 0 !important;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
</style>

// svelte-bootstrap/src/lib/components/Dashboard/LMS/GroupLessons.svelte
<script>
	import { cubicOut } from 'svelte/easing';
	import { onMount } from 'svelte';
	import {
		BarChartIcon,
		CalendarIcon,
		ClockIcon,
		EyeIcon,
		MoreHorizontalIcon,
		PieChartIcon,
		RotateCwIcon,
		TrashIcon
	} from 'svelte-feather-icons';

	let open = false;
	let dropdownRef;

	function fadeScale(node, { delay = 0, duration = 150, easing = cubicOut, baseScale = 0.95 }) {
		const o = +getComputedStyle(node).opacity;
		const s = baseScale;

		return {
			delay,
			duration,
			easing,
			css: (t) => `
        opacity: ${t * o};
        transform: scale(${s + (1 - s) * t});
      `
		};
	}
</script>

<div class="col-xxl-4 col-md-6">
	<div class="card bg-white border-0 rounded-3 mb-4">
		<div class="card-body p-0">
			<div class="p-4">
				<div class="d-flex justify-content-between align-items-center flex-wrap gap-3">
					<h3 class="mb-0">Group Lessons</h3>
					<div class="dropdown action-opt" bind:this={dropdownRef}>
						<button
							class="btn bg-transparent p-0"
							type="button"
							aria-label="More options"
							on:click={() => (open = !open)}
						>
							<MoreHorizontalIcon />
						</button>

						{#if open}
							<ul
								class={`dropdown-menu dropdown-menu-end bg-white border box-shadow ${open ? 'show' : ''}`}
								transition:fadeScale
							>
								<li>
									<button on:click={() => (open = !open)} class="dropdown-item">
										<ClockIcon />
										Today
									</button>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}>
										<PieChartIcon />
										Last 7 Days
									</button>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><RotateCwIcon /> Last Month</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><CalendarIcon /> Last 1 Year</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><BarChartIcon /> All Time</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><EyeIcon /> View</button
									>
								</li>
								<li>
									<button class="dropdown-item" on:click={() => (open = !open)}
										><TrashIcon /> Delete</button
									>
								</li>
							</ul>
						{/if}
					</div>
				</div>
			</div>

			<div class="default-table-area style-two top-instructors">
				<div class="table-responsive">
					<table class="table align-middle border-0">
						<tbody>
							<tr>
								<td class="pt-1">
									<div class="d-flex align-items-center">
										<div class="flex-shrink-0">
											<div class="d-flex">
												<a href="/dashboard/my-profile">
													<img
														src="/assets/images/user-30.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-31.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-32.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
											</div>
										</div>
										<a href="project-list.html" class="flex-grow-1 ms-2 position-relative top-2">
											<h6 class="mb-0 fs-14 fw-medium">Digital Marketing</h6>
											<span class="fs-12 text-body">15 March, 2024</span>
										</a>
									</div>
								</td>
								<td class="text-end pt-1">
									<a
										href="/dashboard/project-list"
										class="wh-35 d-inline-block border text-center lh-35 rounded-circle text-decoration-none hover-bg"
										aria-label="View project list"
									>
										<i class="ri-arrow-right-up-line fs-18"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="flex-shrink-0">
											<div class="d-flex">
												<a href="/dashboard/my-profile">
													<img
														src="/assets/images/user-33.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-34.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-35.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
											</div>
										</div>
										<a href="project-list.html" class="flex-grow-1 ms-2 position-relative top-2">
											<h6 class="mb-0 fs-14 fw-medium">Web Development</h6>
											<span class="fs-12 text-body">10 March, 2024</span>
										</a>
									</div>
								</td>
								<td class="text-end">
									<a
										href="/dashboard/project-list"
										class="wh-35 d-inline-block border text-center lh-35 rounded-circle text-decoration-none hover-bg"
										aria-label="View project list"
									>
										<i class="ri-arrow-right-up-line fs-18"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="flex-shrink-0">
											<div class="d-flex">
												<a href="/dashboard/my-profile">
													<img
														src="/assets/images/user-36.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-37.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-38.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
											</div>
										</div>
										<a href="project-list.html" class="flex-grow-1 ms-2 position-relative top-2">
											<h6 class="mb-0 fs-14 fw-medium">UX/UI Design</h6>
											<span class="fs-12 text-body">05 March, 2024</span>
										</a>
									</div>
								</td>
								<td class="text-end">
									<a
										href="/dashboard/project-list"
										class="wh-35 d-inline-block border text-center lh-35 rounded-circle text-decoration-none hover-bg"
										aria-label="View project list"
									>
										<i class="ri-arrow-right-up-line fs-18"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="flex-shrink-0">
											<div class="d-flex">
												<a href="/dashboard/my-profile">
													<img
														src="/assets/images/user-39.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-40.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-41.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
											</div>
										</div>
										<a href="project-list.html" class="flex-grow-1 ms-2 position-relative top-2">
											<h6 class="mb-0 fs-14 fw-medium">Content Writer</h6>
											<span class="fs-12 text-body">02 March, 2024</span>
										</a>
									</div>
								</td>
								<td class="text-end">
									<a
										href="/dashboard/project-list"
										class="wh-35 d-inline-block border text-center lh-35 rounded-circle text-decoration-none hover-bg"
										aria-label="View project list"
									>
										<i class="ri-arrow-right-up-line fs-18"></i>
									</a>
								</td>
							</tr>
							<tr>
								<td>
									<div class="d-flex align-items-center">
										<div class="flex-shrink-0">
											<div class="d-flex">
												<a href="/dashboard/my-profile">
													<img
														src="/assets/images/user-25.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-28.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
												<a href="/dashboard/my-profile" class="ms-m-20">
													<img
														src="/assets/images/user-31.jpg"
														class="wh-44 rounded-circle border border-2 border-color-white"
														alt="user"
													/>
												</a>
											</div>
										</div>
										<a href="project-list.html" class="flex-grow-1 ms-2 position-relative top-2">
											<h6 class="mb-0 fs-14 fw-medium">Wordpress</h6>
											<span class="fs-12 text-body">07 March, 2024</span>
										</a>
									</div>
								</td>
								<td class="text-end">
									<a
										href="/dashboard/project-list"
										class="wh-35 d-inline-block border text-center lh-35 rounded-circle text-decoration-none hover-bg"
										aria-label="View project list"
									>
										<i class="ri-arrow-right-up-line fs-18"></i>
									</a>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>

			<div class="p-4">
				<div
					class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap"
				>
					<span class="fs-12 fw-medium">Items per pages: 5</span>

					<div class="d-flex align-items-center">
						<span class="fs-12 fw-medium me-2">1 - 5 of 12</span>
						<nav aria-label="Page navigation example">
							<ul class="pagination mb-0 justify-content-center">
								<li class="page-item">
									<a class="page-link icon" href="/dashboard/lms" aria-label="Previous">
										<i class="material-symbols-outlined">keyboard_arrow_left</i>
									</a>
								</li>
								<li class="page-item">
									<a class="page-link icon" href="/dashboard/lms" aria-label="Next">
										<i class="material-symbols-outlined">keyboard_arrow_right</i>
									</a>
								</li>
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
