// react-bootstrap/src/components/Dashboard/Podcast/RecentlyPlayed.js
"use client";

import React, { useState, useRef } from "react";
import { Card, Table, Dropdown } from "react-bootstrap";

const audioData = [
  {
    id: 1,
    title: "Mastering Digital Marketing",
    author: "Sarah Johnson",
    listens: "8,200",
    image: "/images/played-1.jpg",
    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
    played: "40 min. ago",
    duration: "45:30",
  },
  {
    id: 2,
    title: "Content Marketing Essentials",
    author: "Tom Richards",
    listens: "9,500",
    image: "/images/played-2.jpg",
    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
    played: "1 h. ago",
    duration: "25:50",
  },
  {
    id: 3,
    title: "Social Media Trends for 2024",
    author: "David Chen",
    listens: "7,400",
    image: "/images/played-3.jpg",
    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
    played: "1 day ago",
    duration: "30:20",
  },
  {
    id: 4,
    title: "Building Brand Loyalty",
    author: "Michael Young",
    listens: "10,200",
    image: "/images/played-4.jpg",
    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
    played: "2 days ago",
    duration: "15:35",
  },
  {
    id: 5,
    title: "Content Creation Techniques",
    author: "Lisa Kim",
    listens: "9,300",
    image: "/images/played-5.jpg",
    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
    played: "3 days ago",
    duration: "18:45",
  },
  {
    id: 6,
    title: "The Future of AI in Marketing",
    author: "Tom Richards",
    listens: "6,300",
    image: "/images/played-6.jpg",
    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
    played: "4 days ago",
    duration: "22:15",
  },
];

const RecentlyPlayed = () => {
  const [playingTrack, setPlayingTrack] = useState(null);
  const [favorites, setFavorites] = useState({});
  const audioRefs = useRef({});

  // Toggle play/pause for tracks
  const handlePlayPause = (id, audioSrc) => {
    if (playingTrack !== null && playingTrack !== id) {
      audioRefs.current[playingTrack]?.pause();
    }

    if (!audioRefs.current[id]) {
      audioRefs.current[id] = new Audio(audioSrc);
    }

    if (playingTrack === id) {
      audioRefs.current[id].pause();
      setPlayingTrack(null);
    } else {
      audioRefs.current[id].play();
      setPlayingTrack(id);
    }
  };

  // Toggle favorite (like/unlike)
  const toggleFavorite = (id) => {
    setFavorites((prevFavorites) => ({
      ...prevFavorites,
      [id]: !prevFavorites[id], // Toggle state
    }));
  };

  return (
    <>
      <Card
        className="custom-shadow rounded-3 bg-white border mb-4"
        style={{
          paddingBottom: "16px",
        }}
      >
        <div
          className="d-flex justify-content-between align-items-center flex-wrap gap-3 custom-padding-30 position-relative pb-3"
          style={{
            top: "-5px",
          }}
        >
          <h3 className="mb-0 fs-18 fw-semibold">Recently Played</h3>
          <button
            className="bg-transparent border-0 p-0 d-flex align-items-center text-decoration-none position-relative right-for-rtl text-body"
            style={{
              right: "-8px",
            }}
          >
            <span>View All</span>
            <i className="ri-arrow-right-s-line fs-24 position-relative top-1 lh-1 text-body"></i>
          </button>
        </div>

        <div className="default-table-area style-three recently-played">
          <div className="table-responsive">
            <Table className="align-middle border-0">
              <tbody>
                {audioData.map((track) => (
                  <tr key={track.id}>
                    <td>
                      <div className="d-flex">
                        <button
                          className="p-0 border-0 bg-transparent me-3"
                          onClick={() =>
                            handlePlayPause(track.id, track.audioSrc)
                          }
                        >
                          {playingTrack === track.id ? (
                            <i
                              className="ri-pause-large-fill text-primary"
                              style={{ fontSize: "24px" }}
                            ></i>
                          ) : (
                            <i
                              className="ri-play-large-fill text-primary"
                              style={{ fontSize: "24px" }}
                            ></i>
                          )}
                        </button>

                        <div className="d-flex align-items-center gap-2">
                          <div className="flex-shrink-0">
                            <img
                              src={track.image}
                              className="rounded-1"
                              alt="played"
                              width={34}
                              height={34}
                            />
                          </div>
                          <div className="flex-grow-1 ms-10">
                            <h4 className="fs-14 fw-medium mb-0">
                              {track.title}
                            </h4>
                            <span className="fs-12 text-body fw-normal">
                              {track.author}
                            </span>
                          </div>
                        </div>
                      </div>
                    </td>

                    <td>
                      <span className="d-block fs-14 fw-normal text-body">
                        Played {track.played}
                      </span>
                    </td>

                    <td>
                      <div className="d-flex align-items-center gap-2">
                        <i className="ri-customer-service-line text-primary fs-18"></i>
                        <span className="d-block fs-14 fw-normal text-body ms-10">
                          {track.listens}
                        </span>
                      </div>
                    </td>

                    <td>
                      <button
                        className="favorite-button border-0 text-body-color-60 fs-14 bg-transparent p-0"
                        onClick={() => toggleFavorite(track.id)}
                      >
                        {favorites[track.id] ? (
                          <i className="ri-heart-fill fs-20 text-primary"></i>
                        ) : (
                          <i className="ri-heart-line fs-20 text-body"></i>
                        )}
                      </button>
                    </td>
                    <td>
                      <span className="text-body">{track.duration}</span>
                    </td>
                    <td>
                      <Dropdown className="action-opt">
                        <Dropdown.Toggle
                          variant="secondary"
                          id="dropdown-basic"
                          className="bg-transparent p-0"
                        >
                          <i className="material-symbols-outlined">
                            more_horiz
                          </i>
                        </Dropdown.Toggle>

                        <Dropdown.Menu className="bg-white border box-shadow">
                          <Dropdown.Item href="#">
                            <i className="material-symbols-outlined">add</i>
                            Add To Playlist
                          </Dropdown.Item>
                          <Dropdown.Item href="#">
                            <i className="material-symbols-outlined">
                              description
                            </i>
                            Go To Album
                          </Dropdown.Item>

                          <Dropdown.Item href="#">
                            <i className="material-symbols-outlined">
                              volume_up
                            </i>
                            View Credits
                          </Dropdown.Item>
                        </Dropdown.Menu>
                      </Dropdown>
                    </td>
                  </tr>
                ))}
              </tbody>
            </Table>
          </div>
        </div>
      </Card>
    </>
  );
};

export default RecentlyPlayed;

// laravel-vuetify/resources/components/Dashboard/Podcast/RecentlyPlayed.vue
<template>
    <v-card
        class="recently-played-card trezo-card custom-shadow rounded-3 bg-white border p-0"
        style="padding-bottom: 16px"
    >
        <div class="v-card-header mb-0" style="padding: 20px 25px">
            <h3 class="mb-0 fs-18 fw-semibold">Recently Played</h3>
            <button
                class="bg-transparent border-0 p-0 d-flex align-items-center text-decoration-none position-relative right-for-rtl text-body"
                style="right: -8px"
            >
                <span>View All</span>
                <i
                    class="ri-arrow-right-s-line fs-24 position-relative top-1 lh-1 text-body"
                ></i>
            </button>
        </div>

        <div class="default-table-area style-three recently-played pb-20">
            <div class="table-responsive">
                <table class="table align-middle border-0">
                    <tbody>
                        <tr
                            v-for="(item, index) in recentlyPlayed"
                            :key="index"
                        >
                            <td class="border-bottom">
                                <div class="d-flex">
                                    <button
                                        class="p-0 border-0 bg-transparent me-3"
                                        @click="togglePlayback(index)"
                                    >
                                        <audio
                                            ref="audioRefs"
                                            class="track"
                                            :src="item.audioSrc"
                                            type="audio/mpeg"
                                        />
                                        <div class="player-container">
                                            <div
                                                :class="{
                                                    'play-pause': true,
                                                    pause: isPlaying === index,
                                                    play: isPlaying !== index,
                                                }"
                                            >
                                                {{
                                                    isPlaying === index
                                                        ? "Pause"
                                                        : "Play"
                                                }}
                                            </div>
                                        </div>
                                    </button>
                                    <div class="d-flex align-items-center">
                                        <div class="flex-shrink-0">
                                            <v-img
                                                :src="item.imageSrc"
                                                style="
                                                    width: 34px;
                                                    height: 34px;
                                                "
                                                class="rounded-1"
                                                :alt="item.title"
                                            />
                                        </div>
                                        <div class="flex-grow-1 ms-10">
                                            <h4 class="fs-14 fw-medium mb-0">
                                                {{ item.title }}
                                            </h4>
                                            <span
                                                class="fs-12 text-body fw-normal"
                                            >
                                                {{ item.artist }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td class="border-bottom">
                                <span class="d-block fs-14 fw-normal text-body">
                                    {{ item.timePlayed }}
                                </span>
                            </td>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <i
                                        class="ri-customer-service-line fs-18"
                                    ></i>
                                    <span
                                        class="d-block fs-14 fw-normal text-body ms-10"
                                    >
                                        {{ item.playCount.toLocaleString() }}
                                    </span>
                                </div>
                            </td>
                            <td class="border-bottom">
                                <button
                                    class="favorite-button border-0 text-body-color-60 fs-14 bg-transparent p-0"
                                >
                                    <span
                                        class="favorite-icon position-relative"
                                    >
                                        <i class="ri-heart-line fs-20"></i>
                                        <i
                                            class="ri-heart-fill fs-20 position-absolute top-50 start-50 translate-middle text-primary"
                                        ></i>
                                    </span>
                                </button>
                            </td>
                            <td class="border-bottom">
                                <span class="text-body">{{
                                    item.duration
                                }}</span>
                            </td>
                            <td class="border-bottom">
                                <div class="dropdown action-opt">
                                    <v-menu>
                                        <template v-slot:activator="{ props }">
                                            <button
                                                type="button"
                                                v-bind="props"
                                                class="position-relative dot-btn p-0 bg-transparent text-body border-none"
                                            >
                                                <i
                                                    data-feather="more-horizontal"
                                                ></i>
                                            </button>
                                        </template>
                                        <v-list class="menu-content">
                                            <button
                                                type="button"
                                                class="bg-transparent border-none"
                                            >
                                                Add To Playlist
                                            </button>
                                            <button
                                                type="button"
                                                class="bg-transparent border-none"
                                            >
                                                Go To Album
                                            </button>
                                            <button
                                                type="button"
                                                class="bg-transparent border-none"
                                            >
                                                View Credits
                                            </button>
                                        </v-list>
                                    </v-menu>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref, onMounted } from "vue";
import feather from "feather-icons";

import played1 from "../../../../public/images/played-1.jpg";
import played2 from "../../../../public/images/played-2.jpg";
import played3 from "../../../../public/images/played-3.jpg";
import played4 from "../../../../public/images/played-4.jpg";
import played5 from "../../../../public/images/played-5.jpg";
import played6 from "../../../../public/images/played-6.jpg";

export default defineComponent({
    name: "RecentlyPlayed",
    data() {
        return {
            recentlyPlayed: [
                {
                    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
                    imageSrc: played1,
                    title: "Mastering Digital Marketing",
                    artist: "Sarah Johnson",
                    timePlayed: "Played 40 min. ago",
                    playCount: 8200,
                    duration: "45:30",
                },
                {
                    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
                    imageSrc: played2,
                    title: "Content Marketing Essentials",
                    artist: "Tom Richards",
                    timePlayed: "Played 1 h. ago",
                    playCount: 9500,
                    duration: "25:50",
                },
                {
                    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
                    imageSrc: played3,
                    title: "Social Media Trends for 2024",
                    artist: "David Chen",
                    timePlayed: "Played 1 day ago",
                    playCount: 7400,
                    duration: "30:20",
                },
                {
                    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
                    imageSrc: played4,
                    title: "Building Brand Loyalty",
                    artist: "Michael Young",
                    timePlayed: "Played 2 days ago",
                    playCount: 10200,
                    duration: "15:35",
                },
                {
                    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
                    imageSrc: played5,
                    title: "Content Creation Techniques",
                    artist: "Lisa Kim",
                    timePlayed: "Played 3 days ago",
                    playCount: 9300,
                    duration: "20:10",
                },
                {
                    audioSrc: "https://cldup.com/qR72ozoaiQ.mp3",
                    imageSrc: played6,
                    title: "The Future of AI in Marketing",
                    artist: "Tom Richards",
                    timePlayed: "Played 4 days ago",
                    playCount: 6300,
                    duration: "22:15",
                },
            ],
        };
    },

    setup() {
        const audioRefs = ref([]);
        const isPlaying = ref(null);

        const togglePlayback = (index) => {
            const audio = audioRefs.value[index];
            if (!audio) return;

            if (isPlaying.value === index) {
                audio.pause();
                isPlaying.value = null;
            } else {
                audioRefs.value.forEach((otherAudio, otherIndex) => {
                    if (otherIndex !== index) {
                        otherAudio.pause();
                        otherAudio
                            .closest("button")
                            ?.querySelector(".play-pause")
                            ?.classList.add("play");
                    }
                });
                audio.play();
                isPlaying.value = index;
            }
        };

        onMounted(() => {
            feather.replace();
        });

        return {
            audioRefs,
            isPlaying,
            togglePlayback,
        };
    },
});
</script>

<style lang="scss" scoped>
.v-card {
    &.trezo-card {
        border: 1px solid var(--borderColor) !important;
    }
}
.ri-customer-service-line {
    color: var(--secondaryColor) !important;
}
</style>
