// svelte-bootstrap/src/routes/dashboard/help-desk/+page.svelte
<script>
	import Agents from '$lib/components/Dashboard/HelpDesk/Agents.svelte';
	import Congratulation from '$lib/components/Dashboard/HelpDesk/Congratulation.svelte';
	import CustomerRatings from '$lib/components/Dashboard/HelpDesk/CustomerRatings.svelte';
	import CustomerSatisfaction from '$lib/components/Dashboard/HelpDesk/CustomerSatisfaction.svelte';
	import ResponseTime from '$lib/components/Dashboard/HelpDesk/ResponseTime.svelte';
	import SolvedTickets from '$lib/components/Dashboard/HelpDesk/SolvedTickets.svelte';
	import SupportOverview from '$lib/components/Dashboard/HelpDesk/SupportOverview.svelte';
	import TicketDue from '$lib/components/Dashboard/HelpDesk/TicketDue.svelte';
	import TicketOpen from '$lib/components/Dashboard/HelpDesk/TicketOpen.svelte';
	import TicketProgress from '$lib/components/Dashboard/HelpDesk/TicketProgress.svelte';
	import TicketResolved from '$lib/components/Dashboard/HelpDesk/TicketResolved.svelte';
	import TicketStatus from '$lib/components/Dashboard/HelpDesk/TicketStatus.svelte';
	import TicketsWeekly from '$lib/components/Dashboard/HelpDesk/TicketsWeekly.svelte';
	import ToDoList from '$lib/components/Dashboard/HelpDesk/ToDoList.svelte';
</script>

<svelte:head>
	<title>Help Desk | Trezo - Svelte & Bootsrap 5 Admin Dashboard Template</title>
</svelte:head>

<div class="row justify-content-center">
	<div class="col-lg-4">
		<Congratulation />
		<div class="row justify-content-center">
			<TicketResolved />
			<TicketProgress />
			<TicketDue />
			<TicketOpen />
		</div>
	</div>
	<div class="col-lg-8">
		<div class="row mb-4">
			<TicketStatus />
			<TicketsWeekly />
		</div>
		<div class="row">
			<CustomerSatisfaction />
			<ResponseTime />
		</div>
	</div>
</div>

<div class="card bg-white border-0 rounded-3 mb-4">
	<Agents />
</div>

<div class="row justify-content-center">
	<SolvedTickets />
	<CustomerRatings />
</div>

<div class="row justify-content-center">
	<ToDoList />
	<SupportOverview />
</div>

// react-bootstrap/src/pages/dashboard/HelpDesk.js
import React from "react";
import { Row, Col } from "react-bootstrap";
import Congratulations from "../../components/Dashboard/HelpDesk/Congratulations";
import TicketsResolved from "../../components/Dashboard/HelpDesk/TicketsResolved";
import TicketsInProgress from "../../components/Dashboard/HelpDesk/TicketsInProgress";
import TicketsDue from "../../components/Dashboard/HelpDesk/TicketsDue";
import TicketsNewOpen from "../../components/Dashboard/HelpDesk/TicketsNewOpen";
import TicketsStatus from "../../components/Dashboard/HelpDesk/TicketsStatus";
import CustomerSatisfaction from "../../components/Dashboard/HelpDesk/CustomerSatisfaction";
import ResponseTime from "../../components/Dashboard/HelpDesk/ResponseTime";
import PerformanceOfAgents from "../../components/Dashboard/HelpDesk/PerformanceOfAgents";
import NewTicketsSolvedTickets from "../../components/Dashboard/HelpDesk/NewTicketsSolvedTickets";
import RecentCustomerRatings from "../../components/Dashboard/HelpDesk/RecentCustomerRatings";
import ToDoList from "../../components/Dashboard/HelpDesk/ToDoList";
import SupportOverview from "../../components/Dashboard/HelpDesk/SupportOverview";

const HelpDesk = () => {
  return (
    <>
      <Row className="justify-content-center">
        <Col xs={12} sm={12} md={12} lg={4} xl={4} xxl={4}>
          <Congratulations />

          <Row>
            <Col xs={12} sm={6} md={6} lg={12} xl={12} xxl={6}>
              <TicketsResolved />
            </Col>

            <Col xs={12} sm={6} md={6} lg={12} xl={12} xxl={6}>
              <TicketsInProgress />
            </Col>

            <Col xs={12} sm={6} md={6} lg={12} xl={12} xxl={6}>
              <TicketsDue />
            </Col>

            <Col xs={12} sm={6} md={6} lg={12} xl={12} xxl={6}>
              <TicketsNewOpen />
            </Col>
          </Row>
        </Col>

        <Col xs={12} sm={12} md={12} lg={8} xl={8} xxl={8}>
          <TicketsStatus />

          <Row>
            <Col xs={12} sm={6} lg={12} xl={12} xxl={6}>
              <CustomerSatisfaction />
            </Col>

            <Col xs={12} sm={6} lg={12} xl={12} xxl={6}>
              <ResponseTime />
            </Col>
          </Row>
        </Col>
      </Row>

      <PerformanceOfAgents />

      <Row className="justify-content-center">
        <Col xs={12} lg={6} xl={6} xxl={7}>
          <NewTicketsSolvedTickets />
        </Col>

        <Col xs={12} lg={6} xl={6} xxl={5}>
          <RecentCustomerRatings />
        </Col>
      </Row>

      <Row className="justify-content-center">
        <Col xs={12} md={12} lg={12} xl={12} xxl={8}>
          <ToDoList />
        </Col>

        <Col xs={12} md={12} lg={12} xl={12} xxl={4}>
          <SupportOverview />
        </Col>
      </Row>
    </>
  );
};

export default HelpDesk;
