// react-bootstrap/src/components/Dashboard/CryptoTrader/RecentTransactions.js
"use client";

import React, { useState } from "react";
import { Card, Table, Dropdown } from "react-bootstrap";

const RecentTransactions = () => {
  // Sample transaction data
  const transactionsData = [
    {
      id: 1,
      date: "2025-10-31",
      asset: "Bitcoin",
      type: "Buy",
      amount: "0.5 BTC",
      price: "$34,000",
      totalValue: "$17,000",
      status: "Done",
    },
    {
      id: 2,
      date: "2025-10-30",
      asset: "Ethereum",
      type: "Sell",
      amount: "2 ETH",
      price: "$1,800",
      totalValue: "$3,600",
      status: "Done",
    },
    {
      id: 3,
      date: "2025-10-29",
      asset: "Tether",
      type: "Buy",
      amount: "$1.00",
      price: "$175",
      totalValue: "$1,750",
      status: "Failed",
    },
    {
      id: 4,
      date: "2025-10-28",
      asset: "USD Coin",
      type: "Sell",
      amount: "$0.9999",
      price: "$230",
      totalValue: "$1,150",
      status: "Done",
    },
    {
      id: 5,
      date: "2025-10-27",
      asset: "Cardano",
      type: "Buy",
      amount: "5000 ADA",
      price: "$0.07",
      totalValue: "$350",
      status: "Pending",
    },
    {
      id: 6,
      date: "2025-10-26",
      asset: "Tron",
      type: "Buy",
      amount: "142 TRX",
      price: "$0.192391",
      totalValue: "$350",
      status: "Failed",
    },
    {
      id: 7,
      date: "2025-10-25",
      asset: "Solana",
      type: "Sell",
      amount: "5 SOL",
      price: "$32.50",
      totalValue: "$162.50",
      status: "Done",
    },
    {
      id: 8,
      date: "2025-10-24",
      asset: "Polygon",
      type: "Buy",
      amount: "1000 MATIC",
      price: "$0.75",
      totalValue: "$750",
      status: "Pending",
    },
    {
      id: 9,
      date: "2025-10-23",
      asset: "Litecoin",
      type: "Buy",
      amount: "3 LTC",
      price: "$65.00",
      totalValue: "$195.00",
      status: "Done",
    },
    {
      id: 10,
      date: "2025-10-22",
      asset: "Ripple",
      type: "Sell",
      amount: "100 XRP",
      price: "$0.50",
      totalValue: "$50.00",
      status: "Pending",
    },
    {
      id: 11,
      date: "2025-10-21",
      asset: "Binance Coin",
      type: "Buy",
      amount: "1 BNB",
      price: "$220.00",
      totalValue: "$220.00",
      status: "Done",
    },
    {
      id: 12,
      date: "2025-10-20",
      asset: "Shiba Inu",
      type: "Sell",
      amount: "100000 SHIB",
      price: "$0.00001",
      totalValue: "$1.00",
      status: "Failed",
    },
  ];

  // State for pagination
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 6;

  // Calculate pagination
  const totalItems = transactionsData.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = transactionsData.slice(
    indexOfFirstItem,
    indexOfLastItem
  );

  // Change page
  const paginate = (pageNumber) => setCurrentPage(pageNumber);
  const nextPage = () =>
    setCurrentPage((prev) => Math.min(prev + 1, totalPages));
  const prevPage = () => setCurrentPage((prev) => Math.max(prev - 1, 1));

  // Get style for transaction type
  const getTypeStyle = (type) => {
    return type === "Buy"
      ? "bg-success-60 bg-opacity-25 text-success-60"
      : "bg-danger-80 bg-opacity-25 text-danger-80";
  };

  // Get style for status
  const getStatusStyle = (status) => {
    switch (status) {
      case "Done":
        return "bg-success-60 bg-opacity-25 text-success-60";
      case "Failed":
        return "bg-danger-80 bg-opacity-25 text-danger-80";
      case "Pending":
        return "bg-warning bg-opacity-25 text-warning";
      default:
        return "bg-gray-100 bg-opacity-25 text-gray-100";
    }
  };

  return (
    <>
      <Card className="bg-white border-0 rounded-3">
        <Card.Body className="p-0">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-2 p-4">
            <h3 className="mb-0">Recent Transactions</h3>

            <Dropdown className="dropdown select-dropdown">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="dropdown-toggle border text-body rounded-2 bg-transparent"
              >
                Last 30 Days <i className="ri-arrow-down-s-line"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Last 7 Days
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Last 15 Days
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Last 30 Days
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <div className="default-table-area style-two py-14 ct-recent-transactions2">
            <div className="table-responsive">
              <Table className="align-middle">
                <thead>
                  <tr>
                    <th scope="col" className="text-secondary">
                      Date
                    </th>
                    <th scope="col" className="text-secondary">
                      Asset
                    </th>
                    <th scope="col" className="text-secondary">
                      Type
                    </th>
                    <th scope="col" className="text-secondary">
                      Amount
                    </th>
                    <th scope="col" className="text-secondary">
                      Price
                    </th>
                    <th scope="col" className="text-secondary">
                      Total Value{" "}
                    </th>
                    <th scope="col" className="text-secondary">
                      Status
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {currentItems.map((transaction) => (
                    <tr key={transaction.id}>
                      <td>{transaction.date}</td>

                      <td className="fw-medium">{transaction.asset}</td>

                      <td>
                        <span
                          className={`d-inline-block ${getTypeStyle(
                            transaction.type
                          )} rounded-1 fs-12 fw-medium`}
                          style={{ padding: "2px 8px" }}
                        >
                          {transaction.type}
                        </span>
                      </td>

                      <td>{transaction.amount}</td>

                      <td>{transaction.price}</td>

                      <td>{transaction.totalValue}</td>

                      <td>
                        <span
                          className={`d-inline-block ${getStatusStyle(
                            transaction.status
                          )} rounded-1 fs-12 fw-medium`}
                          style={{ padding: "2px 8px" }}
                        >
                          {transaction.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            </div>

            <div
              className="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap p-4"
              style={{
                paddingTop: "15px !important",
              }}
            >
              <span className="fs-13">
                Showing {indexOfFirstItem + 1}-
                {Math.min(indexOfLastItem, totalItems)} of {totalItems} results
              </span>

              <nav aria-label="Page navigation example">
                <ul className="pagination mb-0 justify-content-center">
                  <li className="page-item">
                    <button
                      className="page-link icon hover-bg"
                      aria-label="Previous"
                      onClick={prevPage}
                      disabled={currentPage === 1}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_left
                      </i>
                    </button>
                  </li>

                  {Array.from({ length: totalPages }, (_, i) => i + 1).map(
                    (number) => (
                      <li key={number} className="page-item">
                        <button
                          className={`page-link ${
                            currentPage === number ? "active" : ""
                          }`}
                          onClick={() => paginate(number)}
                        >
                          {number}
                        </button>
                      </li>
                    )
                  )}

                  <li className="page-item">
                    <button
                      className="page-link icon hover-bg"
                      aria-label="Next"
                      onClick={nextPage}
                      disabled={currentPage === totalPages}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_right
                      </i>
                    </button>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default RecentTransactions;

// vuejs-vuetify/src/components/Dashboard/CryptoTrader/RecentTransactions.vue
<template>
  <v-card
    class="trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Recent Transactions</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius"
          >
            {{ timeRange }}
          </button>
        </template>
        <v-list class="menu-content">
          <v-list-item v-for="option in timeOptions" :key="option">
            <v-list-item-title
              @click="changeTimeRange(option)"
              style="cursor: pointer"
            >
              {{ option }}
            </v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="table-style-two">
        <div class="basic-table table-responsive">
          <table class="table mb-0" border="0" cellspacing="0" cellpadding="0">
            <thead>
              <tr>
                <th scope="col" class="fw-medium">Date</th>
                <th scope="col" class="fw-medium">Asset</th>
                <th scope="col" class="fw-medium">Type</th>
                <th scope="col" class="fw-medium">Amount</th>
                <th scope="col" class="fw-medium">Price</th>
                <th scope="col" class="fw-medium">Total Value</th>
                <th scope="col" class="fw-medium">Status</th>
              </tr>
            </thead>

            <tbody>
              <tr
                v-for="transaction in paginatedTransactions"
                :key="transaction.id"
              >
                <td>{{ formatDate(transaction.date) }}</td>
                <td class="fw-medium">{{ transaction.asset }}</td>
                <td>
                  <span
                    :class="[
                      'trezo-badge',
                      transaction.type === 'Buy' ? 'finished' : 'rejected',
                    ]"
                  >
                    {{ transaction.type }}
                  </span>
                </td>
                <td>{{ transaction.amount }} {{ transaction.assetSymbol }}</td>
                <td>${{ formatNumber(transaction.price) }}</td>
                <td>${{ formatNumber(transaction.totalValue) }}</td>
                <td>
                  <span
                    class="trezo-badge"
                    :class="getStatusClass(transaction.status)"
                  >
                    {{ transaction.status }}
                  </span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div
          class="trezo-card-pagination d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
        >
          <span class="fs-12 fw-medium">
            Showing {{ showingFrom }}-{{ showingTo }} of
            {{ filteredTransactions.length }} results
          </span>

          <nav aria-label="Page navigation example">
            <ul class="pagination mb-0 justify-content-center">
              <li class="page-item" :class="{ disabled: currentPage === 1 }">
                <button
                  class="page-link icon"
                  aria-label="Previous"
                  @click="prevPage"
                  :disabled="currentPage === 1"
                >
                  <i class="material-symbols-outlined">keyboard_arrow_left</i>
                </button>
              </li>
              <li class="page-item" v-for="page in totalPages" :key="page">
                <button
                  class="page-link"
                  :class="{ active: currentPage === page }"
                  @click="goToPage(page)"
                >
                  {{ page }}
                </button>
              </li>
              <li
                class="page-item"
                :class="{ disabled: currentPage === totalPages }"
              >
                <button
                  class="page-link icon"
                  aria-label="Next"
                  @click="nextPage"
                  :disabled="currentPage === totalPages"
                >
                  <i class="material-symbols-outlined">keyboard_arrow_right</i>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Transaction {
  id: number;
  date: Date;
  asset: string;
  assetSymbol: string;
  type: "Buy" | "Sell";
  amount: number;
  price: number;
  totalValue: number;
  status: "Done" | "Pending" | "Failed";
}

export default defineComponent({
  name: "RecentTransactions",
  data() {
    return {
      timeRange: "Last 30 Days",
      timeOptions: [
        "Last 7 Days",
        "Last 15 Days",
        "Last 30 Days",
        "Last 90 Days",
      ],
      transactions: [] as Transaction[],
      itemsPerPage: 6,
      currentPage: 1,
    };
  },
  computed: {
    filteredTransactions(): Transaction[] {
      const days = parseInt(this.timeRange.split(" ")[1]);
      const cutoffDate = new Date();
      cutoffDate.setDate(cutoffDate.getDate() - days);

      return this.transactions
        .filter((tx) => new Date(tx.date) >= cutoffDate)
        .sort(
          (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
        );
    },
    paginatedTransactions(): Transaction[] {
      const start = (this.currentPage - 1) * this.itemsPerPage;
      const end = start + this.itemsPerPage;
      return this.filteredTransactions.slice(start, end);
    },
    totalPages(): number {
      return Math.ceil(this.filteredTransactions.length / this.itemsPerPage);
    },
    showingFrom(): number {
      return (this.currentPage - 1) * this.itemsPerPage + 1;
    },
    showingTo(): number {
      const end = this.currentPage * this.itemsPerPage;
      return end > this.filteredTransactions.length
        ? this.filteredTransactions.length
        : end;
    },
  },
  methods: {
    changeTimeRange(range: string) {
      this.timeRange = range;
      this.currentPage = 1; // Reset to first page when changing time range
    },
    formatDate(date: Date): string {
      return new Date(date).toISOString().split("T")[0];
    },
    formatNumber(num: number): string {
      return num.toLocaleString("en-US", {
        minimumFractionDigits: 2,
        maximumFractionDigits: 8,
      });
    },
    getStatusClass(status: string): string {
      switch (status) {
        case "Done":
          return "finished";
        case "Pending":
          return "pending";
        case "Failed":
          return "rejected";
        default:
          return "";
      }
    },
    goToPage(page: number) {
      this.currentPage = page;
    },
    prevPage() {
      if (this.currentPage > 1) {
        this.currentPage--;
      }
    },
    nextPage() {
      if (this.currentPage < this.totalPages) {
        this.currentPage++;
      }
    },
    generateMockTransactions(count: number): Transaction[] {
      const assets = [
        { name: "Bitcoin", symbol: "BTC" },
        { name: "Ethereum", symbol: "ETH" },
        { name: "Tether", symbol: "USDT" },
        { name: "USD Coin", symbol: "USDC" },
        { name: "Cardano", symbol: "ADA" },
        { name: "Tron", symbol: "TRX" },
        { name: "Solana", symbol: "SOL" },
        { name: "Polygon", symbol: "MATIC" },
      ];

      const types: ("Buy" | "Sell")[] = ["Buy", "Sell"];
      const statuses: ("Done" | "Pending" | "Failed")[] = [
        "Done",
        "Pending",
        "Failed",
      ];

      return Array.from({ length: count }, (_, i) => {
        const asset = assets[Math.floor(Math.random() * assets.length)];
        const type = types[Math.floor(Math.random() * types.length)];
        const price =
          type === "Buy"
            ? Math.random() * 10000 + 100
            : Math.random() * 10000 + 100;
        const amount =
          type === "Buy" ? Math.random() * 10 + 0.1 : Math.random() * 100 + 1;

        return {
          id: i + 1,
          date: new Date(Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000),
          asset: asset.name,
          assetSymbol: asset.symbol,
          type,
          amount: parseFloat(amount.toFixed(6)),
          price: parseFloat(price.toFixed(2)),
          totalValue: parseFloat((amount * price).toFixed(2)),
          status: statuses[Math.floor(Math.random() * statuses.length)],
        };
      });
    },
  },
  created() {
    // Generate mock data - in a real app, you would fetch this from an API
    this.transactions = this.generateMockTransactions(36);
  },
});
</script>
