// react-nextjs-material-ui/src/components/Dashboard/RealEstateAgent/Stats.tsx
"use client";

import React from "react";
import { Box, Typography, Card, Grid } from "@mui/material";
import Image from "next/image";

const statsData = [
  {
    title: "Total Listings",
    value: "3251",
    change: "+3.4%",
    changeType: "positive",
    image: "/images/buildings/building1.png",
  },
  {
    title: "Sales Volume",
    value: "$1.2M",
    change: "-3.2%",
    changeType: "negative",
    image: "/images/buildings/building2.png",
  },
  {
    title: "Active Deals",
    value: "1124",
    change: "+1.4%",
    changeType: "positive",
    image: "/images/buildings/building3.png",
  },
  {
    title: "Closed Deals",
    value: "2312",
    change: "-1.2%",
    changeType: "negative",
    image: "/images/buildings/building4.png",
  },
];

const Stats: React.FC = () => {
  return (
    <>
      <Box sx={{ mt: "-60px" }}>
        <Grid container columnSpacing={{ xs: 3 }}>
          {statsData.map((stat, index) => (
            <Grid size={{ xs: 12, sm: 6, md: 6, lg: 3, xl: 3 }} key={index}>
              <Card
                sx={{
                  boxShadow: "none",
                  borderRadius: "7px",
                  mb: "25px",
                  padding: { xs: "15px", sm: "20px", lg: "20px", xl: "25px" },
                }}
                className="rmui-card"
              >
                <Box
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    gap: "10px",
                  }}
                >
                  <Box>
                    <Typography sx={{ mb: "3px" }}>{stat.title}</Typography>
                    <Typography
                      variant="h4"
                      sx={{
                        fontSize: { xs: "22px", md: "24px" },
                        fontWeight: 700,
                        mb: "8px",
                      }}
                    >
                      {stat.value}
                    </Typography>
                    <Box
                      sx={{
                        border: "1px solid",
                        borderRadius: "30px",
                        backgroundColor:
                          stat.changeType === "positive"
                            ? "success.100"
                            : "error.100",
                        color:
                          stat.changeType === "positive"
                            ? "success.700"
                            : "error.700",
                        borderColor:
                          stat.changeType === "positive"
                            ? "success.300"
                            : "error.300",
                        lineHeight: 1,
                        fontSize: "12px",
                        display: "inline-block",
                        fontWeight: 500,
                        p: "3.5px 9px",
                        textTransform: "capitalize",
                      }}
                    >
                      {stat.change}
                    </Box>
                  </Box>
                  <Box>
                    <Image
                      src={stat.image}
                      alt={`${stat.title} image`}
                      width={60}
                      height={60}
                    />
                  </Box>
                </Box>
              </Card>
            </Grid>
          ))}
        </Grid>
      </Box>
    </>
  );
};

export default Stats;

// nuxtjs-vuetify/components/Dashboard/RealEstateAgent/Stats.vue
<template>
  <div class="row">
    <div class="col-lg-3 col-sm-6" v-for="(stat, index) in stats" :key="index">
      <v-card
        class="stat-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
      >
        <div
          class="trezo-card-content d-flex align-items-center justify-content-between"
        >
          <div>
            <span class="d-block">
              {{ stat.title }}
            </span>
            <h3 class="lh-1">
              {{ stat.value }}
            </h3>
            <span
              class="trezo-badge with-border"
              :class="{
                finished: stat.trend > 0,
                cancelled: stat.trend <= 0,
              }"
            >
              {{ stat.trend > 0 ? "+" : "" }}{{ stat.trend }}%
            </span>
          </div>

          <div>
            <v-img :src="stat.image" :alt="'building' + (index + 1)" />
          </div>
        </div>
      </v-card>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

import image1 from "@/assets/images/building1.png";
import image2 from "@/assets/images/building2.png";
import image3 from "@/assets/images/building3.png";
import image4 from "@/assets/images/building4.png";

interface StatItem {
  title: string;
  value: string | number;
  trend: number;
  image: string;
}

export default defineComponent({
  name: "StatsDashboard",
  setup() {
    const stats: StatItem[] = [
      {
        title: "Total Listings",
        value: 3251,
        trend: 3.4,
        image: image1,
      },
      {
        title: "Sales Volume",
        value: "$1.2M",
        trend: -3.2,
        image: image2,
      },
      {
        title: "Active Deals",
        value: 1124,
        trend: 1.4,
        image: image3,
      },
      {
        title: "Closed Deals",
        value: 2312,
        trend: -1.2,
        image: image4,
      },
    ];

    return {
      stats,
    };
  },
});
</script>

<style scoped lang="scss">
.stat-card {
  .trezo-card-content {
    h3 {
      font-size: 24px;
      margin: {
        top: 6px;
        bottom: 11px;
      }
    }
    .trezo-badge {
      border-radius: 30px;
    }
  }
}
</style>
