// vuejs-bootstrap/src/components/Dashboard/Hotel/RecentBookings.vue
<template>
  <div class="recent-bookings-card card bg-white border-0 rounded-3 mb-4">
    <div class="p-25">
      <div
        class="d-flex flex-wrap gap-2 justify-content-between align-items-center mb-3 mb-4"
      >
        <h3 class="fs-18 fw-bold mb-0">Recent Bookings</h3>
        <div>
          <div
            class="d-flex align-items-center bg-gray-100 py-2 px-3 rounded-2 for-dark-digital-date"
          >
            <div>{{ formattedDate }}</div>
            <i class="ri-calendar-2-line ms-2 fs-18 lh-1"></i>
          </div>
        </div>
      </div>

      <div class="calendar">
        <div class="header d-flex align-items-center justify-content-between">
          <button
            @click="previousMonth"
            class="p-0 border-0 d-flex align-items-center justify-content-center rounded-circle transition"
          >
            <i class="material-symbols-outlined">chevron_left</i>
          </button>
          <span class="fw-medium text-black">
            {{ monthNames[currentMonth] }} {{ currentYear }}
          </span>
          <button
            @click="nextMonth"
            class="p-0 border-0 d-flex align-items-center justify-content-center rounded-circle transition"
          >
            <i class="material-symbols-outlined">chevron_right</i>
          </button>
        </div>
        <div class="weekdays text-center">
          <div v-for="day in weekdays" :key="day">{{ day }}</div>
        </div>
        <div class="days text-center">
          <div
            v-for="(day, index) in daysInMonth"
            :key="index"
            class="card border-0 mx-auto text-black fw-medium border-radius"
            :class="{ 'current-day': isToday(day) }"
          >
            <span v-if="day !== null">{{ day }}</span>
            <span v-else class="blank-day">&nbsp;</span>
          </div>
        </div>
      </div>
    </div>
    <div class="p-25 pt-0 pe-0">
      <div
        class="last-child-none pe-4 recent-room-bookings scrollbar"
        style="height: 505px"
      >
        <RouterLink
          v-for="(booking, index) in bookings"
          :key="index"
          to="/hotel/room-details"
          class="mb-3 pb-3 border-bottom border-border-color child d-flex justify-content-between align-items-center flex-wrap gap-3 text-decoration-none"
        >
          <div class="d-flex align-items-center" style="gap: 15px">
            <div class="flex-shrink-0">
              <img
                :src="booking.image"
                class="rounded-1"
                style="max-width: 80px"
                alt="room"
              />
            </div>
            <div class="flex-grow-1">
              <h3 class="fs-14 fw-semibold mb-6">{{ booking.roomName }}</h3>
              <span class="d-block fs-12 mb-9 text-body">
                Booked by {{ booking.guestName }}
              </span>
              <span
                class="bg-border-color-50 fs-12 fw-medium text-primary d-inline-block rounded-1"
                style="padding: 3px 8px"
              >
                {{ formatBookingDates(booking.checkIn, booking.checkOut) }}
              </span>
            </div>
          </div>
          <i
            class="ri-arrow-right-line wh-30 d-flex d-lg-none d-xxl-flex justify-content-center align-items-center bg-border-color rounded-circle hover-bg"
          ></i>
        </RouterLink>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, onMounted, computed } from "vue";

interface Booking {
  id: number;
  roomName: string;
  guestName: string;
  checkIn: Date;
  checkOut: Date;
  image: string;
}

export default defineComponent({
  name: "RecentBookings",
  setup() {
    const currentDate = ref(new Date());
    const currentMonth = ref(currentDate.value.getMonth());
    const currentYear = ref(currentDate.value.getFullYear());
    const currentDay = ref<number>(0);
    const today = ref<{ year: number; month: number; day: number }>({
      year: 0,
      month: 0,
      day: 0,
    });
    const weekdays = ref<string[]>([
      "Sun",
      "Mon",
      "Tue",
      "Wed",
      "Thu",
      "Fri",
      "Sat",
    ]);
    const monthNames = ref<string[]>([
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ]);
    const daysInMonth = ref<(number | null)[]>([]);

    const bookings = ref<Booking[]>([
      {
        id: 1,
        roomName: "Deluxe Room - G - 3215",
        guestName: "Angela Carter",
        checkIn: new Date(2025, 11, 10),
        checkOut: new Date(2025, 11, 15),
        image: require("@/assets/images/room-5.jpg"),
      },
      {
        id: 2,
        roomName: "The Garden Suite 101",
        guestName: "Jack Smith",
        checkIn: new Date(2025, 11, 12),
        checkOut: new Date(2025, 11, 16),
        image: require("@/assets/images/room-6.jpg"),
      },
      {
        id: 3,
        roomName: "The Tranquil S-02",
        guestName: "Jennifer Anderson",
        checkIn: new Date(2025, 11, 15),
        checkOut: new Date(2025, 11, 20),
        image: require("@/assets/images/room-7.jpg"),
      },
      {
        id: 4,
        roomName: "The Queen - X - 231",
        guestName: "Robert Johnson",
        checkIn: new Date(2025, 11, 11),
        checkOut: new Date(2025, 11, 14),
        image: require("@/assets/images/room-8.jpg"),
      },
      {
        id: 5,
        roomName: "Executive Suite - A - 100",
        guestName: "Sarah Williams",
        checkIn: new Date(2025, 11, 18),
        checkOut: new Date(2025, 11, 22),
        image: require("@/assets/images/room-5.jpg"),
      },
      {
        id: 6,
        roomName: "The Garden Suite 101",
        guestName: "Jack Smith",
        checkIn: new Date(2025, 11, 12),
        checkOut: new Date(2025, 11, 16),
        image: require("@/assets/images/room-6.jpg"),
      },
      {
        id: 7,
        roomName: "The Tranquil S-02",
        guestName: "Jennifer Anderson",
        checkIn: new Date(2025, 11, 15),
        checkOut: new Date(2025, 11, 20),
        image: require("@/assets/images/room-7.jpg"),
      },
      {
        id: 8,
        roomName: "The Queen - X - 231",
        guestName: "Robert Johnson",
        checkIn: new Date(2025, 11, 11),
        checkOut: new Date(2025, 11, 14),
        image: require("@/assets/images/room-8.jpg"),
      },
    ]);

    // Initialize calendar
    const initializeCalendar = () => {
      const todayDate = new Date();
      currentMonth.value = todayDate.getMonth();
      currentYear.value = todayDate.getFullYear();
      currentDay.value = todayDate.getDate();
      today.value = {
        year: currentYear.value,
        month: currentMonth.value,
        day: currentDay.value,
      };
      generateCalendar();
    };

    // Generate calendar days
    const generateCalendar = () => {
      daysInMonth.value = [];
      const firstDay = new Date(
        currentYear.value,
        currentMonth.value,
        1
      ).getDay();
      const numberOfDays = new Date(
        currentYear.value,
        currentMonth.value + 1,
        0
      ).getDate();
      for (let i = 0; i < firstDay; i++) {
        daysInMonth.value.push(null); // Placeholder for days before the first of the month
      }
      for (let i = 1; i <= numberOfDays; i++) {
        daysInMonth.value.push(i);
      }
    };

    // Navigate to previous month
    const previousMonth = () => {
      currentMonth.value--;
      if (currentMonth.value < 0) {
        currentMonth.value = 11;
        currentYear.value--;
      }
      generateCalendar();
    };

    // Navigate to next month
    const nextMonth = () => {
      currentMonth.value++;
      if (currentMonth.value > 11) {
        currentMonth.value = 0;
        currentYear.value++;
      }
      generateCalendar();
    };

    // Check if a day is today
    const isToday = (day: number | null): boolean => {
      if (day === null) return false;
      return (
        today.value.year === currentYear.value &&
        today.value.month === currentMonth.value &&
        today.value.day === day
      );
    };

    const formattedDate = computed(() => {
      return currentDate.value.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    });

    const formatBookingDates = (checkIn: Date, checkOut: Date): string => {
      const formatOptions: Intl.DateTimeFormatOptions = {
        month: "short",
        day: "numeric",
      };
      return `${checkIn.toLocaleDateString(
        "en-US",
        formatOptions
      )} - ${checkOut.toLocaleDateString("en-US", formatOptions)}`;
    };

    // Initialize on component mount
    onMounted(() => {
      initializeCalendar();
    });

    return {
      currentMonth,
      currentYear,
      currentDay,
      today,
      weekdays,
      monthNames,
      daysInMonth,
      previousMonth,
      nextMonth,
      isToday,
      formattedDate,
      bookings,
      formatBookingDates,
    };
  },
});
</script>

<style lang="scss" scoped>
.recent-bookings-card {
  .calendar {
    .header {
      margin-bottom: 12px;

      button {
        background-color: #e6eff2;
        color: var(--blackColor);
        height: 30px;
        width: 30px;

        i {
          font-size: 22px;
        }
        &:hover {
          background-color: var(--primaryColor);
          color: var(--whiteColor);
        }
      }
    }
    .weekdays {
      margin-bottom: 10px;
      font-size: 12px;
    }
    .weekdays,
    .days {
      display: grid;
      grid-template-columns: repeat(7, 1fr);
    }
    .days {
      gap: 2px;

      div {
        width: 100%;
        height: 45px;
        cursor: pointer;
        line-height: 45px;
        background-color: #e6eff2;

        &:has(.blank-day) {
          background-color: transparent;
        }
      }
      .current-day {
        line-height: initial;

        span {
          background-color: var(--primaryColor);
          color: var(--whiteColor);
          display: inline-block;
          border-radius: 50%;
          line-height: 30px;
          height: 30px;
          width: 30px;
          margin: auto;
        }
      }
    }
  }
}
</style>

// angular-tailwindcss/src/app/dashboard/hotel/recent-bookings/recent-bookings.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgClass, NgFor, NgIf } from '@angular/common';

@Component({
    selector: 'app-recent-bookings',
    imports: [NgFor, NgIf, NgClass, RouterLink],
    templateUrl: './recent-bookings.component.html',
    styleUrl: './recent-bookings.component.scss'
})
export class RecentBookingsComponent {

    constructor() {
        this.formattedDate = this.formatDate();
    }

    // Current Day
    formattedDate: string;
    formatDate(): string {
        const today = new Date();
        const options: Intl.DateTimeFormatOptions = { month: 'long', day: 'numeric', year: 'numeric' };
        return today.toLocaleDateString('en-US', options); // Format: "December 10, 2025"
    }

    // Calendar
    currentMonth!: number;
    currentYear!: number;
    currentDay!: number; // Current day
    today!: { year: number; month: number; day: number }; // Today's date
    weekdays: string[] = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    monthNames: string[] = [
        'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'
    ];
    daysInMonth: (number | null)[] = []; // Allow null values
    ngOnInit() {
        const today = new Date();
        this.currentMonth = today.getMonth(); // 0-based index
        this.currentYear = today.getFullYear();
        this.currentDay = today.getDate(); // Get current day of the month
        this.today = {
            year: this.currentYear,
            month: this.currentMonth,
            day: this.currentDay
        };
        this.generateCalendar();
    }
    generateCalendar() {
        this.daysInMonth = [];
        const firstDay = new Date(this.currentYear, this.currentMonth, 1).getDay();
        const numberOfDays = new Date(this.currentYear, this.currentMonth + 1, 0).getDate();
        for (let i = 0; i < firstDay; i++) {
            this.daysInMonth.push(null); // Placeholder for days before the first of the month
        }
        for (let i = 1; i <= numberOfDays; i++) {
            this.daysInMonth.push(i);
        }
    }
    previousMonth() {
        this.currentMonth--;
        if (this.currentMonth < 0) {
            this.currentMonth = 11;
            this.currentYear--;
        }
        this.generateCalendar();
    }
    nextMonth() {
        this.currentMonth++;
        if (this.currentMonth > 11) {
            this.currentMonth = 0;
            this.currentYear++;
        }
        this.generateCalendar();
    }
    isToday(day: number | null): boolean {
        if (day === null) return false;
        return (
            this.today.year === this.currentYear &&
            this.today.month === this.currentMonth &&
            this.today.day === day
        );
    }

}
<div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-header mb-[20px] md:mb-[25px] sm:flex items-center justify-between">
        <div class="trezo-card-title">
            <h5 class="!mb-0">
                Recent Bookings
            </h5>
        </div>
        <div class="trezo-card-subtitle mt-[12px] sm:mt-0">
            <div class="inline-block py-[6.5px] px-[19px] bg-[#f5f7f8] dark:bg-[#0a0e19] rounded-md">
                <span class="inline-block relative ltr:pr-[22px] rtl:pl-[22px]">
                    <span>
                        {{ formattedDate }}
                    </span>
                    <i class="ri-calendar-2-line absolute text-lg top-1/2 -translate-y-1/2 ltr:-right-[3px] rtl:-left-[3px]"></i>
                </span>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="calendar">
            <div class="header flex items-center justify-between mb-[22px]">
                <button (click)="previousMonth()" class="transition-all text-black bg-gray-100 dark:text-white dark:bg-[#172036] flex items-center justify-center rounded-full w-[30px] h-[30px] hover:bg-primary-500 hover:text-white">
                    <i class="material-symbols-outlined rtl:-scale-x-[1]">
                        chevron_left
                    </i>
                </button>
                <span class="block font-medium text-black dark:text-white">
                    {{ monthNames[currentMonth] }} {{ currentYear }}
                </span>
                <button (click)="nextMonth()" class="transition-all text-black bg-gray-100 dark:text-white dark:bg-[#172036] flex items-center justify-center rounded-full w-[30px] h-[30px] hover:bg-primary-500 hover:text-white">
                    <i class="material-symbols-outlined rtl:-scale-x-[1]">
                        chevron_right
                    </i>
                </button>
            </div>
            <div class="weekdays grid grid-cols-7 mb-[6px] text-center">
                <div class="text-black dark:text-white font-medium" *ngFor="let day of weekdays">
                    {{ day }}
                </div>
            </div>
            <div class="days grid grid-cols-7 text-center">
                <div
                    *ngFor="let day of daysInMonth"
                    class="w-[32px] h-[32px] cursor-pointer leading-[31px] rounded-full my-[6.5px] mx-auto"
                    [ngClass]="{ 'current-day': isToday(day) }"
                >
                    <span *ngIf="day !== null">
                        {{ day }}
                    </span>
                    <span *ngIf="day === null">
                        &nbsp;
                    </span> <!-- Placeholder for empty days -->
                </div>
            </div>
        </div>
        <div class="schedule-list h-[598px] overflow-y-scroll ltr:-mr-[20px] ltr:md:-mr-[25px] rtl:-ml-[20px] rtl:md:-ml-[25px] ltr:pr-[20px] ltr:md:pr-[25px] rtl:pl-[20px] rtl:md:pl-[25px] mt-[15px]">
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room1.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            Duluxe Room - G - 3215
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Angela Carter</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        10 Dec - 15 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room2.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Garden Suite 101
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Jack Smith</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        12 Dec - 16 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room3.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Tranquil S-02
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Jennifer Anderson</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        15 Dec - 20 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room4.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Queen - X - 231
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Angela Carter</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        11 Dec - 14 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room5.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Velvet - F - 32045
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Skyler White</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        11 Dec - 14 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room1.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            Duluxe Room - G - 3215
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Angela Carter</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        10 Dec - 15 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room2.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Garden Suite 101
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Jack Smith</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        12 Dec - 16 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room3.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Tranquil S-02
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Jennifer Anderson</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        15 Dec - 20 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room4.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Queen - X - 231
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Angela Carter</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        11 Dec - 14 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
            <div class="relative flex items-center gap-[15px] mt-[15px] pt-[15px] border-t border-gray-100 dark:border-[#172036] first:border-t-0 first:pt-0 first:mt-0">
                <a routerLink="." class="image block rounded-[4px] w-[80px]">
                    <img src="images/rooms/room5.jpg" class="rounded-[4px]" alt="room-image">
                </a>
                <div>
                    <h6 class="!font-semibold !mb-[7px]">
                        <a routerLink="." class="text-black dark:text-white hover:text-primary-500 transition-all">
                            The Velvet - F - 32045
                        </a>
                    </h6>
                    <span class="block text-xs">
                        Booked by <strong class="font-semibold">Skyler White</strong>
                    </span>
                    <span class="inline-block text-xs px-[8px] text-primary-500 bg-primary-50 dark:bg-[#15203c] py-[3px] font-medium rounded-[4px] mt-[9px]">
                        11 Dec - 14 Dec
                    </span>
                </div>
                <a routerLink="." class="flex items-center justify-center absolute ltr:right-0 rtl:left-0 top-1/2 -translate-y-1/2 w-[30px] h-[30px] rounded-full bg-gray-100 dark:bg-[#172036] transition-all hover:bg-primary-500 hover:text-white">
                    <i class="ri-arrow-right-line"></i>
                </a>
            </div>
        </div>
    </div>
</div>
