// react-nextjs-material-ui/src/components/Doctor/Appointments/TodaysAppointments.tsx
"use client";

import styles from "./AppointmentsList.module.css";
import React, { useState, FormEvent } from "react";
import {
  Card,
  Box,
  Typography,
  IconButton,
  Dialog,
  DialogTitle,
  Button,
} from "@mui/material";
import Image from "next/image";
import { styled } from "@mui/material/styles";
import ClearIcon from "@mui/icons-material/Clear";
import CloseIcon from "@mui/icons-material/Close";
import PropTypes from "prop-types";

// Modal
interface BootstrapDialogTitleProps {
  children?: React.ReactNode;
  onClose: () => void;
}

const BootstrapDialog = styled(Dialog)(({ theme }) => ({
  "& .MuiDialogContent-root": {
    padding: theme.spacing(2),
  },
  "& .MuiDialogActions-root": {
    padding: theme.spacing(1),
  },
}));

function BootstrapDialogTitle(props: BootstrapDialogTitleProps) {
  const { children, onClose, ...other } = props;

  return (
    <DialogTitle sx={{ m: 0, p: 2 }} {...other}>
      {children}
      {onClose ? (
        <IconButton
          aria-label="close"
          onClick={onClose}
          sx={{
            position: "absolute",
            right: 8,
            top: 8,
            color: (theme) => theme.palette.grey[500],
          }}
        >
          <CloseIcon />
        </IconButton>
      ) : null}
    </DialogTitle>
  );
}

BootstrapDialogTitle.propTypes = {
  children: PropTypes.node,
  onClose: PropTypes.func.isRequired,
};
// End Modal

// Define the Appointment type
interface Appointment {
  id: string;
  time: string;
  title: string;
  patientName: string;
  patientImage: string;
  status: "done" | "upcoming";
  hasNotification?: boolean;
}

// Dynamic appointment data
const appointmentsData: Appointment[] = [
  {
    id: "1",
    time: "10:00 AM",
    title: "Appointment With Cardiac Patient",
    patientName: "Jonathon Ronan",
    patientImage: "/images/users/user32.jpg",
    status: "done",
  },
  {
    id: "2",
    time: "12:00 PM",
    title: "Board Meeting With",
    patientName: "Jessy Pinkman",
    patientImage: "/images/users/user33.jpg",
    status: "done",
  },
  {
    id: "3",
    time: "02:00 PM",
    title: "Major Cardiac Surgery of the Patient",
    patientName: "Walter White",
    patientImage: "/images/users/user34.jpg",
    status: "upcoming",
    hasNotification: true,
  },
  {
    id: "4",
    time: "03:00 PM",
    title: "Appointment With Cardiac Patient",
    patientName: "Jonathon Ronan",
    patientImage: "/images/users/user32.jpg",
    status: "upcoming",
    hasNotification: true,
  },
  {
    id: "5",
    time: "04:00 PM",
    title: "Board Meeting With",
    patientName: "Jessy Pinkman",
    patientImage: "/images/users/user34.jpg",
    status: "upcoming",
    hasNotification: true,
  },
  {
    id: "6",
    time: "05:00 PM",
    title: "Major Cardiac Surgery of the Patient",
    patientName: "Walter White",
    patientImage: "/images/users/user33.jpg",
    status: "upcoming",
    hasNotification: true,
  },
];

const TodaysAppointments: React.FC = () => {
  // Modal
  const [open, setOpen] = useState(false);
  const handleClickOpen = () => {
    setOpen(true);
  };
  const handleClose = () => {
    setOpen(false);
  };
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    // const data = new FormData(event.currentTarget);
    // console.log();
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
            mb: "20px",
          }}
          className="text-black"
        >
          Today's Appointments
        </Typography>

        <Box className={styles.appointmentsList}>
          {appointmentsData.map((appointment) => (
            <Box key={appointment.id} className={styles.appointmentItem}>
              <Box className={styles.icon}>
                <Image
                  src={
                    appointment.status === "done"
                      ? "/images/icons/done.svg"
                      : "/images/icons/not-done.svg"
                  }
                  alt={appointment.status}
                  width={24}
                  height={24}
                />
              </Box>

              <Box
                sx={{
                  display: { xs: "block", md: "flex" },
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <Box>
                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      gap: "10px",
                    }}
                  >
                    <Typography className="text-000" fontWeight={600}>
                      {appointment.time}
                    </Typography>

                    {appointment.hasNotification && (
                      <Box
                        sx={{
                          position: "relative",
                          top: "-5px",
                          display: "flex",
                          gap: "10px",
                          alignItems: "center",
                        }}
                      >
                        <Button
                          type="button"
                          sx={{
                            backgroundColor: "primary.main",
                            color: "white !important",
                            minWidth: "auto",
                            borderRadius: "50%",
                            width: 25,
                            height: 25,
                          }}
                        >
                          <i className="ri-notification-2-line"></i>
                        </Button>

                        <Box
                          sx={{
                            bgcolor: "#fff",
                            color: "primary.main",
                            borderRadius: "30px",
                            fontSize: "12px",
                            padding: "0 10px",
                          }}
                        >
                          Upcoming
                        </Box>
                      </Box>
                    )}
                  </Box>

                  <Typography>{appointment.title}</Typography>

                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      gap: "10px",
                    }}
                  >
                    <Image
                      src={appointment.patientImage}
                      className="rounded-circle"
                      alt="user-image"
                      width={30}
                      height={30}
                    />
                    <Typography
                      sx={{
                        fontWeight: 600,
                        fontSize: "13px",
                        margin: "0 !important",
                      }}
                      className="text-000"
                    >
                      {appointment.patientName}
                    </Typography>
                  </Box>
                </Box>

                <Button
                  onClick={handleClickOpen}
                  type="button"
                  className={styles.btnPrimary}
                  sx={{
                    background: "#fff",
                    borderRadius: "5px",
                    padding: "5.5px 16px",
                    fontWeight: 500,
                    textTransform: "capitalize",
                    fontSize: "14px",
                  }}
                >
                  View Details
                </Button>
              </Box>

              <Box className={styles.shape}>
                <Image
                  src="/images/icons/vector.png"
                  alt="vector"
                  width={124}
                  height={35}
                />
              </Box>
            </Box>
          ))}
        </Box>
      </Card>

      {/* Modal */}
      <BootstrapDialog
        onClose={handleClose}
        aria-labelledby="customized-dialog-title"
        open={open}
        className="rmu-modal"
      >
        <Box sx={{ width: { xs: "100%", sm: "550px" } }}>
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              background: "#f6f7f9",
              padding: { xs: "15px 20px", md: "25px" },
            }}
            className="rmu-modal-header"
          >
            <Typography
              id="modal-modal-title"
              variant="h6"
              sx={{
                fontWeight: "600",
                fontSize: { xs: "16px", md: "18px" },
              }}
              className="text-black"
            >
              Schedule Details
            </Typography>

            <IconButton aria-label="remove" size="small" onClick={handleClose}>
              <ClearIcon />
            </IconButton>
          </Box>

          <Box className="rmu-modal-content">
            <Box
              sx={{
                padding: { xs: "0 20px", md: "0 25px" },
              }}
            >
              <Box sx={{ my: "20px" }}>
                <Typography sx={{ mb: "5px" }}>Date</Typography>
                <Typography
                  variant="h5"
                  sx={{ fontSize: "16px", fontWeight: 500 }}
                >
                  07 Nov, 2025
                </Typography>
              </Box>

              <Box sx={{ my: "20px" }}>
                <Typography sx={{ mb: "5px" }}>Time</Typography>
                <Typography
                  variant="h5"
                  sx={{ fontSize: { xs: "20px", md: "28px" }, fontWeight: 900 }}
                >
                  10:00
                </Typography>
              </Box>

              <Box sx={{ my: "20px" }}>
                <Typography sx={{ mb: "5px" }}>Schedule Description</Typography>
                <Typography
                  variant="h5"
                  sx={{ fontSize: "16px", fontWeight: 500 }}
                >
                  Appointment with Patient
                </Typography>
              </Box>

              <Box sx={{ my: "20px" }}>
                <Typography sx={{ mb: "5px" }}>Patient Name</Typography>

                <Box
                  sx={{ display: "flex", alignItems: "center", gap: "10px" }}
                >
                  <Image
                    src="/images/patient.jpg"
                    alt="patient-image"
                    className="rounded-circle"
                    width={25}
                    height={25}
                  />
                  <Typography
                    variant="h5"
                    sx={{ fontSize: "14px", fontWeight: 500, margin: "0" }}
                  >
                    Jessy Pinkman
                  </Typography>
                </Box>
              </Box>

              <Box sx={{ my: "20px" }}>
                <Typography sx={{ mb: "5px" }}>Schedule Status</Typography>

                <Box
                  sx={{
                    borderRadius: "30px",
                    padding: "1px 10px",
                    fontSize: "12px",
                    backgroundColor: "success.100",
                    color: "success.main",
                    display: "inline-block",
                  }}
                >
                  Completed
                </Box>
              </Box>
            </Box>
          </Box>
        </Box>
      </BootstrapDialog>
    </>
  );
};

export default TodaysAppointments;

// angular-material/src/app/pages/doctor-page/d-appointments/todays-appointments/todays-appointments.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';
import { CustomizerSettingsService } from '../../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-todays-appointments',
    imports: [MatCardModule, MatButtonModule],
    templateUrl: './todays-appointments.component.html',
    styleUrl: './todays-appointments.component.scss'
})
export class TodaysAppointmentsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

    // Popup Trigger
    classApplied = false;
    toggleClass() {
        this.classApplied = !this.classApplied;
    }

}
<!-- Today's Appointments -->
<mat-card
    class="todays-appointments-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Today's Appointments
            </h5>
        </mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <div class="appointments-list position-relative">
            <div class="appointment-item position-relative z-1 border-radius">
                <div class="icon">
                    <img src="images/icons/done.svg" alt="done">
                </div>
                <div class="d-md-flex align-items-center justify-content-between">
                    <div>
                        <div class="info d-flex align-items-center">
                            <span class="d-block text-black fw-semibold">
                                10:00 AM
                            </span>
                        </div>
                        <p>
                            Appointment With Cardiac Patient
                        </p>
                        <div class="user d-flex align-items-center">
                            <img src="images/users/user32.jpg" class="rounded-circle" alt="user-image">
                            <span class="d-block text-black fw-semibold">
                                Jonathon Ronan
                            </span>
                        </div>
                    </div>
                    <button type="button" mat-button (click)="toggleClass()" class="btn">
                        View Details
                    </button>
                </div>
                <div class="shape position-absolute left-0 right-0 text-center z-n1 top-0 mx-auto">
                    <img src="images/icons/vector.png" alt="vector">
                </div>
            </div>
            <div class="appointment-item position-relative z-1 border-radius">
                <div class="icon">
                    <img src="images/icons/done.svg" alt="done">
                </div>
                <div class="d-md-flex align-items-center justify-content-between">
                    <div>
                        <div class="info d-flex align-items-center">
                            <span class="d-block text-black fw-semibold">
                                12:00 PM
                            </span>
                        </div>
                        <p>
                            Board Meeting With
                        </p>
                        <div class="user d-flex align-items-center">
                            <img src="images/users/user33.jpg" class="rounded-circle" alt="user-image">
                            <span class="d-block text-black fw-semibold">
                                Jessy Pinkman
                            </span>
                        </div>
                    </div>
                    <button type="button" mat-button (click)="toggleClass()" class="btn">
                        View Details
                    </button>
                </div>
                <div class="shape position-absolute left-0 right-0 text-center z-n1 top-0 mx-auto">
                    <img src="images/icons/vector.png" alt="vector">
                </div>
            </div>
            <div class="appointment-item position-relative z-1 border-radius">
                <div class="icon">
                    <img src="images/icons/not-done.svg" alt="not-done">
                </div>
                <div class="d-md-flex align-items-center justify-content-between">
                    <div>
                        <div class="info d-flex align-items-center">
                            <span class="d-block text-black fw-semibold">
                                02:00 PM
                            </span>
                            <button type="button" mat-button class="notification-btn bg-primary text-white p-0 border-0 rounded-circle">
                                <i class="ri-notification-2-line"></i>
                            </button>
                            <span class="trezo-badge bg-white">
                                Upcoming
                            </span>
                        </div>
                        <p>
                            Major Cardiac Surgery of the Patient
                        </p>
                        <div class="user d-flex align-items-center">
                            <img src="images/users/user34.jpg" class="rounded-circle" alt="user-image">
                            <span class="d-block text-black fw-semibold">
                                Walter White
                            </span>
                        </div>
                    </div>
                    <button type="button" mat-button (click)="toggleClass()" class="btn">
                        View Details
                    </button>
                </div>
                <div class="shape position-absolute left-0 right-0 text-center z-n1 top-0 mx-auto">
                    <img src="images/icons/vector.png" alt="vector">
                </div>
            </div>
            <div class="appointment-item position-relative z-1 border-radius">
                <div class="icon">
                    <img src="images/icons/not-done.svg" alt="not-done">
                </div>
                <div class="d-md-flex align-items-center justify-content-between">
                    <div>
                        <div class="info d-flex align-items-center">
                            <span class="d-block text-black fw-semibold">
                                03:00 PM
                            </span>
                            <button type="button" mat-button class="notification-btn bg-primary text-white p-0 border-0 rounded-circle">
                                <i class="ri-notification-2-line"></i>
                            </button>
                            <span class="trezo-badge bg-white">
                                Upcoming
                            </span>
                        </div>
                        <p>
                            Appointment With Cardiac Patient
                        </p>
                        <div class="user d-flex align-items-center">
                            <img src="images/users/user32.jpg" class="rounded-circle" alt="user-image">
                            <span class="d-block text-black fw-semibold">
                                Jonathon Ronan
                            </span>
                        </div>
                    </div>
                    <button type="button" mat-button (click)="toggleClass()" class="btn">
                        View Details
                    </button>
                </div>
                <div class="shape position-absolute left-0 right-0 text-center z-n1 top-0 mx-auto">
                    <img src="images/icons/vector.png" alt="vector">
                </div>
            </div>
            <div class="appointment-item position-relative z-1 border-radius">
                <div class="icon">
                    <img src="images/icons/not-done.svg" alt="not-done">
                </div>
                <div class="d-md-flex align-items-center justify-content-between">
                    <div>
                        <div class="info d-flex align-items-center">
                            <span class="d-block text-black fw-semibold">
                                04:00 PM
                            </span>
                            <button type="button" mat-button class="notification-btn bg-primary text-white p-0 border-0 rounded-circle">
                                <i class="ri-notification-2-line"></i>
                            </button>
                            <span class="trezo-badge bg-white">
                                Upcoming
                            </span>
                        </div>
                        <p>
                            Board Meeting With
                        </p>
                        <div class="user d-flex align-items-center">
                            <img src="images/users/user34.jpg" class="rounded-circle" alt="user-image">
                            <span class="d-block text-black fw-semibold">
                                Jessy Pinkman
                            </span>
                        </div>
                    </div>
                    <button type="button" mat-button (click)="toggleClass()" class="btn">
                        View Details
                    </button>
                </div>
                <div class="shape position-absolute left-0 right-0 text-center z-n1 top-0 mx-auto">
                    <img src="images/icons/vector.png" alt="vector">
                </div>
            </div>
            <div class="appointment-item position-relative z-1 border-radius">
                <div class="icon">
                    <img src="images/icons/not-done.svg" alt="not-done">
                </div>
                <div class="d-md-flex align-items-center justify-content-between">
                    <div>
                        <div class="info d-flex align-items-center">
                            <span class="d-block text-black fw-semibold">
                                05:00 PM
                            </span>
                            <button type="button" mat-button class="notification-btn bg-primary text-white p-0 border-0 rounded-circle">
                                <i class="ri-notification-2-line"></i>
                            </button>
                            <span class="trezo-badge bg-white">
                                Upcoming
                            </span>
                        </div>
                        <p>
                            Major Cardiac Surgery of the Patient
                        </p>
                        <div class="user d-flex align-items-center">
                            <img src="images/users/user33.jpg" class="rounded-circle" alt="user-image">
                            <span class="d-block text-black fw-semibold">
                                Walter White
                            </span>
                        </div>
                    </div>
                    <button type="button" mat-button (click)="toggleClass()" class="btn">
                        View Details
                    </button>
                </div>
                <div class="shape position-absolute left-0 right-0 text-center z-n1 top-0 mx-auto">
                    <img src="images/icons/vector.png" alt="vector">
                </div>
            </div>
        </div>
    </mat-card-content>
</mat-card>

<!-- Schedule Details -->
<div
    class="add-new-popup"
    [class.active]="classApplied"
>
    <div class="popup-dialog">
        <mat-card class="border-radius w-100 d-block bg-white border-0 shadow-none">
            <mat-card-header>
                <mat-card-title>
                    <h5 class="mb-0">
                        Schedule Details
                    </h5>
                </mat-card-title>
                <mat-card-subtitle>
                    <button
                        mat-button
                        (click)="toggleClass()"
                    >
                        <i class="ri-close-fill"></i>
                    </button>
                </mat-card-subtitle>
            </mat-card-header>
            <mat-card-content>
                <ul class="p-0 m-0 list-unstyled">
                    <li class="fw-medium text-black">
                        <span class="d-block fw-normal text-body">
                            Date
                        </span>
                        07 Nov, 2025
                    </li>
                    <li class="time text-black">
                        <span class="d-block fw-normal text-body">
                            Time
                        </span>
                        10:00
                    </li>
                    <li class="fw-medium text-black">
                        <span class="d-block fw-normal text-body">
                            Schedule Description
                        </span>
                        Appointment with Patient
                    </li>
                    <li class="fw-medium text-black">
                        <span class="d-block fw-normal text-body">
                            Patient Name
                        </span>
                        <div class="patient-name d-flex align-items-center">
                            <img src="images/patient.jpg" alt="patient-image" class="rounded-circle">
                            <span>
                                Jessy Pinkman
                            </span>
                        </div>
                    </li>
                    <li>
                        <span class="d-block fw-normal">
                            Schedule Status
                        </span>
                        <span class="trezo-badge finished fw-normal">
                            Completed
                        </span>
                    </li>
                </ul>
            </mat-card-content>
        </mat-card>
    </div>
</div>
