// vuejs-vuetify/src/components/FrontPages/Common/OurTeam.vue
<template>
  <div class="team-area">
    <div class="container position-relative z-1">
      <div class="section-title">
        <div class="sub-title d-inline-block position-relative">
          <span class="d-inline-block position-relative text-purple">
            Our Team
          </span>
        </div>
        <h2 class="mb-0">
          Introducing Our Exceptional Team. Meet the Minds Driving Our Success
        </h2>
      </div>
      <div class="team-slides">
        <Carousel v-bind="config">
          <Slide v-for="slide in items" :key="slide.id">
            <div class="single-team-member">
              <div class="image border-radius">
                <v-img
                  :src="slide.image"
                  class="border-radius"
                  alt="team-image"
                />
              </div>
              <div
                class="content border-radius d-flex align-items-center justify-content-between"
              >
                <div>
                  <h3 class="fw-semibold">{{ slide.name }}</h3>
                  <span class="d-block"> {{ slide.designation }} </span>
                </div>
                <div class="socials">
                  <a
                    v-for="social in slide.socials"
                    :key="social.id"
                    :href="social.link"
                    class="d-inline-block lh-1"
                    target="_blank"
                  >
                    <i :class="social.icon"></i>
                  </a>
                </div>
              </div>
            </div>
          </Slide>

          <template #addons>
            <Navigation>
              <template #next>
                <span> <i class="ri-arrow-right-line"></i> </span>
              </template>
              <template #prev>
                <span> <i class="ri-arrow-left-line"></i> </span>
              </template>
            </Navigation>
          </template>
        </Carousel>
      </div>
      <div class="shape1">
        <v-img src="@/assets/images/front-pages/shape1.png" alt="shape1" />
      </div>
      <div class="shape2">
        <v-img src="@/assets/images/front-pages/shape2.png" alt="shape2" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Carousel, Slide, Navigation } from "vue3-carousel";
import "vue3-carousel/carousel.css";

export default defineComponent({
  name: "OurTeam",
  components: {
    Carousel,
    Slide,
    Navigation,
  },
  setup() {
    const config = {
      itemsToShow: 1,
      autoplay: 3000,
      wrapAround: true,
      pauseAutoplayOnHover: true,
      breakpoints: {
        0: {
          itemsToShow: 1,
          snapAlign: "start",
        },
        515: {
          itemsToShow: 2,
          snapAlign: "start",
        },
        695: {
          itemsToShow: 2,
          snapAlign: "start",
        },
        935: {
          itemsToShow: 3,
          snapAlign: "center",
        },
        1200: {
          itemsToShow: 3,
          snapAlign: "center",
        },
      },
    };

    const items = [
      {
        id: 1,
        image: require("@/assets/images/front-pages/team1.jpg"),
        name: "Michael Johnson",
        designation: "CEO",
        socials: [
          {
            id: 1,
            link: "https://www.facebook.com/",
            icon: "ri-facebook-fill",
          },
          {
            id: 2,
            link: "https://x.com/",
            icon: "ri-twitter-x-fill",
          },
          {
            id: 3,
            link: "https://www.linkedin.com/",
            icon: "ri-linkedin-fill",
          },
        ],
      },
      {
        id: 2,
        image: require("@/assets/images/front-pages/team2.jpg"),
        name: "Emily Davis",
        designation: "Project Manager",
        socials: [
          {
            id: 1,
            link: "https://www.facebook.com/",
            icon: "ri-facebook-fill",
          },
          {
            id: 2,
            link: "https://x.com/",
            icon: "ri-twitter-x-fill",
          },
          {
            id: 3,
            link: "https://www.linkedin.com/",
            icon: "ri-linkedin-fill",
          },
        ],
      },
      {
        id: 3,
        image: require("@/assets/images/front-pages/team3.jpg"),
        name: "Daniel Lee",
        designation: "Sales Team Lead",
        socials: [
          {
            id: 1,
            link: "https://www.facebook.com/",
            icon: "ri-facebook-fill",
          },
          {
            id: 2,
            link: "https://x.com/",
            icon: "ri-twitter-x-fill",
          },
          {
            id: 3,
            link: "https://www.linkedin.com/",
            icon: "ri-linkedin-fill",
          },
        ],
      },
      {
        id: 4,
        image: require("@/assets/images/front-pages/team4.jpg"),
        name: "Olivia John",
        designation: "Frontend Lead",
        socials: [
          {
            id: 1,
            link: "https://www.facebook.com/",
            icon: "ri-facebook-fill",
          },
          {
            id: 2,
            link: "https://x.com/",
            icon: "ri-twitter-x-fill",
          },
          {
            id: 3,
            link: "https://www.linkedin.com/",
            icon: "ri-linkedin-fill",
          },
        ],
      },
    ];

    return {
      config,
      items,
    };
  },
});
</script>

<style lang="scss" scoped>
.team-area {
  .section-title {
    max-width: 630px;
  }
  .single-team-member {
    .image {
      padding: 15px;
      background: rgba(255, 255, 255, 0.26);
      backdrop-filter: blur(3.6px);
      border: 1px solid rgba(255, 255, 255, 0.24);

      .v-img {
        margin-bottom: -3px;
      }
    }

    .content {
      padding: 30px;
      background: rgba(255, 255, 255, 0.26);
      backdrop-filter: blur(3.6px);
      border: 1px solid rgba(255, 255, 255, 0.24);

      h3 {
        font-size: 18px;
        margin-bottom: 6px;
      }

      .socials {
        a {
          font-size: 20px;
          margin-right: 8px;
          color: var(--primaryColor);

          &:hover {
            color: var(--purpleColor);
          }

          &:last-child {
            margin-right: 0;
          }
        }
      }
    }
  }
  .shape1 {
    left: 90px;
    z-index: -1;
    bottom: 15px;
    position: absolute;
    filter: blur(150px);
  }

  .shape2 {
    z-index: -1;
    right: -15px;
    bottom: -130px;
    position: absolute;
    filter: blur(125px);
  }
}

@media only screen and (max-width: 767px) {
  .team-area {
    .section-title {
      max-width: 100%;
    }
    .single-team-member {
      .content {
        padding: 22px;

        h3 {
          font-size: 16px;
        }

        .socials {
          a {
            margin-right: 5px;
            font-size: 17px;
          }
        }
      }
    }
    .shape1 {
      left: 0;
      right: 0;
      bottom: 150px;
      text-align: center;
      margin: {
        left: auto;
        right: auto;
      }
    }
    .shape2 {
      text-align: center;
      bottom: -100px;
      right: 0;
      left: 0;
      margin: {
        left: auto;
        right: auto;
      }
    }
  }
}

@media only screen and (min-width: 576px) and (max-width: 767px) {
}

@media only screen and (min-width: 768px) and (max-width: 991px) {
  .team-area {
    .section-title {
      max-width: 500px;
    }
    .single-team-member {
      .content {
        padding: 25px;

        h3 {
          font-size: 17px;
        }
        .socials {
          a {
            font-size: 18px;
            margin-right: 7px;
          }
        }
      }
    }
    .shape2 {
      bottom: -30px;
    }
  }
}

@media only screen and (min-width: 992px) and (max-width: 1199px) {
  .team-area {
    .single-team-member {
      .content {
        .socials {
          a {
            font-size: 18px;
            margin-right: 5px;
          }
        }
      }
    }
  }
}
</style>

// svelte-bootstrap/src/lib/components/Front/Index/OurTeam.svelte
<script>
	import { onMount } from 'svelte';
	import { register } from 'swiper/element/bundle';

	export let className = '';

	/** @type {import('swiper/element').SwiperContainer} */
	let swiperEl;

	onMount(() => {
		register();

		if (swiperEl) {
			Object.assign(swiperEl, {
				spaceBetween: 25,
				loop: true,
				navigation: {
					nextEl: '.next',
					prevEl: '.prev'
				},
				autoplay: {
					delay: 2500,
					disableOnInteraction: false
				},
				breakpoints: {
					640: { slidesPerView: 2 },
					768: { slidesPerView: 2 },
					1024: { slidesPerView: 3 }
				}
			});
			swiperEl.initialize();
		}
	});

	const team = [
		{
			name: 'Michael Johnson',
			position: 'CEO',
			image: '/assets/images/landing/team-1.jpg'
		},
		{
			name: 'Emily Davis',
			position: 'Project Manager',
			image: '/assets/images/landing/team-2.jpg'
		},
		{
			name: 'Daniel Lee',
			position: 'Sales Team Lead',
			image: '/assets/images/landing/team-3.jpg'
		},
		{
			name: 'Olivia John',
			position: 'Frontend Lead',
			image: '/assets/images/landing/team-1.jpg'
		}
	];
</script>

<div class={`our-team-area position-relative z-1 ${className}`} id="ourteam">
	<div class="container">
		<div class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4 mb-lg-5">
			<div class="section-title ms-0 text-start mw-630 mb-0">
				<span class="top-title"><span>Our Team</span></span>
				<h2>Introducing Our Exceptional Team. Meet the Minds Driving Our Success</h2>
			</div>

			<div class="team-controller d-flex gap-3">
				<div class="controller-icon prev">
					<i class="ri-arrow-left-line"></i>
				</div>
				<div class="controller-icon next">
					<i class="ri-arrow-right-line"></i>
				</div>
			</div>
		</div>

		<!-- Swiper Element -->
		<swiper-container class="swiper team-slide" init="false" bind:this={swiperEl}>
			{#each team as member}
				<swiper-slide>
					<div class="our-team-single-item">
						<div class="team-img">
							<img src={member.image} alt={member.name} />
						</div>
						<div class="team-content d-flex justify-content-between align-items-center">
							<div>
								<h3>{member.name}</h3>
								<span>{member.position}</span>
							</div>
							<ul class="ps-0 mb-0 list-unstyled d-flex flex-wrap gap-3">
								<li>
									<a
										href="https://www.facebook.com/"
										target="_blank"
										class="text-decoration-none fs-20 text-primary"
										aria-label="Facebook"
									>
										<i class="ri-facebook-fill"></i>
									</a>
								</li>
								<li>
									<a
										href="https://www.twitter.com/"
										target="_blank"
										class="text-decoration-none fs-20 text-primary"
										aria-label="Twitter"
									>
										<i class="ri-twitter-x-line"></i>
									</a>
								</li>
								<li>
									<a
										href="https://www.linkedin.com/"
										target="_blank"
										class="text-decoration-none fs-20 text-primary"
										aria-label="LinkedIn"
									>
										<i class="ri-linkedin-fill"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</swiper-slide>
			{/each}
		</swiper-container>
	</div>

	<img src="/assets/images/landing/shape-1.png" class="shape shape-3" alt="shape" />
	<img src="/assets/images/landing/shape-2.png" class="shape shape-4" alt="shape" />
</div>
