// angular-material/src/app/dashboard/beauty-salon/top-customers/top-customers.component.ts
import { NgIf } from '@angular/common';
import { Component, ViewChild } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatMenuModule } from '@angular/material/menu';
import { MatButtonModule } from '@angular/material/button';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { MatPaginator, MatPaginatorModule } from '@angular/material/paginator';

@Component({
    selector: 'app-top-customers',
    imports: [MatCardModule, MatButtonModule, MatMenuModule, MatTableModule, MatPaginatorModule, NgIf],
    templateUrl: './top-customers.component.html',
    styleUrl: './top-customers.component.scss'
})
export class TopCustomersComponent {
        
    displayedColumns: string[] = ['id', 'customerName', 'phoneNo', 'email', 'preferredService', 'lastVisit', 'status', 'action'];
    dataSource = new MatTableDataSource<PeriodicElement>(ELEMENT_DATA);
    
    @ViewChild(MatPaginator) paginator!: MatPaginator;

    ngAfterViewInit() {
        this.dataSource.paginator = this.paginator;
    }

}

export interface PeriodicElement {
    id: string;
    customerName: any;
    phoneNo: string;
    email: string;
    preferredService: string;
    lastVisit: string;
    status: any;
    action: string;
}

const ELEMENT_DATA: PeriodicElement[] = [
    {
        id: '#001',
        customerName: {
            img: 'images/users/user33.jpg',
            name: 'Johhna Loren'
        },
        phoneNo: '+321 427 8690',
        email: 'loren123@gmail.com',
        preferredService: 'Nail Art',
        lastVisit: '17 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: true,
            royal: false,
            normal: false
        }
    },
    {
        id: '#002',
        customerName: {
            img: 'images/users/user34.jpg',
            name: 'Skyler White'
        },
        phoneNo: '+321 427 3980',
        email: 'skyqueen@gmail.com',
        preferredService: 'Hair Cut',
        lastVisit: '18 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: false,
            royal: true,
            normal: false
        }
    },
    {
        id: '#003',
        customerName: {
            img: 'images/users/user35.jpg',
            name: 'Jonathon Watson'
        },
        phoneNo: '+321 427 1243',
        email: 'jona2134@gmail.com',
        preferredService: 'Manicure',
        lastVisit: '19 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: false,
            royal: false,
            normal: true
        }
    },
    {
        id: '#004',
        customerName: {
            img: 'images/users/user36.jpg',
            name: 'Walter White'
        },
        phoneNo: '+321 427 7685',
        email: 'puzzleworld@gmail.com',
        preferredService: 'Facial',
        lastVisit: '21 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: true,
            royal: false,
            normal: false
        }
    },
    {
        id: '#005',
        customerName: {
            img: 'images/users/user37.jpg',
            name: 'David Carlen'
        },
        phoneNo: '+321 427 9021',
        email: 'liveslong@gmail.com',
        preferredService: 'Pedicure',
        lastVisit: '25 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: false,
            royal: true,
            normal: false
        }
    },
    {
        id: '#005',
        customerName: {
            img: 'images/users/user37.jpg',
            name: 'David Carlen'
        },
        phoneNo: '+321 427 9021',
        email: 'liveslong@gmail.com',
        preferredService: 'Pedicure',
        lastVisit: '25 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: false,
            royal: true,
            normal: false
        }
    },
    {
        id: '#001',
        customerName: {
            img: 'images/users/user33.jpg',
            name: 'Johhna Loren'
        },
        phoneNo: '+321 427 8690',
        email: 'loren123@gmail.com',
        preferredService: 'Nail Art',
        lastVisit: '17 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: true,
            royal: false,
            normal: false
        }
    },
    {
        id: '#004',
        customerName: {
            img: 'images/users/user36.jpg',
            name: 'Walter White'
        },
        phoneNo: '+321 427 7685',
        email: 'puzzleworld@gmail.com',
        preferredService: 'Facial',
        lastVisit: '21 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: true,
            royal: false,
            normal: false
        }
    },
    {
        id: '#003',
        customerName: {
            img: 'images/users/user35.jpg',
            name: 'Jonathon Watson'
        },
        phoneNo: '+321 427 1243',
        email: 'jona2134@gmail.com',
        preferredService: 'Manicure',
        lastVisit: '19 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: false,
            royal: false,
            normal: true
        }
    },
    {
        id: '#002',
        customerName: {
            img: 'images/users/user34.jpg',
            name: 'Skyler White'
        },
        phoneNo: '+321 427 3980',
        email: 'skyqueen@gmail.com',
        preferredService: 'Hair Cut',
        lastVisit: '18 Oct, 2025',
        action: "ri-more-2-fill",
        status: {
            vip: false,
            royal: true,
            normal: false
        }
    }
];
<mat-card class="top-customers-card mb-25 border-radius d-block bg-white border-0 shadow-none">
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Top Customers
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="card-header-menu bg-gray border-none d-inline-block border-radius">
                This Week
            </button>
            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                <ul class="p-0 mt-0 mb-0 list-unstyled">
                    <li>
                        <button mat-menu-item>
                            This Day
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Week
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Month
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Year
                        </button>
                    </li>
                </ul>
            </mat-menu>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <div class="table-style-five">
            <div class="table-responsive">
                <table mat-table [dataSource]="dataSource">

                    <!-- ID Column -->
                    <ng-container matColumnDef="id">
                        <th mat-header-cell *matHeaderCellDef>
                            ID
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.id}}
                        </td>
                    </ng-container>

                    <!-- Customer Name Column -->
                    <ng-container matColumnDef="customerName">
                        <th mat-header-cell *matHeaderCellDef>
                            Customer Name
                        </th>
                        <td mat-cell *matCellDef="let element">
                            <div class="employee-info d-flex align-items-center">
                                <img [src]="element.customerName.img" class="rounded-circle" alt="user-image">
                                <span class="d-block text-black fw-bold">
                                    {{element.customerName.name}}
                                </span>
                            </div>
                        </td>
                    </ng-container>

                    <!-- Phone No Column -->
                    <ng-container matColumnDef="phoneNo">
                        <th mat-header-cell *matHeaderCellDef>
                            Phone No
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.phoneNo}}
                        </td>
                    </ng-container>

                    <!-- Email Column -->
                    <ng-container matColumnDef="email">
                        <th mat-header-cell *matHeaderCellDef>
                            Email
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.email}}
                        </td>
                    </ng-container>

                    <!-- Preferred Service Column -->
                    <ng-container matColumnDef="preferredService">
                        <th mat-header-cell *matHeaderCellDef>
                            Preferred Service
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.preferredService}}
                        </td>
                    </ng-container>

                    <!-- Last Visit Column -->
                    <ng-container matColumnDef="lastVisit">
                        <th mat-header-cell *matHeaderCellDef>
                            Last Visit
                        </th>
                        <td class="fw-bold text-body" mat-cell *matCellDef="let element">
                            {{element.lastVisit}}
                        </td>
                    </ng-container>

                    <!-- Status Column -->
                    <ng-container matColumnDef="status">
                        <th mat-header-cell *matHeaderCellDef>
                            Status
                        </th>
                        <td mat-cell *matCellDef="let element">
                            <span class="trezo-badge fw-semibold inProgress" *ngIf="element.status.vip">
                                VIP
                            </span>
                            <span class="trezo-badge fw-semibold pPending" *ngIf="element.status.royal">
                                Royal
                            </span>
                            <span class="trezo-badge fw-semibold" *ngIf="element.status.normal">
                                Normal
                            </span>
                        </td>
                    </ng-container>

                    <!-- Action Column -->
                    <ng-container matColumnDef="action">
                        <th mat-header-cell *matHeaderCellDef></th>
                        <td mat-cell *matCellDef="let element">
                            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu p-0 d-inline-block border-radius-0">
                                <i class="{{element.action}}"></i>
                            </button>
                            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                                <ul class="p-0 mt-0 mb-0 list-unstyled">
                                    <li>
                                        <button mat-menu-item>
                                            View
                                        </button>
                                    </li>
                                    <li>
                                        <button mat-menu-item>
                                            Edit
                                        </button>
                                    </li>
                                    <li>
                                        <button mat-menu-item>
                                            Delete
                                        </button>
                                    </li>
                                </ul>
                            </mat-menu>
                        </td>
                    </ng-container>

                    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
                    <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>

                </table>
            </div>
            <mat-paginator [pageSizeOptions]="[5]" showFirstLastButtons></mat-paginator>
        </div>
    </mat-card-content>
</mat-card>

// vuejs-vuetify/src/components/Dashboard/BeautySalon/TopCustomers.vue
<template>
  <v-card
    class="top-customers-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Top Customers</h5>
      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius border-0 bg-gray"
          >
            This Day
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="trezo-table basic-table table-responsive">
        <table class="table mb-0">
          <thead>
            <tr>
              <th scope="col" class="fw-bold">ID</th>
              <th scope="col" class="fw-bold">Customer Name</th>
              <th scope="col" class="fw-bold">Phone No</th>
              <th scope="col" class="fw-bold">Email</th>
              <th scope="col" class="fw-bold">Preferred Service</th>
              <th scope="col" class="fw-bold">Last Visit</th>
              <th scope="col" class="fw-bold">Status</th>
              <th scope="col" class="fw-bold"></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="customer in paginatedCustomers" :key="customer.id">
              <td class="fw-semibold text-body">{{ customer.id }}</td>
              <td>
                <div class="employee-info d-flex align-items-center">
                  <div class="img rounded-circle">
                    <v-img
                      :src="customer.image"
                      alt="user-image"
                      class="rounded-circle"
                    />
                  </div>
                  <div>
                    <span class="d-block fw-semibold">{{ customer.name }}</span>
                  </div>
                </div>
              </td>
              <td class="fw-semibold text-body">{{ customer.phone }}</td>
              <td class="text-body">{{ customer.email }}</td>
              <td class="fw-semibold text-body">{{ customer.service }}</td>
              <td class="fw-semibold text-body">{{ customer.lastVisit }}</td>
              <td>
                <span :class="`trezo-status-badge ${customer.statusClass}`">
                  {{ customer.status }}
                </span>
              </td>
              <td>
                <div
                  class="action-buttons d-flex justify-content-end align-items-center"
                >
                  <button
                    type="button"
                    class="p-0 bg-transparent d-inline-block lh-1 border-0"
                  >
                    <i class="material-symbols-outlined"> visibility </i>
                  </button>
                  <button
                    type="button"
                    class="p-0 bg-transparent d-inline-block lh-1 border-0"
                  >
                    <i class="material-symbols-outlined"> edit </i>
                  </button>
                  <button
                    type="button"
                    class="p-0 bg-transparent d-inline-block lh-1 border-0"
                  >
                    <i class="material-symbols-outlined"> delete </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        class="d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
      >
        <span class="fs-12 fw-medium">
          Showing {{ startIndex + 1 }} to {{ endIndex }} of
          {{ customers.length }} Results
        </span>

        <nav aria-label="Page navigation example">
          <ul class="pagination mb-0 justify-content-center">
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Previous"
                @click="prevPage"
                :disabled="currentPage === 1"
              >
                <i class="material-symbols-outlined">keyboard_arrow_left</i>
              </button>
            </li>
            <li class="page-item" v-for="page in totalPages" :key="page">
              <button
                class="page-link"
                :class="{ active: page === currentPage }"
                @click="goToPage(page)"
              >
                {{ page }}
              </button>
            </li>
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Next"
                @click="nextPage"
                :disabled="currentPage === totalPages"
              >
                <i class="material-symbols-outlined">keyboard_arrow_right</i>
              </button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

export default defineComponent({
  name: "TopCustomers",
  setup() {
    const currentPage = ref(1);
    const itemsPerPage = ref(5);

    const customers = ref([
      {
        id: "#001",
        name: "Johhna Loren",
        phone: "+321 427 8690",
        email: "loren123@gmail.com",
        service: "Nail Art",
        lastVisit: "17 Oct, 2025",
        status: "VIP",
        statusClass: "shipped",
        image: require("@/assets/images/users/user36.jpg"),
      },
      {
        id: "#002",
        name: "Skyler White",
        phone: "+321 427 3980",
        email: "skyqueen@gmail.com",
        service: "Hair Cut",
        lastVisit: "18 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user37.jpg"),
      },
      {
        id: "#003",
        name: "Jonathon Watson",
        phone: "+321 427 1243",
        email: "jona2134@gmail.com",
        service: "Manicure",
        lastVisit: "19 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user38.jpg"),
      },
      {
        id: "#004",
        name: "Walter Olivia",
        phone: "+321 427 7685",
        email: "puzzleworld@gmail.com",
        service: "Pedicure",
        lastVisit: "21 Oct, 2025",
        status: "VIP",
        statusClass: "shipped",
        image: require("@/assets/images/users/user43.jpg"),
      },
      {
        id: "#005",
        name: "David Carlen",
        phone: "+321 427 9021",
        email: "liveslong@gmail.com",
        service: "Facial",
        lastVisit: "25 Oct, 2025",
        status: "Normal",
        statusClass: "",
        image: require("@/assets/images/users/user40.jpg"),
      },
      {
        id: "#002",
        name: "Skyler White",
        phone: "+321 427 3980",
        email: "skyqueen@gmail.com",
        service: "Hair Cut",
        lastVisit: "18 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user37.jpg"),
      },
      {
        id: "#003",
        name: "Jonathon Watson",
        phone: "+321 427 1243",
        email: "jona2134@gmail.com",
        service: "Manicure",
        lastVisit: "19 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user38.jpg"),
      },
      {
        id: "#004",
        name: "Walter Olivia",
        phone: "+321 427 7685",
        email: "puzzleworld@gmail.com",
        service: "Pedicure",
        lastVisit: "21 Oct, 2025",
        status: "VIP",
        statusClass: "shipped",
        image: require("@/assets/images/users/user43.jpg"),
      },
    ]);

    const totalPages = computed(() =>
      Math.ceil(customers.value.length / itemsPerPage.value)
    );

    const paginatedCustomers = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage.value;
      const end = start + itemsPerPage.value;
      return customers.value.slice(start, end);
    });

    const startIndex = computed(
      () => (currentPage.value - 1) * itemsPerPage.value
    );
    const endIndex = computed(() =>
      Math.min(currentPage.value * itemsPerPage.value, customers.value.length)
    );

    const goToPage = (page: number) => {
      currentPage.value = page;
    };

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    return {
      currentPage,
      itemsPerPage,
      customers,
      paginatedCustomers,
      totalPages,
      startIndex,
      endIndex,
      goToPage,
      nextPage,
      prevPage,
    };
  },
});
</script>

<style lang="scss" scoped>
.top-customers-card {
  .trezo-card-content {
    .basic-table {
      table,
      .table {
        thead {
          tr {
            background-color: transparent !important;
            th {
              font-size: 10px;
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent !important;
              text-align: start;
              padding: {
                bottom: 10px;
                top: 0;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
                text-align: end;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              font-size: 12px;
              padding: {
                top: 10px;
                bottom: 10px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 40px;
                }
                span {
                  &:nth-child(1) {
                    font-size: var(--fontSize);
                    margin-bottom: 2px;
                  }
                }
              }
              .trezo-badge {
                border-radius: 30px;
                padding: 1px 10px !important;
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0 !important;
                text-align: end;
              }
            }
          }
        }
      }
    }
  }
}
</style>
