// react-bootstrap/src/components/Dashboard/BeautySalon/TopCustomers.js
"use client";

import { useState, useEffect } from "react";
import { Table, Card, Dropdown } from "react-bootstrap";

const TopCustomers = () => {
  const [customers, setCustomers] = useState([]);
  const [loading, setLoading] = useState(true);

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 5;

  useEffect(() => {
    // Simulate API call (replace with actual API)
    setTimeout(() => {
      // Example data: Extend this array to simulate more items
      const data = [
        {
          id: "#001",
          name: "Johhna Loren",
          phone: "+321 427 8690",
          email: "loren123@gmail.com",
          service: "Nail Art",
          lastVisit: "17 Oct, 2024",
          status: "VIP",
          statusColor: "success",
          image: "/images/user-81.png",
        },
        {
          id: "#002",
          name: "Skyler White",
          phone: "+321 427 3980",
          email: "skyqueen@gmail.com",
          service: "Hair Cut",
          lastVisit: "18 Oct, 2024",
          status: "Royal",
          statusColor: "primary",
          image: "/images/user-80.png",
        },
        {
          id: "#003",
          name: "Alice Johnson",
          phone: "+321 123 4567",
          email: "alice@gmail.com",
          service: "Hair Coloring",
          lastVisit: "19 Oct, 2024",
          status: "Regular",
          statusColor: "warning",
          image: "/images/user-82.png",
        },
        {
          id: "#004",
          name: "Bob Smith",
          phone: "+321 987 6543",
          email: "bobsmith@gmail.com",
          service: "Massage",
          lastVisit: "20 Oct, 2024",
          status: "VIP",
          statusColor: "success",
          image: "/images/user-83.png",
        },
        {
          id: "#005",
          name: "Charlie Brown",
          phone: "+321 555 6666",
          email: "charliebrown@gmail.com",
          service: "Facial",
          lastVisit: "21 Oct, 2024",
          status: "Royal",
          statusColor: "primary",
          image: "/images/user-84.png",
        },
        {
          id: "#006",
          name: "Dana White",
          phone: "+321 444 7777",
          email: "danawhite@gmail.com",
          service: "Hair Styling",
          lastVisit: "22 Oct, 2024",
          status: "VIP",
          statusColor: "success",
          image: "/images/user-85.png",
        },
        {
          id: "#007",
          name: "Eleanor Rigby",
          phone: "+321 333 8888",
          email: "eleanor@gmail.com",
          service: "Manicure",
          lastVisit: "23 Oct, 2024",
          status: "Regular",
          statusColor: "warning",
          image: "/images/user-86.png",
        },
        {
          id: "#008",
          name: "Frank Castle",
          phone: "+321 222 9999",
          email: "punisher@gmail.com",
          service: "Beard Trim",
          lastVisit: "24 Oct, 2024",
          status: "VIP",
          statusColor: "success",
          image: "/images/user-87.png",
        },
        {
          id: "#009",
          name: "Grace Hopper",
          phone: "+321 111 0000",
          email: "hopper@gmail.com",
          service: "Skin Treatment",
          lastVisit: "25 Oct, 2024",
          status: "Royal",
          statusColor: "primary",
          image: "/images/user-88.png",
        },
        {
          id: "#010",
          name: "Henry Cavill",
          phone: "+321 999 8888",
          email: "superman@gmail.com",
          service: "Muscle Therapy",
          lastVisit: "26 Oct, 2024",
          status: "Regular",
          statusColor: "warning",
          image: "/images/user-89.png",
        },
      ];
      setCustomers(data);
      setLoading(false);
    }, 1000);
  }, []);

  // Calculate total pages
  const totalPages = Math.ceil(customers.length / itemsPerPage);

  // Get current page data
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentCustomers = customers.slice(indexOfFirstItem, indexOfLastItem);

  // Pagination handlers
  const goToPage = (pageNumber) => {
    setCurrentPage(pageNumber);
  };

  const goToPrevPage = () => {
    if (currentPage > 1) {
      setCurrentPage((prev) => prev - 1);
    }
  };

  const goToNextPage = () => {
    if (currentPage < totalPages) {
      setCurrentPage((prev) => prev + 1);
    }
  };

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-0">
            <h3 className="mb-0">Top Customers</h3>

            <Dropdown className="dropdown select-dropdown">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="dropdown-toggle bg-border-color border text-body rounded-2"
              >
                This Week <i className="ri-arrow-down-s-line"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Day
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Week
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Month
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Year
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          {loading ? (
            <p>Loading...</p>
          ) : (
            <div className="default-table-area style-two campaigns-table bs-top-customers">
              <div className="table-responsive">
                <Table className="align-middle border-0">
                  <thead>
                    <tr className="border-bottom">
                      <th
                        scope="col"
                        className=" bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          ID
                        </span>
                      </th>
                      <th
                        scope="col"
                        className="bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          CUSTOMER NAME
                        </span>
                      </th>
                      <th
                        scope="col"
                        className="bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          PHONE NO
                        </span>
                      </th>
                      <th
                        scope="col"
                        className="bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          EMAIL
                        </span>
                      </th>
                      <th
                        scope="col"
                        className="bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          PROFFERED SERVICE
                        </span>
                      </th>
                      <th
                        scope="col"
                        className="bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          LAST VISIT
                        </span>
                      </th>
                      <th
                        scope="col"
                        className="bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          STATUS
                        </span>
                      </th>
                      <th
                        scope="col"
                        className="text-end bg-transparent text-body fw-medium"
                      >
                        <span className="fs-10 fw-bold letter-spacing-1 text-body-color-60">
                          ACTION
                        </span>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {currentCustomers.map((customer, index) => (
                      <tr key={index}>
                        <td className="fs-12 fw-semibold text-body-color-50">
                          {customer.id}
                        </td>

                        <td>
                          <div className="d-flex align-items-center gap-2">
                            <div className="flex-shrink-0">
                              <img
                                src={customer.image}
                                className="rounded-circle"
                                alt="user"
                                width={32}
                                height={32}
                              />
                            </div>
                            <div className="flex-grow-1">
                              <h4 className="fs-14 fw-semibold mb-0 text-secondary-50">
                                {customer.name}
                              </h4>
                            </div>
                          </div>
                        </td>

                        <td className="fs-12 fw-semibold text-body-color-50">
                          {customer.phone}
                        </td>

                        <td className="fs-12 fw-normal text-body">
                          {customer.email}
                        </td>

                        <td className="fs-12 fw-semibold text-body-color-50">
                          {customer.service}
                        </td>

                        <td className="fs-12 fw-semibold text-body-color-50">
                          {customer.lastVisit}
                        </td>

                        <td>
                          <span
                            className={`d-inline-block px-2 bg-${customer.statusColor} bg-opacity-10 text-${customer.statusColor} border border-${customer.statusColor} rounded-pill fs-12 fw-medium`}
                          >
                            {customer.status}
                          </span>
                        </td>

                        <td className="text-end">
                          <Dropdown className="action-opt">
                            <Dropdown.Toggle
                              variant="secondary"
                              id="dropdown-basic"
                              className="bg-transparent p-0"
                            >
                              <i className="material-symbols-outlined">
                                more_horiz
                              </i>
                            </Dropdown.Toggle>

                            <Dropdown.Menu className="bg-white border box-shadow">
                              <Dropdown.Item href="#">
                                <i className="material-symbols-outlined">
                                  edit
                                </i>
                                Edit
                              </Dropdown.Item>
                              <Dropdown.Item href="#">
                                <i className="material-symbols-outlined">
                                  visibility
                                </i>
                                View
                              </Dropdown.Item>
                              <Dropdown.Item href="#">
                                <i className="material-symbols-outlined">
                                  delete
                                </i>
                                Delete
                              </Dropdown.Item>
                            </Dropdown.Menu>
                          </Dropdown>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </Table>
              </div>

              <div className="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap mt-4">
                <span className="fs-12 fw-medium">
                  Showing {currentCustomers.length} of {customers.length}{" "}
                  Results
                </span>

                <nav aria-label="Page navigation example">
                  <ul className="pagination mb-0 justify-content-center">
                    <li className="page-item">
                      <button
                        className={`page-link icon hover-bg ${
                          currentPage === 1 ? "disabled" : ""
                        }`}
                        onClick={goToPrevPage}
                      >
                        <i className="material-symbols-outlined">
                          keyboard_arrow_left
                        </i>
                      </button>
                    </li>

                    {Array.from({ length: totalPages }, (_, i) => i + 1).map(
                      (page) => (
                        <li key={page} className="page-item">
                          <button
                            className={`page-link ${
                              currentPage === page ? "active" : ""
                            }`}
                            onClick={() => goToPage(page)}
                          >
                            {page}
                          </button>
                        </li>
                      )
                    )}

                    <li className="page-item">
                      <button
                        className={`page-link icon hover-bg ${
                          currentPage === totalPages ? "disabled" : ""
                        }`}
                        onClick={goToNextPage}
                      >
                        <i className="material-symbols-outlined">
                          keyboard_arrow_right
                        </i>
                      </button>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          )}
        </Card.Body>
      </Card>
    </>
  );
};

export default TopCustomers;

// vuejs-vuetify/src/components/Dashboard/BeautySalon/TopCustomers.vue
<template>
  <v-card
    class="top-customers-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Top Customers</h5>
      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius border-0 bg-gray"
          >
            This Day
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="trezo-table basic-table table-responsive">
        <table class="table mb-0">
          <thead>
            <tr>
              <th scope="col" class="fw-bold">ID</th>
              <th scope="col" class="fw-bold">Customer Name</th>
              <th scope="col" class="fw-bold">Phone No</th>
              <th scope="col" class="fw-bold">Email</th>
              <th scope="col" class="fw-bold">Preferred Service</th>
              <th scope="col" class="fw-bold">Last Visit</th>
              <th scope="col" class="fw-bold">Status</th>
              <th scope="col" class="fw-bold"></th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="customer in paginatedCustomers" :key="customer.id">
              <td class="fw-semibold text-body">{{ customer.id }}</td>
              <td>
                <div class="employee-info d-flex align-items-center">
                  <div class="img rounded-circle">
                    <v-img
                      :src="customer.image"
                      alt="user-image"
                      class="rounded-circle"
                    />
                  </div>
                  <div>
                    <span class="d-block fw-semibold">{{ customer.name }}</span>
                  </div>
                </div>
              </td>
              <td class="fw-semibold text-body">{{ customer.phone }}</td>
              <td class="text-body">{{ customer.email }}</td>
              <td class="fw-semibold text-body">{{ customer.service }}</td>
              <td class="fw-semibold text-body">{{ customer.lastVisit }}</td>
              <td>
                <span :class="`trezo-status-badge ${customer.statusClass}`">
                  {{ customer.status }}
                </span>
              </td>
              <td>
                <div
                  class="action-buttons d-flex justify-content-end align-items-center"
                >
                  <button
                    type="button"
                    class="p-0 bg-transparent d-inline-block lh-1 border-0"
                  >
                    <i class="material-symbols-outlined"> visibility </i>
                  </button>
                  <button
                    type="button"
                    class="p-0 bg-transparent d-inline-block lh-1 border-0"
                  >
                    <i class="material-symbols-outlined"> edit </i>
                  </button>
                  <button
                    type="button"
                    class="p-0 bg-transparent d-inline-block lh-1 border-0"
                  >
                    <i class="material-symbols-outlined"> delete </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        class="d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
      >
        <span class="fs-12 fw-medium">
          Showing {{ startIndex + 1 }} to {{ endIndex }} of
          {{ customers.length }} Results
        </span>

        <nav aria-label="Page navigation example">
          <ul class="pagination mb-0 justify-content-center">
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Previous"
                @click="prevPage"
                :disabled="currentPage === 1"
              >
                <i class="material-symbols-outlined">keyboard_arrow_left</i>
              </button>
            </li>
            <li class="page-item" v-for="page in totalPages" :key="page">
              <button
                class="page-link"
                :class="{ active: page === currentPage }"
                @click="goToPage(page)"
              >
                {{ page }}
              </button>
            </li>
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Next"
                @click="nextPage"
                :disabled="currentPage === totalPages"
              >
                <i class="material-symbols-outlined">keyboard_arrow_right</i>
              </button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

export default defineComponent({
  name: "TopCustomers",
  setup() {
    const currentPage = ref(1);
    const itemsPerPage = ref(5);

    const customers = ref([
      {
        id: "#001",
        name: "Johhna Loren",
        phone: "+321 427 8690",
        email: "loren123@gmail.com",
        service: "Nail Art",
        lastVisit: "17 Oct, 2025",
        status: "VIP",
        statusClass: "shipped",
        image: require("@/assets/images/users/user36.jpg"),
      },
      {
        id: "#002",
        name: "Skyler White",
        phone: "+321 427 3980",
        email: "skyqueen@gmail.com",
        service: "Hair Cut",
        lastVisit: "18 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user37.jpg"),
      },
      {
        id: "#003",
        name: "Jonathon Watson",
        phone: "+321 427 1243",
        email: "jona2134@gmail.com",
        service: "Manicure",
        lastVisit: "19 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user38.jpg"),
      },
      {
        id: "#004",
        name: "Walter Olivia",
        phone: "+321 427 7685",
        email: "puzzleworld@gmail.com",
        service: "Pedicure",
        lastVisit: "21 Oct, 2025",
        status: "VIP",
        statusClass: "shipped",
        image: require("@/assets/images/users/user43.jpg"),
      },
      {
        id: "#005",
        name: "David Carlen",
        phone: "+321 427 9021",
        email: "liveslong@gmail.com",
        service: "Facial",
        lastVisit: "25 Oct, 2025",
        status: "Normal",
        statusClass: "",
        image: require("@/assets/images/users/user40.jpg"),
      },
      {
        id: "#002",
        name: "Skyler White",
        phone: "+321 427 3980",
        email: "skyqueen@gmail.com",
        service: "Hair Cut",
        lastVisit: "18 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user37.jpg"),
      },
      {
        id: "#003",
        name: "Jonathon Watson",
        phone: "+321 427 1243",
        email: "jona2134@gmail.com",
        service: "Manicure",
        lastVisit: "19 Oct, 2025",
        status: "Royal",
        statusClass: "pPending",
        image: require("@/assets/images/users/user38.jpg"),
      },
      {
        id: "#004",
        name: "Walter Olivia",
        phone: "+321 427 7685",
        email: "puzzleworld@gmail.com",
        service: "Pedicure",
        lastVisit: "21 Oct, 2025",
        status: "VIP",
        statusClass: "shipped",
        image: require("@/assets/images/users/user43.jpg"),
      },
    ]);

    const totalPages = computed(() =>
      Math.ceil(customers.value.length / itemsPerPage.value)
    );

    const paginatedCustomers = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage.value;
      const end = start + itemsPerPage.value;
      return customers.value.slice(start, end);
    });

    const startIndex = computed(
      () => (currentPage.value - 1) * itemsPerPage.value
    );
    const endIndex = computed(() =>
      Math.min(currentPage.value * itemsPerPage.value, customers.value.length)
    );

    const goToPage = (page: number) => {
      currentPage.value = page;
    };

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    return {
      currentPage,
      itemsPerPage,
      customers,
      paginatedCustomers,
      totalPages,
      startIndex,
      endIndex,
      goToPage,
      nextPage,
      prevPage,
    };
  },
});
</script>

<style lang="scss" scoped>
.top-customers-card {
  .trezo-card-content {
    .basic-table {
      table,
      .table {
        thead {
          tr {
            background-color: transparent !important;
            th {
              font-size: 10px;
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent !important;
              text-align: start;
              padding: {
                bottom: 10px;
                top: 0;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
                text-align: end;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              font-size: 12px;
              padding: {
                top: 10px;
                bottom: 10px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 40px;
                }
                span {
                  &:nth-child(1) {
                    font-size: var(--fontSize);
                    margin-bottom: 2px;
                  }
                }
              }
              .trezo-badge {
                border-radius: 30px;
                padding: 1px 10px !important;
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0 !important;
                text-align: end;
              }
            }
          }
        }
      }
    }
  }
}
</style>
