// react-bootstrap/src/components/Dashboard/BeautySalon/FeaturedServices.js
"use client";

import { Card } from "react-bootstrap";

const featuredServicesData = [
  {
    id: 1,
    image: "/images/featured-1.png",
    name: "Hair Cut",
    served: "132 Served this week",
    rank: "01",
  },
  {
    id: 2,
    image: "/images/featured-2.png",
    name: "Manicure",
    served: "102 Served this week",
    rank: "02",
  },
  {
    id: 3,
    image: "/images/featured-3.png",
    name: "Pedicure",
    served: "99 Served this week",
    rank: "03",
  },
  {
    id: 4,
    image: "/images/featured-4.png",
    name: "Nail Art",
    served: "89 Served this week",
    rank: "04",
  },
  {
    id: 5,
    image: "/images/featured-5.png",
    name: "Facial Treatment",
    served: "72 Served this week",
    rank: "05",
  },
];

const FeaturedServices = () => {
  return (
    <>
      <Card className="border-0 rounded-3 bg-white p-4 mb-4">
        <h3 className="fs-18 mb-3 pb-1">Featured Services</h3>

        <ul className="ps-0 mb-0 list-unstyled">
          {featuredServicesData.map((service) => (
            <li
              key={service.id}
              className="border-bottom lcbmp-none"
              style={{
                paddingBottom: "18px",
                marginBottom: "18px",
              }}
            >
              <div className="d-flex flex-wrap gap-2 justify-content-between align-items-center">
                <div className="d-flex align-items-center gap-3">
                  <div className="flex-shrink-0">
                    <img
                      src={service.image}
                      alt={service.name}
                      width={32}
                      height={32}
                    />
                  </div>
                  <div className="flex-grow-1">
                    <h4 className="fs-14 fw-semibold mb-0">{service.name}</h4>
                    <span className="fs-12">{service.served}</span>
                  </div>
                </div>

                <span
                  className="fs-12 fw-medium bg-primary bg-opacity-10 d-inline-block text-center text-primary rounded-circle"
                  style={{
                    width: "20px",
                    height: "20px",
                    lineHeight: "20px",
                  }}
                >
                  {service.rank}
                </span>
              </div>
            </li>
          ))}
        </ul>
      </Card>
    </>
  );
};

export default FeaturedServices;

// vuejs-bootstrap/src/components/Dashboard/BeautySalon/FeaturedServices.vue
<template>
  <div
    class="featured-services-card card mb-4 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-30"
      >
        <h5 class="mb-0">Featured Services</h5>
      </div>

      <div class="trezo-card-content">
        <ul class="p-0 m-0 list-unstyled">
          <li
            v-for="(service, index) in services"
            :key="service.id"
            class="d-flex align-items-center justify-content-between"
          >
            <div class="info d-flex align-items-center">
              <img :src="service.icon" :alt="service.name" />
              <div>
                <span class="d-block text-black fw-semibold">
                  {{ service.name }}
                </span>
                <span class="d-block text-body">
                  {{ service.served }} Served this week
                </span>
              </div>
            </div>
            <span
              class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center"
            >
              {{ index + 1 }}
            </span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "FeaturedServices",
  setup() {
    const services = [
      {
        id: 1,
        name: "Hair Cut",
        icon: require("@/assets/images/icons/hair-cutting.svg"),
        served: 132,
      },
      {
        id: 2,
        name: "Manicure",
        icon: require("@/assets/images/icons/manicure.svg"),
        served: 102,
      },
      {
        id: 3,
        name: "Pedicure",
        icon: require("@/assets/images/icons/pedicure.svg"),
        served: 99,
      },
      {
        id: 4,
        name: "Nail Art",
        icon: require("@/assets/images/icons/nail-polish.svg"),
        served: 89,
      },
      {
        id: 5,
        name: "Facial Treatment",
        icon: require("@/assets/images/icons/woman.svg"),
        served: 72,
      },
    ];
    return {
      services,
    };
  },
});
</script>

<style lang="scss" scoped>
.featured-services-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        padding-bottom: 12px;
        margin-bottom: 12px;

        .info {
          gap: 15px;

          span {
            font-size: 12px;

            &:nth-child(1) {
              font-size: var(--fontSize);
              margin-bottom: 2px;
            }
          }
        }
        .number {
          width: 25px;
          height: 25px;
          font-size: 12px;
          background-color: #dde4ff;
        }
        &:last-child {
          border-bottom-width: 0;
          padding-bottom: 0;
          margin-bottom: 0;
        }
      }
    }
  }
}
</style>
