// landing-pages/angular-material/src/app/ecommerce-demo/common/navbar/navbar.component.ts
import { NgClass } from '@angular/common';
import { Component, HostListener } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { RouterLink, RouterLinkActive, Router } from '@angular/router';

@Component({
    selector: 'app-navbar',
    imports: [RouterLink, NgClass, RouterLinkActive, MatButtonModule],
    templateUrl: './navbar.component.html',
    styleUrl: './navbar.component.scss'
})
export class NavbarComponent {

    constructor(
        public router: Router
    ) {}

    // Toggle Class
    classApplied = false;
    toggleClass() {
        this.classApplied = !this.classApplied;
    }

    // Navbar Sticky
    isSticky: boolean = false;
    @HostListener('window:scroll', ['$event'])
    checkScroll() {
        const scrollPosition = window.scrollY || document.documentElement.scrollTop || document.body.scrollTop || 0;
        if (scrollPosition >= 50) {
            this.isSticky = true;
        } else {
            this.isSticky = false;
        }
    }

}
<nav
    class="navbar navbar-expand-lg d-flex align-items-center flex-wrap justify-content-between"
    [ngClass]="{'is-sticky': isSticky, 'position-fixed bg-transparent': router.url === '/'}"
>
    <div class="container d-flex align-items-center justify-content-between flex-wrap-inherit">
        <a
            class="d-block lh-1"
            routerLink="/"
        >
            <img src="images/ecommerce/logo.svg" alt="logo">
        </a>
        <button
            class="navbar-toggler p-0 d-inline-block rounded-0"
            [class.active]="classApplied"
            (click)="toggleClass()"
            type="button"
            mat-button
        >
            <span></span>
            <span></span>
            <span></span>
        </button>
        <div
            class="collapse navbar-collapse align-items-center flex-grow-1 flex-basis-full"
            [class.active]="classApplied"
        >
            <ul class="navbar-nav p-0 m-0 d-flex mx-auto p-0 list-unstyled flex-column">
                <li class="nav-item">
                    <a class="nav-link d-block" routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-block" routerLink="/features" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                        Features
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-block" routerLink="/use-cases" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                        Use Cases
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-block" routerLink="/testimonials" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                        Testimonials
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-block" routerLink="/pricing" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                        Pricing
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link d-block" routerLink="/blog" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}">
                        Blog
                    </a>
                </li>
            </ul>
            <a
                mat-button
                routerLink="/pricing"
                class="ecommerce-default-btn"
            >
                Get Started
            </a>
        </div>
    </div>
</nav>

// landing-pages/react-bootstrap/marketing-landing/src/components/Layout/Navbar.js
"use client";

import React, { useState, useEffect } from "react";
import { Link, useLocation } from "react-router-dom";
import Container from "react-bootstrap/Container";

// Navigation data defined outside the component
const navigationItems = [
  { name: "Home", path: "/" },
  { name: "Features", path: "/features/" },
  { name: "Pricing", path: "/pricing/" },
  { name: "Blog", path: "/blogs/" },
];

const Navbar = () => {
  const location = useLocation(); // Use `useLocation` to get the current path
  const pathname = location.pathname;

  const [isToggleNavbar, setToggleNavbar] = useState(true);
  const handleToggleNavbar = () => {
    setToggleNavbar(!isToggleNavbar);
  };

  // Scroll to top on route change
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, [pathname]); // Trigger when pathname changes

  // Sticky navbar
  useEffect(() => {
    const elementId = document.getElementById("navbar");
    const handleScroll = () => {
      if (window.scrollY > 100) {
        elementId?.classList.add("sticky");
      } else {
        elementId?.classList.remove("sticky");
      }
    };

    document.addEventListener("scroll", handleScroll);

    // Cleanup event listener on component unmount
    return () => {
      document.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <>
      <nav
        className="navbar navbar-expand-lg bg-transparent fixed-top navbar-for-landing-page py-30 style-two"
        id="navbar"
      >
        <Container className="cmw-1308">
          <div
            className="d-flex w-100 align-items-center justify-content-between bg-white rounded-5 for-mobile-p"
            style={{
              padding: "8px 16px",
              flexWrap: "inherit",
            }}
          >
            <Link className="navbar-brand" to="/">
              <img
                src="/images/logo.svg"
                className="black-logo"
                alt="logo"
                width={109}
                height={29}
              />
              <img
                src="/images/white-logo.svg"
                className="white-logo d-none"
                alt="logo"
                width={109}
                height={29}
              />
            </Link>

            <button
              className="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent"
              aria-expanded="false"
              aria-label="Toggle navigation"
              onClick={handleToggleNavbar}
            >
              <span className="border-bottom border-3 border-secondary top"></span>
              <span className="border-bottom border-3 border-secondary middle my-5px"></span>
              <span className="border-bottom border-3 border-secondary bottom"></span>
            </button>

            <div
              id="navbarSupportedContent"
              className={`collapse navbar-collapse ${
                isToggleNavbar ? "" : "show"
              }`}
            >
              <ul className="navbar-nav m-auto">
                {navigationItems.map((item) => (
                  <li className="nav-item" key={item.path}>
                    <Link
                      className={`nav-link fs-14 fw-medium text-body-bg hover p-0 ${
                        pathname === item.path ? "active" : ""
                      }`}
                      to={item.path}
                    >
                      {item.name}
                    </Link>
                  </li>
                ))}
              </ul>

              <div
                className="othres d-flex align-items-center"
                style={{
                  gap: "30px",
                }}
              >
                <Link
                  to="#"
                  className="fw-medium fs-14 text-decoration-none text-danger-50"
                >
                  Login
                </Link>
                <Link
                  to="#"
                  className="btn btn-outline-danger-50 fw-medium fs-14 rounded-pill"
                >
                  Get Started
                </Link>
              </div>
            </div>
          </div>
        </Container>
      </nav>
    </>
  );
};

export default Navbar;
