// laravel-vuetify/resources/components/Pages/LMS/CourseDetails/ManageReviews.vue
<template>
    <v-card
        class="reviews-card trezo-card border-radius d-block bg-white border-0 shadow-none"
    >
        <div class="v-card-header">
            <h5 class="mb-0">Manage Reviews</h5>
        </div>
        <div class="trezo-table-content">
            <div class="trezo-table">
                <v-table>
                    <thead>
                        <tr>
                            <th class="text-start">Reviewer</th>
                            <th class="text-start">Review</th>
                            <th class="text-start">Date</th>
                            <th class="text-start">Status</th>
                            <th class="text-start">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="item in items.slice(0, 5)" :key="item.id">
                            <td>
                                <div
                                    class="user-info d-flex align-items-center"
                                >
                                    <div class="image">
                                        <v-img
                                            :src="item.reviewer.image"
                                            class="rounded-circle"
                                            alt="reviewer-image"
                                        />
                                    </div>
                                    <div class="info">
                                        <span class="fw-medium d-block">
                                            {{ item.reviewer.name }}
                                        </span>
                                        <span class="email d-block text-body">
                                            {{ item.reviewer.email }}
                                        </span>
                                    </div>
                                </div>
                            </td>
                            <td style="white-space: normal">
                                <div class="review">
                                    <div class="ratings lh-1">
                                        <i
                                            v-for="(content, index) in item
                                                .ratings.stars"
                                            :key="index"
                                            :class="content.star"
                                        ></i>
                                    </div>
                                    <p class="text-black">
                                        {{ item.ratings.review }}
                                    </p>
                                </div>
                            </td>
                            <td class="text-body">
                                <span class="d-block">
                                    {{ item.date.date }}
                                </span>
                                <span class="d-block">
                                    {{ item.date.time }}
                                </span>
                            </td>
                            <td>
                                <span
                                    class="trezo-status-badge"
                                    :class="computeClass(item.status)"
                                >
                                    {{ item.status }}
                                </span>
                            </td>
                            <td>
                                <div
                                    class="action-buttons d-flex align-items-center"
                                >
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.approved }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.reply }}
                                        </i>
                                    </button>
                                    <button type="button">
                                        <i class="material-symbols-outlined">
                                            {{ item.action.delete }}
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </v-table>
                <PaginationTwo items="5" />
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref } from "vue";
import PaginationTwo from "../../../Common/PaginationTwo.vue";

import user6 from "../../../../../public/images/users/user6.jpg";
import user7 from "../../../../../public/images/users/user7.jpg";
import user8 from "../../../../../public/images/users/user8.jpg";
import user9 from "../../../../../public/images/users/user9.jpg";
import user10 from "../../../../../public/images/users/user10.jpg";
import user11 from "../../../../../public/images/users/user11.jpg";
import user12 from "../../../../../public/images/users/user12.jpg";
import user13 from "../../../../../public/images/users/user13.jpg";
import user14 from "../../../../../public/images/users/user14.jpg";
import user15 from "../../../../../public/images/users/user15.jpg";

import product1 from "../../../../../public/images/products/product1.jpg";
import product2 from "../../../../../public/images/products/product2.jpg";
import product3 from "../../../../../public/images/products/product3.jpg";
import product4 from "../../../../../public/images/products/product4.jpg";
import product5 from "../../../../../public/images/products/product5.jpg";
import product6 from "../../../../../public/images/products/product6.jpg";

export default defineComponent({
    name: "ManageReviews",
    components: {
        PaginationTwo,
    },
    setup() {
        const items = ref([
            {
                id: "#999",
                reviewer: {
                    image: user6,
                    name: "Olivia Clark",
                    email: "olivia@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                    ],
                    review: `Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
                },
                product: {
                    image: product1,
                    title: "Smart Band",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#998",
                reviewer: {
                    image: user7,
                    name: "Zephyr Zing",
                    email: "zephyr@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-half-fill",
                        },
                    ],
                    review: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.`,
                },
                product: {
                    image: product2,
                    title: "Headphone",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#997",
                reviewer: {
                    image: user8,
                    name: "Nova Nectar",
                    email: "nova@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-line",
                        },
                    ],
                    review: `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
                },
                product: {
                    image: product3,
                    title: "iPhone 15 Plus",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#996",
                reviewer: {
                    image: user9,
                    name: "Isabella Chang",
                    email: "isabella@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-half-fill",
                        },
                        {
                            star: "ri-star-line",
                        },
                    ],
                    review: `It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing.`,
                },
                product: {
                    image: product4,
                    title: "Bluetooth Speaker",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#995",
                reviewer: {
                    image: user10,
                    name: "Alina Bennett",
                    email: "alina@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                    ],
                    review: `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.`,
                },
                product: {
                    image: product5,
                    title: "Airbuds 2nd Gen",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Published",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#994",
                reviewer: {
                    image: user11,
                    name: "Marcia Baker",
                    email: "marcia@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                    ],
                    review: `Lorem Ipsum is simply dummy text of the printing and typesetting industry.`,
                },
                product: {
                    image: product1,
                    title: "Smart Band",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#993",
                reviewer: {
                    image: user12,
                    name: "Carolyn Barnes",
                    email: "carolyn@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-half-fill",
                        },
                    ],
                    review: `Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type.`,
                },
                product: {
                    image: product2,
                    title: "Headphone",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#992",
                reviewer: {
                    image: user13,
                    name: "Donna Miller",
                    email: "donna@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-line",
                        },
                    ],
                    review: `It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.`,
                },
                product: {
                    image: product3,
                    title: "iPhone 15 Plus",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#991",
                reviewer: {
                    image: user14,
                    name: "Barbara Cross",
                    email: "barbara@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-half-fill",
                        },
                        {
                            star: "ri-star-line",
                        },
                    ],
                    review: `It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing.`,
                },
                product: {
                    image: product4,
                    title: "Bluetooth Speaker",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
            {
                id: "#990",
                reviewer: {
                    image: user15,
                    name: "Rebecca Block",
                    email: "rebecca@trezo.com",
                },
                ratings: {
                    stars: [
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                        {
                            star: "ri-star-fill",
                        },
                    ],
                    review: `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.`,
                },
                product: {
                    image: product5,
                    title: "Airbuds 2nd Gen",
                },
                date: {
                    date: "17 Dec 2024",
                    time: "08:30 PM",
                },
                status: "Pending",
                action: {
                    approved: "download_done",
                    delete: "delete",
                    reply: "reply",
                },
            },
        ]);

        const wordPending = ref("Pending");
        const wordPublished = ref("Published");

        const computeClass = (classValue) => {
            return {
                published: wordPending.value === classValue,
                warning: wordPublished.value === classValue,
            };
        };

        return {
            items,
            computeClass,
        };
    },
});
</script>

<style lang="scss" scoped>
.reviews-card {
    .trezo-table-content {
        .trezo-table {
            .v-table {
                table {
                    tbody {
                        tr {
                            td {
                                vertical-align: top !important;
                            }
                        }
                    }
                }
            }
            .pagination-content {
                margin-top: 0;
                padding: 15px 20px;
                border-radius: 0 0 7px 7px;
                color: var(--blackColor) !important;
                background-color: transparent !important;
                border-left: 1px solid #eceef2;
                border-right: 1px solid #eceef2;
                border-bottom: 1px solid #eceef2;
            }
        }
    }
}
</style>

// react-nextjs-material-ui/src/components/LMS/CoursesDetails/Reviews/ManageReviews.tsx
"use client";

import * as React from "react";
import Image from "next/image";
import {
  Card,
  Box,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableFooter,
  TablePagination,
  TableRow,
  Paper,
  IconButton,
  TableHead,
  Tooltip,
} from "@mui/material";
import { useTheme } from "@mui/material/styles";
import KeyboardArrowLeft from "@mui/icons-material/KeyboardArrowLeft";
import KeyboardArrowRight from "@mui/icons-material/KeyboardArrowRight";

interface TablePaginationActionsProps {
  count: number;
  page: number;
  rowsPerPage: number;
  onPageChange: (
    event: React.MouseEvent<HTMLButtonElement>,
    newPage: number
  ) => void;
}

function TablePaginationActions(props: TablePaginationActionsProps) {
  const theme = useTheme();
  const { count, page, rowsPerPage, onPageChange } = props;

  const handleBackButtonClick = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    onPageChange(event, page - 1);
  };

  const handleNextButtonClick = (
    event: React.MouseEvent<HTMLButtonElement>
  ) => {
    onPageChange(event, page + 1);
  };

  return (
    <Box
      sx={{
        flexShrink: 0,
        display: "flex",
        gap: "10px",
        padding: "14px 20px",
      }}
    >
      <IconButton
        onClick={handleBackButtonClick}
        disabled={page === 0}
        aria-label="previous page"
        sx={{
          borderRadius: "4px",
          padding: "6px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowRight />
        ) : (
          <KeyboardArrowLeft />
        )}
      </IconButton>

      <IconButton
        onClick={handleNextButtonClick}
        disabled={page >= Math.ceil(count / rowsPerPage) - 1}
        aria-label="next page"
        sx={{
          borderRadius: "4px",
          padding: "6px",
        }}
        className="border"
      >
        {theme.direction === "rtl" ? (
          <KeyboardArrowLeft />
        ) : (
          <KeyboardArrowRight />
        )}
      </IconButton>
    </Box>
  );
}

interface Rating {
  stars: string;
}

interface Reviews {
  id: number;
  reviewerImg: string;
  reviewerName: string;
  email: string;
  ratings: Rating[];
  review: string;
  date: string;
  time: string;
  status: string;
}

function createData(
  id: number,
  reviewerImg: string,
  reviewerName: string,
  email: string,
  ratings: Rating[],
  review: string,
  date: string,
  time: string,
  status: string
): Reviews {
  return {
    id,
    reviewerImg,
    reviewerName,
    email,
    ratings,
    review,
    date,
    time,
    status,
  };
}

const rows = [
  createData(
    1,
    "/images/users/user6.jpg",
    "Olivia Clark",
    "olivia@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
  createData(
    2,
    "/images/users/user7.jpg",
    "Zephyr Zing",
    "zephyr@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
  createData(
    3,
    "/images/users/user8.jpg",
    "Nova Nectar",
    "nova@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Published"
  ),
  createData(
    4,
    "/images/users/user9.jpg",
    "Isabella Chang",
    "isabella@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
  createData(
    5,
    "/images/users/user9.jpg",
    "Isabella Chang",
    "isabella@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
  createData(
    6,
    "/images/users/user6.jpg",
    "Olivia Clark",
    "olivia@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Published"
  ),
  createData(
    7,
    "/images/users/user7.jpg",
    "Zephyr Zing",
    "zephyr@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
  createData(
    8,
    "/images/users/user8.jpg",
    "Nova Nectar",
    "nova@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
  createData(
    9,
    "/images/users/user9.jpg",
    "Isabella Chang",
    "isabella@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
  createData(
    10,
    "/images/users/user9.jpg",
    "Isabella Chang",
    "isabella@trezo.com",
    [
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
      {
        stars: "ri-star-fill",
      },
    ],
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    "17 Dec 2024",
    "08:30 PM",
    "Pending"
  ),
].sort((b, a) => (a.id < b.id ? -1 : 1));

const ManageReviews: React.FC = () => {
  // Table
  const [page, setPage] = React.useState(0);
  const [rowsPerPage, setRowsPerPage] = React.useState(5);

  // Avoid a layout jump when reaching the last page with empty rows.
  const emptyRows =
    page > 0 ? Math.max(0, (1 + page) * rowsPerPage - rows.length) : 0;

  const handleChangePage = (
    event: React.MouseEvent<HTMLButtonElement> | null,
    newPage: number
  ) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (
    event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: { xs: "block", sm: "flex" },
            alignItems: "center",
            justifyContent: "space-between",
            mb: "25px",
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Manage Reviews
          </Typography>
        </Box>

        {/* Table */}
        <TableContainer
          component={Paper}
          sx={{
            boxShadow: "none",
            borderRadius: "7px",
          }}
          className="rmui-table border"
        >
          <Table sx={{ minWidth: 1000 }} aria-label="Table">
            <TableHead className="bg-f6f7f9">
              <TableRow>
                <TableCell
                  sx={{
                    fontWeight: "500",
                    padding: "10px 20px",
                    fontSize: "14px",
                  }}
                  className="text-black border-bottom"
                >
                  Reviewer
                </TableCell>

                <TableCell
                  sx={{
                    fontWeight: "500",
                    padding: "10px 20px",
                    fontSize: "14px",
                  }}
                  className="text-black border-bottom"
                >
                  Review
                </TableCell>

                <TableCell
                  sx={{
                    fontWeight: "500",
                    padding: "10px 20px",
                    fontSize: "14px",
                  }}
                  className="text-black border-bottom"
                >
                  Date
                </TableCell>

                <TableCell
                  sx={{
                    fontWeight: "500",
                    padding: "10px 20px",
                    fontSize: "14px",
                  }}
                  className="text-black border-bottom"
                >
                  Status
                </TableCell>

                <TableCell
                  sx={{
                    fontWeight: "500",
                    padding: "10px 20px",
                    fontSize: "14px",
                  }}
                  className="text-black border-bottom"
                >
                  Action
                </TableCell>
              </TableRow>
            </TableHead>

            <TableBody>
              {(rowsPerPage > 0
                ? rows.slice(
                    page * rowsPerPage,
                    page * rowsPerPage + rowsPerPage
                  )
                : rows
              ).map((row) => (
                <TableRow key={row.id}>
                  <TableCell
                    sx={{
                      padding: "14px 20px",
                      fontSize: "14px",
                      verticalAlign: "top",
                    }}
                    className="text-black border-bottom"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                        gap: "13px",
                      }}
                    >
                      <Box sx={{ flexShrink: "0" }}>
                        <Image
                          src={row.reviewerImg}
                          alt="Product"
                          width={40}
                          height={40}
                          style={{ borderRadius: "100px" }}
                        />
                      </Box>

                      <Box>
                        <Typography
                          sx={{
                            fontSize: "15px",
                            fontWeight: "500",
                          }}
                          className="text-black"
                        >
                          {row.reviewerName}
                        </Typography>

                        <Typography
                          sx={{
                            fontSize: "13px",
                          }}
                        >
                          {row.email}
                        </Typography>
                      </Box>
                    </Box>
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "14px 20px",
                      fontSize: "14px",
                      verticalAlign: "top",
                    }}
                    className="text-black border-bottom"
                  >
                    <Box>
                      <Box
                        sx={{
                          display: "flex",
                          alignItems: "center",
                          gap: "2px",
                        }}
                      >
                        {row.ratings.map((rating, index) => (
                          <i
                            key={index}
                            className={rating.stars}
                            style={{ color: "#ee8336", fontSize: "18px" }}
                          />
                        ))}
                      </Box>

                      <Box sx={{ width: "350px", mt: "5px" }}>
                        <Typography
                          sx={{
                            fontSize: "13px",
                          }}
                        >
                          {row.review}
                        </Typography>
                      </Box>
                    </Box>
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "14px 20px",
                      fontSize: "14px",
                      verticalAlign: "top",
                    }}
                    className="border-bottom"
                  >
                    {row.date}
                    <Typography
                      sx={{
                        fontSize: "13px",
                      }}
                    >
                      {row.time}
                    </Typography>
                  </TableCell>

                  <TableCell
                    sx={{
                      borderBottom: "1px solid #eceef2",
                      padding: "14px 20px",
                      verticalAlign: "top",
                    }}
                    className="border-bottom"
                  >
                    <div className={`trezo-badge ${row.status}`}>
                      {row.status}
                    </div>
                  </TableCell>

                  <TableCell
                    sx={{
                      padding: "14px 20px",
                      fontSize: "14px",
                      verticalAlign: "top",
                    }}
                    className="text-black border-bottom"
                  >
                    <Box
                      sx={{
                        display: "flex",
                        alignItems: "center",
                      }}
                    >
                      <Tooltip title="Approved">
                        <IconButton
                          aria-label="view"
                          color="primary"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            download_done
                          </i>
                        </IconButton>
                      </Tooltip>

                      <Tooltip title="Reply">
                        <IconButton
                          aria-label="edit"
                          color="secondary"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            reply
                          </i>
                        </IconButton>
                      </Tooltip>

                      <Tooltip title="Delete">
                        <IconButton
                          aria-label="delete"
                          color="error"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            delete
                          </i>
                        </IconButton>
                      </Tooltip>
                    </Box>
                  </TableCell>
                </TableRow>
              ))}
              {emptyRows > 0 && (
                <TableRow style={{ height: 53 * emptyRows }}>
                  <TableCell className="border-bottom" colSpan={5} />
                </TableRow>
              )}
            </TableBody>

            <TableFooter>
              <TableRow>
                <TablePagination
                  rowsPerPageOptions={[5, 10, 25, { label: "All", value: -1 }]}
                  colSpan={5}
                  count={rows.length}
                  rowsPerPage={rowsPerPage}
                  page={page}
                  slotProps={{
                    select: {
                      inputProps: {
                        "aria-label": "rows per page",
                      },
                      native: true,
                    },
                  }}
                  onPageChange={handleChangePage}
                  onRowsPerPageChange={handleChangeRowsPerPage}
                  ActionsComponent={TablePaginationActions}
                  sx={{
                    border: "none",
                  }}
                />
              </TableRow>
            </TableFooter>
          </Table>
        </TableContainer>
      </Card>
    </>
  );
};

export default ManageReviews;
