// laravel-vuetify/resources/components/Dashboard/Podcast/TopPodcasts.vue
<template>
    <v-card
        class="top-podcasts-card trezo-card custom-shadow rounded-3 bg-white border p-0"
        style="padding-bottom: 18px"
    >
        <div class="v-card-header mb-0" style="padding: 20px 25px">
            <h3 class="mb-0 fs-18 fw-semibold">Top Podcasts</h3>
            <div
                class="dropdown select-dropdown without-border position-relative"
                style="right: -5px"
            >
                <v-menu>
                    <template v-slot:activator="{ props }">
                        <button
                            type="button"
                            v-bind="props"
                            class="card-header-menu text-body border-none d-inline-block border-radius"
                        >
                            Last 28 days
                        </button>
                    </template>
                    <v-list class="menu-content">
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            Last 28 days
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            Last 48 days
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            Last 90 days
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            Last Year
                        </button>
                    </v-list>
                </v-menu>
            </div>
        </div>

        <div
            class="default-table-area style-three style-two top-podcasts pb-10"
        >
            <div class="table-responsive">
                <table
                    class="table align-middle border-0"
                    border="0"
                    cellspacing="0"
                    cellpadding="0"
                >
                    <thead>
                        <tr>
                            <th
                                scope="col"
                                class="bg-body-bg"
                                style="
                                    padding-top: 6.5px;
                                    padding-bottom: 6.5px;
                                "
                            >
                                <span class="fs-12 fw-medium text-body"
                                    >Name</span
                                >
                            </th>
                            <th
                                scope="col"
                                class="bg-body-bg"
                                style="
                                    padding-top: 6.5px;
                                    padding-bottom: 6.5px;
                                "
                            >
                                <span class="fs-12 fw-medium text-body"
                                    >Episodes</span
                                >
                            </th>
                            <th
                                scope="col"
                                class="bg-body-bg"
                                style="
                                    padding-top: 6.5px;
                                    padding-bottom: 6.5px;
                                "
                            >
                                <span class="fs-12 fw-medium text-body"
                                    >Earnings</span
                                >
                            </th>
                            <th
                                scope="col"
                                class="bg-body-bg"
                                style="
                                    padding-top: 6.5px;
                                    padding-bottom: 6.5px;
                                "
                            >
                                <span class="fs-12 fw-medium text-body"
                                    >Ratings</span
                                >
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="(podcast, index) in podcasts" :key="index">
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <div class="flex-shrink-0">
                                        <v-img
                                            :src="podcast.image"
                                            class="wh-44 rounded-circle"
                                            alt="user"
                                        />
                                    </div>
                                    <div
                                        class="flex-grow-1 ms-10 position-relative top-2"
                                    >
                                        <h6 class="mb-0 fs-14 fw-medium">
                                            {{ podcast.name }}
                                        </h6>
                                        <span class="fs-12 text-body">{{
                                            podcast.role
                                        }}</span>
                                    </div>
                                </div>
                            </td>
                            <td class="border-bottom">
                                <span class="fs-14 fw-medium">{{
                                    podcast.episodes
                                }}</span>
                            </td>
                            <td class="border-bottom">
                                <span class="fs-14 fw-medium">{{
                                    podcast.earnings
                                }}</span>
                            </td>
                            <td class="border-bottom">
                                <ul class="ps-0 mb-0 list-unstyled d-flex ga-1">
                                    <li v-for="star in 5" :key="star">
                                        <i
                                            :class="
                                                getStarClass(
                                                    star,
                                                    podcast.rating
                                                )
                                            "
                                            class="text-orange-darken-2 fs-15"
                                        ></i>
                                    </li>
                                </ul>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent, ref } from "vue";

import user129 from "../../../../public/images/user-129.png";
import user130 from "../../../../public/images/user-130.png";
import user131 from "../../../../public/images/user-131.png";
import user132 from "../../../../public/images/user-132.png";
import user133 from "../../../../public/images/user-133.png";

export default defineComponent({
    name: "TopPodcasts",
    setup() {
        const podcasts = ref([
            {
                image: user129,
                name: "Tom Richards",
                role: "Content Strategist",
                episodes: 95,
                earnings: "$125,000",
                rating: 4.5,
            },
            {
                image: user130,
                name: "Amanda Garcia",
                role: "Social Media",
                episodes: 110,
                earnings: "$140,000",
                rating: 4.5,
            },
            {
                image: user131,
                name: "Lisa Kim",
                role: "Branding Consultant",
                episodes: 85,
                earnings: "$160,000",
                rating: 4,
            },
            {
                image: user132,
                name: "Michael Young",
                role: "Data Analytics",
                episodes: 130,
                earnings: "$90,000",
                rating: 3.5,
            },
            {
                image: user133,
                name: "Ravi Patel",
                role: "SEO & SEM",
                episodes: 75,
                earnings: "$85,000",
                rating: 3,
            },
        ]);

        // Function to determine star icons based on rating
        const getStarClass = (star, rating) => {
            if (star <= Math.floor(rating)) {
                return "ri-star-fill text-rating-color";
            } else if (star === Math.ceil(rating) && rating % 1 !== 0) {
                return "ri-star-half-line text-rating-color";
            } else {
                return "ri-star-line text-rating-color";
            }
        };

        return {
            podcasts,
            getStarClass,
        };
    },
});
</script>

<style lang="scss" scoped>
.v-card {
    &.trezo-card {
        border: 1px solid var(--borderColor) !important;
    }
}
</style>

// react-bootstrap/src/components/Dashboard/Podcast/TopPodcasts.js
"use client";

import { useState } from "react";
import { Dropdown } from "react-bootstrap";

const podcastsData = [
  {
    id: 1,
    name: "Tom Richards",
    category: "Content Strategist",
    episodes: 95,
    earnings: "$125,000",
    image: "/images/user-129.png",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Amanda Garcia",
    category: "Social Media",
    episodes: 110,
    earnings: "$140,000",
    image: "/images/user-130.png",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Lisa Kim",
    category: "Branding Consultant",
    episodes: 85,
    earnings: "$160,000",
    image: "/images/user-131.png",
    rating: 4.0,
  },
  {
    id: 4,
    name: "Michael Young",
    category: "Data Analytics",
    episodes: 130,
    earnings: "$90,000",
    image: "/images/user-132.png",
    rating: 3.5,
  },
  {
    id: 5,
    name: "Ravi Patel",
    category: "SEO & SEM",
    episodes: 75,
    earnings: "$85,000",
    image: "/images/user-133.png",
    rating: 3.0,
  },
];

const timeRanges = [
  "Last 28 days",
  "Last 48 days",
  "Last 90 days",
  "Last Year",
];

const TopPodcasts = () => {
  const [selectedTimeRange, setSelectedTimeRange] = useState(timeRanges[0]);

  return (
    <div
      className="card custom-shadow rounded-3 bg-white border mb-4"
      style={{ paddingBottom: "18px" }}
    >
      <div
        className="d-flex justify-content-between align-items-center flex-wrap gap-3 position-relative custom-padding-30"
        style={{
          top: "-5px",
          paddingBottom: "18px"
        }}
      >
        <h3 className="mb-0 fs-18 fw-semibold">Top Podcasts</h3>

        <Dropdown
          className="dropdown select-dropdown without-border position-relative"
          style={{ right: "-10px" }}
        >
          <Dropdown.Toggle
            variant="secondary"
            id="dropdown-basic"
            className="dropdown-toggle bg-transparent border text-body rounded-2"
          >
            {selectedTimeRange} <i className="ri-arrow-down-s-line"></i>
          </Dropdown.Toggle>

          <Dropdown.Menu className="bg-white border box-shadow">
            {timeRanges.map((range, index) => (
              <Dropdown.Item
                key={index}
                onClick={() => setSelectedTimeRange(range)}
                className="text-secondary py-2 px-3"
              >
                {range}
              </Dropdown.Item>
            ))}
          </Dropdown.Menu>
        </Dropdown>
      </div>

      <div className="default-table-area style-three style-two top-podcasts">
        <div className="table-responsive">
          <table className="table align-middle border-0">
            <thead>
              <tr>
                {["Name", "Episodes", "Earnings", "Ratings"].map(
                  (header, index) => (
                    <th
                      key={index}
                      scope="col"
                      className="bg-body-bg"
                      style={{ paddingTop: "6.5px", paddingBottom: "6.5px" }}
                    >
                      <span className="fs-12 fw-medium text-body">
                        {header}
                      </span>
                    </th>
                  )
                )}
              </tr>
            </thead>
            <tbody>
              {podcastsData.map((podcast) => (
                <tr key={podcast.id}>
                  <td>
                    <div className="d-flex align-items-center gap-2">
                      <div className="flex-shrink-0">
                        <img
                          src={podcast.image}
                          className="wh-44 rounded-circle"
                          alt={podcast.name}
                          width={44}
                          height={44}
                        />
                      </div>
                      <div className="flex-grow-1 ms-10 position-relative top-2">
                        <h6 className="mb-0 fs-14 fw-medium">{podcast.name}</h6>
                        <span className="fs-12 text-body">
                          {podcast.category}
                        </span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span className="fs-14 fw-medium text-secondary">
                      {podcast.episodes}
                    </span>
                  </td>
                  <td>
                    <span className="fs-14 fw-medium text-secondary">
                      {podcast.earnings}
                    </span>
                  </td>
                  <td>
                    <ul className="ps-0 mb-0 list-unstyled d-flex gap-1">
                      {Array.from({ length: 5 }).map((_, i) => (
                        <li key={i}>
                          <i
                            className={`ri-star-${
                              i + 1 <= Math.floor(podcast.rating)
                                ? "fill"
                                : i < podcast.rating
                                ? "half-line"
                                : "line"
                            } text-rating-color fs-15`}
                          ></i>
                        </li>
                      ))}
                    </ul>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default TopPodcasts;
