// svelte-bootstrap/src/routes/dashboard/hospital/+page.svelte
<script>
	import BedOccupancyRate from '$lib/components/Dashboard/Hospital/BedOccupancyRate.svelte';
	import CriticalPatients from '$lib/components/Dashboard/Hospital/CriticalPatients.svelte';
	import EmergencyRoomVisits from '$lib/components/Dashboard/Hospital/EmergencyRoomVisits.svelte';
	import HospitalEarnings from '$lib/components/Dashboard/Hospital/HospitalEarnings.svelte';
	import PatientAdmissionsDischarges from '$lib/components/Dashboard/Hospital/PatientAdmissionsDischarges.svelte';
	import PatientAppointments from '$lib/components/Dashboard/Hospital/PatientAppointments.svelte';
	import PatientByAge from '$lib/components/Dashboard/Hospital/PatientByAge.svelte';
	import ScheduleAppointment from '$lib/components/Dashboard/Hospital/ScheduleAppointment.svelte';
	import ScheduleToday from '$lib/components/Dashboard/Hospital/ScheduleToday.svelte';
</script>

<svelte:head>
	<title>Hospital | Trezo - Svelte & Bootsrap 5 Admin Dashboard Template</title>
</svelte:head>

<div class="row">
	<ScheduleToday />
	<PatientAdmissionsDischarges />
</div>

<div class="row">
	<EmergencyRoomVisits />
	<CriticalPatients />
	<BedOccupancyRate />
</div>

<div class="row">
	<PatientAppointments />
	<ScheduleAppointment />
</div>

<div class="row">
	<PatientByAge />
	<HospitalEarnings />
</div>

// react-nextjs-material-ui/src/app/dashboard/hospital/page.tsx
import * as React from "react";
import { Grid } from "@mui/material";
import Welcome from "@/components/Dashboard/Hospital/Welcome";
import PatientAdmissionsDischarges from "@/components/Dashboard/Hospital/PatientAdmissionsDischarges";
import OverallVisitors from "@/components/Dashboard/Hospital/OverallVisitors";
import PatientsLast7Days from "@/components/Dashboard/Hospital/PatientsLast7Days";
import EmergencyRoomVisits from "@/components/Dashboard/Hospital/EmergencyRoomVisits";
import CriticalPatients from "@/components/Dashboard/Hospital/CriticalPatients";
import BedOccupancyRate from "@/components/Dashboard/Hospital/BedOccupancyRate";
import PatientAppointments from "@/components/Dashboard/Hospital/PatientAppointments";
import ScheduleAppointment from "@/components/Dashboard/Hospital/ScheduleAppointment";
import PatientByAge from "@/components/Dashboard/Hospital/PatientByAge";
import HospitalEarnings from "@/components/Dashboard/Hospital/HospitalEarnings";

export default function Page() {
  return (
    <>
      <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 5 }}>
          <Welcome />

          <Grid container columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}>
            <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 6 }}>
              <OverallVisitors />
            </Grid>

            <Grid size={{ xs: 12, sm: 6, md: 6, lg: 6, xl: 6 }}>
              <PatientsLast7Days />
            </Grid>
          </Grid>
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 7 }}>
          <PatientAdmissionsDischarges />
        </Grid>
      </Grid>

      <Grid
        container
        columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}
        justifyContent="center"
      >
        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 5 }}>
          <EmergencyRoomVisits />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 2 }}>
          <CriticalPatients />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 6, lg: 6, xl: 5 }}>
          <BedOccupancyRate />
        </Grid>
      </Grid>

      <Grid
        container
        columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}
        justifyContent="center"
      >
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 8 }}>
          <PatientAppointments />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 4 }}>
          <ScheduleAppointment />
        </Grid>
      </Grid>

      <Grid
        container
        columnSpacing={{ xs: 1, sm: 2, md: 2, lg: 3 }}
        justifyContent="center"
      >
        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 4 }}>
          <PatientByAge />
        </Grid>

        <Grid size={{ xs: 12, sm: 12, md: 12, lg: 12, xl: 8 }}>
          <HospitalEarnings />
        </Grid>
      </Grid>
    </>
  );
}
