// landing-pages/angular-material/src/app/lms-courses-demo/common/cta/cta.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { ToggleService } from '../../../settings/toggle.service';

@Component({
    selector: 'app-cta',
    imports: [RouterLink, MatButtonModule],
    templateUrl: './cta.component.html',
    styleUrl: './cta.component.scss'
})
export class CtaComponent {

    constructor(
        public toggleService: ToggleService
    ) {}

}
<div class="cta-area">
    <div class="container">
        <div
            class="cta-inner-area position-relative z-1"
            [class.component-dark]="toggleService.isLandingDark()"
            [class.component-rtl]="toggleService.isLandingRtlEnabled()"
        >
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="cta-content">
                        <h2 class="fw-bold">
                            Join Thousands of Learners Advancing Their Careers
                        </h2>
                        <a routerLink="/lms-courses-demo/courses" class="lms-default-btn" mat-button>
                            <i class="material-symbols-outlined">
                                school
                            </i>
                            Start Learning Now
                        </a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="cta-image">
                        <img src="images/lms-courses/learning.png" alt="learning-image">
                    </div>
                </div>
            </div>
            <div class="shape1">
                <img src="images/lms-courses/shapes/shape3.png" alt="shape">
            </div>
            <div class="shape2">
                <img src="images/lms-courses/shapes/shape4.png" alt="shape">
            </div>
        </div>
    </div>
</div>

// landing-pages/react-nextjs-bootstrap/lms-landing/src/components/Common/Cta.js
"use client";

import React from "react";
import Image from "next/image";
import Link from "next/link";
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

const Cta = () => {
  return (
    <>
      <div className="advancing-lms-area bg-fffef8 pb-180">
        <Container className="cmw-1308">
          <div className="advancing-lms-wrap">
            <Row className="g-4 align-items-center">
              <Col md={6}>
                <div className="advancing-lms-content">
                  <h2>Join Thousands of Learners Advancing Their Careers</h2>

                  <div className="d-inline-block">
                    <Link
                      href="#"
                      className="btn btn-primary-50 landing-page-btn fw-medium fs-16 rounded-2 d-flex align-items-center pyx-11-18"
                      style={{
                        gap: "10px",
                      }}
                    >
                      <i className="material-symbols-outlined fs-24">school</i>
                      <span>Start Learning Now</span>
                    </Link>
                  </div>
                </div>
              </Col>

              <Col md={6}>
                <div className="advancing-lms-img position-relative text-md-end text-center">
                  <Image
                    src="/images/learning.png"
                    alt="learning"
                    width={343}
                    height={324}
                  />
                  <Image
                    src="/images/shapes/shape3.png"
                    className="position-absolute shape3"
                    alt="shape3"
                    width={92}
                    height={47}
                  />
                  <Image
                    src="/images/shapes/shape3.png"
                    className="position-absolute shape4"
                    alt="shape3"
                    width={92}
                    height={47}
                  />
                </div>
              </Col>
            </Row>
          </div>
        </Container>
      </div>
    </>
  );
};

export default Cta;
