// laravel-vuetify/resources/components/Dashboard/Finance/TransactionHistory.vue
<template>
    <v-card
        class="transaction-history-card trezo-card border-radius d-block border-0 shadow-none p-0"
    >
        <div class="v-card-header mb-0 p-25">
            <h5 class="mb-0">Transaction History</h5>
            <div class="d-flex align-items-center">
                <v-menu>
                    <template v-slot:activator="{ props }">
                        <button
                            type="button"
                            v-bind="props"
                            class="bg-white card-header-menu d-inline-block border-radius"
                        >
                            Last 30 days
                        </button>
                    </template>
                    <v-list class="menu-content">
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            Last 30 days
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            Last 90 days
                        </button>
                        <button
                            type="button"
                            class="bg-transparent border-none"
                        >
                            Last 1 year
                        </button>
                    </v-list>
                </v-menu>
            </div>
        </div>

        <div class="default-table-area style-two transaction-history">
            <div class="table-responsive">
                <table
                    class="table align-middle"
                    border="0"
                    cellspacing="0"
                    cellpadding="0"
                >
                    <thead>
                        <tr>
                            <th>
                                <div class="d-flex align-items-center">
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            value=""
                                            id="flexCheckDefault"
                                        />
                                    </div>
                                    <span class="ms-1">
                                        <span class="fs-12 fw-bold"
                                            >Transaction</span
                                        >
                                        ID
                                    </span>
                                </div>
                            </th>
                            <th>Date</th>
                            <th>Description</th>
                            <th>Amount</th>
                            <th>Type</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            value=""
                                            id="flexCheckDefault2"
                                        />
                                    </div>
                                    <span class="ms-1">#TID0015</span>
                                </div>
                            </td>
                            <td class="border-bottom">2024-10-01</td>
                            <td class="border-bottom">Payment from Client</td>
                            <td class="text-primary border-bottom">$5,000</td>
                            <td class="border-bottom">Income</td>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center ga-1">
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-primary"
                                        >
                                            visibility
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-body"
                                        >
                                            edit
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-danger"
                                        >
                                            delete
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            value=""
                                            id="flexCheckDefault2"
                                        />
                                    </div>
                                    <span class="ms-1">#TID0099</span>
                                </div>
                            </td>
                            <td class="border-bottom">2024-09-28</td>
                            <td class="border-bottom">Office Supplies</td>
                            <td class="text-primary border-bottom">$10,000</td>
                            <td class="border-bottom">Expense</td>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center ga-1">
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-primary"
                                        >
                                            visibility
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-body"
                                        >
                                            edit
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-danger"
                                        >
                                            delete
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            value=""
                                            id="flexCheckDefault2"
                                        />
                                    </div>
                                    <span class="ms-1">#TID0145</span>
                                </div>
                            </td>
                            <td class="border-bottom">2024-09-25</td>
                            <td class="border-bottom">Website Maintenance</td>
                            <td class="text-primary border-bottom">$35,000</td>
                            <td class="border-bottom">Expense</td>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center ga-1">
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-primary"
                                        >
                                            visibility
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-body"
                                        >
                                            edit
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-danger"
                                        >
                                            delete
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            value=""
                                            id="flexCheckDefault2"
                                        />
                                    </div>
                                    <span class="ms-1">#TID0247</span>
                                </div>
                            </td>
                            <td class="border-bottom">2024-09-22</td>
                            <td class="border-bottom">Payment from Client</td>
                            <td class="text-primary border-bottom">$2,000</td>
                            <td class="border-bottom">Income</td>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center ga-1">
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-primary"
                                        >
                                            visibility
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-body"
                                        >
                                            edit
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-danger"
                                        >
                                            delete
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center">
                                    <div class="form-check">
                                        <input
                                            class="form-check-input"
                                            type="checkbox"
                                            value=""
                                            id="flexCheckDefault2"
                                        />
                                    </div>
                                    <span class="ms-1">#TID0299</span>
                                </div>
                            </td>
                            <td class="border-bottom">2024-09-20</td>
                            <td class="border-bottom">Advertising Campaign</td>
                            <td class="text-primary border-bottom">$15,500</td>
                            <td class="border-bottom">Expense</td>
                            <td class="border-bottom">
                                <div class="d-flex align-items-center ga-1">
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-primary"
                                        >
                                            visibility
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-body"
                                        >
                                            edit
                                        </i>
                                    </button>
                                    <button
                                        class="ps-0 border-0 bg-transparent lh-1 position-relative top-2"
                                    >
                                        <i
                                            class="material-symbols-outlined fs-16 text-danger"
                                        >
                                            delete
                                        </i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <Pagination items="05" total="30" class="p-14 border-0" />
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";
import Pagination from "../../Common/Pagination.vue";

export default defineComponent({
    name: "TransactionHistory",
    components: {
        Pagination,
    },
});
</script>

<style lang="scss" scoped>
.transaction-history-card {
    .form-check {
        .form-check-input {
            width: 16px;
            height: 16px;
            cursor: pointer;
            position: relative;
            top: 3px;
        }
    }
}
.p-14 {
    padding: 14px;
}
</style>

// svelte-bootstrap/src/lib/components/Dashboard/Finance/TransactionHistory.svelte
<div class="card-body p-0">
	<div class="d-flex justify-content-between align-items-center flex-wrap gap-3 p-4">
		<h3 class="mb-0">Transaction History</h3>
		<select
			class="form-select month-select form-control w-135 bg-border-color border-color bg-transparent"
			aria-label="Default select example"
		>
			<option selected>Last 30 days</option>
			<option value="1">Last 90 days</option>
			<option value="2">Last 1 year</option>
		</select>
	</div>

	<div class="default-table-area style-two transaction-history">
		<div class="table-responsive">
			<table class="table align-middle">
				<thead>
					<tr>
						<th scope="col">
							<div class="d-flex align-items-center">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" />
								</div>
								<span class="ms-1"><span class="fs-12 fw-bold">Transaction</span> ID</span>
							</div>
						</th>
						<th scope="col">Date</th>
						<th scope="col">Description</th>
						<th scope="col">Amount</th>
						<th scope="col">Type</th>
						<th scope="col">Action</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>
							<div class="d-flex align-items-center">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault2" />
								</div>
								<span class="ms-1 text-secondary">#TID0015</span>
							</div>
						</td>
						<td>2024-10-01</td>
						<td>Payment from Client</td>
						<td class="text-primary">$5,000</td>
						<td>Income</td>
						<td>
							<div class="d-flex align-items-center gap-1">
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-body">edit</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-danger">delete</i>
								</button>
							</div>
						</td>
					</tr>
					<tr>
						<td>
							<div class="d-flex align-items-center">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault2" />
								</div>
								<span class="ms-1 text-secondary">#TID0099</span>
							</div>
						</td>
						<td>2024-09-28</td>
						<td>Office Supplies</td>
						<td class="text-primary">$10,000</td>
						<td>Expense</td>
						<td>
							<div class="d-flex align-items-center gap-1">
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-body">edit</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-danger">delete</i>
								</button>
							</div>
						</td>
					</tr>
					<tr>
						<td>
							<div class="d-flex align-items-center">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault2" />
								</div>
								<span class="ms-1 text-secondary">#TID0145</span>
							</div>
						</td>
						<td>2024-09-25</td>
						<td>Website Maintenance</td>
						<td class="text-primary">$35,000</td>
						<td>Expense</td>
						<td>
							<div class="d-flex align-items-center gap-1">
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-body">edit</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-danger">delete</i>
								</button>
							</div>
						</td>
					</tr>
					<tr>
						<td>
							<div class="d-flex align-items-center">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault2" />
								</div>
								<span class="ms-1 text-secondary">#TID0247</span>
							</div>
						</td>
						<td>2024-09-22</td>
						<td>Payment from Client</td>
						<td class="text-primary">$2,000</td>
						<td>Income</td>
						<td>
							<div class="d-flex align-items-center gap-1">
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-body">edit</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-danger">delete</i>
								</button>
							</div>
						</td>
					</tr>
					<tr>
						<td>
							<div class="d-flex align-items-center">
								<div class="form-check">
									<input class="form-check-input" type="checkbox" value="" id="flexCheckDefault2" />
								</div>
								<span class="ms-1 text-secondary">#TID0299</span>
							</div>
						</td>
						<td>2024-09-20</td>
						<td>Advertising Campaign</td>
						<td class="text-primary">$15,500</td>
						<td>Expense</td>
						<td>
							<div class="d-flex align-items-center gap-1">
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-primary">visibility</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-body">edit</i>
								</button>
								<button class="ps-0 border-0 bg-transparent lh-1 position-relative top-2">
									<i class="material-symbols-outlined fs-16 text-danger">delete</i>
								</button>
							</div>
						</td>
					</tr>
				</tbody>
			</table>
		</div>

		<div
			class="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap p-4"
		>
			<span class="fs-12 fw-medium">Showing 5 of 30 Results</span>

			<nav aria-label="Page navigation example">
				<ul class="pagination mb-0 justify-content-center">
					<li class="page-item">
						<a class="page-link icon" href="/dashboard/finance" aria-label="Previous">
							<i class="material-symbols-outlined">keyboard_arrow_left</i>
						</a>
					</li>
					<li class="page-item"><a class="page-link active" href="/dashboard/finance">1</a></li>
					<li class="page-item"><a class="page-link" href="/dashboard/finance">2</a></li>
					<li class="page-item"><a class="page-link" href="/dashboard/finance">3</a></li>
					<li class="page-item"><a class="page-link" href="/dashboard/finance">4</a></li>
					<li class="page-item">
						<a class="page-link icon" href="/dashboard/finance" aria-label="Next">
							<i class="material-symbols-outlined">keyboard_arrow_right</i>
						</a>
					</li>
				</ul>
			</nav>
		</div>
	</div>
</div>
