// vuejs-vuetify/src/components/Dashboard/CryptoPerformance/CryptoMarketCap.vue
<template>
  <v-card
    class="crypto-market-cap-card trezo-card mb-25 border-radius d-block border-0 shadow-none"
  >
    <div
      class="trezo-card-content d-flex align-items-center justify-content-between"
    >
      <div>
        <span class="d-block"> Crypto Market Cap </span>
        <h5 class="mb-0">$2.64T</h5>
      </div>
      <div
        class="icon rounded-circle bg-white text-purple d-flex align-items-center justify-content-center"
      >
        <i class="material-symbols-outlined"> payments </i>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "CryptoMarketCap",
});
</script>

<style lang="scss" scoped>
.crypto-market-cap-card {
  &.v-card {
    &.trezo-card {
      background-color: #f3e8ff;
    }
  }
  padding: {
    top: 15px !important;
    bottom: 15px !important;
  }
  .trezo-card-content {
    h5 {
      margin-top: 4px;
      font-size: 20px;
    }
    .icon {
      width: 53px;
      height: 53px;
    }
  }
}
</style>

// react-nextjs-material-ui/src/components/Dashboard/CryptoPerformance/CryptoMarketCap.tsx
"use client";

import React from "react";
import { Card, Box, Typography } from "@mui/material";

const CryptoMarketCap: React.FC = () => {
  return (
    <>
      <Card
        sx={{
          backgroundColor: "#F3E8FF",
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          paddingY: { xs: "18px", sm: "20px", lg: "15px" },
          paddingX: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card for-dark-bg-162243"
      >
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            gap: "10px",
          }}
        >
          <Box>
            <Typography sx={{ mb: "3px" }}>Crypto Market Cap</Typography>

            <Typography
              variant="h5"
              sx={{ fontWeight: "700", fontSize: { xs: "18px", md: "20px" } }}
            >
              $2.64T
            </Typography>
          </Box>

          <Box
            className="bg-white"
            sx={{
              width: "53px",
              height: "53px",
              borderRadius: "50%",
              color: "purple.main",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              flexShrink: 0,
            }}
          >
            <i className="material-symbols-outlined">payments</i>
          </Box>
        </Box>
      </Card>
    </>
  );
};

export default CryptoMarketCap;
