// angular-material/src/app/dashboard/credit-card/my-cards/my-cards.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatNativeDateModule } from '@angular/material/core';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-my-cards',
    imports: [MatCardModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule, MatDatepickerModule, MatNativeDateModule],
    templateUrl: './my-cards.component.html',
    styleUrl: './my-cards.component.scss'
})
export class MyCardsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

    // Popup Trigger
    classApplied = false;
    toggleClass() {
        this.classApplied = !this.classApplied;
    }

}
<!-- My Cards -->
<mat-card
    class="my-cards-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    style="background-image: url(images/cards-bg.jpg);"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                My Cards
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button class="add-btn" type="button" mat-button (click)="toggleClass()">
                <i class="material-symbols-outlined">
                    add
                </i>
                Add Card
            </button>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <div class="row">
            <div class="col-sm-6">
                <div
                    class="card-item border-radius bg-primary"
                    style="background-image: url(images/wallet/card3.jpg);"
                >
                    <div class="d-flex justify-content-between">
                        <div class="title">
                            <div class="d-block text-white text-xs">
                                Credit Card
                            </div>
                            <img src="images/icons/card-frame.png" alt="card-frame">
                        </div>
                        <div class="icon lh-1 text-white">
                            <i class="ri-visa-fill"></i>
                        </div>
                    </div>
                    <h5 class="text-white fw-semibold">
                        **** **** **** 1784
                    </h5>
                    <div class="d-flex justify-content-between align-items-center">
                        <span class="d-block lh-1 text-white">
                            Russell McCray
                        </span>
                        <span class="d-block lh-1 text-white text-xs">
                            EXP : 12/30
                        </span>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div
                    class="card-item border-radius bg-primary"
                    style="background-image: url(images/wallet/card4.jpg);"
                >
                    <div class="d-flex justify-content-between">
                        <div class="title">
                            <div class="d-block text-white text-xs">
                                Credit Card
                            </div>
                            <img src="images/icons/card-frame.png" alt="card-frame">
                        </div>
                        <div class="icon lh-1 text-white">
                            <i class="ri-mastercard-fill"></i>
                        </div>
                    </div>
                    <h5 class="text-white fw-semibold">
                        **** **** **** 1794
                    </h5>
                    <div class="d-flex justify-content-between align-items-center">
                        <span class="d-block lh-1 text-white">
                            Russell McCray
                        </span>
                        <span class="d-block lh-1 text-white text-xs">
                            EXP : 12/30
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </mat-card-content>
</mat-card>

<!-- Add New Popup -->
<div
    class="add-new-popup"
    [class.active]="classApplied"
>
    <div class="popup-dialog">
        <mat-card class="border-radius d-block bg-white border-0 shadow-none">
            <mat-card-header>
                <mat-card-title>
                    <h5 class="mb-0">
                        Add New Card
                    </h5>
                </mat-card-title>
                <mat-card-subtitle>
                    <button
                        mat-button
                        (click)="toggleClass()"
                    >
                        <i class="ri-close-fill"></i>
                    </button>
                </mat-card-subtitle>
            </mat-card-header>
            <mat-card-content>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Full Name
                            </label>
                            <mat-form-field>
                                <mat-label>
                                    Enter name
                                </mat-label>
                                <input matInput>
                            </mat-form-field>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Card Number
                            </label>
                            <mat-form-field>
                                <mat-label>
                                    Enter card number
                                </mat-label>
                                <input matInput>
                            </mat-form-field>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                Expiry Date
                            </label>
                            <mat-form-field>
                                <mat-label>mm/dd/yyyy</mat-label>
                                <input matInput [matDatepicker]="dueDatePicker">
                                <!-- <mat-hint>MM/DD/YYYY</mat-hint> -->
                                <mat-datepicker-toggle matIconSuffix [for]="dueDatePicker"></mat-datepicker-toggle>
                                <mat-datepicker #dueDatePicker></mat-datepicker>
                            </mat-form-field>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label class="main-label d-block fw-medium text-black">
                                CVV
                            </label>
                            <mat-form-field>
                                <mat-label>
                                    Enter cvv
                                </mat-label>
                                <input matInput>
                            </mat-form-field>
                        </div>
                    </div>
                </div>
                <div class="btn-box">
                    <button
                        mat-button
                        (click)="toggleClass()"
                        color="warn"
                    >
                        Cancel
                    </button>
                    <button
                        mat-button
                        color="primary"
                    >
                        <i class="material-symbols-outlined">
                            add
                        </i>
                        Add Card
                    </button>
                </div>
            </mat-card-content>
        </mat-card>
    </div>
</div>

// vuejs-bootstrap/src/components/Dashboard/CreditCard/MyCards.vue
<template>
  <div
    class="card border-0 rounded-3 bg-white p-25 bg-img debit-card-bg-for-dark-mode"
    :style="{ 'background-image': `url(${debitCardBg})` }"
  >
    <div
      class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4"
    >
      <h5 class="mb-0">My Cards</h5>

      <button
        class="btn btn-outline-primary d-flex align-items-center gap-1 hover-bg"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal"
      >
        <i
          class="material-symbols-outlined fs-22"
          style="position: relative; margin-left: -2px"
        >
          add
        </i>
        <span>Add Card</span>
      </button>
    </div>

    <div class="row g-4">
      <div class="col-sm-6">
        <div
          class="bg-img p-4 rounded-3"
          :style="{ 'background-image': `url(${debitCard1})` }"
        >
          <div class="d-flex align-content-center justify-content-between">
            <div>
              <span class="text-white fs-12 fw-medium d-block mb-12">
                Credit Card
              </span>
              <img src="@/assets/images/board-1.png" alt="board" />
            </div>
            <i class="ri-visa-fill fs-35 text-white lh-1"></i>
          </div>

          <h5
            class="fw-semibold text-white mb-12 d-flex gap-1 lh-1"
            style="margin-top: 40px"
          >
            <span>****</span><span>****</span><span>****</span><span>1784</span>
          </h5>
          <div class="d-flex align-content-center justify-content-between">
            <span class="text-white">Russell McCray</span>
            <span class="text-white fs-12">EXP : 12/30</span>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div
          class="bg-img p-4 rounded-3"
          :style="{ 'background-image': `url(${debitCard2})` }"
        >
          <div class="d-flex align-content-center justify-content-between">
            <div>
              <span class="text-white fs-12 fw-medium d-block mb-12">
                Credit Card
              </span>
              <img src="@/assets/images/board-1.png" alt="board" />
            </div>
            <i class="ri-mastercard-fill fs-35 text-white lh-1"></i>
          </div>

          <h5
            class="fw-semibold text-white mb-12 d-flex gap-1 lh-1"
            style="margin-top: 40px"
          >
            <span>****</span><span>****</span><span>****</span><span>1794</span>
          </h5>
          <div class="d-flex align-content-center justify-content-between">
            <span class="text-white">Russell McCray</span>
            <span class="text-white fs-12">EXP : 12/30</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal Card Add -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" style="max-width: 738px">
        <div class="modal-content p-4 p-md-5">
          <div class="modal-header p-0 border-0">
            <h3 class="mb-0">Add Card Detail</h3>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body p-0 pt-4">
            <form>
              <div class="row">
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">Full Name</label>
                    <input
                      type="text"
                      class="form-control h-55"
                      placeholder="Enter name"
                    />
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">Card Number</label>
                    <input
                      type="text"
                      class="form-control h-55"
                      placeholder="Enter card number"
                    />
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">Expiry Date</label>
                    <input type="date" class="form-control h-55" />
                  </div>
                </div>
                <div class="col-sm-6">
                  <div class="mb-4">
                    <label class="label text-secondary">CVV</label>
                    <input
                      type="number"
                      class="form-control h-55"
                      placeholder="212"
                    />
                  </div>
                </div>
              </div>
            </form>
          </div>
          <div class="modal-footer border-0 p-0">
            <button
              type="button"
              class="btn btn-danger text-white px-3"
              data-bs-dismiss="modal"
            >
              Cancel
            </button>
            <button type="button" class="btn btn-primary hover-bg px-3">
              Add Card
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
// import debitCardBg from "@/assets/images/debit-card-bg.jpg";
// import debitCard1 from "@/assets/images/debit-card-2.jpg";
// import debitCard2 from "@/assets/images/debit-card-3.jpg";

export default defineComponent({
  name: "MyCards",
  setup() {
    return {
      debitCardBg: require("@/assets/images/debit-card-bg.jpg"),
      debitCard1: require("@/assets/images/debit-card-2.jpg"),
      debitCard2: require("@/assets/images/debit-card-3.jpg"),
    };
  },
});
</script>
