// vuejs-bootstrap/src/components/Dashboard/BeautySalon/TopSellingProducts.vue
<template>
  <div
    class="top-selling-products-card card mb-4 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-30"
      >
        <h5 class="mb-0">Top Selling Products</h5>
        <select
          class="form-select month-select bg-gray border-0 form-control"
          aria-label="Default select example"
        >
          <option value="This Day">This Day</option>
          <option value="This Week">This Week</option>
          <option value="This Month">This Month</option>
          <option value="This Year">This Year</option>
        </select>
      </div>

      <div class="trezo-card-content position-relative">
        <Swiper
          :slidesPerView="1"
          :spaceBetween="25"
          :centeredSlides="false"
          :preventClicks="true"
          :loop="true"
          :autoplay="{
            delay: 8000,
            disableOnInteraction: false,
            pauseOnMouseEnter: true,
          }"
          :navigation="{
            prevEl: '.prev',
            nextEl: '.next',
          }"
          :breakpoints="{
            0: {
              slidesPerView: 1,
            },
            506: {
              slidesPerView: 2,
            },
            668: {
              slidesPerView: 3,
            },
            705: {
              slidesPerView: 4,
            },
          }"
          :modules="modules"
          class="product-slider"
        >
          <SwiperSlide v-for="product in products" :key="product.id">
            <div class="product-item">
              <RouterLink
                to="/ecommerce/product-details/"
                class="image d-block border-radius"
                :style="{ backgroundImage: `url(${product.image})` }"
              ></RouterLink>
              <div class="content d-flex justify-content-between">
                <div class="title">
                  <h6 class="fw-semibold">
                    <RouterLink to="/ecommerce/product-details/" class='text-black'>
                      {{ product.name }}
                    </RouterLink>
                  </h6>
                  <span class="price d-block fw-semibold">
                    ${{ product.price }}
                  </span>
                </div>
                <div class="sold">
                  <span class="trezo-badge shipped"> {{ product.sold }} </span>
                  <span class="d-block"> sold </span>
                </div>
              </div>
            </div>
          </SwiperSlide>
        </Swiper>

        <div class="product-controller">
          <div class="controller-icon prev">
            <i class="ri-arrow-left-line"></i>
          </div>
          <div class="controller-icon next">
            <i class="ri-arrow-right-line"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { Swiper, SwiperSlide } from "swiper/vue";
import { Autoplay, Navigation } from "swiper/modules";

export default defineComponent({
  name: "TopSellingProducts",
  components: {
    Swiper,
    SwiperSlide,
  },

  setup() {
    const products = ref([
      {
        id: 1,
        name: "Hair Treatment",
        image: require("@/assets/images/products/product24.jpg"),
        price: 23.5,
        sold: 321,
      },
      {
        id: 2,
        name: "Facial Kit",
        image: require("@/assets/images/products/product25.jpg"),
        price: 20.5,
        sold: 124,
      },
      {
        id: 3,
        name: "Winter Cream",
        image: require("@/assets/images/products/product26.jpg"),
        price: 12.43,
        sold: 99,
      },
      {
        id: 4,
        name: "Perfume",
        image: require("@/assets/images/products/product27.jpg"),
        price: 22.12,
        sold: 23,
      },
      {
        id: 5,
        name: "Hair Treatment",
        image: require("@/assets/images/products/product24.jpg"),
        price: 23.5,
        sold: 321,
      },
      {
        id: 6,
        name: "Facial Kit",
        image: require("@/assets/images/products/product25.jpg"),
        price: 20.5,
        sold: 124,
      },
      {
        id: 7,
        name: "Winter Cream",
        image: require("@/assets/images/products/product26.jpg"),
        price: 12.43,
        sold: 99,
      },
      {
        id: 9,
        name: "Perfume",
        image: require("@/assets/images/products/product27.jpg"),
        price: 22.12,
        sold: 23,
      },
    ]);

    return {
      modules: [Autoplay, Navigation],
      products,
    };
  },
});
</script>

<style lang="scss" scoped>
.top-selling-products-card {
  .trezo-card-content {
    .product-item {
      .image {
        height: 179px;
        border-radius: 5px;
        background: {
          position: center center;
          repeat: no-repeat;
          size: cover;
        }
      }
      .content {
        margin-top: 18px;

        .title {
          h6 {
            font-size: 14px;
            margin-bottom: 2px;
            a {
              color: var(--blackColor);
            }
          }
          .price {
            color: #3225ae;
          }
        }
        .sold {
          text-align: center;

          .trezo-badge {
            border-radius: 30px;
            margin-bottom: 2px;
            padding: 0 10px;
          }
          span {
            font-size: 12px;
          }
        }
      }
    }
  }
}
</style>

// react-nextjs-material-ui/src/components/Dashboard/BeautySalon/TopSellingProducts/index.tsx
"use client";

import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation } from "swiper/modules";
import Image from "next/image";
import Link from "next/link";
import { Card, Box, Typography, Avatar, AvatarGroup } from "@mui/material";
import CustomDropdown from "./CustomDropdown";

interface Product {
  id: number;
  image: string;
  name: string;
  viewDetails: string;
  sold: number;
  price: number;
}

const TopSellingProducts: React.FC = () => {
  const products = [
    {
      id: 1,
      image: "/images/beauty-salon/product-1.png",
      name: "Hair Treatment",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 321,
      price: 23.5,
    },
    {
      id: 2,
      image: "/images/beauty-salon/product-2.png",
      name: "Facial Kit",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 124,
      price: 20.5,
    },
    {
      id: 3,
      image: "/images/beauty-salon/product-3.png",
      name: "Winter Cream",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 76,
      price: 25.5,
    },
    {
      id: 4,
      image: "/images/beauty-salon/product-4.png",
      name: "Perfume",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 24,
      price: 30.5,
    },
    {
      id: 5,
      image: "/images/beauty-salon/product-5.png",
      name: "Face Wash",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 12,
      price: 15.5,
    },
    {
      id: 6,
      image: "/images/beauty-salon/product-6.png",
      name: "Glow Serum",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 23,
      price: 45.5,
    },
    {
      id: 7,
      image: "/images/beauty-salon/product-7.png",
      name: "Facial Kit",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 124,
      price: 20.5,
    },
    {
      id: 8,
      image: "/images/beauty-salon/product-2.png",
      name: "Winter Cream",
      viewDetails: "/ecommerce/products-list/details/",
      sold: 76,
      price: 25.5,
    },
  ];

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            mb: "25px",
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Top Selling Products
          </Typography>

          <CustomDropdown
            options={["This Day", "This Week", "This Month", "This Year"]} // Need to change the options also in CustomDropdown file
            onSelect={(value) => console.log(value)}
            defaultLabel="This Month"
          />
        </Box>

        <Box sx={{ position: "relative", zIndex: 0 }}>
          <Swiper
            slidesPerView={1}
            spaceBetween={20}
            navigation={true}
            breakpoints={{
              0: {
                slidesPerView: 1,
              },
              450: {
                slidesPerView: 2,
              },
              768: {
                slidesPerView: 3,
              },
              992: {
                slidesPerView: 4,
              },
              1199: {
                slidesPerView: 4,
              },
              1400: {
                slidesPerView: 4,
              },
              1600: {
                slidesPerView: 4,
              },
              1800: {
                slidesPerView: 6,
              },
            }}
            modules={[Navigation]}
            className="bsts-products-slide"
          >
            {products.map((product) => (
              <SwiperSlide key={product.id}>
                <Link
                  href={product.viewDetails}
                  className="beauty-product d-block text-decoration-none"
                >
                  <Image
                    src={product.image}
                    alt={product.name}
                    width={465}
                    height={552}
                    style={{
                      marginBottom: "10px",
                      borderRadius: "7px",
                    }}
                  />

                  <Box
                    sx={{
                      display: "flex",
                      alignItems: "center",
                      flexWrap: "wrap",
                      gap: "5px",
                      justifyContent: "space-between",
                      mb: "10px",
                    }}
                  >
                    <Typography
                      variant="h4"
                      sx={{
                        mb: "0",
                        fontSize: "14px",
                        fontWeight: 600,
                        lineHeight: 1,
                      }}
                    >
                      {product.name}
                    </Typography>

                    <Box
                      sx={{
                        bgcolor: "success.100",
                        border: "1px solid",
                        borderColor: "success.300",
                        px: "8px",
                        py: "3px",
                        borderRadius: "30px",
                        color: "success.700",
                        fontSize: "11px",
                        fontWeight: 500,
                        lineHeight: 1,
                      }}
                    >
                      {product.sold}
                    </Box>
                  </Box>

                  <Box
                    className="d-flex justify-content-between"
                    sx={{
                      display: "flex",
                      justifyContent: "space-between",
                      alignItems: "center",
                      gap: "5px",
                    }}
                  >
                    <Box
                      sx={{
                        fontSize: "14px",
                        fontWeight: 600,
                        color: "#3225ae",
                      }}
                    >
                      ${product.price.toFixed(2)}
                    </Box>

                    <Box fontSize={"12px"}>sold</Box>
                  </Box>
                </Link>
              </SwiperSlide>
            ))}
          </Swiper>
        </Box>
      </Card>
    </>
  );
};

export default TopSellingProducts;
