// react-nextjs-material-ui/src/components/Dashboard/Crypto/Portfolio/index.tsx
"use client";

import React from "react";
import Image from "next/image";
import {
  Card,
  Box,
  Typography,
  Button,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Paper,
  TableHead,
} from "@mui/material";
import Link from "next/link";
import styles from "@/components/Dashboard/Crypto/Portfolio/Portfolio.module.css";

 
function createData(
  id: any,
  coinName: string,
  abbreviation: string,
  amount: string,
  totalValue: string
) {
  return {
    id,
    coinName,
    abbreviation,
    amount,
    totalValue,
  };
}

const rows = [
  createData(
    "1",
    "Bitcoin",
    "BTC",
    "0.50 BTC",
    "$13,500"
  ),
  createData(
    "2",
    "Ethereum",
    "ETH",
    "5.00 ETH",
    "$8,750"
  ),
  createData(
    "3",
    "Binance",
    "BNB",
    "100 SOL",
    "$250",
  ),
  createData(
    "4",
    "Tether",
    "USDT",
    "10 BNB",
    "$1.00",
  ),
  createData(
    "5",
    "XRP",
    "XRP",
    "1,000 ADA",
    "$0.50",
  ),
  createData(
    "6",
    "Solana",
    "SOL",
    "0.40 BTC",
    "$35",
  ),
  createData(
    "7",
    "USDC",
    "USDC",
    "3.00 USDC",
    "$0.9999",
  ),
  createData(
    "8",
    "Dogecoin",
    "DOGE",
    "3.00 DOGE",
    "$0,1221",
  ),
  createData(
    "9",
    "Toncoin",
    "TON",
    "3.00 TON",
    "$5.82",
  ),
  createData(
    "10",
    "Cardano",
    "ADA",
    "3.00 ADA",
    "$0,3884",
  ),
].sort((b, a) => (a.id < b.id ? -1 : 1));


const Portfolio: React.FC = () => {

  // Table
  const [page, setPage] = React.useState(0);
  const [rowsPerPage, setRowsPerPage] = React.useState(5);

  // Avoid a layout jump when reaching the last page with empty rows.
  const emptyRows =
    page > 0 ? Math.max(0, (1 + page) * rowsPerPage - rows.length) : 0;
  
  return (
    <>
      <Card
        sx={{
          bgcolor: "#4936F5 !important",
          position: 'relative',
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        style={{
          backgroundImage: `url(/images/portfolio-bg.jpg)`,
          backgroundPosition: 'left bottom',
          backgroundRepeat: 'no-repeat',
          backgroundSize: 'contain',
        }}
        className="rmui-card"
      >
        <Typography
          variant="h5"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
            mb: "25px",
          }}
          className="text-white"
        >
          Portfolio
        </Typography>
         
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            gap: "10px",
            mb: '30px'
          }}
        >
          <Image
            src="/images/icons/total-balance.svg"
            alt="total-balance"
            width={41}
            height={41}
          />

          <Box>
            <Typography
              component="span"
              className="text-white"
              sx={{
                display: "block",
                textTransform: "uppercase",
                fontWeight: "500",
              }}
            >
              Total balance
            </Typography>

            <Typography
              component="h4"
              sx={{
                fontWeight: "600",
                fontSize: "20px",
                mt: "5px",
                display: "flex",
                alignItems: "center",
                gap: "10px",
                color: '#fff !important'
              }}
            >
              $78,350.00
              <Typography
                component="span"
                sx={{
                  color: "#d8ffc8 !important",
                  fontWeight: "500",
                  fontSize: "14px",
                  display: "flex",
                  alignItems: "center",
                  gap: "2px",
                }}
              >
                <i
                  className="bx bx-trending-up"
                  style={{ fontSize: "20px" }}
                ></i>
                +2.3%
              </Typography>
            </Typography>
          </Box>
        </Box>
    
        {/* Table */}
        <TableContainer
          component={Paper}
          sx={{
            bgcolor: 'transparent !important',
            boxShadow: "none",
            borderRadius: "0",
          }}
          className="rmui-table"
        >
          <Table sx={{ minWidth: 400 }} className={styles.pTable}>
            <TableHead>
              <TableRow>
                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    color: '#fff !important',
                    borderColor: '#757dff !important'
                  }}
                  className="border-bottom"
                >
                  Coin
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "center",
                    color: '#fff !important',
                    borderColor: '#757dff !important'
                  }}
                  className="border-bottom"
                >
                  Amount
                </TableCell>

                <TableCell
                  sx={{
                    padding: "0 14px 7px",
                    fontSize: "12px",
                    textAlign: "end",
                    color: '#fff !important',
                    borderColor: '#757dff !important'
                  }}
                  className="border-bottom"
                >
                  Total Value
                </TableCell>
              </TableRow>
            </TableHead>

            <TableBody>
              {(rowsPerPage > 0
                ? rows.slice(
                    page * rowsPerPage,
                    page * rowsPerPage + rowsPerPage
                  )
                : rows
              ).map((row) => (
                <TableRow key={row.id}>
                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      color: '#fff !important',
                      borderColor: '#757dff !important'
                    }}
                    className="border-bottom"
                  >
                    <Typography
                      sx={{
                        fontWeight: "500",
                        color: '#fff !important',
                      }}
                    >
                      {row.coinName}{" "}
                      <Typography
                        component="span"
                        sx={{ fontWeight: "400", fontSize: "12px", color: '#fff !important', }}
                      >
                        {row.abbreviation}
                      </Typography>
                    </Typography>
                  </TableCell>
 
                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "center",
                      fontWeight: "500",
                      color: '#fff !important',
                      borderColor: '#757dff !important'
                    }}
                    className="border-bottom"
                  >
                    {row.amount}
                  </TableCell>
  
                  <TableCell
                    sx={{
                      padding: "10px 14px",
                      fontSize: "14px",
                      textAlign: "end",
                      fontWeight: "500",
                      color: '#fff !important',
                      borderColor: '#757dff !important'
                    }}
                    className="border-bottom"
                  >
                    {row.totalValue}
                  </TableCell>
                </TableRow>
              ))}
              {emptyRows > 0 && (
                <TableRow style={{ height: 53 * emptyRows }}>
                  <TableCell className="border-bottom" colSpan={6} />
                </TableRow>
              )}
            </TableBody>
          </Table>
        </TableContainer>
      
        <div className="text-end">
          <Link href="#">
            <Button
              variant="outlined"
              sx={{
                borderColor: "#605DFF",
                color: "#fff !important",
                mt: "20px",
                textTransform: 'capitalize',
                fontSize: '14px'
              }}
            >
              View All Portfolio <i className="ri-arrow-right-s-line" style={{ fontSize: '18px', lineHeight: '0' }}></i>
            </Button>
          </Link>
        </div>

        <Box 
          className={styles.shape}
          sx={{
            display: {xs: 'none', xl: 'block'}
          }} 
        >
          <Image src="/images/sphere-bowl.png" alt="sphere-bowl" width={130} height={107} />
        </Box>
      </Card>
    </>
  );
};

export default Portfolio;

// svelte-bootstrap/src/lib/components/Dashboard/Crypto/Portfolio.svelte
<div class="col-xxl-5">
	<div class="card bg-primary p-4 border-0 position-relative z-1">
		<div class="pb-4 mb-3">
			<h3 class="mb-0 text-white">Portfolio</h3>
		</div>
		<div class="d-flex align-items-center mb-4">
			<div class="flex-shrink-0">
				<img src="/assets/images/balance.png" style="width: 41px;" alt="balance" />
			</div>
			<div class="flex-grow-1 ms-2">
				<span class="mb-1 d-block fw-medium text-white">TOTAL BALANCE</span>
				<div class="d-flex">
					<h3 class="mb-0 fs-20 fw-semibold me-1 text-white">$78,350.00</h3>
					<i class="material-symbols-outlined fs-16 position-relative top-3 text-success"
						>trending_up</i
					>
					<span class="text-success">+2.3%</span>
				</div>
			</div>
		</div>
		<div class="default-table-area style-two portfolio-table">
			<div class="table-responsive">
				<table class="table align-middle border-0">
					<thead>
						<tr class="border-bottom">
							<th scope="col" class="text-white bg-transparent">Coin</th>
							<th scope="col" class="text-white text-end bg-transparent">Amount</th>
							<th scope="col" class="text-white text-end bg-transparent pe-0">Total Value</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="fw-medium ps-0 text-white">
								<span class="fw-medium">Bitcoin <span>(BTC)</span></span>
							</td>
							<td class="text-end fw-medium text-white">0.50 BTC</td>
							<td class="text-end fw-medium text-white pe-0">$41,250</td>
						</tr>
						<tr>
							<td class="fw-medium ps-0">
								<span class="fw-medium text-white">Ethereum <span>(ETH)</span></span>
							</td>
							<td class="text-end fw-medium text-white">10.00 ETH</td>
							<td class="text-end fw-medium text-white pe-0">$17,500</td>
						</tr>
						<tr>
							<td class="fw-medium ps-0">
								<span class="fw-medium text-white">Solana <span>(SOL)</span></span>
							</td>
							<td class="text-end fw-medium text-white">500 BTC </td>
							<td class="text-end fw-medium text-white">$17,500</td>
						</tr>
						<tr>
							<td class="fw-medium text-white ps-0">
								<span class="fw-medium">Cardano <span>(ADA)</span></span>
							</td>
							<td class="text-end fw-medium text-white">2,000 ADA</td>
							<td class="text-end fw-medium text-white">$500</td>
						</tr>
						<tr>
							<td class="fw-medium text-white ps-0">
								<span class="fw-medium">Binance <span>(BNB)</span></span>
							</td>
							<td class="text-end fw-medium text-white">5.00 BNB</td>
							<td class="text-end fw-medium text-white">$1,250</td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="text-end mt-4 pt-3">
				<a
					href="/dashboard/analytics"
					class="btn btn-outline-primary text-white py-2 px-3"
					style="border-color: #757DFF;"
				>
					View All Portfolio
				</a>
			</div>
		</div>
		<img
			src="/assets/images/shape-5.png"
			class="position-absolute bottom-0 start-0 z-n1"
			alt="shape"
		/>
		<img
			src="/assets/images/shape-6.png"
			class="position-absolute top-0 end-0 z-n1 pt-4 pe-4 shape-6"
			alt="shape"
		/>
	</div>
</div>
