// vuejs-vuetify/src/components/Dashboard/RealEstateAgent/TopChannels.vue
<template>
  <v-card
    class="top-channels-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Top Channels</h5>
      <div class="trezo-card-subtitle">
        <a href="#" class="view-all-btn d-inline-block">
          <span class="d-inline-block position-relative">
            Browse All
            <i class="ri-arrow-right-s-line"></i>
          </span>
        </a>
      </div>
    </div>

    <div class="trezo-card-content">
      <ul class="p-0 m-0 list-unstyled">
        <li
          class="d-flex align-items-center justify-content-between"
          v-for="channel in channels"
          :key="channel.id"
        >
          <div class="title d-flex align-items-center">
            <v-img :src="channel.icon" :alt="channel.name" />
            <div>
              <span class="d-block fw-semibold text-black">
                {{ channel.name }}
              </span>
              <span class="d-block">
                {{ channel.category }}
              </span>
            </div>
          </div>
          <div class="circle-progress-bar rounded-circle position-relative">
            <svg
              width="60"
              height="60"
              viewBox="-25 -25 250 250"
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              style="transform: rotate(-90deg)"
            >
              <circle
                r="90"
                cx="100"
                cy="100"
                fill="transparent"
                stroke="transparent"
                stroke-width="16px"
                stroke-dasharray="565.48px"
                stroke-dashoffset="0"
              ></circle>
              <circle
                r="90"
                cx="100"
                cy="100"
                :stroke="channel.color"
                stroke-width="16px"
                stroke-linecap="round"
                :stroke-dashoffset="getStrokeDashOffset(channel.percentage)"
                fill="transparent"
                stroke-dasharray="565.48px"
              ></circle>
            </svg>
            <span class="percentage d-block text-body">
              {{ channel.percentage }}%
            </span>
          </div>
        </li>
      </ul>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Channel {
  id: number;
  name: string;
  category: string;
  icon: string;
  percentage: number;
  color: string;
}

export default defineComponent({
  name: "TopChannels",
  setup() {
    const channels: Channel[] = [
      {
        id: 1,
        name: "Facebook",
        category: "Community",
        icon: require("@/assets/images/facebook-real.svg"),
        percentage: 80,
        color: "#6f77f3",
      },
      {
        id: 2,
        name: "Dribbble",
        category: "Community",
        icon: require("@/assets/images/dribbble-real.svg"),
        percentage: 75,
        color: "#5ba5fa",
      },
      {
        id: 3,
        name: "Instagram",
        category: "Reel",
        icon: require("@/assets/images/instagram-real.svg"),
        percentage: 80,
        color: "#fc7936",
      },
      {
        id: 4,
        name: "Google",
        category: "SEO & PPC",
        icon: require("@/assets/images/google-real.svg"),
        percentage: 100,
        color: "#58f229",
      },
      {
        id: 5,
        name: "Figma",
        category: "Community",
        icon: require("@/assets/images/figma-real.svg"),
        percentage: 60,
        color: "#bf85fb",
      },
    ];

    const getStrokeDashOffset = (percentage: number): string => {
      const circumference = 565.48; // 2 * π * r (where r = 90)
      return ((100 - percentage) / 100) * circumference + "px";
    };

    return {
      channels,
      getStrokeDashOffset,
    };
  },
});
</script>

<style lang="scss" scoped>
.top-channels-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        padding-bottom: 10px;
        margin-bottom: 10px;

        .title {
          gap: 15px;

          span {
            &:nth-child(2) {
              font-size: 12px;
              margin-top: 2px;
            }
          }
        }
        .circle-progress-bar {
          width: 50px;
          height: 50px;

          svg {
            top: -5px;
            left: -5px;
            position: relative;
          }
          .percentage {
            top: 50%;
            left: 50%;
            font-size: 10px;
            position: absolute;
            transform: translateY(-50%) translateX(-50%);
          }
        }
        &:last-child {
          margin-bottom: 0;
          padding-bottom: 0;
          border-bottom-width: 0;
        }
      }
    }
  }
}
</style>

// react-nextjs-material-ui/src/components/Dashboard/RealEstateAgent/TopChannels.tsx
"use client";

import React from "react";
import { Box, Typography, Card } from "@mui/material";
import Image from "next/image";
import Link from "next/link";

interface ChannelData {
  id: string;
  name: string;
  icon: string;
  alt: string;
  category: string;
  percentage: number;
}

const TopChannels: React.FC = () => {
  // Calculate strokeDashoffset based on percentage
  const calculateOffset = (percentage: number) => {
    const circumference = 565.48; // 2 * π * r (where r = 90)
    return circumference - (circumference * percentage) / 100;
  };

  // Determine circle color based on percentage
  const getCircleColor = (percentage: number) => {
    if (percentage >= 80) return "#58F229"; // Green for high percentages
    if (percentage >= 60) return "#757DFF"; // Blue for medium-high
    if (percentage >= 40) return "#5DA8FF"; // Light blue for medium
    if (percentage >= 20) return "#FE7A36"; // Orange for low-medium
    return "#BF85FB"; // Purple for low
  };

  const channels: ChannelData[] = [
    {
      id: "facebook",
      name: "Facebook",
      icon: "/images/icons/facebook3.svg",
      alt: "facebook",
      category: "Community",
      percentage: 80,
    },
    {
      id: "dribbble",
      name: "Dribbble",
      icon: "/images/icons/dribbble2.svg",
      alt: "dribbble2",
      category: "Community",
      percentage: 75,
    },
    {
      id: "instagram",
      name: "Instagram",
      icon: "/images/icons/instagram2.svg",
      alt: "instagram2",
      category: "Community",
      percentage: 80,
    },
    {
      id: "google",
      name: "Google",
      icon: "/images/icons/google3.svg",
      alt: "google3",
      category: "Community",
      percentage: 100,
    },
    {
      id: "figma",
      name: "Figma",
      icon: "/images/icons/figma2.svg",
      alt: "figma2",
      category: "Community",
      percentage: 60,
    },
  ];

  return (
    <Card
      sx={{
        boxShadow: "none",
        borderRadius: "7px",
        mb: "25px",
        padding: { xs: "18px", sm: "20px", lg: "25px" },
      }}
      className="rmui-card"
    >
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          mb: "25px",
        }}
      >
        <Typography
          variant="h3"
          sx={{
            fontSize: { xs: "16px", md: "18px" },
            fontWeight: 700,
          }}
        >
          Top Channels
        </Typography>

        <Box>
          <Link href="#" className="text-body hover-text-color:hover">
            Browse All
            <i className="ri-arrow-right-s-line"></i>
          </Link>
        </Box>
      </Box>

      <Box>
        {channels.map((channel) => (
          <Box
            key={channel.id}
            sx={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              pb: "10px",
              mb: "10px",
            }}
            className="border-bottom lcbpm-none"
          >
            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: "15px",
              }}
            >
              <Image
                src={channel.icon}
                alt={channel.alt}
                width={26}
                height={26}
              />

              <Box>
                <Typography
                  className="text-black"
                  sx={{
                    fontWeight: 600,
                  }}
                >
                  {channel.name}
                </Typography>
                <Typography sx={{ fontSize: "12px" }}>
                  {channel.category}
                </Typography>
              </Box>
            </Box>

            <Box
              sx={{
                position: "relative",
                width: "60px",
                height: "50px",
              }}
            >
              <svg
                width="60"
                height="60"
                viewBox="-25 -25 250 250"
                version="1.1"
                xmlns="http://www.w3.org/2000/svg"
                style={{ transform: "rotate(-90deg)" }}
              >
                <circle
                  r="90"
                  cx="100"
                  cy="100"
                  fill="transparent"
                  stroke="transparent"
                  strokeWidth="16px"
                  strokeDasharray="565.48px"
                  strokeDashoffset="0"
                ></circle>
                <circle
                  r="90"
                  cx="100"
                  cy="100"
                  stroke={getCircleColor(channel.percentage)}
                  strokeWidth="16px"
                  strokeLinecap="round"
                  strokeDashoffset={calculateOffset(channel.percentage)}
                  fill="transparent"
                  strokeDasharray="565.48px"
                ></circle>
              </svg>

              <Typography
                sx={{
                  fontSize: "10px",
                  position: "absolute",
                  top: "60%",
                  left: "50%",
                  transform: "translateY(-50%) translateX(-50%)",
                }}
              >
                {channel.percentage}%
              </Typography>
            </Box>
          </Box>
        ))}
      </Box>
    </Card>
  );
};

export default TopChannels;
