// vuejs-bootstrap/src/components/Dashboard/BeautySalon/FeaturedServices.vue
<template>
  <div
    class="featured-services-card card mb-4 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-3 mb-lg-30"
      >
        <h5 class="mb-0">Featured Services</h5>
      </div>

      <div class="trezo-card-content">
        <ul class="p-0 m-0 list-unstyled">
          <li
            v-for="(service, index) in services"
            :key="service.id"
            class="d-flex align-items-center justify-content-between"
          >
            <div class="info d-flex align-items-center">
              <img :src="service.icon" :alt="service.name" />
              <div>
                <span class="d-block text-black fw-semibold">
                  {{ service.name }}
                </span>
                <span class="d-block text-body">
                  {{ service.served }} Served this week
                </span>
              </div>
            </div>
            <span
              class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center"
            >
              {{ index + 1 }}
            </span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "FeaturedServices",
  setup() {
    const services = [
      {
        id: 1,
        name: "Hair Cut",
        icon: require("@/assets/images/icons/hair-cutting.svg"),
        served: 132,
      },
      {
        id: 2,
        name: "Manicure",
        icon: require("@/assets/images/icons/manicure.svg"),
        served: 102,
      },
      {
        id: 3,
        name: "Pedicure",
        icon: require("@/assets/images/icons/pedicure.svg"),
        served: 99,
      },
      {
        id: 4,
        name: "Nail Art",
        icon: require("@/assets/images/icons/nail-polish.svg"),
        served: 89,
      },
      {
        id: 5,
        name: "Facial Treatment",
        icon: require("@/assets/images/icons/woman.svg"),
        served: 72,
      },
    ];
    return {
      services,
    };
  },
});
</script>

<style lang="scss" scoped>
.featured-services-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        padding-bottom: 12px;
        margin-bottom: 12px;

        .info {
          gap: 15px;

          span {
            font-size: 12px;

            &:nth-child(1) {
              font-size: var(--fontSize);
              margin-bottom: 2px;
            }
          }
        }
        .number {
          width: 25px;
          height: 25px;
          font-size: 12px;
          background-color: #dde4ff;
        }
        &:last-child {
          border-bottom-width: 0;
          padding-bottom: 0;
          margin-bottom: 0;
        }
      }
    }
  }
}
</style>

// angular-material/src/app/dashboard/beauty-salon/featured-services/featured-services.component.ts
import { Component } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-featured-services',
    imports: [MatCardModule],
    templateUrl: './featured-services.component.html',
    styleUrl: './featured-services.component.scss'
})
export class FeaturedServicesComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<mat-card
    class="featured-services-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Featured Services
            </h5>
        </mat-card-title>
    </mat-card-header>
    <mat-card-content>
        <ul class="p-0 m-0 list-unstyled">
            <li class="d-flex align-items-center justify-content-between">
                <div class="info d-flex align-items-center">
                    <img src="images/icons/hair-cutting.svg" alt="hair-cutting">
                    <div>
                        <span class="d-block text-black fw-semibold">
                            Hair Cut
                        </span>
                        <span class="d-block text-body">
                            132 Served this week
                        </span>
                    </div>
                </div>
                <span class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center">
                    01
                </span>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="info d-flex align-items-center">
                    <img src="images/icons/manicure.svg" alt="manicure">
                    <div>
                        <span class="d-block text-black fw-semibold">
                            Manicure
                        </span>
                        <span class="d-block text-body">
                            102 Served this week
                        </span>
                    </div>
                </div>
                <span class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center">
                    02
                </span>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="info d-flex align-items-center">
                    <img src="images/icons/pedicure.svg" alt="pedicure">
                    <div>
                        <span class="d-block text-black fw-semibold">
                            Pedicure
                        </span>
                        <span class="d-block text-body">
                            99 Served this week
                        </span>
                    </div>
                </div>
                <span class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center">
                    03
                </span>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="info d-flex align-items-center">
                    <img src="images/icons/nail-polish.svg" alt="nail-polish">
                    <div>
                        <span class="d-block text-black fw-semibold">
                            Nail Art
                        </span>
                        <span class="d-block text-body">
                            89 Served this week
                        </span>
                    </div>
                </div>
                <span class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center">
                    04
                </span>
            </li>
            <li class="d-flex align-items-center justify-content-between">
                <div class="info d-flex align-items-center">
                    <img src="images/icons/woman.svg" alt="woman">
                    <div>
                        <span class="d-block text-black fw-semibold">
                            Facial Treatment
                        </span>
                        <span class="d-block text-body">
                            72 Served this week
                        </span>
                    </div>
                </div>
                <span class="number fw-medium text-primary rounded-circle d-flex align-items-center justify-content-center">
                    05
                </span>
            </li>
        </ul>
    </mat-card-content>
</mat-card>
