// react-nextjs-material-ui/src/components/Dashboard/RealEstateAgent/MyFeaturedListings.tsx
"use client";

import React from "react";
import { Box, Typography } from "@mui/material";
import Link from "next/link";
import { Swiper, SwiperSlide } from "swiper/react";
import { Pagination, Autoplay } from "swiper/modules";

interface Listing {
  id: number;
  title: string;
  location: string;
  image: string;
  type: "rent" | "sale";
  price: string;
  size: string;
  bedrooms: number;
  bathrooms: number;
  link: string;
}

const MyFeaturedListings: React.FC = () => {
  // Listing data state
  const listings: Listing[] = [
    {
      id: 1,
      title: "White House Villa",
      location: "New Castle, United Kingdom",
      image: "/images/properties/property13.jpg",
      type: "rent",
      price: "$3,124/m",
      size: "321 Sft",
      bedrooms: 2,
      bathrooms: 1,
      link: "/real-estate-agent/property-details",
    },
    {
      id: 2,
      title: "Luxury Comfort Villa",
      location: "London, United Kingdom",
      image: "/images/properties/property14.jpg",
      type: "sale",
      price: "$4,274/m",
      size: "425 Sft",
      bedrooms: 3,
      bathrooms: 2,
      link: "/real-estate-agent/property-details",
    },
    {
      id: 3,
      title: "Modern Downtown Apartment",
      location: "Manchester, United Kingdom",
      image: "/images/properties/property13.jpg",
      type: "rent",
      price: "$2,850/m",
      size: "380 Sft",
      bedrooms: 1,
      bathrooms: 1,
      link: "/real-estate-agent/property-details",
    },
    {
      id: 4,
      title: "Seaside Cottage",
      location: "Brighton, United Kingdom",
      image: "/images/properties/property14.jpg",
      type: "sale",
      price: "$3,950/m",
      size: "450 Sft",
      bedrooms: 2,
      bathrooms: 2,
      link: "/real-estate-agent/property-details",
    },
  ];

  return (
    <Box
      sx={{
        backgroundColor: "#FFE8D4",
        boxShadow: "none",
        borderRadius: "7px",
        mb: "25px",
        padding: { xs: "18px", sm: "20px", lg: "25px" },
      }}
    >
      <Box
        sx={{
          fontSize: { xs: "16px", md: "18px" },
          fontWeight: 700,
          mb: "20px",
          color: "#3a4252 !important",
        }}
      >
        My Featured Listings
      </Box>

      <Swiper
        spaceBetween={25}
        pagination={{
          clickable: true,
        }}
        autoHeight={true}
        breakpoints={{
          0: {
            slidesPerView: 1,
          },
          506: {
            slidesPerView: 2,
          },
        }}
        autoplay={{
          delay: 5000,
          disableOnInteraction: false,
          pauseOnMouseEnter: true,
        }}
        modules={[Pagination, Autoplay]}
        className="rea-my-featured-listings"
      >
        {listings.map((listing) => (
          <SwiperSlide key={listing.id}>
            <Box
              style={{
                backgroundImage: `url(${listing.image})`,
                height: "200px",
                backgroundSize: "cover",
                backgroundPosition: "center",
                borderRadius: "7px 7px 0 0",
                position: "relative",
                padding: "10px",
              }}
            >
              <Box
                className="po-left-10"
                sx={{
                  position: "absolute",
                  top: "10px",
                  left: "10px",
                  backgroundColor:
                    listing.type === "rent" ? "error.50" : "primary.50",
                  color:
                    listing.type === "rent" ? "error.main" : "primary.main",
                  padding: "3.5px 10px",
                  display: "inline-block",
                  fontWeight: 500,
                  fontSize: "12px",
                  borderRadius: "4px",
                  lineHeight: "1",
                }}
              >
                {listing.type === "rent" ? "For Rent" : "For Sale"}
              </Box>
            </Box>

            <Box
              className="bg-white"
              sx={{
                padding: "20px",
                borderRadius: "0 0 7px 7px",
              }}
            >
              <Typography
                variant="h6"
                sx={{
                  fontSize: { xs: "15px", md: "16px" },
                  fontWeight: 600,
                  mb: "3px",
                }}
              >
                <Link
                  href={listing.link}
                  className="text-black hover-text-color"
                >
                  {listing.title}
                </Link>
              </Typography>

              <Typography sx={{ mb: "15px" }}>{listing.location}</Typography>

              <Box
                sx={{
                  padding: "0",
                  margin: "0",
                  listStyle: "none",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "center",
                }}
              >
                <Box
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: "5px",
                    fontSize: "12px",
                  }}
                >
                  <i
                    className="material-symbols-outlined"
                    style={{ fontSize: "18px" }}
                  >
                    open_run
                  </i>
                  {listing.size}
                </Box>

                <Box
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: "5px",
                    fontSize: "12px",
                  }}
                >
                  <i
                    className="material-symbols-outlined"
                    style={{ fontSize: "18px" }}
                  >
                    bed
                  </i>
                  {listing.bedrooms} Bed
                </Box>

                <Box
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: "5px",
                    fontSize: "12px",
                  }}
                >
                  <i
                    className="material-symbols-outlined"
                    style={{ fontSize: "18px" }}
                  >
                    bathtub
                  </i>
                  {listing.bathrooms} Bath
                </Box>
              </Box>

              <Box
                className="border-top"
                sx={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                  pt: "12px",
                  mt: "12px",
                }}
              >
                <Box
                  className="text-black"
                  sx={{ fontWeight: 700, fontSize: "16px" }}
                >
                  {listing.price}
                </Box>

                <Link
                  href={listing.link}
                  className="bg-gray"
                  style={{
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    width: "30px",
                    height: "30px",
                    borderRadius: "50%",
                  }}
                >
                  <i className="ri-arrow-right-line"></i>
                </Link>
              </Box>
            </Box>
          </SwiperSlide>
        ))}
      </Swiper>
    </Box>
  );
};

export default MyFeaturedListings;

// vuejs-bootstrap/src/components/Dashboard/RealEstateAgent/MyFeaturedListings.vue
<template>
  <div
    class="border-0 rounded-3 position-relative z-1 p-25 bg-card-text-c my-featured-listings-bg"
  >
    <div
      class="d-flex justify-content-between align-items-center flex-wrap gap-1 mb-4"
    >
      <h5 class="mb-0">My Featured Listings</h5>
      <div class="">
        <div class="swiper-pagination-my-featured-listings"></div>
      </div>
    </div>

    <Swiper
      :slidesPerView="1"
      :spaceBetween="30"
      :centeredSlides="false"
      :preventClicks="true"
      :loop="false"
      :autoplay="{
        delay: 5000,
        disableOnInteraction: false,
        pauseOnMouseEnter: true,
      }"
      :pagination="{
        el: '.swiper-pagination-my-featured-listings',
        clickable: true,
      }"
      :breakpoints="{
        0: {
          slidesPerView: 1,
        },
        576: {
          slidesPerView: 1,
        },
        768: {
          slidesPerView: 2,
        },
        992: {
          slidesPerView: 2,
        },
        1200: {
          slidesPerView: 2,
        },
        1440: {
          slidesPerView: 2,
        },
        1850: {
          slidesPerView: 2,
        },
      }"
      :modules="modules"
      class="my-featured-listings-slide"
    >
      <SwiperSlide v-for="(property, index) in featuredProperties" :key="index">
        <RouterLink
          to="/real-estate-agent/property-details"
          class="text-decoration-none position-relative d-block"
        >
          <div
            class="position-relative z-1 bg-img rounded-top-2"
            :style="{
              'background-image': `url(${property.image})`,
              height: '202px',
            }"
          >
            <div class="position-absolute top-0 start-0 m-2">
              <span
                class="d-inline-block bg-card-text-c px-2 rounded-1 text-danger-50 fs-12 fw-medium"
                style="padding-top: 3px; padding-bottom: 3px"
                >{{ property.type }}</span
              >
            </div>
          </div>

          <div class="bg-white rounded-bottom-2" style="padding: 20px">
            <h3 class="fs-16 fw-semibold mb-6">{{ property.title }}</h3>
            <span class="text-body">{{ property.location }}</span>

            <ul
              class="px-0 pb-13 mb-13 border-bottom mt-13 list-unstyled d-flex justify-content-between align-items-center"
            >
              <li class="d-flex align-items-center gap-1 text-body">
                <i class="material-symbols-outlined fs-18">open_run</i>
                <span>{{ property.area }} Sft</span>
              </li>
              <li class="d-flex align-items-center gap-1 text-body">
                <i class="material-symbols-outlined fs-18">bed</i>
                <span>{{ property.bedrooms }} Bed</span>
              </li>
              <li class="d-flex align-items-center gap-1 text-body">
                <i class="material-symbols-outlined fs-18">bathtub</i>
                <span>{{ property.bathrooms }} Bath</span>
              </li>
            </ul>

            <div class="d-flex justify-content-between align-items-center">
              <h3 class="mb-0">${{ property.price }}/m</h3>
              <i
                class="ri-arrow-right-line wh-30 d-flex justify-content-center align-items-center bg-border-color rounded-circle hover-bg lh-1"
              ></i>
            </div>
          </div>
        </RouterLink>
      </SwiperSlide>
    </Swiper>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import { Swiper, SwiperSlide } from "swiper/vue";
import { Autoplay, Pagination } from "swiper/modules";

interface Property {
  id: number;
  image: string;
  type: string;
  title: string;
  location: string;
  area: number;
  bedrooms: number;
  bathrooms: number;
  price: number;
}

export default defineComponent({
  name: "MyFeaturedListings",
  components: {
    Swiper,
    SwiperSlide,
  },
  setup() {
    const featuredProperties = ref<Property[]>([
      {
        id: 1,
        image: require("@/assets/images/property-1.jpg"),
        type: "For Rent",
        title: "Luxury Comfort Villa",
        location: "London, United Kingdom",
        area: 425,
        bedrooms: 3,
        bathrooms: 2,
        price: 4274,
      },
      {
        id: 2,
        image: require("@/assets/images/property-2.jpg"),
        type: "For Rent",
        title: "White House Villa",
        location: "New Castle, United Kingdom",
        area: 321,
        bedrooms: 2,
        bathrooms: 1,
        price: 4274,
      },
      {
        id: 3,
        image: require("@/assets/images/property-1.jpg"),
        type: "For Rent",
        title: "Luxury Comfort Villa",
        location: "London, United Kingdom",
        area: 425,
        bedrooms: 3,
        bathrooms: 2,
        price: 4274,
      },
      {
        id: 4,
        image: require("@/assets/images/property-2.jpg"),
        type: "For Rent",
        title: "White House Villa",
        location: "New Castle, United Kingdom",
        area: 321,
        bedrooms: 2,
        bathrooms: 1,
        price: 4274,
      },
    ]);

    return {
      modules: [Autoplay, Pagination],
      featuredProperties,
    };
  },
});
</script>
