// landing-pages/react-nextjs-bootstrap/marketing-landing/src/components/Common/UseCasesIdealUsers.js
"use client";

import React from "react";
import Image from "next/image";
import Container from 'react-bootstrap/Container';

const UseCasesIdealUsers = () => {
  // Use cases data array
  const useCases = [
    {
      icon: "/images/icons/chart.svg",
      title: "Freelance Marketers",
      description:
        "Plan, launch, and report on campaigns faster. Spend more time creating and less time managing tools.",
    },
    {
      icon: "/images/icons/management.svg",
      title: "Agencies & Teams",
      description:
        "Plan, launch, and report on campaigns faster. Spend more time creating and less time managing tools.",
    },
    {
      icon: "/images/icons/start-up.svg",
      title: "Startups",
      description:
        "Plan, launch, and report on campaigns faster. Spend more time creating and less time managing tools.",
    },
    {
      icon: "/images/icons/leader.svg",
      title: "Marketing Leaders",
      description:
        "Plan, launch, and report on campaigns faster. Spend more time creating and less time managing tools.",
    },
    {
      icon: "/images/icons/saas.svg",
      title: "SaaS & Tech Companies",
      description:
        "Plan, launch, and report on campaigns faster. Spend more time creating and less time managing tools.",
    },
  ];

  return (
    <>
      <div className="use-cases-ideal-users-marketing">
        <Container className="cmw-1308">
          <div
            className="section-title2 text-center mx-auto mb-70"
            style={{
              maxWidth: "570px",
            }}
          >
            <span className="top-title2 bg-card-text-c text-danger-90">
              Use Cases & Ideal Users
            </span>
            <h2>Built for Modern Marketers. Trusted by Teams of All Sizes.</h2>
            <p className="dec">
              Trezo is flexible, powerful, and ready to scale with you.
            </p>
          </div>

          <div className="hover-accordion-wrap" style={{ gap: "24px" }}>
            {useCases.map((useCase, index) => (
              <div className="col-lg-25" key={`use-case-${index}`}>
                <div className="users-marketing-single-item">
                  <div className="users-marketing-content">
                    <div className="icon">
                      <Image
                        src={useCase.icon}
                        alt={useCase.title
                          .toLowerCase()
                          .replace(/[&\s]+/g, "-")}
                        width={64}
                        height={64}
                      />
                    </div>
                    <h3>{useCase.title}</h3>
                    <p>{useCase.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </Container>
      </div>
    </>
  );
};

export default UseCasesIdealUsers;

// landing-pages/angular-tailwindcss/src/app/marketing-demo/common/use-cases-ideal-users/use-cases-ideal-users.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'app-use-cases-ideal-users',
    imports: [],
    templateUrl: './use-cases-ideal-users.component.html',
    styleUrl: './use-cases-ideal-users.component.scss'
})
export class UseCasesIdealUsersComponent {}
<div class="pt-[70px] md:pt-[90px] lg:pt-[110px] xl:pt-[150px] 2xl:pt-[180px]">
    <div class="container sm:max-w-[540px] md:max-w-[720px] lg:max-w-[960px] xl:max-w-[1308px] mx-auto px-[12px]">
        <div class="text-center mb-[30px] md:mb-[40px] lg:mb-[50px] xl:mb-[60px] 2xl:mb-[70px]">
            <span class="inline-block py-[4.5px] px-[15px] rounded-[100px] bg-orange-100 dark:bg-[#0a0e19] text-orange-700 mb-[12px]">
                Use Cases & Ideal Users
            </span>
            <h2 class="!text-gray-900 dark:!text-white md:-tracking-[1px] !font-medium !text-xl md:!text-3xl lg:!text-4xl xl:!text-5xl xl:max-w-[570px] mx-auto !leading-[1.2] !mb-[10px] lg:!mb-[12px]">
                Built for Modern Marketers. Trusted by Teams of All Sizes.
            </h2>
            <p class="md:text-[15px] lg:text-md !leading-[1.6]">
                Trezo is flexible, powerful, and ready to scale with you.
            </p>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-[25px]">
            <div class="bg-white dark:bg-[#0a0e19] rounded-[15px] px-[20px] py-[30px] md:px-[25px] md:py-[50px] lg:px-[35px] lg:py-[60px] xl:px-[60px] relative z-[1]">
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, #FFF8F1 0%, #F7F9FF 100%);"
                ></div>
                <div class="ltr:pl-[22px] rtl:pr-[22px] relative z-[1] mb-[30px] md:mb-[50px] lg:mb-[90px] xl:mb-[155px]">
                    <img src="images/marketing/icons/chart.svg" alt="chart">
                    <div class="absolute top-[5px] ltr:left-0 rtl:right-0 bg-orange-50 dark:bg-dark w-[55px] h-[55px] rounded-full -z-[1]"></div>
                </div>
                <h3 class="!text-gray-900 dark:!text-white !font-medium !text-lg md:!text-[20px] lg:!text-xl !mb-[15px] md:!mb-[20px] lg:!mb-[25px]">
                    Freelance Marketers
                </h3>
                <p class="!leading-[1.6]">
                    Plan, launch, and report on campaigns faster. Spend more time creating and less time managing tools.
                </p>
            </div>
            <div class="bg-white dark:bg-[#0a0e19] rounded-[15px] px-[20px] py-[30px] md:px-[25px] md:py-[50px] lg:px-[35px] lg:py-[60px] xl:px-[60px] relative z-[1]">
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, #FFF8F1 0%, #F7F9FF 100%);"
                ></div>
                <div class="ltr:pl-[22px] rtl:pr-[22px] relative z-[1] mb-[30px] md:mb-[50px] lg:mb-[90px] xl:mb-[155px]">
                    <img src="images/marketing/icons/management.svg" alt="management">
                    <div class="absolute top-[5px] ltr:left-0 rtl:right-0 bg-orange-50 dark:bg-dark w-[55px] h-[55px] rounded-full -z-[1]"></div>
                </div>
                <h3 class="!text-gray-900 dark:!text-white !font-medium !text-lg md:!text-[20px] lg:!text-xl !mb-[15px] md:!mb-[20px] lg:!mb-[25px]">
                    Agencies & Teams
                </h3>
                <p class="!leading-[1.6]">
                    Collaborate seamlessly, manage multiple clients with ease, and keep every campaign on track—from planning to reporting.
                </p>
            </div>
            <div class="bg-white dark:bg-[#0a0e19] rounded-[15px] px-[20px] py-[30px] md:px-[25px] md:py-[50px] lg:px-[35px] lg:py-[60px] xl:px-[60px] relative z-[1]">
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, #FFF8F1 0%, #F7F9FF 100%);"
                ></div>
                <div class="ltr:pl-[22px] rtl:pr-[22px] relative z-[1] mb-[30px] md:mb-[50px] lg:mb-[90px] xl:mb-[155px]">
                    <img src="images/marketing/icons/start-up.svg" alt="start-up">
                    <div class="absolute top-[5px] ltr:left-0 rtl:right-0 bg-orange-50 dark:bg-dark w-[55px] h-[55px] rounded-full -z-[1]"></div>
                </div>
                <h3 class="!text-gray-900 dark:!text-white !font-medium !text-lg md:!text-[20px] lg:!text-xl !mb-[15px] md:!mb-[20px] lg:!mb-[25px]">
                    Startups
                </h3>
                <p class="!leading-[1.6]">
                    Move fast, stay lean, and launch impactful campaigns without the overhead. Everything you need to grow in one place.
                </p>
            </div>
            <div class="bg-white dark:bg-[#0a0e19] rounded-[15px] px-[20px] py-[30px] md:px-[25px] md:py-[50px] lg:px-[35px] lg:py-[60px] xl:px-[60px] relative z-[1]">
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, #FFF8F1 0%, #F7F9FF 100%);"
                ></div>
                <div class="ltr:pl-[22px] rtl:pr-[22px] relative z-[1] mb-[30px] md:mb-[50px] lg:mb-[90px] xl:mb-[155px]">
                    <img src="images/marketing/icons/leader.svg" alt="leader">
                    <div class="absolute top-[5px] ltr:left-0 rtl:right-0 bg-orange-50 dark:bg-dark w-[55px] h-[55px] rounded-full -z-[1]"></div>
                </div>
                <h3 class="!text-gray-900 dark:!text-white !font-medium !text-lg md:!text-[20px] lg:!text-xl !mb-[15px] md:!mb-[20px] lg:!mb-[25px]">
                    Marketing Leaders
                </h3>
                <p class="!leading-[1.6]">
                    Gain full visibility, align your team, and drive growth with data-backed decisions—all from one centralized platform.
                </p>
            </div>
            <div class="bg-white dark:bg-[#0a0e19] rounded-[15px] px-[20px] py-[30px] md:px-[25px] md:py-[50px] lg:px-[35px] lg:py-[60px] xl:px-[60px] relative z-[1]">
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, #FFF8F1 0%, #F7F9FF 100%);"
                ></div>
                <div class="ltr:pl-[22px] rtl:pr-[22px] relative z-[1] mb-[30px] md:mb-[50px] lg:mb-[90px] xl:mb-[155px]">
                    <img src="images/marketing/icons/saas.svg" alt="saas">
                    <div class="absolute top-[5px] ltr:left-0 rtl:right-0 bg-orange-50 dark:bg-dark w-[55px] h-[55px] rounded-full -z-[1]"></div>
                </div>
                <h3 class="!text-gray-900 dark:!text-white !font-medium !text-lg md:!text-[20px] lg:!text-xl !mb-[15px] md:!mb-[20px] lg:!mb-[25px]">
                    SaaS & Tech Companies
                </h3>
                <p class="!leading-[1.6]">
                    Accelerate growth with streamlined campaigns, real-time analytics, and tools built for scale—all in one unified platform.
                </p>
            </div>
            <div class="bg-white dark:bg-[#0a0e19] rounded-[15px] px-[20px] py-[30px] md:px-[25px] md:py-[50px] lg:px-[35px] lg:py-[60px] xl:px-[60px] relative z-[1]">
                <div
                    class="rounded-[15px] absolute top-0 left-0 right-0 bottom-0 -z-[1] dark:hidden"
                    style="background: linear-gradient(0deg, #FFF8F1 0%, #F7F9FF 100%);"
                ></div>
                <div class="ltr:pl-[22px] rtl:pr-[22px] relative z-[1] mb-[30px] md:mb-[50px] lg:mb-[90px] xl:mb-[155px]">
                    <img src="images/marketing/icons/conversion.svg" alt="conversion">
                    <div class="absolute top-[5px] ltr:left-0 rtl:right-0 bg-orange-50 dark:bg-dark w-[55px] h-[55px] rounded-full -z-[1]"></div>
                </div>
                <h3 class="!text-gray-900 dark:!text-white !font-medium !text-lg md:!text-[20px] lg:!text-xl !mb-[15px] md:!mb-[20px] lg:!mb-[25px]">
                    Customizable Widgets
                </h3>
                <p class="!leading-[1.6]">
                    Tailor every element to match your brand and workflow. Drag, drop, and design your perfect dashboard experience.
                </p>
            </div>
        </div>
    </div>
</div>
