// vuejs-vuetify/src/components/Dashboard/Restaurant/RecentOrdersList.vue
<template>
  <v-card
    class="recent-orders-list-card trezo-card bg-white border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Recent Orders List</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius bg-gray border-0"
          >
            Weekly
          </button>
        </template>
        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            Weekly
          </button>
          <button type="button" class="bg-transparent border-none">
            Monthly
          </button>
          <button type="button" class="bg-transparent border-none">
            Yearly
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="trezo-table basic-table table-responsive">
        <table class="table mb-0">
          <thead>
            <tr>
              <th scope="col" class="fw-bold">Code</th>
              <th scope="col" class="fw-bold">Item</th>
              <th scope="col" class="fw-bold">Quantity</th>
              <th scope="col" class="fw-bold">Customer</th>
              <th scope="col" class="fw-bold">Location</th>
              <th scope="col" class="fw-bold">Delivery Time</th>
              <th scope="col" class="fw-bold">Price</th>
              <th scope="col" class="fw-bold">Status</th>
              <th scope="col" class="fw-bold"></th>
            </tr>
          </thead>

          <tbody>
            <tr v-for="order in paginatedOrders" :key="order.code">
              <td class="fw-semibold text-body">{{ order.code }}</td>
              <td>
                <div class="employee-info d-flex align-items-center">
                  <div class="img rounded-circle">
                    <v-img
                      :src="order.image"
                      alt="user-image"
                      class="rounded-circle"
                    />
                  </div>
                  <div>
                    <RouterLink
                      to="/restaurant/dish-details"
                      class="d-block fw-semibold"
                    >
                      {{ order.item }}
                    </RouterLink>
                  </div>
                </div>
              </td>
              <td class="fw-semibold text-body">{{ order.quantity }}</td>
              <td class="fw-semibold text-body">{{ order.customer }}</td>
              <td class="fw-semibold text-body">{{ order.location }}</td>
              <td class="fw-semibold text-body">{{ order.deliveryTime }}</td>
              <td class="fw-semibold text-body">{{ order.price }}</td>
              <td>
                <span
                  :class="`trezo-status-badge ${order.status.toLowerCase()}`"
                >
                  {{ order.status }}
                </span>
              </td>
              <td>
                <div class="action-buttons d-flex align-items-center">
                  <button type="button">
                    <i class="material-symbols-outlined"> visibility </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined"> edit </i>
                  </button>
                  <button type="button">
                    <i class="material-symbols-outlined"> delete </i>
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        class="d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
      >
        <span class="fs-12 fw-medium">
          Showing {{ startIndex + 1 }} to {{ endIndex }} of
          {{ orders.length }} Results
        </span>

        <nav aria-label="Page navigation example">
          <ul class="pagination mb-0 justify-content-center">
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Previous"
                @click="prevPage"
                :disabled="currentPage === 1"
              >
                <i class="material-symbols-outlined">keyboard_arrow_left</i>
              </button>
            </li>
            <li class="page-item" v-for="page in totalPages" :key="page">
              <button
                class="page-link"
                :class="{ active: page === currentPage }"
                @click="goToPage(page)"
              >
                {{ page }}
              </button>
            </li>
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Next"
                @click="nextPage"
                :disabled="currentPage === totalPages"
              >
                <i class="material-symbols-outlined">keyboard_arrow_right</i>
              </button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

export default defineComponent({
  name: "RecentOrdersList",
  setup() {
    const currentPage = ref(1);
    const itemsPerPage = ref(5);

    const orders = ref([
      {
        code: "#001",
        image: require("@/assets/images/restaurant/order1.jpg"),
        item: "Fish Cutlet",
        quantity: 5,
        customer: "Johnna Loren",
        location: "Washington, D.C.",
        deliveryTime: "10:05 AM",
        price: "$ 35.75",
        status: "Delivered",
      },
      {
        code: "#002",
        image: require("@/assets/images/restaurant/order2.jpg"),
        item: "Pea Creamy Soup",
        quantity: 1,
        customer: "Skyler White",
        location: "Los Angeles, CA",
        deliveryTime: "11:15 AM",
        price: "$ 24.30",
        status: "Processing",
      },
      {
        code: "#003",
        image: require("@/assets/images/restaurant/order3.jpg"),
        item: "Macaroon 02",
        quantity: 2,
        customer: "Jonathon Watson",
        location: "New York, NY",
        deliveryTime: "11:30 AM",
        price: "$ 21.15",
        status: "Cancelled",
      },
      {
        code: "#004",
        image: require("@/assets/images/restaurant/order4.jpg"),
        item: "Healthy Salad Bowl",
        quantity: 1,
        customer: "Walter White",
        location: "San Jose, CA",
        deliveryTime: "11:52 AM",
        price: "$ 12.20",
        status: "Delivered",
      },
      {
        code: "#005",
        image: require("@/assets/images/restaurant/order5.jpg"),
        item: "Macaroon",
        quantity: 1,
        customer: "David Carlen",
        location: "Redmond, WA",
        deliveryTime: "12:05 PM",
        price: "$ 21.50",
        status: "Processing",
      },
      {
        code: "#006",
        image: require("@/assets/images/restaurant/order2.jpg"),
        item: "Pea Creamy Soup",
        quantity: 1,
        customer: "Skyler White",
        location: "Los Angeles, CA",
        deliveryTime: "11:15 AM",
        price: "$ 24.30",
        status: "Processing",
      },
      {
        code: "#007",
        image: require("@/assets/images/restaurant/order3.jpg"),
        item: "Macaroon 02",
        quantity: 2,
        customer: "Jonathon Watson",
        location: "New York, NY",
        deliveryTime: "11:30 AM",
        price: "$ 21.15",
        status: "Cancelled",
      },
      {
        code: "#008",
        image: require("@/assets/images/restaurant/order4.jpg"),
        item: "Healthy Salad Bowl",
        quantity: 1,
        customer: "Walter White",
        location: "San Jose, CA",
        deliveryTime: "11:52 AM",
        price: "$ 12.20",
        status: "Delivered",
      },
    ]);

    const totalPages = computed(() =>
      Math.ceil(orders.value.length / itemsPerPage.value)
    );

    const paginatedOrders = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage.value;
      const end = start + itemsPerPage.value;
      return orders.value.slice(start, end);
    });

    const startIndex = computed(
      () => (currentPage.value - 1) * itemsPerPage.value
    );
    const endIndex = computed(() =>
      Math.min(currentPage.value * itemsPerPage.value, orders.value.length)
    );

    const goToPage = (page: number) => {
      currentPage.value = page;
    };

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    return {
      currentPage,
      itemsPerPage,
      orders,
      paginatedOrders,
      totalPages,
      startIndex,
      endIndex,
      goToPage,
      nextPage,
      prevPage,
    };
  },
});
</script>

<style lang="scss" scoped>
.recent-orders-list-card {
  .trezo-card-content {
    .basic-table {
      table,
      .table {
        thead {
          tr {
            background-color: transparent !important;
            th {
              font-size: 10px;
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              text-align: start;
              padding: {
                bottom: 13px;
                top: 0;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
                text-align: end;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              font-size: 12px;
              padding: {
                top: 13px !important;
                bottom: 13px !important;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 30px;
                }
                a {
                  font-size: var(--fontSize);
                }
              }
              .trezo-status-badge {
                border-radius: 30px;
                padding: 1px 10px;
              }
              .action-buttons {
                justify-content: end;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
              }
            }
          }
        }
      }
    }
    .trezo-card-pagination {
      border-width: 0;
      border-radius: 0;
      padding: {
        left: 0;
        right: 0;
        bottom: 0;
        top: 13px;
      }
      p {
        font: {
          size: 12px;
          weight: 500;
        }
      }
    }
  }
}
</style>

// react-nextjs-material-ui/src/components/Dashboard/Restaurant/RecentOrdersList/index.tsx
"use client";

import { useState, useEffect } from "react";
import {
  Box,
  Typography,
  Card,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableRow,
  Paper,
  Button,
  TableHead,
  IconButton,
} from "@mui/material";
import Image from "next/image";
import CustomDropdown from "./CustomDropdown";

type Order = {
  id: string;
  code: string;
  item: {
    name: string;
    image: string;
  };
  quantity: number;
  customer: string;
  location: string;
  deliveryTime: string;
  price: number;
  status: "Delivered" | "Processing" | "Cancelled";
};

const RecentOrdersList = () => {
  const [orders, setOrders] = useState<Order[]>([]);
  const [currentPage, setCurrentPage] = useState(1);
  const [itemsPerPage, setItemsPerPage] = useState(5);
  const [totalItems, setTotalItems] = useState(0);

  useEffect(() => {
    // Simulated API call
    const fetchData = async () => {
      const mockOrders: Order[] = [
        {
          id: "1",
          code: "#001",
          item: { name: "Fish Cutlet", image: "/images/restaurant/order1.jpg" },
          quantity: 5,
          customer: "Johnna Loren",
          location: "Washington, D.C.",
          deliveryTime: "10:05 AM",
          price: 35.75,
          status: "Delivered",
        },
        {
          id: "2",
          code: "#002",
          item: {
            name: "Pea Creamy Soup",
            image: "/images/restaurant/order2.jpg",
          },
          quantity: 1,
          customer: "Skyler White",
          location: "Los Angeles, CA",
          deliveryTime: "11:15 AM",
          price: 24.3,
          status: "Processing",
        },
        {
          id: "3",
          code: "#003",
          item: {
            name: "Jonathon Watson",
            image: "/images/restaurant/order3.jpg",
          },
          quantity: 3,
          customer: "Jonathon Watson",
          location: "New York, NY",
          deliveryTime: "11:30 AM",
          price: 21.15,
          status: "Cancelled",
        },
        {
          id: "4",
          code: "#004",
          item: {
            name: "Grilled Salmon",
            image: "/images/restaurant/order4.jpg",
          },
          quantity: 2,
          customer: "Alice Johnson",
          location: "Chicago, IL",
          deliveryTime: "12:45 PM",
          price: 28.5,
          status: "Delivered",
        },
        {
          id: "5",
          code: "#005",
          item: {
            name: "Vegetable Stir Fry",
            image: "/images/restaurant/order5.jpg",
          },
          quantity: 4,
          customer: "Bob Smith",
          location: "Houston, TX",
          deliveryTime: "1:15 PM",
          price: 18.9,
          status: "Processing",
        },
        {
          id: "6",
          code: "#006",
          item: {
            name: "Chicken Alfredo",
            image: "/images/restaurant/order1.jpg",
          },
          quantity: 3,
          customer: "Charlie Brown",
          location: "Phoenix, AZ",
          deliveryTime: "2:00 PM",
          price: 22.75,
          status: "Delivered",
        },
        {
          id: "7",
          code: "#007",
          item: { name: "Beef Burger", image: "/images/restaurant/order2.jpg" },
          quantity: 1,
          customer: "Diana Prince",
          location: "Philadelphia, PA",
          deliveryTime: "2:30 PM",
          price: 15.25,
          status: "Cancelled",
        },
        {
          id: "8",
          code: "#008",
          item: {
            name: "Margherita Pizza",
            image: "/images/restaurant/order3.jpg",
          },
          quantity: 2,
          customer: "Ethan Hunt",
          location: "San Antonio, TX",
          deliveryTime: "3:00 PM",
          price: 19.99,
          status: "Processing",
        },
        {
          id: "9",
          code: "#009",
          item: {
            name: "Sushi Platter",
            image: "/images/restaurant/order4.jpg",
          },
          quantity: 5,
          customer: "Fiona Gallagher",
          location: "San Diego, CA",
          deliveryTime: "3:45 PM",
          price: 45.0,
          status: "Delivered",
        },
        {
          id: "10",
          code: "#010",
          item: {
            name: "Caesar Salad",
            image: "/images/restaurant/order5.jpg",
          },
          quantity: 1,
          customer: "George Lopez",
          location: "Dallas, TX",
          deliveryTime: "4:15 PM",
          price: 12.5,
          status: "Processing",
        },
      ];
      setOrders(mockOrders);
      setTotalItems(mockOrders.length); // Set total items from API response
    };

    fetchData();
  }, []);

  const getStatusColor = (status: string) => {
    switch (status) {
      case "Delivered":
        return { color: "success.main", bg: "success.100" };
      case "Processing":
        return { color: "secondary.main", bg: "secondary.100" };
      case "Cancelled":
        return { color: "error.main", bg: "error.100" };
      default:
        return { color: "text.primary", bg: "grey.100" };
    }
  };

  const handlePageChange = (newPage: number) => {
    setCurrentPage(newPage);
  };

  const handleItemsPerPageChange = (value: string) => {
    setItemsPerPage(Number(value));
    setCurrentPage(1); // Reset to first page when changing items per page
  };

  // Calculate paginated data
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = orders.slice(indexOfFirstItem, indexOfLastItem);

  // Generate page numbers
  const pageNumbers = [];
  for (let i = 1; i <= Math.ceil(totalItems / itemsPerPage); i++) {
    pageNumbers.push(i);
  }

  return (
    <>
      <Card
        sx={{
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            flexWrap: "wrap",
            gap: "15px",
            mb: "10px",
          }}
        >
          <Typography
            variant="h3"
            sx={{
              fontSize: { xs: "16px", md: "18px" },
              fontWeight: 700,
            }}
            className="text-black"
          >
            Recent Orders List
          </Typography>

          <CustomDropdown
            options={["This Day", "This Week", "This Month", "This Year"]} // Need to change the options also in CustomDropdown file
            onSelect={(value) => console.log(value)}
            defaultLabel="This Month"
          />
        </Box>

        <TableContainer
          component={Paper}
          sx={{
            boxShadow: "none",
            borderRadius: "0",
          }}
          className="rmui-table"
        >
          <Table sx={{ minWidth: 900 }}>
            <TableHead>
              <TableRow
                className="border-bottom"
                sx={{
                  "& th": {
                    fontSize: "10px",
                    fontWeight: 700,
                    color: "text.primary",
                    padding: "15px 8px",
                  },
                }}
              >
                <th className="text-start">CODE</th>

                <th className="text-start">ITEM</th>

                <th className="text-start">QUANTITY</th>

                <th className="text-start">CUSTOMER</th>

                <th className="text-start">LOCATION</th>

                <th className="text-start">DELIVERY TIME</th>

                <th className="text-start">PRICE</th>

                <th className="text-start">STATUS</th>

                <th className="text-end">ACTION</th>
              </TableRow>
            </TableHead>

            <TableBody>
              {currentItems.map((order) => {
                const statusColors = getStatusColor(order.status);

                return (
                  <TableRow
                    key={order.id}
                    sx={{
                      "& td": {
                        padding: "13px 8px",
                        fontSize: "12px",
                        fontWeight: 600,
                      },
                    }}
                  >
                    <TableCell className="border-bottom">
                      {order.code}
                    </TableCell>

                    <TableCell className="border-bottom">
                      <Box
                        sx={{
                          display: "flex",
                          alignItems: "center",
                          gap: "10px",
                        }}
                      >
                        <Image
                          src={order.item.image}
                          alt="order"
                          width={30}
                          height={30}
                          style={{
                            borderRadius: "50%",
                          }}
                        />

                        <Box>
                          <Typography
                            variant="h3"
                            sx={{
                              fontSize: {xs: '13px', md: '14px'},
                              fontWeight: 600,
                              mb: 0,
                            }}
                          >
                            {order.item.name}
                          </Typography>
                        </Box>
                      </Box>
                    </TableCell>

                    <TableCell className="border-bottom">
                      {order.quantity}
                    </TableCell>

                    <TableCell className="border-bottom">
                      {order.customer}
                    </TableCell>

                    <TableCell className="border-bottom">
                      {order.location}
                    </TableCell>

                    <TableCell className="border-bottom">
                      {order.deliveryTime}
                    </TableCell>

                    <TableCell className="border-bottom">
                      ${order.price.toFixed(2)}
                    </TableCell>

                    <TableCell className="border-bottom">
                      <Box
                        sx={{
                          fontSize: "12px",
                          fontWeight: 500,
                          padding: "4px 10px",
                          borderRadius: "30px",
                          color: statusColors.color,
                          backgroundColor: statusColors.bg,
                          display: "inline-block",
                          lineHeight: 1,
                        }}
                      >
                        {order.status}
                      </Box>
                    </TableCell>

                    <TableCell className="border-bottom">
                      <Box
                        sx={{
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "end",
                        }}
                      >
                        <IconButton
                          aria-label="view"
                          color="primary"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            visibility
                          </i>
                        </IconButton>

                        <IconButton
                          aria-label="edit"
                          color="secondary"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            edit
                          </i>
                        </IconButton>

                        <IconButton
                          aria-label="delete"
                          color="error"
                          sx={{ padding: "5px" }}
                        >
                          <i
                            className="material-symbols-outlined"
                            style={{ fontSize: "16px" }}
                          >
                            delete
                          </i>
                        </IconButton>
                      </Box>
                    </TableCell>
                  </TableRow>
                );
              })}
            </TableBody>
          </Table>

          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              flexWrap: "wrap",
              gap: "15px",
              mt: "15px",
            }}
          >
            <Typography fontSize={"12px"} fontWeight={500} mb={"0"}>
              Showing {indexOfFirstItem + 1}-
              {Math.min(indexOfLastItem, totalItems)} of {totalItems} results
            </Typography>

            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: "5px",
              }}
            >
              <Button
                className="border text-body"
                sx={{
                  minWidth: "auto",
                  padding: "0",
                  width: { xs: "28px", md: "34px" },
                  height: { xs: "28px", md: "34px" },
                }}
                onClick={() => handlePageChange(currentPage - 1)}
                disabled={currentPage === 1}
              >
                <i className="material-symbols-outlined">keyboard_arrow_left</i>
              </Button>

              {pageNumbers.map((number) => (
                <Button
                  key={number}
                  onClick={() => handlePageChange(number)}
                  className="border"
                  sx={{
                    minWidth: "auto",
                    padding: "0",
                    width: { xs: "28px", md: "34px" },
                    height: { xs: "28px", md: "34px" },
                    backgroundColor:
                      number === currentPage ? "primary.main" : "transparent",
                    color: number === currentPage ? "white !important" : "text.primary",
                  }}
                >
                  {number}
                </Button>
              ))}

              <Button
                onClick={() => handlePageChange(currentPage + 1)}
                disabled={currentPage === pageNumbers.length}
                className="border text-body"
                sx={{
                  minWidth: "auto",
                  padding: "0",
                  width: { xs: "28px", md: "34px" },
                  height: { xs: "28px", md: "34px" },
                }}
              >
                <i className="material-symbols-outlined">
                  keyboard_arrow_right
                </i>
              </Button>
            </Box>
          </Box>
        </TableContainer>
      </Card>
    </>
  );
};

export default RecentOrdersList;
