// vuejs-bootstrap/src/components/Dashboard/Restaurant/StaffPerformanceScores.vue
<template>
  <div
    class="staff-performance-scores-card card mb-4 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="card-body p-4">
      <div
        class="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-2 mb-lg-20"
      >
        <h5 class="mb-0">Staff Performance Scores</h5>
        <div class="dropdown action-opt">
          <button
            class="btn bg-transparent p-0"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <i class="ri-more-2-fill"></i>
          </button>
          <ul
            class="dropdown-menu dropdown-menu-end bg-white border box-shadow"
          >
            <li>
              <button class="dropdown-item">This Day</button>
            </li>
            <li>
              <button class="dropdown-item">This Week</button>
            </li>
            <li>
              <button class="dropdown-item">This Month</button>
            </li>
            <li>
              <button class="dropdown-item">This Year</button>
            </li>
          </ul>
        </div>
      </div>

      <div class="trezo-card-content">
        <div class="basic-table table-responsive">
          <table class="table mb-0">
            <tbody>
              <tr v-for="(employee, index) in employees" :key="index">
                <td>
                  <div class="employee-info d-flex align-items-center">
                    <div class="img rounded-circle">
                      <img
                        :alt="employee.name"
                        :src="employee.image"
                        class="rounded-circle"
                      />
                    </div>
                    <div>
                      <span class="d-block fw-medium">{{ employee.name }}</span>
                    </div>
                  </div>
                </td>
                <td class="text-body">{{ employee.score }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "StaffPerformanceScores",
  setup() {
    const employees = [
      {
        name: "Joanna Watson",
        image: require("@/assets/images/users/user58.jpg"),
        score: 98,
      },
      {
        name: "Angela Carter",
        image: require("@/assets/images/users/user59.jpg"),
        score: 97,
      },
      {
        name: "Walter White",
        image: require("@/assets/images/users/user60.jpg"),
        score: 96,
      },
      {
        name: "Gary Simon",
        image: require("@/assets/images/users/user61.jpg"),
        score: 88,
      },
      {
        name: "Zinia Anderson",
        image: require("@/assets/images/users/user62.jpg"),
        score: 85,
      },
      {
        name: "Loren Walter",
        image: require("@/assets/images/users/user63.jpg"),
        score: 82,
      },
      {
        name: "Jessy Pinkman",
        image: require("@/assets/images/users/user64.jpg"),
        score: 80,
      },
      {
        name: "Handy Curter",
        image: require("@/assets/images/users/user65.jpg"),
        score: 77,
      },
      {
        name: "Skyler Lorensa",
        image: require("@/assets/images/users/user66.jpg"),
        score: 75,
      },
    ];

    return {
      employees,
    };
  },
});
</script>

<style lang="scss" scoped>
.staff-performance-scores-card {
  .trezo-card-content {
    margin-bottom: -10px;

    .basic-table {
      table,
      .table {
        thead {
          tr {
            th {
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              padding: {
                bottom: 13px;
                top: 0;
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              padding: {
                top: 10px;
                bottom: 10px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .img {
                  width: 30px;
                }
                span {
                  &:nth-child(1) {
                    margin-bottom: 1px;
                    font-size: var(--fontSize);
                  }
                }
              }
              &:first-child {
                padding-left: 0;
              }
              &:last-child {
                padding-right: 0;
                text-align: end;
              }
            }
            &:first-child {
              td {
                padding-top: 0;
                border-top-width: 0;
              }
            }
            &:last-child {
              td {
                border-bottom-width: 0;
              }
            }
          }
        }
      }
    }
  }
}
</style>

// react-bootstrap/src/components/Dashboard/Restaurant/StaffPerformanceScores.js
"use client";

import React, { useEffect, useState } from "react";
import { Card, Dropdown } from "react-bootstrap";

const StaffPerformanceScores = () => {
  const [staffPerformance, setStaffPerformance] = useState([]);

  useEffect(() => {
    // Simulate an API call or data fetch
    const mockStaffPerformance = [
      {
        id: 1,
        name: "Jonathon Ronan",
        score: 98,
        image: "/images/user-84.png",
      },
      { id: 2, name: "Angela Carter", score: 97, image: "/images/user-81.png" },
      { id: 3, name: "Walter White", score: 96, image: "/images/user-82.png" },
      { id: 4, name: "Gary Simon", score: 88, image: "/images/user-83.png" },
      {
        id: 5,
        name: "Zinia Anderson",
        score: 85,
        image: "/images/user-109.png",
      },
      { id: 6, name: "Loren Walter", score: 82, image: "/images/user-81.png" },
      {
        id: 7,
        name: "Jessy Pinkman",
        score: 80,
        image: "/images/user-135.png",
      },
      { id: 8, name: "Handy Curter", score: 77, image: "/images/user-139.png" },
      {
        id: 9,
        name: "Skyler Lorensa",
        score: 75,
        image: "/images/user-138.png",
      },
    ];

    setStaffPerformance(mockStaffPerformance);
  }, []);

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-3 mb-4">
            <h3 className="mb-0 text-text-secondary-50">
              Staff Performance Score
            </h3>

            <Dropdown className="action-opt">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="bg-transparent p-0"
              >
                <i className="ri-more-2-fill fs-20"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Day
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Week
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Month
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Year
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <ul className="p-0 m-0 list-unstyled last-child-none">
            {staffPerformance.map((staff) => (
              <li
                key={staff.id}
                className="d-flex justify-content-between align-items-center border-bottom border-border-color-50 lcbmp-none"
                style={{
                  paddingBottom: "13.5px",
                  marginBottom: "13.5px",
                }}
              >
                <div
                  className="d-flex align-items-center"
                  style={{ gap: "8px" }}
                >
                  <img
                    src={staff.image}
                    className="rounded-circle"
                    alt="user"
                    width={24}
                    height={24}
                  />
                  <h5 className="fs-14 fw-medium m-0">{staff.name}</h5>
                </div>
                <span className="fs-14 fw-medium">{staff.score}</span>
              </li>
            ))}
          </ul>
        </Card.Body>
      </Card>
    </>
  );
};

export default StaffPerformanceScores;
