// vuejs-vuetify/src/components/Dashboard/Restaurant/TopSellingItems.vue
<template>
  <v-card
    class="top-selling-items-card trezo-card bg-white border-radius d-block border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Top Selling Items</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius bg-gray border-0"
          >
            {{ timeRange }}
          </button>
        </template>
        <v-list class="menu-content">
          <v-list-item
            v-for="(range, index) in timeRanges"
            :key="index"
            @click="handleTimeRangeChange(range)"
            :class="{ 'active-range': timeRange === range }"
          >
            <v-list-item-title>{{ range }}</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="row">
        <div
          class="col-md-3 col-sm-6"
          v-for="(item, index) in topSellingItems.slice(0, 4)"
          :key="index"
        >
          <div class="item position-relative">
            <div
              class="rating fw-semibold d-flex align-items-center bg-dark text-white"
            >
              <i class="ri-star-fill"></i>
              {{ item.rating }}
            </div>
            <RouterLink
              to="/restaurant/dish-details/"
              class="d-block image"
              :style="{ backgroundImage: `url(${item.image})` }"
            ></RouterLink>
            <h6 class="fw-semibold">
              <RouterLink to="/restaurant/dish-details/">
                {{ item.name }}
              </RouterLink>
            </h6>
            <span class="d-block">{{ item.sold }} sold</span>
          </div>
        </div>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

interface TopSellingItem {
  id: number;
  name: string;
  image: string;
  rating: number;
  sold: number;
}

export default defineComponent({
  name: "TopSellingItems",
  setup() {
    const timeRanges = ["Weekly", "Monthly", "Yearly"];
    const timeRange = ref(timeRanges[0]);
    const topSellingItems = ref<TopSellingItem[]>([]);

    const fetchTopSellingItems = () => {
      // Simulate different data based on time range
      if (timeRange.value === "Weekly") {
        topSellingItems.value = [
          {
            id: 1,
            name: "Thai Bean Soup",
            image: require("@/assets/images/products/product28.jpg"),
            rating: 5.0,
            sold: 1235,
          },
          {
            id: 2,
            name: "Meat Lasagnia",
            image: require("@/assets/images/products/product29.jpg"),
            rating: 4.8,
            sold: 1045,
          },
          {
            id: 3,
            name: "Veg Sandwich",
            image: require("@/assets/images/products/product30.jpg"),
            rating: 4.9,
            sold: 1015,
          },
          {
            id: 4,
            name: "Creamy Fish",
            image: require("@/assets/images/products/product31.jpg"),
            rating: 4.7,
            sold: 996,
          },
        ];
      } else if (timeRange.value === "Monthly") {
        topSellingItems.value = [
          {
            id: 1,
            name: "Thai Bean Soup",
            image: require("@/assets/images/products/product31.jpg"),
            rating: 5.0,
            sold: 5000,
          },
          {
            id: 2,
            name: "Meat Lasagnia",
            image: require("@/assets/images/products/product30.jpg"),
            rating: 4.8,
            sold: 4500,
          },
          {
            id: 3,
            name: "Veg Sandwich",
            image: require("@/assets/images/products/product29.jpg"),
            rating: 4.9,
            sold: 4200,
          },
          {
            id: 4,
            name: "Creamy Fish",
            image: require("@/assets/images/products/product28.jpg"),
            rating: 4.7,
            sold: 4000,
          },
        ];
      } else if (timeRange.value === "Yearly") {
        topSellingItems.value = [
          {
            id: 1,
            name: "Thai Bean Soup",
            image: require("@/assets/images/products/product30.jpg"),
            rating: 5.0,
            sold: 15000,
          },
          {
            id: 2,
            name: "Meat Lasagnia",
            image: require("@/assets/images/products/product29.jpg"),
            rating: 4.8,
            sold: 14000,
          },
          {
            id: 3,
            name: "Veg Sandwich",
            image: require("@/assets/images/products/product28.jpg"),
            rating: 4.9,
            sold: 13000,
          },
          {
            id: 4,
            name: "Creamy Fish",
            image: require("@/assets/images/products/product31.jpg"),
            rating: 4.7,
            sold: 12000,
          },
        ];
      }
    };

    const handleTimeRangeChange = (range: string) => {
      timeRange.value = range;
      fetchTopSellingItems();
    };

    // Initial data fetch
    fetchTopSellingItems();

    return {
      topSellingItems,
      timeRange,
      timeRanges,
      handleTimeRangeChange,
    };
  },
});
</script>

<style lang="scss" scoped>
.top-selling-items-card {
  .trezo-card-content {
    .item {
      .rating {
        border-radius: 30px;
        position: absolute;
        padding: 1.5px 5px;
        font-size: 12px;
        right: 3px;
        gap: 3px;
        top: 3px;

        i {
          color: #fd5812;
          font-size: 14px;
        }
      }
      .image {
        height: 137px;
        margin-bottom: 15px;
        border-radius: 10px;
        background: {
          position: center center;
          repeat: no-repeat;
          size: cover;
        }
      }
      h6 {
        font-size: 14px;
        margin-bottom: 4px;
      }
      span {
        font-size: 12px;
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .top-selling-items-card {
    .trezo-card-content {
      margin-bottom: -15px;

      .item {
        margin-bottom: 15px;

        .image {
          margin-bottom: 12px;
        }
      }
    }
  }
}
</style>

// react-bootstrap/src/components/Dashboard/Restaurant/TopSellingItems.js
"use client";

import React from "react";
import { Link } from "react-router-dom";
import { Row, Col, Card, Dropdown } from "react-bootstrap";

const topSellingItems = [
  {
    id: 1,
    name: "Thai Bean Soup",
    image: "/images/top-item-1.jpg",
    rating: 5.0,
    sold: 1235,
    link: "/restaurant/dish-details",
  },
  {
    id: 2,
    name: "Meat Lasagna",
    image: "/images/top-item-2.jpg",
    rating: 4.8,
    sold: 1045,
    link: "/restaurant/dish-details",
  },
  {
    id: 3,
    name: "Veg Sandwich",
    image: "/images/top-item-3.jpg",
    rating: 4.9,
    sold: 1015,
    link: "/restaurant/dish-details",
  },
  {
    id: 4,
    name: "Creamy Fish",
    image: "/images/top-item-4.jpg",
    rating: 4.8,
    sold: 996,
    link: "/restaurant/dish-details",
  },
];

const TopSellingItems = () => {
  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-4">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-3">
            <h3 className="mb-0 text-secondary-50">Top Selling Item</h3>

            <Dropdown className="dropdown select-dropdown">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="dropdown-toggle bg-border-color border text-body rounded-2"
              >
                Weekly <i className="ri-arrow-down-s-line"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Weekly
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Monthly
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  Yearly
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <Row>
            {topSellingItems.slice(0, 4).map((item) => (
              <Col key={item.id} sm={6} md={3}>
                <Link
                  to={item.link}
                  className="text-decoration-none d-block"
                  style={{ marginTop: "22px" }}
                >
                  <div className="position-relative mb-2 pb-1">
                    <div
                      className="bg-img"
                      style={{
                        backgroundImage: `url(${item.image})`,
                        height: "145px",
                        borderRadius: "10px",
                      }}
                    ></div>
                    <div
                      className="d-inline-block position-absolute top-0 end-0"
                      style={{
                        padding: "3px",
                      }}
                    >
                      <div
                        className="d-flex align-items-center bg-dark rounded-pill"
                        style={{
                          gap: "2px",
                          padding: "1.5px 5px",
                        }}
                      >
                        <i className="ri-star-fill fs-14 text-danger"></i>
                        <span
                          className="fs-12 fw-semibold"
                          style={{
                            color: "#FFF5ED",
                          }}
                        >
                          {item.rating}
                        </span>
                      </div>
                    </div>
                  </div>
                  <h4 className="fs-14 fw-semibold mb-0 text-secondary-50">
                    {item.name}
                  </h4>
                  <span className="fs-12 fw-medium text-body">
                    {item.sold} sold
                  </span>
                </Link>
              </Col>
            ))}
          </Row>
        </Card.Body>
      </Card>
    </>
  );
};

export default TopSellingItems;
