// svelte-bootstrap/src/lib/components/Dashboard/LMS/Welcome.svelte
<div class="card bg-primary border-0 rounded-3 welcome-box style-two mb-4 position-relative">
	<div class="card-body py-38 px-4">
		<div class="mb-5">
			<h3 class="text-white fw-semibold">
				Welcome Back, <span class="text-danger-div">Olivia!</span>
			</h3>
			<p class="text-light">Your progress this week is Awesome.</p>
		</div>

		<div class="d-flex align-items-center flex-wrap gap-4 gap-xxl-5">
			<div class="d-flex align-items-center welcome-status-item style-two">
				<div class="flex-shrink-0">
					<i class="material-symbols-outlined">airplay</i>
				</div>
				<div class="flex-grow-1 ms-3">
					<h5 class="text-white fw-semibold mb-0 fs-16">75h</h5>
					<p class="text-light">Hours Spent</p>
				</div>
			</div>

			<div class="d-flex align-items-center welcome-status-item style-two">
				<div class="flex-shrink-0">
					<i class="material-symbols-outlined icon-bg two">local_library</i>
				</div>
				<div class="flex-grow-1 ms-3">
					<h5 class="text-white fw-semibold mb-0 fs-16">15</h5>
					<p class="text-light">Course Completed</p>
				</div>
			</div>
		</div>
	</div>
	<img src="/assets/images/welcome-2.gif" class="welcome-2 d-none d-sm-block" alt="welcome" />
</div>

// react-bootstrap/src/components/Dashboard/Restaurant/Welcome.js
"use client";

import React from "react";
import { Card } from "react-bootstrap";

const Welcome = () => {
  return (
    <>
      <Card className="border-0 rounded-3 bg-rating-color welcome-restaurant position-relative mb-4">
        <div className="mb-1">
          <span
            className="d-inline-block bg-dark fs-16 fw-medium"
            style={{
              padding: "1px 13px",
              color: "#FFE8D4",
            }}
          >
            Hello Olivia!
          </span>
        </div>
        <h2>Here Your Restaurant Stats Today.</h2>

        <div className="d-flex align-items-center" style={{ gap: "40px" }}>
          <div className="d-flex" style={{ gap: "10px" }}>
            <div className="flex-shrink-0">
              <i className="material-symbols-outlined fs-24 text-border-color position-relative top-5">
                order_approve
              </i>
            </div>
            <div className="flex-grow-1">
              <span
                className="fs-14 d-block"
                style={{
                  color: "#FFE8D4",
                  marginBottom: "3px",
                }}
              >
                Total Order
              </span>
              <h4 className="mb-0 fs-16 fw-bold text-white">12051+</h4>
            </div>
          </div>
          <div className="d-flex" style={{ gap: "10px" }}>
            <div className="flex-shrink-0">
              <i className="material-symbols-outlined fs-24 text-border-color position-relative top-5">
                group
              </i>
            </div>
            <div className="flex-grow-1">
              <span
                className="fs-14 d-block"
                style={{
                  color: "#FFE8D4",
                  marginBottom: "3px",
                }}
              >
                Total Users
              </span>
              <h4 className="mb-0 fs-16 fw-bold text-white">153K+</h4>
            </div>
          </div>
        </div>

        <div className="dish-wrap">
          <img
            src="/images/dish.png"
            className="dish-img"
            alt="dish"
            width={185}
            height={183}
          />
          <img
            src="/images/dish-shape1.png"
            className="dish-shape1"
            alt="dish-shape"
            width={42}
            height={45}
          />
          <img
            src="/images/dish-shape2.png"
            className="dish-shape2"
            alt="dish-shape"
            width={42}
            height={45}
          />
        </div>
      </Card>
    </>
  );
};

export default Welcome;
