// laravel-vuetify/resources/components/Dashboard/POSSystem/OrderDetails.vue
<template>
    <v-card
        class="order-details-card trezo-card custom-shadow for-dark-rounded-bg rounded-3 border mb-4 p-0 bg-body-bg"
    >
        <div class="v-card-header mb-0" style="padding: 8.5px 25px">
            <h3 class="mb-0 fs-20 fw-medium">Order Details</h3>

            <button class="bg-transparent p-0 border-0 text-primary">
                <i class="ri-refresh-line"></i>
            </button>
        </div>

        <div class="bg-white py-4 px-0 rounded-3 border-top">
            <div class="last-child-none">
                <div
                    class="d-flex justify-content-between align-items-center child border-bottom px-3 px-sm-4"
                    style="padding-bottom: 20px; margin-bottom: 20px"
                >
                    <div class="d-flex align-items-center">
                        <div class="flex-shrink-0">
                            <v-img
                                src="/images/product-45.jpg"
                                style="width: 40px; height: 28px"
                                class="rounded-1"
                                alt="product"
                            />
                        </div>
                        <div class="flex-grow-1 ms-10">
                            <h3
                                class="fs-14 fw-medium mb-0"
                                style="max-width: 78px"
                            >
                                Maybelline Lash
                            </h3>
                        </div>
                    </div>

                    <div
                        class="d-flex justify-content-between align-items-center"
                    >
                        <div
                            class="product-quantity border-0 bg-body-bg rounded-2"
                        >
                            <QuantityCounter />
                        </div>

                        <span class="fs-18 fw-medium text-primary ms-2 ms-sm-4"
                            >$29</span
                        >
                    </div>
                </div>
                <div
                    class="d-flex justify-content-between align-items-center child border-bottom px-3 px-sm-4"
                    style="padding-bottom: 20px; margin-bottom: 20px"
                >
                    <div class="d-flex align-items-center">
                        <div class="flex-shrink-0">
                            <v-img
                                src="/images/product-46.jpg"
                                style="width: 40px; height: 28px"
                                class="rounded-1"
                                alt="product"
                            />
                        </div>
                        <div class="flex-grow-1 ms-10">
                            <h3
                                class="fs-14 fw-medium mb-0"
                                style="max-width: 78px"
                            >
                                Apple iPhone 16
                            </h3>
                        </div>
                    </div>

                    <div
                        class="d-flex justify-content-between align-items-center"
                    >
                        <div
                            class="product-quantity border-0 bg-body-bg rounded-2"
                        >
                            <QuantityCounter />
                        </div>

                        <span class="fs-18 fw-medium text-primary ms-2 ms-sm-4"
                            >$799</span
                        >
                    </div>
                </div>
                <div
                    class="d-flex justify-content-between align-items-center child border-bottom px-3 px-sm-4"
                    style="padding-bottom: 20px; margin-bottom: 20px"
                >
                    <div class="d-flex align-items-center">
                        <div class="flex-shrink-0">
                            <v-img
                                src="/images/product-47.jpg"
                                style="width: 40px; height: 28px"
                                class="rounded-1"
                                alt="product"
                            />
                        </div>
                        <div class="flex-grow-1 ms-10">
                            <h3
                                class="fs-14 fw-medium mb-0"
                                style="max-width: 78px"
                            >
                                Adidas Woman
                            </h3>
                        </div>
                    </div>

                    <div
                        class="d-flex justify-content-between align-items-center"
                    >
                        <div
                            class="product-quantity border-0 bg-body-bg rounded-2"
                        >
                            <QuantityCounter />
                        </div>

                        <span class="fs-18 fw-medium text-primary ms-2 ms-sm-4"
                            >$85</span
                        >
                    </div>
                </div>
            </div>

            <div class="p-4 pb-0">
                <div class="bg-body-bg p-20 rounded-3 mb-30">
                    <ul class="ps-0 mb-3 list-unstyled last-child-none">
                        <li
                            class="d-flex justify-content-between align-items-center"
                            style="margin-bottom: 7px"
                        >
                            <span class="text-body">Total</span>
                            <span class="text-body">3 Items</span>
                        </li>
                        <li
                            class="d-flex justify-content-between align-items-center"
                            style="margin-bottom: 7px"
                        >
                            <span class="fw-medium text-secondary"
                                >Subtotal:</span
                            >
                            <span class="fw-medium text-secondary"
                                >$913.00</span
                            >
                        </li>
                        <li
                            class="d-flex justify-content-between align-items-center"
                            style="margin-bottom: 7px"
                        >
                            <span class="fw-medium text-secondary"
                                >Shipping:</span
                            >
                            <span class="fw-medium text-secondary">$0.00</span>
                        </li>
                        <li
                            class="d-flex justify-content-between align-items-center"
                            style="margin-bottom: 7px"
                        >
                            <span class="fw-medium text-secondary"
                                >Tax (10%):</span
                            >
                            <span class="fw-medium text-secondary">$91.30</span>
                        </li>
                    </ul>
                    <div
                        class="d-flex justify-content-between align-items-center"
                    >
                        <h3 class="fs-20 fw-medium mb-0">Payable Total</h3>
                        <h3 class="fs-20 fw-medium mb-0">$1004.30</h3>
                    </div>
                </div>

                <h3 class="fs-20 fw-medium mb-3">Payment Method</h3>

                <div
                    class="d-flex flex-wrap ga-2 justify-content-between align-items-center payment-method mb-30"
                >
                    <div>
                        <input
                            type="radio"
                            class="btn-check"
                            name="options-base"
                            id="option5"
                            autocomplete="off"
                        />
                        <label
                            class="btn text-center"
                            for="option5"
                            style="
                                width: 81px;
                                height: 66px;
                                background-color: #f6f7f9;
                                border: 1px solid #dde4ff;
                                border-radius: 0.375rem;
                                padding: 9px 0;
                                display: block;
                                cursor: pointer;
                            "
                        >
                            <div
                                class="d-flex justify-content-center align-items-center"
                            >
                                <v-img src="/images/cash.svg" alt="cash" />
                            </div>
                            <span class="d-block text-body">Cash</span>
                        </label>
                    </div>

                    <div class="">
                        <input
                            type="radio"
                            class="btn-check"
                            name="options-base"
                            id="option6"
                            autocomplete="off"
                            checked
                        />
                        <label
                            class="btn text-center"
                            for="option6"
                            style="
                                width: 81px;
                                height: 66px;
                                background-color: #f6f7f9;
                                border: 1px solid #dde4ff;
                                border-radius: 0.375rem;
                                padding: 9px 0;
                                display: block;
                                cursor: pointer;
                            "
                        >
                            <div
                                class="d-flex justify-content-center align-items-center"
                            >
                                <v-img src="/images/card.svg" alt="cash" />
                            </div>
                            <span class="d-block text-body">Card</span>
                        </label>
                    </div>

                    <div class="">
                        <input
                            type="radio"
                            class="btn-check"
                            name="options-base"
                            id="option8"
                            autocomplete="off"
                        />
                        <label
                            class="btn text-center"
                            for="option8"
                            style="
                                width: 81px;
                                height: 66px;
                                background-color: #f6f7f9;
                                border: 1px solid #dde4ff;
                                border-radius: 0.375rem;
                                padding: 9px 0;
                                display: block;
                                cursor: pointer;
                            "
                        >
                            <div
                                class="d-flex justify-content-center align-items-center"
                            >
                                <v-img src="/images/e-wallet.svg" alt="cash" />
                            </div>
                            <span class="d-block text-body">E-Wallet</span>
                        </label>
                    </div>
                </div>

                <RouterLink to="/ecommerce/checkout" class="place-order-btn">
                    Place Order
                </RouterLink>
            </div>
        </div>
    </v-card>
</template>

<script>
import { defineComponent } from "vue";
import QuantityCounter from "./QuantityCounter.vue";

export default defineComponent({
    name: "OrderDetails",
    components: {
        QuantityCounter,
    },
});
</script>

<style lang="scss" scoped>
.v-card {
    &.trezo-card {
        border: 1px solid var(--borderColor) !important;
    }
}
.order-details-card {
    .v-card-header {
        button {
            font-size: 24px !important;
        }
    }
    .text-primary {
        color: #605dff !important;
    }
    .text-secondary {
        --bs-text-opacity: 1;
        color: rgb(58 66 82) !important;
    }
    .payment-method {
        .btn-check:checked + .btn,
        :not(.btn-check) + .btn:active,
        .btn:first-child:active,
        .btn.active,
        .btn.show {
            border-color: #605dff !important;
            background-color: #ecf0ff !important;
        }
    }
    .btn-check {
        position: absolute;
        clip: rect(0, 0, 0, 0);
        pointer-events: none;
    }
    .place-order-btn {
        height: auto;
        min-width: auto;
        font-size: 16px;
        font-weight: 500;
        padding: 8px 1.5rem;
        width: 100%;
        position: relative;
        border-radius: 7px;
        text-align: center;
        display: inline-block;
        color: var(--whiteColor);
        border: 1px solid var(--primaryColor);
        background-color: var(--primaryColor);
    }
}
</style>

// angular-material/src/app/dashboard/pos-system/order-details/order-details.component.ts
import { Component } from '@angular/core';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';
import { RouterLink } from '@angular/router';
import { QuantityCounterComponent } from './quantity-counter/quantity-counter.component';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';

@Component({
    selector: 'app-order-details',
    imports: [RouterLink, MatCardModule, MatButtonModule, QuantityCounterComponent],
    templateUrl: './order-details.component.html',
    styleUrl: './order-details.component.scss'
})
export class OrderDetailsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<mat-card
    class="order-details-card style-two mb-25 border-radius d-block border-0 shadow-none"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0 fw-medium">
                Order Details
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button type="button" mat-button class="lh-1 p-0">
                <i class="material-symbols-outlined">
                    autorenew
                </i>
            </button>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content class="bg-white">
        <div class="list">
            <div class="item d-md-flex align-items-center justify-content-between">
                <div class="info position-relative d-flex align-items-center">
                    <img src="images/products/product15.jpg" alt="product-image">
                    <h6 class="mb-0 fw-medium">
                        Maybelline Lash
                    </h6>
                    <a routerLink="." class="position-absolute top-0 start-0 end-0 bottom-0 z-1"></a>
                </div>
                <div class="quantity-price d-flex align-items-center">
                    <app-quantity-counter [initialValue]="1" />
                    <div class="price lh-1 fw-medium text-primary">
                        $29
                    </div>
                </div>
            </div>
            <div class="item d-md-flex align-items-center justify-content-between">
                <div class="info position-relative d-flex align-items-center">
                    <img src="images/products/product16.jpg" alt="product-image">
                    <h6 class="mb-0 fw-medium">
                        Apple iPhone 16
                    </h6>
                    <a routerLink="." class="position-absolute top-0 start-0 end-0 bottom-0 z-1"></a>
                </div>
                <div class="quantity-price d-flex align-items-center">
                    <app-quantity-counter [initialValue]="2" />
                    <div class="price lh-1 fw-medium text-primary">
                        $799
                    </div>
                </div>
            </div>
            <div class="item d-md-flex align-items-center justify-content-between">
                <div class="info position-relative d-flex align-items-center">
                    <img src="images/products/product17.jpg" alt="product-image">
                    <h6 class="mb-0 fw-medium">
                        Adidas Woman
                    </h6>
                    <a routerLink="." class="position-absolute top-0 start-0 end-0 bottom-0 z-1"></a>
                </div>
                <div class="quantity-price d-flex align-items-center">
                    <app-quantity-counter [initialValue]="1" />
                    <div class="price lh-1 fw-medium text-primary">
                        $85
                    </div>
                </div>
            </div>
        </div>
        <div class="payble-total border-radius">
            <div class="item d-flex align-items-center justify-content-between">
                <span class="d-block">
                    Total:
                </span>
                <span class="d-block">
                    3 Items
                </span>
            </div>
            <div class="item d-flex align-items-center justify-content-between">
                <span class="d-block fw-medium text-black">
                    Subtotal:
                </span>
                <span class="d-block fw-medium text-black">
                    $913.00
                </span>
            </div>
            <div class="item d-flex align-items-center justify-content-between">
                <span class="d-block fw-medium text-black">
                    Shipping:
                </span>
                <span class="d-block fw-medium text-black">
                    $0.00
                </span>
            </div>
            <div class="item d-flex align-items-center justify-content-between">
                <span class="d-block fw-medium text-black">
                    Tax (10%):
                </span>
                <span class="d-block fw-medium text-black">
                    $91.30
                </span>
            </div>
            <div class="item total d-flex align-items-center justify-content-between">
                <span class="d-block fw-medium text-black">
                    Payble Total:
                </span>
                <span class="d-block fw-medium text-black">
                    $1004.30
                </span>
            </div>
        </div>
        <div class="payment-method">
            <h4 class="fw-medium">
                Payment Method
            </h4>
            <div class="method-type d-flex align-items-center">
                <div class="item text-center position-relative">
                    <i class="material-symbols-outlined">
                        paid
                    </i>
                    <span class="d-block">
                        Cash
                    </span>
                    <input class="form-check-input" type="radio" name="paymentMethod" id="cashType">
                </div>
                <div class="item text-center position-relative">
                    <i class="material-symbols-outlined">
                        credit_card
                    </i>
                    <span class="d-block">
                        Card
                    </span>
                    <input class="form-check-input" type="radio" name="paymentMethod" id="cardType" checked>
                </div>
                <div class="item text-center position-relative">
                    <i class="material-symbols-outlined">
                        wallet
                    </i>
                    <span class="d-block">
                        E-Wallet
                    </span>
                    <input class="form-check-input" type="radio" name="paymentMethod" id="eWalletType">
                </div>
            </div>
        </div>
        <button type="button" mat-button>
            Place Order
        </button>
    </mat-card-content>
</mat-card>
