// react-bootstrap/src/components/Dashboard/Doctor/UpgradePlan.js
"use client";

import React from "react";
import { Card } from "react-bootstrap";

const UpgradePlan = () => {
  return (
    <>
      <Card
        className="border-0 rounded-3 p-4 mb-4"
        style={{
          background: "linear-gradient(90deg, #4936F5 0%, #4737D6 100%)",
        }}
      >
        <div className="d-flex flex-wrap gap-3 align-items-center justify-content-between">
          <h3
            className="fs-20 text-white mb-0"
            style={{
              maxWidth: "300px",
              lineHeight: 1.6,
            }}
          >
            Upgrade Plan To Manage 20K+ Patients
          </h3>

          <div>
            <img
              src="/images/upgrade.png"
              alt="upgrade"
              width={145}
              height={76}
            />
          </div>
        </div>
      </Card>
    </>
  );
};

export default UpgradePlan;

// nuxtjs-vuetify/components/Dashboard/Doctor/UpgradePlan.vue
<template>
  <v-card
    class="upgrade-plan-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="trezo-card-content">
      <div class="row align-items-center">
        <div class="col-sm-6">
          <h3 class="mb-0 text-white fw-semibold">
            Upgrade Plan To Manage 20K+ Patients
          </h3>
        </div>
        <div class="col-sm-6">
          <div class="image text-center text-sm-end">
            <v-img src="@/assets/images/users.png" alt="users-image" />
          </div>
        </div>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "UpgradePlan",
});
</script>

<style lang="scss" scoped>
.upgrade-plan-card {
  background: linear-gradient(90deg, #4936f5 0%, #4737d6 100%);
  padding: {
    top: 18.5px;
    bottom: 18.5px;
    left: 25px;
    right: 25px;
  }
  .trezo-card-content {
    h3 {
      font-size: 20px;
      line-height: 1.5;
      max-width: 250px;
    }
    .image {
      .v-img {
        justify-content: end;
      }
    }
  }
}

/* Max width 767px */
@media only screen and (max-width: 767px) {
  .upgrade-plan-card {
    text-align: center;
    padding: {
      top: 17px;
      bottom: 17px;
    }
    .trezo-card-content {
      h3 {
        font-size: 16px;
        max-width: 100%;
        margin-bottom: 15px !important;
      }
    }
  }
}

/* Min width 576px to Max width 767px */
@media only screen and (min-width: 576px) and (max-width: 767px) {
  .upgrade-plan-card {
    text-align: start;
    padding: {
      top: 20px;
      bottom: 20px;
    }
    .trezo-card-content {
      h3 {
        margin-bottom: 0 !important;
      }
    }
  }
}

/* Min width 768px to Max width 991px */
@media only screen and (min-width: 768px) and (max-width: 991px) {
  .upgrade-plan-card {
    padding: {
      top: 20px;
      bottom: 20px;
    }
    .trezo-card-content {
      h3 {
        font-size: 18px;
      }
    }
  }
}
</style>
