// angular-tailwindcss/src/app/dashboard/real-estate-agent/latest-transactions/latest-transactions.component.ts
import { NgIf } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Component, HostListener } from '@angular/core';

@Component({
    selector: 'app-latest-transactions',
    imports: [NgIf, RouterLink],
    templateUrl: './latest-transactions.component.html',
    styleUrl: './latest-transactions.component.scss'
})
export class LatestTransactionsComponent {

    // Card Header Menu
    isCardHeaderOpen = false;
    toggleCardHeaderMenu() {
        this.isCardHeaderOpen = !this.isCardHeaderOpen;
    }
    @HostListener('document:click', ['$event'])
    handleClickOutside(event: Event) {
        const target = event.target as HTMLElement;
        if (!target.closest('.trezo-card-dropdown')) {
            this.isCardHeaderOpen = false;
        }
    }

}
<div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
        <div class="trezo-card-title">
            <h5 class="!mb-0">
                Latest Transactions
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <div class="trezo-card-dropdown relative">
                <button type="button" class="trezo-card-dropdown-btn inline-block rounded-md bg-[#f5f7f8] dark:bg-[#0a0e19] py-[5px] md:py-[6.5px] px-[12px] md:px-[19px] transition-all hover:bg-gray-100 dark:hover:bg-dark" (click)="toggleCardHeaderMenu()">
                    <span class="inline-block relative ltr:pr-[17px] ltr:md:pr-[20px] rtl:pl-[17px] rtl:ml:pr-[20px]">
                        Monthly
                        <i class="ri-arrow-down-s-line text-lg absolute ltr:-right-[3px] rtl:-left-[3px] top-1/2 -translate-y-1/2 mt-px"></i>
                    </span>
                </button>
                <ul class="trezo-card-dropdown-menu transition-all bg-white shadow-3xl rounded-md top-full py-[15px] absolute ltr:right-0 rtl:left-0 w-[195px] z-[5] dark:bg-dark dark:shadow-none" *ngIf="isCardHeaderOpen">
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            Weekly
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            Monthly
                        </button>
                    </li>
                    <li>
                        <button type="button" class="block w-full transition-all text-black ltr:text-left rtl:text-right relative py-[8px] px-[20px] hover:bg-gray-50 dark:text-white dark:hover:bg-black">
                            Yearly
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="table-responsive overflow-x-auto">
            <table class="w-full">
                <thead>
                    <tr>
                        <th class="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[13px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                            Client
                        </th>
                        <th class="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[13px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                            Email
                        </th>
                        <th class="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[13px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                            Amount
                        </th>
                        <th class="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[13px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                            Payment Method
                        </th>
                        <th class="whitespace-nowrap uppercase text-[10px] font-bold tracking-[1px] ltr:text-left rtl:text-right pt-0 pb-[13px] px-[20px] text-gray-500 dark:text-gray-400 ltr:first:pl-0 rtl:first:pr-0 ltr:last:pr-0 rtl:first:pl-0">
                            Status
                        </th>
                    </tr>
                </thead>
                <tbody class="text-black dark:text-white">
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[10px]">
                                <div class="rounded-full w-[32px]">
                                    <img src="images/users/user58.jpg" class="inline-block rounded-full" alt="user-image">
                                </div>
                                <span class="font-semibold inline-block">
                                    Johhna Loren
                                </span>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-medium text-gray-500 dark:text-gray-400">
                                loren123&#64;gmail.com
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-semibold">
                                $6240
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[8px] text-xs font-semibold text-gray-600 dark:text-gray-400">
                                <img src="images/payment-method/paypal.svg" alt="paypal">
                                Paypal
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="inline-block text-xs font-medium py-px px-[10px] text-success-600 border border-success-500 bg-success-100 dark:bg-[#15203c] dark:border-[#15203c] text-sm rounded-[100px]">
                                Completed
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[10px]">
                                <div class="rounded-full w-[30px]">
                                    <img src="images/users/user53.jpg" class="inline-block rounded-full" alt="user-image">
                                </div>
                                <span class="font-semibold inline-block">
                                    Skyler Queen
                                </span>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-medium text-gray-500 dark:text-gray-400">
                                skyqueen&#64;gmail.com
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-semibold">
                                $5135
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[8px] text-xs font-semibold text-gray-600 dark:text-gray-400">
                                <img src="images/payment-method/wise.svg" alt="wise">
                                Wise
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="inline-block text-xs font-medium py-px px-[10px] text-info-600 border border-info-500 bg-info-50 dark:bg-[#15203c] dark:border-[#15203c] text-sm rounded-[100px]">
                                Pending
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[10px]">
                                <div class="rounded-full w-[30px]">
                                    <img src="images/users/user55.jpg" class="inline-block rounded-full" alt="user-image">
                                </div>
                                <span class="font-semibold inline-block">
                                    Jonathon Watson
                                </span>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-medium text-gray-500 dark:text-gray-400">
                                jona2134&#64;gmail.com
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-semibold">
                                $4321
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[8px] text-xs font-semibold text-gray-600 dark:text-gray-400">
                                <img src="images/payment-method/bank.svg" alt="bank">
                                Bank
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="inline-block text-xs font-medium py-px px-[10px] text-danger-600 border border-danger-500 bg-danger-100 dark:bg-[#15203c] dark:border-[#15203c] text-sm rounded-[100px]">
                                Failed
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[10px]">
                                <div class="rounded-full w-[30px]">
                                    <img src="images/users/user54.jpg" class="inline-block rounded-full" alt="user-image">
                                </div>
                                <span class="font-semibold inline-block">
                                    Walter White
                                </span>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-medium text-gray-500 dark:text-gray-400">
                                puzzleworld&#64;gmail.com
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-semibold">
                                $3124
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[8px] text-xs font-semibold text-gray-600 dark:text-gray-400">
                                <img src="images/payment-method/paypal.svg" alt="paypal">
                                Paypal
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="inline-block text-xs font-medium py-px px-[10px] text-success-600 border border-success-500 bg-success-100 dark:bg-[#15203c] dark:border-[#15203c] text-sm rounded-[100px]">
                                Completed
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[10px]">
                                <div class="rounded-full w-[30px]">
                                    <img src="images/users/user40.jpg" class="inline-block rounded-full" alt="user-image">
                                </div>
                                <span class="font-semibold inline-block">
                                    David Carlen
                                </span>
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-medium text-gray-500 dark:text-gray-400">
                                liveslong&#64;gmail.com
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="block text-xs font-semibold">
                                $2137
                            </span>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <div class="flex items-center gap-[8px] text-xs font-semibold text-gray-600 dark:text-gray-400">
                                <img src="images/payment-method/skrill.svg" alt="skrill">
                                Skrill
                            </div>
                        </td>
                        <td class="ltr:text-left rtl:text-right whitespace-nowrap px-[20px] py-[13px] ltr:first:pl-0 rtl:first:pr-0 border-b border-primary-50 dark:border-[#172036] ltr:last:pr-0 rtl:last:pl-0">
                            <span class="inline-block text-xs font-medium py-px px-[10px] text-info-600 border border-info-500 bg-info-50 dark:bg-[#15203c] dark:border-[#15203c] text-sm rounded-[100px]">
                                Pending
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="pt-[13px] sm:flex sm:items-center justify-between">
            <p class="!mb-0 text-xs">
                Showing 5 of 36 results
            </p>
            <ol class="mt-[10px] sm:mt-0">
                <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                    <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500">
                        <span class="opacity-0">
                            0
                        </span>
                        <i class="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                            chevron_left
                        </i>
                    </a>
                </li>
                <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                    <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-primary-500 bg-primary-500 text-white">
                        1
                    </a>
                </li>
                <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                    <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500">
                        2
                    </a>
                </li>
                <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                    <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500">
                        3
                    </a>
                </li>
                <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                    <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500">
                        4
                    </a>
                </li>
                <li class="inline-block mx-[3px] ltr:first:ml-0 ltr:last:mr-0 rtl:first:mr-0 rtl:last:ml-0">
                    <a routerLink="." class="w-[31px] h-[31px] block leading-[29px] relative text-center rounded-md border border-gray-100 dark:border-[#172036] transition-all hover:bg-primary-500 hover:text-white hover:border-primary-500">
                        <span class="opacity-0">
                            0
                        </span>
                        <i class="material-symbols-outlined left-0 right-0 absolute top-1/2 -translate-y-1/2">
                            chevron_right
                        </i>
                    </a>
                </li>
            </ol>
        </div>
    </div>
</div>

// vuejs-vuetify/src/components/Dashboard/RealEstateAgent/LatestTransactions.vue
<template>
  <v-card
    class="latest-transactions-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Latest Transactions</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="card-header-menu d-inline-block border-radius bg-gray border-0"
          >
            {{ selectedPeriod }}
          </button>
        </template>
        <v-list class="menu-content">
          <v-list-item
            v-for="period in timePeriods"
            :key="period"
            @click="selectedPeriod = period"
          >
            <v-list-item-title>{{ period }}</v-list-item-title>
          </v-list-item>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="basic-table table-responsive">
        <table class="table mb-0">
          <thead>
            <tr>
              <th scope="col" class="fw-semibold">Client</th>
              <th scope="col" class="fw-semibold">Email</th>
              <th scope="col" class="fw-semibold">Amount</th>
              <th scope="col" class="fw-semibold">Payment Method</th>
              <th scope="col" class="fw-semibold">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="transaction in paginatedTransactions"
              :key="transaction.id"
            >
              <td>
                <div class="employee-info d-flex align-items-center">
                  <v-img
                    :src="transaction.avatar"
                    class="rounded-circle"
                    alt="user"
                  />
                  <span class="d-block fw-semibold">
                    {{ transaction.name }}
                  </span>
                </div>
              </td>
              <td class="fw-medium text-body">
                {{ transaction.email }}
              </td>
              <td class="fw-semibold">
                {{ formatCurrency(transaction.amount) }}
              </td>
              <td>
                <div class="payment-method-info d-flex align-items-center">
                  <v-img
                    :src="transaction.paymentMethod.icon"
                    :alt="transaction.paymentMethod.name"
                  />
                  <span class="d-block fw-semibold">
                    {{ transaction.paymentMethod.name }}
                  </span>
                </div>
              </td>
              <td>
                <span
                  class="trezo-badge with-border border-radius"
                  :class="statusClasses(transaction.status)"
                >
                  {{ transaction.status }}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div
        class="d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
      >
        <span class="fs-12 fw-medium">
          Showing {{ showingFrom }}-{{ showingTo }} of
          {{ transactions.length }} Results
        </span>

        <nav aria-label="Page navigation example">
          <ul class="pagination mb-0 justify-content-center">
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Previous"
                @click="prevPage"
                :disabled="currentPage === 1"
              >
                <i class="material-symbols-outlined">keyboard_arrow_left</i>
              </button>
            </li>
            <li class="page-item" v-for="page in totalPages" :key="page">
              <button
                class="page-link"
                :class="{ active: currentPage === page }"
                @click="currentPage = page"
              >
                {{ page }}
              </button>
            </li>
            <li class="page-item">
              <button
                class="page-link icon"
                aria-label="Next"
                @click="nextPage"
                :disabled="currentPage === totalPages"
              >
                <i class="material-symbols-outlined">keyboard_arrow_right</i>
              </button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, ref, computed } from "vue";

interface PaymentMethod {
  name: string;
  icon: string;
}

interface Transaction {
  id: number;
  name: string;
  email: string;
  avatar: string;
  amount: number;
  paymentMethod: PaymentMethod;
  status: "Completed" | "Pending" | "Failed";
  date: string;
}

export default defineComponent({
  name: "LatestTransactions",
  setup() {
    const timePeriods = ["Daily", "Weekly", "Monthly", "Yearly"];
    const selectedPeriod = ref("Monthly");

    const transactions = ref<Transaction[]>([
      {
        id: 1,
        name: "Johhna Loren",
        email: "loren123@gmail.com",
        avatar: require("@/assets/images/user-166.png"),
        amount: 6240,
        paymentMethod: {
          name: "Paypal",
          icon: require("@/assets/images/paypal.png"),
        },
        status: "Completed",
        date: "2023-05-15",
      },
      {
        id: 2,
        name: "Skyler Queen",
        email: "skyqueen@gmail.com",
        avatar: require("@/assets/images/user-170.png"),
        amount: 5135,
        paymentMethod: {
          name: "Wise",
          icon: require("@/assets/images/wise.png"),
        },
        status: "Pending",
        date: "2023-05-14",
      },
      {
        id: 3,
        name: "Jonathon Watson",
        email: "jona2134@gmail.com",
        avatar: require("@/assets/images/user-172.png"),
        amount: 4321,
        paymentMethod: {
          name: "Bank",
          icon: require("@/assets/images/bank.png"),
        },
        status: "Failed",
        date: "2023-05-13",
      },
      {
        id: 4,
        name: "Walter White",
        email: "puzzleworld@gmail.com",
        avatar: require("@/assets/images/user-171.png"),
        amount: 3124,
        paymentMethod: {
          name: "Paypal",
          icon: require("@/assets/images/paypal.png"),
        },
        status: "Completed",
        date: "2023-05-12",
      },
      {
        id: 5,
        name: "David Carlen",
        email: "liveslong@gmail.com",
        avatar: require("@/assets/images/user-166.png"),
        amount: 2137,
        paymentMethod: {
          name: "Skrill",
          icon: require("@/assets/images/skrill.png"),
        },
        status: "Pending",
        date: "2023-05-11",
      },
      {
        id: 6,
        name: "Walter White",
        email: "puzzleworld@gmail.com",
        avatar: require("@/assets/images/user-171.png"),
        amount: 3124,
        paymentMethod: {
          name: "Paypal",
          icon: require("@/assets/images/paypal.png"),
        },
        status: "Completed",
        date: "2023-05-12",
      },
      {
        id: 7,
        name: "Skyler Queen",
        email: "skyqueen@gmail.com",
        avatar: require("@/assets/images/user-170.png"),
        amount: 5135,
        paymentMethod: {
          name: "Wise",
          icon: require("@/assets/images/wise.png"),
        },
        status: "Pending",
        date: "2023-05-14",
      },
    ]);

    // Pagination
    const itemsPerPage = 5;
    const currentPage = ref(1);

    const totalPages = computed(() =>
      Math.ceil(transactions.value.length / itemsPerPage)
    );
    const paginatedTransactions = computed(() => {
      const start = (currentPage.value - 1) * itemsPerPage;
      const end = start + itemsPerPage;
      return transactions.value.slice(start, end);
    });

    const showingFrom = computed(
      () => (currentPage.value - 1) * itemsPerPage + 1
    );
    const showingTo = computed(() => {
      const end = currentPage.value * itemsPerPage;
      return end > transactions.value.length ? transactions.value.length : end;
    });

    const nextPage = () => {
      if (currentPage.value < totalPages.value) {
        currentPage.value++;
      }
    };

    const prevPage = () => {
      if (currentPage.value > 1) {
        currentPage.value--;
      }
    };

    // Helper functions
    const formatCurrency = (amount: number) => {
      return new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
        minimumFractionDigits: 0,
      }).format(amount);
    };

    const statusClasses = (status: string) => {
      const classes: Record<string, string> = {
        Completed: "finished",
        Pending: "sPending",
        Failed: "rejected",
      };
      return classes[status] || "";
    };

    return {
      timePeriods,
      selectedPeriod,
      transactions,
      paginatedTransactions,
      currentPage,
      totalPages,
      showingFrom,
      showingTo,
      nextPage,
      prevPage,
      formatCurrency,
      statusClasses,
    };
  },
});
</script>

<style lang="scss" scoped>
.latest-transactions-card {
  .trezo-card-content {
    .basic-table {
      table,
      .table {
        thead {
          tr {
            background-color: transparent !important;
            th {
              font-size: 10px;
              letter-spacing: 1px;
              color: var(--bodyColor);
              text-transform: uppercase;
              background-color: transparent;
              text-align: left;
              padding: {
                bottom: 12px;
                top: 0;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
              }
            }
          }
        }
        tbody {
          tr {
            td {
              font-size: 12px;
              padding: {
                top: 10px;
                bottom: 11px;
              }
              border: {
                left-width: 0;
                right-width: 0;
              }
              .employee-info {
                gap: 10px;

                .v-img {
                  width: 32px;
                }
                span {
                  font-size: var(--fontSize);
                }
              }
              .payment-method-info {
                gap: 8px;
              }
              .trezo-badge {
                padding: 1px 10px;
              }
              &:first-child {
                padding-left: 0 !important;
              }
              &:last-child {
                padding-right: 0 !important;
              }
            }
          }
        }
      }
    }
  }
}
</style>
