// angular-material/src/app/dashboard/real-estate-agent/recent-clients/recent-clients.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatMenuModule } from '@angular/material/menu';
import { MatButtonModule } from '@angular/material/button';
import { CustomizerSettingsService } from '../../../customizer-settings/customizer-settings.service';

@Component({
    selector: 'app-recent-clients',
    imports: [RouterLink, MatCardModule, MatButtonModule, MatMenuModule],
    templateUrl: './recent-clients.component.html',
    styleUrl: './recent-clients.component.scss'
})
export class RecentClientsComponent {

    constructor(
        public themeService: CustomizerSettingsService
    ) {}

}
<mat-card
    class="recent-clients-card mb-25 border-radius d-block bg-white border-0 shadow-none"
    [class.component-rtl-enabled]="themeService.isRTLEnabled()"
    [class.component-dark-theme]="themeService.isDark()"
>
    <mat-card-header>
        <mat-card-title>
            <h5 class="mb-0">
                Recent Clients
            </h5>
        </mat-card-title>
        <mat-card-subtitle>
            <button mat-button [matMenuTriggerFor]="cardHeaderMenu" class="dot-menu style-two p-0 d-inline-block border-radius-0">
                <i class="ri-more-2-fill"></i>
            </button>
            <mat-menu #cardHeaderMenu="matMenu" class="card-header-menu" xPosition="before">
                <ul class="p-0 mt-0 mb-0 list-unstyled">
                    <li>
                        <button mat-menu-item>
                            This Day
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Week
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Month
                        </button>
                    </li>
                    <li>
                        <button mat-menu-item>
                            This Year
                        </button>
                    </li>
                </ul>
            </mat-menu>
        </mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
        <ul class="m-0 p-0 list-unstyled">
            <li class="d-flex align-items-center position-relative">
                <div class="image position-relative">
                    <img src="images/users/user48.jpg" alt="user-image" class="rounded-circle">
                    <span class="active-status"></span>
                </div>
                <div class="content">
                    <span class="d-block fw-semibold text-black">
                        Johhna Loren
                    </span>
                    <span class="d-block">
                        Doctor
                    </span>
                </div>
                <a routerLink="." class="lh-1 p-0 rounded-circle" mat-button>
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="d-flex align-items-center position-relative">
                <div class="image position-relative">
                    <img src="images/users/user37.jpg" alt="user-image" class="rounded-circle">
                    <span class="active-status"></span>
                </div>
                <div class="content">
                    <span class="d-block fw-semibold text-black">
                        Zinia Watson
                    </span>
                    <span class="d-block">
                        Lawyer
                    </span>
                </div>
                <a routerLink="." class="lh-1 p-0 rounded-circle" mat-button>
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="d-flex align-items-center position-relative">
                <div class="image position-relative">
                    <img src="images/users/user38.jpg" alt="user-image" class="rounded-circle">
                    <span class="active-status"></span>
                </div>
                <div class="content">
                    <span class="d-block fw-semibold text-black">
                        Angela Carter
                    </span>
                    <span class="d-block">
                        Businesswoman
                    </span>
                </div>
                <a routerLink="." class="lh-1 p-0 rounded-circle" mat-button>
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="d-flex align-items-center position-relative">
                <div class="image position-relative">
                    <img src="images/users/user39.jpg" alt="user-image" class="rounded-circle">
                    <span class="active-status offline"></span>
                </div>
                <div class="content">
                    <span class="d-block fw-semibold text-black">
                        Skyler White
                    </span>
                    <span class="d-block">
                        Enterpreuner
                    </span>
                </div>
                <a routerLink="." class="lh-1 p-0 rounded-circle" mat-button>
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="d-flex align-items-center position-relative">
                <div class="image position-relative">
                    <img src="images/users/user40.jpg" alt="user-image" class="rounded-circle">
                    <span class="active-status"></span>
                </div>
                <div class="content">
                    <span class="d-block fw-semibold text-black">
                        Jane Ronan
                    </span>
                    <span class="d-block">
                        Editor
                    </span>
                </div>
                <a routerLink="." class="lh-1 p-0 rounded-circle" mat-button>
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
            <li class="d-flex align-items-center position-relative">
                <div class="image position-relative">
                    <img src="images/users/user42.jpg" alt="user-image" class="rounded-circle">
                    <span class="active-status offline"></span>
                </div>
                <div class="content">
                    <span class="d-block fw-semibold text-black">
                        Viktor James
                    </span>
                    <span class="d-block">
                        Editor
                    </span>
                </div>
                <a routerLink="." class="lh-1 p-0 rounded-circle" mat-button>
                    <i class="ri-arrow-right-line"></i>
                </a>
            </li>
        </ul>
    </mat-card-content>
</mat-card>

// vuejs-vuetify/src/components/Dashboard/RealEstateAgent/RecentClients.vue
<template>
  <v-card
    class="recent-clients-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Recent Clients</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-2-fill"></i>
          </button>
        </template>

        <v-list class="menu-content">
          <button type="button" class="bg-transparent border-none">
            This Day
          </button>
          <button type="button" class="bg-transparent border-none">
            This Week
          </button>
          <button type="button" class="bg-transparent border-none">
            This Month
          </button>
          <button type="button" class="bg-transparent border-none">
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <ul class="m-0 p-0 list-unstyled">
        <li
          class="d-flex align-items-center position-relative"
          v-for="client in clients"
          :key="client.id"
        >
          <div class="image position-relative">
            <v-img :src="client.avatar" alt="user" class="rounded-circle" />
            <span
              :class="[
                'active-status',
                client.status === 'online' ? 'online' : 'offline',
              ]"
            ></span>
          </div>
          <div class="content">
            <span class="d-block fw-semibold text-black"> Johhna Loren </span>
            <span class="d-block"> Doctor </span>
          </div>
          <RouterLink to="/social/profile" class="link-btn lh-1">
            <i class="ri-arrow-right-line"></i>
          </RouterLink>
        </li>
      </ul>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Client {
  id: number;
  name: string;
  profession: string;
  avatar: string;
  status: "online" | "offline";
}

export default defineComponent({
  name: "RecentClients",
  setup() {
    const clients: Client[] = [
      {
        id: 1,
        name: "Johhna Loren",
        profession: "Doctor",
        avatar: require("@/assets/images/user-177.png"),
        status: "online",
      },
      {
        id: 2,
        name: "Zinia Watson",
        profession: "Lawyer",
        avatar: require("@/assets/images/user-157.png"),
        status: "online",
      },
      {
        id: 3,
        name: "Angela Carter",
        profession: "Businesswoman",
        avatar: require("@/assets/images/user-158.png"),
        status: "online",
      },
      {
        id: 4,
        name: "Skyler White",
        profession: "Enterpreuner",
        avatar: require("@/assets/images/user-159.png"),
        status: "offline",
      },
      {
        id: 5,
        name: "Jane Ronan",
        profession: "Editor",
        avatar: require("@/assets/images/user-160.png"),
        status: "online",
      },
      {
        id: 6,
        name: "Viktor James",
        profession: "Editor",
        avatar: require("@/assets/images/user-154.png"),
        status: "offline",
      },
    ];

    return {
      clients,
    };
  },
});
</script>

<style scoped lang="scss">
.recent-clients-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        gap: 12px;
        padding: {
          top: 10px;
          bottom: 10px;
        }
        .image {
          padding: {
            right: 2px;
            bottom: 2px;
          }
          img {
            width: 35px;
          }
          .active-status {
            right: 0;
            bottom: 0;
            width: 12px;
            height: 12px;
            border-radius: 50%;
            position: absolute;
            background: var(--successColor);
            border: 1px solid var(--whiteColor);

            &.offline {
              background: #8695aa;
            }
          }
        }
        .content {
          span {
            &:nth-child(2) {
              font-size: 12px;
              margin-top: 2px;
            }
          }
        }
        .link-btn {
          top: 50%;
          right: 0;
          font-size: 18px;
          position: absolute;
          color: var(--bodyColor);
          transform: translateY(-50%);

          &:hover {
            color: var(--primaryColor);
          }
        }
        &:first-child {
          border-top: 1px solid var(--borderColor);
        }
      }
    }
  }
}
</style>
