// react-bootstrap/src/components/FrontPages/Common/Footer.js
"use client";

import { Container, Row, Col } from "react-bootstrap";
import { Link } from "react-router-dom";

const footerData = {
  logo: {
    black: "/images/landing/logo.svg",
    white: "/images/white-logo.svg",
  },
  description:
    "With customizable dashboards tailored to your needs, collaborate effortlessly with your team and stay ahead with real-time updates.",
  socialLinks: [
    { url: "https://www.facebook.com/", icon: "ri-facebook-fill" },
    { url: "https://www.twitter.com/", icon: "ri-twitter-x-line" },
    { url: "https://www.linkedin.com/", icon: "ri-linkedin-fill" },
    { url: "https://www.dribbble.com/", icon: "ri-dribbble-line" },
  ],
  sections: [
    {
      title: "Our Products",
      links: [
        { label: "Trezo Dashboard", url: "#" },
        { label: "Tagus Admin", url: "#" },
        { label: "eCademy LMS", url: "#" },
        { label: "Admash Template", url: "#" },
      ],
    },
    {
      title: "Quick Links",
      links: [
        { label: "Home", url: "#" },
        { label: "Features", url: "#" },
        { label: "Testimonials", url: "#" },
        { label: "Our Team", url: "#" },
      ],
    },
    {
      title: "Privacy Policy",
      links: [
        { label: "Terms & Conditions", url: "#" },
        { label: "Cookie Policy", url: "#" },
        { label: "Notice at Collection", url: "#" },
        { label: "Privacy Policy", url: "#" },
      ],
    },
  ],
  brand: "Trezo",
  copyright: {
    ownerName: "EnvyTheme",
    ownerUrl: "https://envytheme.com/",
  },
};

const Footer = () => {
  return (
    <>
      <div className="footers-area pb-125 position-relative z-2">
        <Container>
          <Row>
            {/* Logo and Description */}
            <Col sm={6} lg={3}>
              <div className="footer-single-item mb-4">
                <Link to="/" className="footer-logo d-inline-block mb-4">
                  <img
                    src={footerData.logo.black}
                    alt="logo"
                    width={132}
                    height={34}
                    className="black-logo"
                  />
                  <img
                    src={footerData.logo.white}
                    alt="logo"
                    width={132}
                    height={34}
                    className="white-logo"
                  />
                </Link>

                <p className="mb-4 pb-lg-2">{footerData.description}</p>

                <ul className="ps-0 mb-0 list-unstyled d-flex flex-wrap gap-3">
                  {footerData.socialLinks.map((link, index) => (
                    <li key={index}>
                      <a
                        href={link.url}
                        target="_blank"
                        rel="noreferrer"
                        className="text-decoration-none fs-20 text-primary"
                      >
                        <i className={link.icon}></i>
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            </Col>

            {/* Dynamic Sections */}
            {footerData.sections.map((section, index) => (
              <Col key={index} sm={6} lg={3}>
                <div
                  className={`footer-single-item mb-4 ${
                    section.addClasses || ""
                  }`}
                >
                  <h3 className="mb-md-4 mb-3 fw-semibold">{section.title}</h3>
                  <ul className="ps-0 mb-0 list-unstyled">
                    {section.links.map((link, linkIndex) => (
                      <li key={linkIndex} className="mb-2 pb-1">
                        <a href={link.url} className="text-decoration-none">
                          {link.label}
                        </a>
                      </li>
                    ))}
                  </ul>
                </div>
              </Col>
            ))}
          </Row>
        </Container>
      </div>

      <div className="copyright-area bg-white text-center py-4">
        <Container>
          <p className="fs-14">
            © <span className="text-primary-div">{footerData.brand}</span> is
            Proudly Owned by{" "}
            <a
              href={footerData.copyright.ownerUrl}
              target="_blank"
              rel="noreferrer"
              className="text-decoration-none text-primary"
            >
              {footerData.copyright.ownerName}
            </a>
          </p>
        </Container>
      </div>
    </>
  );
};

export default Footer;

// svelte-bootstrap/src/lib/components/App/Footer.svelte
<div class="footers-area pb-125 position-relative z-2">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4">
					<a href="/" class="footer-logo d-inline-block mb-4">
						<img src="/assets/images/landing/logo.svg" alt="logo" />
					</a>
					<p class="mb-4 pb-lg-2">
						With customizable dashboards tailored to your needs, collaborate effortlessly with your
						team and stay ahead with real-time updates.
					</p>

					<ul class="ps-0 mb-0 list-unstyled d-flex flex-wrap gap-3">
						<li>
							<a
								href="https://www.facebook.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="Facebook"
							>
								<i class="ri-facebook-fill"></i>
							</a>
						</li>
						<li>
							<a
								href="https://www.twitter.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="Twitter"
							>
								<i class="ri-twitter-x-line"></i>
							</a>
						</li>
						<li>
							<a
								href="https://www.linkedin.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="LinkedIn"
							>
								<i class="ri-linkedin-fill"></i>
							</a>
						</li>
						<li>
							<a
								href="https://www.dribbble.com/"
								target="_blank"
								class="text-decoration-none fs-20 text-primary"
								aria-label="Dribble"
							>
								<i class="ri-dribbble-line"></i>
							</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4 ms-lg-5 ps-lg-5">
					<h3 class="mb-md-4 mb-3 fw-semibold">Our Products</h3>
					<ul class="ps-0 mb-0 list-unstyled">
						<li class="mb-2 pb-1">
							<a href="/dahsboard" class="text-decoration-none">Trezo Dashboard</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/" class="text-decoration-none">Tagus Admin</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/" class="text-decoration-none">eCademy LMS</a>
						</li>
						<li class="mb-0">
							<a href="/" class="text-decoration-none">Admash Template</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4 ms-lg-5 ps-lg-4">
					<h3 class="mb-md-4 mb-3 fw-semibold">Quick Links</h3>
					<ul class="ps-0 mb-0 list-unstyled">
						<li class="mb-2 pb-1">
							<a href="/" class="text-decoration-none">Home</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/features" class="text-decoration-none">Features</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/faqs" class="text-decoration-none">Testimonials</a>
						</li>
						<li class="mb-0">
							<a href="/our-team" class="text-decoration-none">Our Team</a>
						</li>
					</ul>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6">
				<div class="footer-single-item mb-4">
					<h3 class="mb-md-4 mb-3 fw-semibold">Privacy Policy</h3>
					<ul class="ps-0 mb-0 list-unstyled">
						<li class="mb-2 pb-1">
							<a href="/#" class="text-decoration-none">Terms & Conditions</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/#" class="text-decoration-none">Cookie Policy</a>
						</li>
						<li class="mb-2 pb-1">
							<a href="/#" class="text-decoration-none">Notice at Collection</a>
						</li>
						<li class="mb-0">
							<a href="/#" class="text-decoration-none">Privacy Policy</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
