// vuejs-vuetify/src/components/Dashboard/RealEstateAgent/TopChannels.vue
<template>
  <v-card
    class="top-channels-card trezo-card border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Top Channels</h5>
      <div class="trezo-card-subtitle">
        <a href="#" class="view-all-btn d-inline-block">
          <span class="d-inline-block position-relative">
            Browse All
            <i class="ri-arrow-right-s-line"></i>
          </span>
        </a>
      </div>
    </div>

    <div class="trezo-card-content">
      <ul class="p-0 m-0 list-unstyled">
        <li
          class="d-flex align-items-center justify-content-between"
          v-for="channel in channels"
          :key="channel.id"
        >
          <div class="title d-flex align-items-center">
            <v-img :src="channel.icon" :alt="channel.name" />
            <div>
              <span class="d-block fw-semibold text-black">
                {{ channel.name }}
              </span>
              <span class="d-block">
                {{ channel.category }}
              </span>
            </div>
          </div>
          <div class="circle-progress-bar rounded-circle position-relative">
            <svg
              width="60"
              height="60"
              viewBox="-25 -25 250 250"
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              style="transform: rotate(-90deg)"
            >
              <circle
                r="90"
                cx="100"
                cy="100"
                fill="transparent"
                stroke="transparent"
                stroke-width="16px"
                stroke-dasharray="565.48px"
                stroke-dashoffset="0"
              ></circle>
              <circle
                r="90"
                cx="100"
                cy="100"
                :stroke="channel.color"
                stroke-width="16px"
                stroke-linecap="round"
                :stroke-dashoffset="getStrokeDashOffset(channel.percentage)"
                fill="transparent"
                stroke-dasharray="565.48px"
              ></circle>
            </svg>
            <span class="percentage d-block text-body">
              {{ channel.percentage }}%
            </span>
          </div>
        </li>
      </ul>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Channel {
  id: number;
  name: string;
  category: string;
  icon: string;
  percentage: number;
  color: string;
}

export default defineComponent({
  name: "TopChannels",
  setup() {
    const channels: Channel[] = [
      {
        id: 1,
        name: "Facebook",
        category: "Community",
        icon: require("@/assets/images/facebook-real.svg"),
        percentage: 80,
        color: "#6f77f3",
      },
      {
        id: 2,
        name: "Dribbble",
        category: "Community",
        icon: require("@/assets/images/dribbble-real.svg"),
        percentage: 75,
        color: "#5ba5fa",
      },
      {
        id: 3,
        name: "Instagram",
        category: "Reel",
        icon: require("@/assets/images/instagram-real.svg"),
        percentage: 80,
        color: "#fc7936",
      },
      {
        id: 4,
        name: "Google",
        category: "SEO & PPC",
        icon: require("@/assets/images/google-real.svg"),
        percentage: 100,
        color: "#58f229",
      },
      {
        id: 5,
        name: "Figma",
        category: "Community",
        icon: require("@/assets/images/figma-real.svg"),
        percentage: 60,
        color: "#bf85fb",
      },
    ];

    const getStrokeDashOffset = (percentage: number): string => {
      const circumference = 565.48; // 2 * π * r (where r = 90)
      return ((100 - percentage) / 100) * circumference + "px";
    };

    return {
      channels,
      getStrokeDashOffset,
    };
  },
});
</script>

<style lang="scss" scoped>
.top-channels-card {
  .trezo-card-content {
    ul {
      li {
        border-bottom: 1px solid var(--borderColor);
        padding-bottom: 10px;
        margin-bottom: 10px;

        .title {
          gap: 15px;

          span {
            &:nth-child(2) {
              font-size: 12px;
              margin-top: 2px;
            }
          }
        }
        .circle-progress-bar {
          width: 50px;
          height: 50px;

          svg {
            top: -5px;
            left: -5px;
            position: relative;
          }
          .percentage {
            top: 50%;
            left: 50%;
            font-size: 10px;
            position: absolute;
            transform: translateY(-50%) translateX(-50%);
          }
        }
        &:last-child {
          margin-bottom: 0;
          padding-bottom: 0;
          border-bottom-width: 0;
        }
      }
    }
  }
}
</style>

// angular-tailwindcss/src/app/dashboard/real-estate-agent/top-channels/top-channels.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-top-channels',
    imports: [RouterLink],
    templateUrl: './top-channels.component.html',
    styleUrl: './top-channels.component.scss'
})
export class TopChannelsComponent {}
<div class="trezo-card bg-white dark:bg-[#0c1427] p-[20px] md:p-[25px] rounded-md">
    <div class="trezo-card-header mb-[20px] md:mb-[25px] flex items-center justify-between">
        <div class="trezo-card-title">
            <h5 class="!mb-0">
                Top Channels
            </h5>
        </div>
        <div class="trezo-card-subtitle">
            <a routerLink="." class="inline-block relative ltr:pr-[13px] rtl:pl-[13px] leading-none transition-all hover:text-primary-500">
                Browse All <i class="ri-arrow-right-s-line absolute top-1/2 -translate-y-1/2 ltr:-right-[8px] rtl:-left-[8px] text-[23px] -mt-px"></i>
            </a>
        </div>
    </div>
    <div class="trezo-card-content">
        <div class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[10px] mb-[10px] last:border-none last:mb-0 last:pb-0">
            <div class="flex items-center gap-[15px]">
                <img src="images/icons/facebook3.svg" alt="facebook">
                <div>
                    <span class="block font-semibold text-black dark:text-white">
                        Facebook
                    </span>
                    <span class="block text-xs mt-[2px]">
                        Community
                    </span>
                </div>
            </div>
            <div class="rounded-full relative w-[50px] h-[50px]">
                <!-- Create Here: https://nikitahl.github.io/svg-circle-progress-generator/ -->
                <svg width="60" height="60" viewBox="-25 -25 250 250" version="1.1" xmlns="http://www.w3.org/2000/svg" class="relative -top-[5px] ltr:-left-[5px] rtl:-right-[5px]" style="transform:rotate(-90deg)">
                    <circle r="90" cx="100" cy="100" fill="transparent" stroke="transparent" stroke-width="16px" stroke-dasharray="565.48px" stroke-dashoffset="0"></circle>
                    <circle r="90" cx="100" cy="100" stroke="#605DFF" stroke-width="16px" stroke-linecap="round" stroke-dashoffset="113px" fill="transparent" stroke-dasharray="565.48px"></circle>
                </svg>
                <span class="block text-gray-500 dark:text-gray-400 top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-[10px] absolute">
                    80%
                </span>
            </div>
        </div>
        <div class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[10px] mb-[10px] last:border-none last:mb-0 last:pb-0">
            <div class="flex items-center gap-[15px]">
                <img src="images/icons/dribbble2.svg" alt="dribbble">
                <div>
                    <span class="block font-semibold text-black dark:text-white">
                        Dribbble
                    </span>
                    <span class="block text-xs mt-[2px]">
                        Community
                    </span>
                </div>
            </div>
            <div class="rounded-full relative w-[50px] h-[50px]">
                <!-- Create Here: https://nikitahl.github.io/svg-circle-progress-generator/ -->
                <svg width="60" height="60" viewBox="-25 -25 250 250" version="1.1" xmlns="http://www.w3.org/2000/svg" class="relative -top-[5px] ltr:-left-[5px] rtl:-right-[5px]" style="transform:rotate(-90deg)">
                    <circle r="90" cx="100" cy="100" fill="transparent" stroke="transparent" stroke-width="16px" stroke-dasharray="565.48px" stroke-dashoffset="0"></circle>
                    <circle r="90" cx="100" cy="100" stroke="#5DA8FF" stroke-width="16px" stroke-linecap="round" stroke-dashoffset="141px" fill="transparent" stroke-dasharray="565.48px"></circle>
                </svg>
                <span class="block text-gray-500 dark:text-gray-400 top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-[10px] absolute">
                    75%
                </span>
            </div>
        </div>
        <div class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[10px] mb-[10px] last:border-none last:mb-0 last:pb-0">
            <div class="flex items-center gap-[15px]">
                <img src="images/icons/instagram2.svg" alt="instagram">
                <div>
                    <span class="block font-semibold text-black dark:text-white">
                        Instagram
                    </span>
                    <span class="block text-xs mt-[2px]">
                        Reels
                    </span>
                </div>
            </div>
            <div class="rounded-full relative w-[50px] h-[50px]">
                <!-- Create Here: https://nikitahl.github.io/svg-circle-progress-generator/ -->
                <svg width="60" height="60" viewBox="-25 -25 250 250" version="1.1" xmlns="http://www.w3.org/2000/svg" class="relative -top-[5px] ltr:-left-[5px] rtl:-right-[5px]" style="transform:rotate(-90deg)">
                    <circle r="90" cx="100" cy="100" fill="transparent" stroke="transparent" stroke-width="16px" stroke-dasharray="565.48px" stroke-dashoffset="0"></circle>
                    <circle r="90" cx="100" cy="100" stroke="#FE7A36" stroke-width="16px" stroke-linecap="round" stroke-dashoffset="113px" fill="transparent" stroke-dasharray="565.48px"></circle>
                </svg>
                <span class="block text-gray-500 dark:text-gray-400 top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-[10px] absolute">
                    80%
                </span>
            </div>
        </div>
        <div class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[10px] mb-[10px] last:border-none last:mb-0 last:pb-0">
            <div class="flex items-center gap-[15px]">
                <img src="images/icons/google3.svg" alt="google">
                <div>
                    <span class="block font-semibold text-black dark:text-white">
                        Google
                    </span>
                    <span class="block text-xs mt-[2px]">
                        SEO & PPC
                    </span>
                </div>
            </div>
            <div class="rounded-full relative w-[50px] h-[50px]">
                <!-- Create Here: https://nikitahl.github.io/svg-circle-progress-generator/ -->
                <svg width="60" height="60" viewBox="-25 -25 250 250" version="1.1" xmlns="http://www.w3.org/2000/svg" class="relative -top-[5px] ltr:-left-[5px] rtl:-right-[5px]" style="transform:rotate(-90deg)">
                    <circle r="90" cx="100" cy="100" fill="transparent" stroke="transparent" stroke-width="16px" stroke-dasharray="565.48px" stroke-dashoffset="0"></circle>
                    <circle r="90" cx="100" cy="100" stroke="#58F229" stroke-width="16px" stroke-linecap="round" stroke-dashoffset="0px" fill="transparent" stroke-dasharray="565.48px"></circle>
                </svg>
                <span class="block text-gray-500 dark:text-gray-400 top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-[10px] absolute">
                    100%
                </span>
            </div>
        </div>
        <div class="flex items-center justify-between border-b border-gray-100 dark:border-[#172036] pb-[10px] mb-[10px] last:border-none last:mb-0 last:pb-0">
            <div class="flex items-center gap-[15px]">
                <img src="images/icons/figma2.svg" alt="figma">
                <div>
                    <span class="block font-semibold text-black dark:text-white">
                        Figma
                    </span>
                    <span class="block text-xs mt-px">
                        Community
                    </span>
                </div>
            </div>
            <div class="rounded-full relative w-[50px] h-[50px]">
                <!-- Create Here: https://nikitahl.github.io/svg-circle-progress-generator/ -->
                <svg width="60" height="60" viewBox="-25 -25 250 250" version="1.1" xmlns="http://www.w3.org/2000/svg" class="relative -top-[5px] ltr:-left-[5px] rtl:-right-[5px]" style="transform:rotate(-90deg)">
                    <circle r="90" cx="100" cy="100" fill="transparent" stroke="transparent" stroke-width="16px" stroke-dasharray="565.48px" stroke-dashoffset="0"></circle>
                    <circle r="90" cx="100" cy="100" stroke="#BF85FB" stroke-width="16px" stroke-linecap="round" stroke-dashoffset="226px" fill="transparent" stroke-dasharray="565.48px"></circle>
                </svg>
                <span class="block text-gray-500 dark:text-gray-400 top-1/2 -translate-y-1/2 left-1/2 -translate-x-1/2 text-[10px] absolute">
                    60%
                </span>
            </div>
        </div>
    </div>
</div>
