// react-nextjs-material-ui/src/components/Dashboard/CreditCard/TotalExpense.tsx
"use client";

import React from "react";
import { Card, Box, Typography } from "@mui/material";

const TotalExpense: React.FC = () => {
  return (
    <>
      <Card
        sx={{
          background: "linear-gradient(90deg, #F3E8FF 0%, #FFF 100%)",
          boxShadow: "none",
          borderRadius: "7px",
          mb: "25px",
          padding: { xs: "18px", sm: "20px", lg: "25px" },
        }}
        className="rmui-card for-dark-bg"
      >
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            gap: "10px",
          }}
        >
          <Box>
            <Typography sx={{ mb: "5px" }}>Total Expense</Typography>

            <Typography
              variant="h3"
              sx={{
                fontSize: { xs: "17px", md: "20px" },
                fontWeight: 700,
                mb: "22px",
              }}
            >
              $18,950
            </Typography>

            <Box
              sx={{
                display: "flex",
                alignItems: "center",
                gap: "10px",
              }}
            >
              <Box
                sx={{
                  border: "1px solid",
                  borderRadius: "30px",
                  backgroundColor: "error.50",
                  color: "error.main",
                  borderColor: "error.40",
                  lineHeight: 1,
                  fontSize: "12px",
                  display: "inline-block",
                  fontWeight: 500,
                  p: "3.5px 9px",
                  textTransform: "capitalize",
                }}
              >
                -18.1%
              </Box>

              <Typography sx={{ fontSize: "12px" }}>Last month</Typography>
            </Box>
          </Box>

          <Box
            sx={{
              width: "75px",
              height: "75px",
              backgroundColor: "purple.100",
              color: "purple.main",
              borderRadius: "50%",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <i
              className="material-symbols-outlined"
              style={{ fontSize: "35px" }}
            >
              payments
            </i>
          </Box>
        </Box>
      </Card>
    </>
  );
};

export default TotalExpense;

// vuejs-vuetify/src/components/Dashboard/CreditCard/TotalExpense.vue
<template>
  <v-card
    class="total-expense-card trezo-card mb-25 border-radius d-block border-0 shadow-none"
  >
    <div
      class="trezo-card-content d-flex justify-content-between align-items-center"
    >
      <div class="info">
        <span class="d-block"> Total Expense </span>
        <h3>$18,950</h3>
        <div class="gap-10 d-flex align-items-center">
          <span class="trezo-badge with-border border-radius rejected">
            -18.1%
          </span>
          <span class="d-block text-xs"> Last Month </span>
        </div>
      </div>
      <div
        class="icon text-purple rounded-circle d-flex align-items-center justify-content-center"
      >
        <i class="material-symbols-outlined"> payments </i>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  name: "TotalExpense",
});
</script>

<style scoped lang="scss">
.total-expense-card {
  &.v-card {
    &.trezo-card {
      background: linear-gradient(90deg, #f3e8ff 0%, #fff 100%) !important;
    }
  }

  .trezo-card-content {
    .info {
      h3 {
        font-size: 20px;
        margin: {
          top: 4px;
          bottom: 22px;
        }
      }
      .trezo-badge {
        border-radius: 15px !important;
      }
      .gap-10 {
        gap: 10px;
      }
    }
    .icon {
      width: 75px;
      height: 75px;
      background-color: #f3e8ff;

      i {
        font-size: 35px;
      }
    }
  }
}
</style>
