// vuejs-vuetify/src/components/Dashboard/CryptoTrader/LivePriceTracker.vue
<template>
  <v-card
    class="live-price-tracker-card trezo-card mb-25 border-radius d-block bg-white border-0 shadow-none"
  >
    <div class="v-card-header">
      <h5 class="mb-0">Live Price Tracker</h5>

      <v-menu>
        <template v-slot:activator="{ props }">
          <button
            type="button"
            v-bind="props"
            class="position-relative dot-btn p-0 bg-transparent border-none"
          >
            <i class="ri-more-fill"></i>
          </button>
        </template>

        <v-list class="menu-content">
          <button
            type="button"
            class="bg-transparent border-none"
            @click="setTimeRange('24h')"
          >
            This Day
          </button>
          <button
            type="button"
            class="bg-transparent border-none"
            @click="setTimeRange('7d')"
          >
            This Week
          </button>
          <button
            type="button"
            class="bg-transparent border-none"
            @click="setTimeRange('30d')"
          >
            This Month
          </button>
          <button
            type="button"
            class="bg-transparent border-none"
            @click="setTimeRange('1y')"
          >
            This Year
          </button>
        </v-list>
      </v-menu>
    </div>

    <div class="trezo-card-content">
      <div class="table-style-two">
        <div class="basic-table table-responsive">
          <table class="table mb-0">
            <tbody>
              <tr v-for="coin in paginatedCoins" :key="coin.id">
                <td>
                  <div class="customer-info d-flex align-items-center">
                    <div class="img rounded-0">
                      <v-img
                        :src="coin.image"
                        class="rounded-0"
                        :alt="coin.name"
                      />
                    </div>
                    <span class="d-block fw-medium m-0">
                      {{ coin.name }}
                      <span class="text-body fw-normal text-xs m-0">
                        ({{ coin.symbol.toUpperCase() }})
                      </span>
                    </span>
                  </div>
                </td>
                <td>${{ formatPrice(coin.current_price) }}</td>
                <td
                  class="text-end"
                  :class="getPriceChangeClass(coin.price_change_percentage_24h)"
                >
                  ${{ formatPrice(coin.current_price) }}
                </td>
              </tr>
            </tbody>
          </table>
        </div>

        <div
          class="trezo-card-pagination d-flex justify-content-center justify-content-between align-items-center text-center flex-wrap gap-2 showing-wrap pt-3"
        >
          <span class="fs-12 fw-medium">
            Showing {{ showingRange }} of {{ coins.length }} results
          </span>

          <nav aria-label="Page navigation example">
            <ul class="pagination mb-0 justify-content-center">
              <li class="page-item" :class="{ disabled: currentPage === 1 }">
                <button
                  class="page-link icon"
                  aria-label="Previous"
                  @click="prevPage"
                  :disabled="currentPage === 1"
                >
                  <i class="material-symbols-outlined">keyboard_arrow_left</i>
                </button>
              </li>
              <!-- First page button (shown when not in first range) -->
              <li class="page-item" v-if="currentPage > 4">
                <button class="page-link" @click="goToPage(1)">1</button>
              </li>
              <li class="page-item disabled" v-if="currentPage > 4">
                <span class="page-link">...</span>
              </li>
              <!-- Dynamic page buttons -->
              <li class="page-item" v-for="page in visiblePages" :key="page">
                <button
                  class="page-link"
                  :class="{ active: currentPage === page }"
                  @click="goToPage(page)"
                >
                  {{ page }}
                </button>
              </li>
              <!-- Last page indicators -->
              <li
                class="page-item disabled"
                v-if="currentPage < totalPages - 3"
              >
                <span class="page-link">...</span>
              </li>
              <li class="page-item" v-if="currentPage < totalPages - 3">
                <button class="page-link" @click="goToPage(totalPages)">
                  {{ totalPages }}
                </button>
              </li>

              <li
                class="page-item"
                :class="{ disabled: currentPage === totalPages }"
              >
                <button
                  class="page-link icon"
                  aria-label="Next"
                  @click="nextPage"
                  :disabled="currentPage === totalPages"
                >
                  <i class="material-symbols-outlined">keyboard_arrow_right</i>
                </button>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from "vue";

interface Coin {
  id: string;
  name: string;
  symbol: string;
  current_price: number;
  price_change_percentage_24h: number;
  image: string;
}

export default defineComponent({
  name: "LivePriceTracker",
  data() {
    return {
      coins: [] as Coin[],
      currentPage: 1,
      itemsPerPage: 8,
      timeRange: "24h",
      isLoading: false,
      error: null as string | null,
    };
  },
  computed: {
    totalPages(): number {
      return Math.ceil(this.coins.length / this.itemsPerPage);
    },
    paginatedCoins(): Coin[] {
      const start = (this.currentPage - 1) * this.itemsPerPage;
      const end = start + this.itemsPerPage;
      return this.coins.slice(start, end);
    },
    showingRange(): string {
      const start = (this.currentPage - 1) * this.itemsPerPage + 1;
      const end = Math.min(
        this.currentPage * this.itemsPerPage,
        this.coins.length
      );
      return `${start}-${end}`;
    },
    visiblePages(): number[] {
      const pages = [];
      const maxVisible = 3; // Show 5 page numbers (can be adjusted)
      let startPage = 1;

      if (this.totalPages <= maxVisible) {
        // If total pages is less than max visible, show all
        for (let i = 1; i <= this.totalPages; i++) {
          pages.push(i);
        }
      } else {
        // Calculate start and end pages for sliding window
        if (this.currentPage <= 3) {
          startPage = 1;
        } else if (this.currentPage >= this.totalPages - 2) {
          startPage = this.totalPages - maxVisible + 1;
        } else {
          startPage = this.currentPage - 2;
        }

        // Add pages to the array
        for (let i = 0; i < maxVisible; i++) {
          pages.push(startPage + i);
        }
      }

      return pages;
    },
  },
  methods: {
    async fetchCoinData() {
      this.isLoading = true;
      this.error = null;

      try {
        // Using CoinGecko API
        const response = await fetch(
          `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false&price_change_percentage=${this.timeRange}`
        );

        if (!response.ok) {
          throw new Error("Failed to fetch data");
        }

        const data = await response.json();
        this.coins = data;
      } catch (err) {
        this.error =
          err instanceof Error ? err.message : "An unknown error occurred";
        console.error("Error fetching coin data:", err);
      } finally {
        this.isLoading = false;
      }
    },
    formatPrice(price: number): string {
      if (price < 1) {
        return price.toFixed(6);
      } else if (price < 10) {
        return price.toFixed(4);
      } else if (price < 1000) {
        return price.toFixed(2);
      } else {
        return price.toLocaleString("en-US", { maximumFractionDigits: 2 });
      }
    },
    formatPercentage(percent: number): string {
      return percent ? percent.toFixed(2) + "%" : "0.00%";
    },
    getPriceChangeClass(percent: number): string {
      if (percent > 0) return "text-success";
      if (percent < 0) return "text-danger";
      return "text-body";
    },
    setTimeRange(range: string) {
      this.timeRange = range;
      this.fetchCoinData();
    },
    nextPage() {
      if (this.currentPage < this.totalPages) {
        this.currentPage++;
      }
    },
    prevPage() {
      if (this.currentPage > 1) {
        this.currentPage--;
      }
    },
    goToPage(page: number) {
      this.currentPage = page;
    },
  },
  mounted() {
    this.fetchCoinData();
    // Refresh data every 60 seconds
    setInterval(this.fetchCoinData, 60000);
  },
});
</script>

<style scoped lang="scss">
.live-price-tracker-card {
  .trezo-card-content {
    .basic-table {
      table {
        tbody {
          tr {
            td {
              font-size: 13px;
              padding: {
                top: 10px;
                bottom: 11px;
              }
              .customer-info {
                gap: 8px;

                .img {
                  width: 22px;
                }
              }
              &:last-child {
                text-align: end !important;
              }
            }
            &:first-child {
              td {
                border-top-width: 1px;
              }
            }
          }
        }
      }
    }
  }
}
</style>

// react-bootstrap/src/components/Dashboard/CryptoTrader/LivePriceTracker.js
"use client";

import React, { useEffect, useState } from "react";
import { Card, Dropdown, Table } from "react-bootstrap";

const LivePriceTracker = () => {
  // Sample cryptocurrency data
  const [cryptoData, setCryptoData] = useState([
    {
      id: 1,
      name: "Bitcoin",
      symbol: "BTC",
      icon: "/images/cardano.png",
      price: 68848.92,
      change24h: 2.5,
    },
    {
      id: 2,
      name: "Ethereum",
      symbol: "ETH",
      icon: "/images/ethereum-2.png",
      price: 2565.77,
      change24h: -1.2,
    },
    {
      id: 3,
      name: "Binance",
      symbol: "BNB",
      icon: "/images/binance-2.png",
      price: 2565.77,
      change24h: 0.8,
    },
    {
      id: 4,
      name: "Tether",
      symbol: "USDT",
      icon: "/images/tether.png",
      price: 1.0,
      change24h: 0.0,
    },
    {
      id: 5,
      name: "XRP",
      symbol: "XRP",
      icon: "/images/xrp.png",
      price: 0.529105,
      change24h: 3.7,
    },
    {
      id: 6,
      name: "Solana",
      symbol: "SOL",
      icon: "/images/solana-2.png",
      price: 179.44,
      change24h: -2.1,
    },
    {
      id: 7,
      name: "USDC",
      symbol: "USDC",
      icon: "/images/usdc.png",
      price: 1.0,
      change24h: 0.0,
    },
    {
      id: 8,
      name: "Tron",
      symbol: "TRX",
      icon: "/images/tron.png",
      price: 0.192391,
      change24h: 1.5,
    },
    {
      id: 9,
      name: "Polygon",
      symbol: "MATIC",
      icon: "/images/polkadot.png",
      price: 1.02,
      change24h: -0.4,
    },
    {
      id: 10,
      name: "Litecoin",
      symbol: "LTC",
      icon: "/images/litecoin.png",
      price: 84.75,
      change24h: 1.1,
    },
    {
      id: 11,
      name: "Avalanche",
      symbol: "AVAX",
      icon: "/images/avalanche.png",
      price: 42.31,
      change24h: -3.2,
    },
    {
      id: 12,
      name: "Polkadot",
      symbol: "DOT",
      icon: "/images/polkadot.png",
      price: 6.71,
      change24h: 2.3,
    },
    {
      id: 13,
      name: "Shiba Inu",
      symbol: "SHIB",
      icon: "/images/shiba-inu.png",
      price: 0.000025,
      change24h: -0.8,
    },
    {
      id: 14,
      name: "Chainlink",
      symbol: "LINK",
      icon: "/images/chainlink.png",
      price: 15.52,
      change24h: 4.9,
    },
    {
      id: 15,
      name: "Uniswap",
      symbol: "UNI",
      icon: "/images/uniswap.png",
      price: 7.82,
      change24h: 0.6,
    },
    {
      id: 16,
      name: "Stellar",
      symbol: "XLM",
      icon: "/images/stellar.png",
      price: 0.13,
      change24h: 1.2,
    },
  ]);

  // State for pagination
  const [currentPage, setCurrentPage] = useState(1);
  const itemsPerPage = 7;

  // Calculate pagination
  const totalItems = cryptoData.length;
  const totalPages = Math.ceil(totalItems / itemsPerPage);
  const indexOfLastItem = currentPage * itemsPerPage;
  const indexOfFirstItem = indexOfLastItem - itemsPerPage;
  const currentItems = cryptoData.slice(indexOfFirstItem, indexOfLastItem);

  // Change page
  const nextPage = () =>
    setCurrentPage((prev) => Math.min(prev + 1, totalPages));
  const prevPage = () => setCurrentPage((prev) => Math.max(prev - 1, 1));

  // Simulate real-time price updates
  useEffect(() => {
    const interval = setInterval(() => {
      setCryptoData((prevData) =>
        prevData.map((crypto) => ({
          ...crypto,
          price: crypto.price * (1 + (Math.random() * 0.02 - 0.01)), // Random price fluctuation
          change24h: crypto.change24h + (Math.random() * 0.2 - 0.1), // Random change fluctuation
        }))
      );
    }, 5000); // Update every 5 seconds

    return () => clearInterval(interval);
  }, []);

  // Format price with commas
  const formatPrice = (price) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency",
      currency: "USD",
      minimumFractionDigits: price < 1 ? 6 : 2,
      maximumFractionDigits: price < 1 ? 6 : 2,
    }).format(price);
  };

  // Get color class based on price change
  const getChangeColor = (change) => {
    return change > 0
      ? "text-success"
      : change < 0
      ? "text-danger"
      : "text-body";
  };

  return (
    <>
      <Card className="bg-white border-0 rounded-3 mb-4">
        <Card.Body className="p-0">
          <div className="d-flex justify-content-between align-items-center flex-wrap gap-2 p-4">
            <h3 className="mb-0 text-secondary-50">Live Price Tracker</h3>

            <Dropdown className="action-opt">
              <Dropdown.Toggle
                variant="secondary"
                id="dropdown-basic"
                className="bg-transparent p-0"
              >
                <i className="ri-more-fill fs-26 text-body lh-1"></i>
              </Dropdown.Toggle>

              <Dropdown.Menu className="bg-white border box-shadow">
                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Day
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Week
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Month
                </Dropdown.Item>

                <Dropdown.Item href="#" className="text-secondary py-2 px-3">
                  This Year
                </Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown>
          </div>

          <div className="default-table-area style-two py-11">
            <div className="table-responsive">
              <Table className="align-middle">
                <tbody>
                  {currentItems.map((crypto) => (
                    <tr key={crypto.id}>
                      <td className="text-body">
                        <div className="d-flex align-items-center gap-2">
                          <img
                            src={crypto.icon}
                            alt={crypto.symbol}
                            width={22}
                            height={22}
                          />
                          <span className="fw-medium text-secondary fs-13">
                            {crypto.name}{" "}
                            <span className="fw-normal fs-12 text-body">
                              ({crypto.symbol})
                            </span>
                          </span>

                          <div
                            className={`fs-11 ${getChangeColor(
                              crypto.change24h
                            )}`}
                          >
                            {crypto.change24h > 0 ? "+" : ""}
                            {crypto.change24h.toFixed(2)}%
                          </div>
                        </div>
                      </td>
                      <td className="text-body text-end fs-13">
                        {formatPrice(crypto.price)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </Table>
            </div>

            <div
              className="d-flex justify-content-center justify-content-sm-between align-items-center text-center flex-wrap gap-2 showing-wrap p-4"
              style={{
                paddingTop: "15px !important",
              }}
            >
              <span className="fs-13">
                Showing {indexOfFirstItem + 1} to{" "}
                {Math.min(indexOfLastItem, totalItems)} of {totalItems} results
              </span>

              <nav aria-label="Page navigation example">
                <ul className="pagination mb-0 justify-content-center">
                  <li
                    className={`page-item ${
                      currentPage === 1 ? "disabled" : ""
                    }`}
                  >
                    <button
                      className="page-link icon hover-bg"
                      onClick={prevPage}
                      aria-label="Previous"
                      disabled={currentPage === 1}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_left
                      </i>
                    </button>
                  </li>

                  <li
                    className={`page-item ${
                      currentPage === totalPages ? "disabled" : ""
                    }`}
                  >
                    <button
                      className="page-link icon hover-bg"
                      onClick={nextPage}
                      aria-label="Next"
                      disabled={currentPage === totalPages}
                    >
                      <i className="material-symbols-outlined">
                        keyboard_arrow_right
                      </i>
                    </button>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </Card.Body>
      </Card>
    </>
  );
};

export default LivePriceTracker;
